// ============================================================
// PRESCREVE-AI — Banco Farmacológico: Oncologia + Hematologia
// Phase 21.12
// ============================================================

import { QuickDrug } from './pharma-database';

export const PHARMA_DB_ONCO: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════
  // ── PLATINAS ─────────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'cisplatina',
    molecula: 'cisplatina',
    nome_generico: 'Cisplatina',
    sinonimos: ['CDDP', 'platinol', 'platina', 'DDP'],
    categoria: 'oncologia',
    classe: 'Agente alquilante — platina',
    indicacoes_principais: ['Câncer de pulmão (CPPC e CPNPC)', 'Câncer de testículo (1ª linha)', 'Câncer de ovário', 'Câncer de bexiga', 'Câncer de cabeça e pescoço', 'Carcinoma cervical', 'Mesotelioma'],
    dose_adulto: {
      habitual: '75–100 mg/m² IV a cada 3–4 semanas (dose única) ou 20 mg/m²/dia × 5 dias',
      max: '100 mg/m²/ciclo (dose única)',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 21 dias (q3w)', 'A cada 28 dias (q4w)', 'Semanal: 40 mg/m² com radioterapia'],
      instrucoes: 'Hidratação obrigatória: SF 1–2 L antes e após. Mannitol 200 mL 20% antes da dose. Monitorar creatinina, eletrólitos (Mg, K), audiometria.',
    },
    contraindicacoes_rapidas: [
      'ClCr < 45 mL/min (suspender)',
      'Neuropatia periférica grau ≥ 2 pré-existente',
      'Perda auditiva grave pré-existente',
      'Gravidez',
      'Hipersensibilidade à cisplatina ou outros compostos platinados',
    ],
    interacoes_importantes: [
      { com: 'aminoglicosídeos', severidade: 'grave', descricao: 'Nefrotoxicidade e ototoxicidade aditivas — evitar combinação' },
      { com: 'furosemida', severidade: 'moderada', descricao: 'Potencializa ototoxicidade' },
      { com: 'metotrexato', severidade: 'moderada', descricao: 'Reduz clearance de MTX → toxicidade' },
    ],
    alertas_especiais: [
      '⚠ NEFROTÓXICO: hidratação IV obrigatória (2–3 L/dia)',
      '⚠ OTOTÓXICO: audiometria pré e seriada; evitar em pré-escolares (perda auditiva permanente)',
      '⚠ EMETOGÊNICO ALTO: protocolo 3 drogas antiemese obrigatório (5-HT3 + NK1 + dex)',
      'Hipomagnesemia crônica: suplementar Mg IV/VO durante e após o tratamento',
      'Neuropatia: 30–40% de pacientes desenvolvem neuropatia periférica dose-cumulativa',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Dose plena (ClCr > 60)',
      tfg_60_30: 'ClCr 45–60: reduzir 25–50%. ClCr < 45: CONTRAINDICADO',
      tfg_30_15: 'CONTRAINDICADO',
      tfg_lt_15: 'CONTRAINDICADO',
      dialisavel: false,
    },
    marcas: [{ nome: 'Cisplatina (genérico)', laboratorio: 'Várias', concentracoes: ['0,5 mg/mL', '1 mg/mL'], formas: ['Solução injetável IV'] }],
    espectro: ['Platina 1ª geração', 'Ligações cruzadas DNA N7-guanina'],
  },
  {
    id: 'carboplatina',
    molecula: 'carboplatina',
    nome_generico: 'Carboplatina',
    sinonimos: ['CBDCA', 'paraplatin', 'carbo'],
    categoria: 'oncologia',
    classe: 'Agente alquilante — platina 2ª geração',
    indicacoes_principais: ['Câncer de ovário (1ª linha em combinação)', 'CPNPC', 'CPPC', 'Câncer de endométrio', 'Câncer de mama triplo negativo', 'Neoplasias hematológicas (transplante)'],
    dose_adulto: {
      habitual: 'Dose calculada por fórmula de Calvert: Dose (mg) = AUC × (ClCr + 25). AUC 5–7 mg/mL·min (1ª linha); AUC 4–5 (resgate)',
      max: 'AUC 7 (combinação) / AUC 5 (monoterapia resgate)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['A cada 21 dias (q3w)', 'Semanal em alguns esquemas'],
      instrucoes: 'Fórmula de Calvert obrigatória. ClCr pelo método de Cockcroft-Gault (capped a 125 mL/min em muitos protocolos). Infundir em 30–60 min. Hidratação leve (SF 250–500 mL).',
    },
    contraindicacoes_rapidas: [
      'Hipersensibilidade a platinas (cross-reatividade com cisplatina ~15%)',
      'Gravidez',
      'ClCr < 15 mL/min',
    ],
    interacoes_importantes: [
      { com: 'aminoglicosídeos', severidade: 'moderada', descricao: 'Potencializa nefrotoxicidade' },
      { com: 'fenitoína', severidade: 'moderada', descricao: 'Pode reduzir nível sérico de fenitoína' },
    ],
    alertas_especiais: [
      'FÓRMULA DE CALVERT: Dose = AUC × (ClCr + 25) — NUNCA dosar por mg/m² como cisplatina',
      'Mielotoxicidade: principal toxicidade (trombocitopenia > anemia > leucopenia)',
      'Emetogênico MODERADO-ALTO (AUC ≥ 4): tratar como alto risco',
      'Reação de hipersensibilidade: ↑ com exposições repetidas (> 6 ciclos) — pré-medicar',
      'Menos nefrotóxico e ototóxico que cisplatina',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Usar fórmula de Calvert',
      tfg_60_30: 'Ajuste pela fórmula Calvert (menor ClCr → menor dose)',
      tfg_30_15: 'Usar fórmula Calvert com cautela — capped a 125 mL/min',
      tfg_lt_15: 'Dados insuficientes — evitar',
      dialisavel: true,
    },
    marcas: [{ nome: 'Carboplatina (genérico)', laboratorio: 'Várias', concentracoes: ['10 mg/mL'], formas: ['Solução injetável IV'] }],
  },
  {
    id: 'oxaliplatina',
    molecula: 'oxaliplatina',
    nome_generico: 'Oxaliplatina',
    sinonimos: ['Eloxatin', 'oxali', 'platina 3ª geração'],
    categoria: 'oncologia',
    classe: 'Agente alquilante — platina 3ª geração',
    indicacoes_principais: ['CCR metastático (FOLFOX, XELOX)', 'CCR adjuvante estádio III', 'Câncer gástrico (EOX, FLOT)'],
    dose_adulto: {
      habitual: 'FOLFOX: 85 mg/m² IV a cada 14 dias | XELOX: 130 mg/m² IV a cada 21 dias',
      max: '130 mg/m²/ciclo',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 14 dias (FOLFOX)', 'A cada 21 dias (XELOX/CAPOX)'],
      instrucoes: 'Infundir em 2h em SG 5% (NÃO em SF — precipita). Não usar material contendo alumínio. ATENÇÃO: sensação ao frio nas primeiras 24h — orientar paciente.',
    },
    contraindicacoes_rapidas: [
      'Neuropatia periférica grau ≥ 2',
      'Gravidez',
      'Hipersensibilidade a compostos de platina',
    ],
    interacoes_importantes: [
      { com: 'fluorouracil', severidade: 'leve', descricao: 'Sinergia terapêutica (FOLFOX) — combinação intencional' },
    ],
    alertas_especiais: [
      '⚠ NEUROPATIA FRIA: parestesias ao frio nas primeiras 24–72h após infusão (aguda, reversível). Orientar: não segurar objetos frios, usar luvas, não ingerir bebidas geladas',
      '⚠ NEUROPATIA CUMULATIVA: neuropatia sensorial crônica e dose-limitante (> 800 mg/m² acumulado)',
      'Oxaliplatina em SF: precipitação — usar EXCLUSIVAMENTE em SG 5%',
      'Emetogênico MODERADO: dupla antiemese (5-HT3 + dex)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Eloxatin', laboratorio: 'Sanofi', concentracoes: ['5 mg/mL'], formas: ['Solução concentrada IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── TAXANOS ──────────────────────────────────════════════
  // ══════════════════════════════════════════════════════════
  {
    id: 'paclitaxel',
    molecula: 'paclitaxel',
    nome_generico: 'Paclitaxel',
    sinonimos: ['Taxol', 'PTX', 'taxano'],
    categoria: 'oncologia',
    classe: 'Taxano — estabilizador de microtúbulos',
    indicacoes_principais: ['Câncer de mama (AC-T, TC)', 'CPNPC', 'Câncer de ovário', 'Câncer gástrico', 'Sarcoma de Kaposi'],
    dose_adulto: {
      habitual: '175 mg/m² IV a cada 21 dias (q3w) | 80 mg/m² IV semanal (dose densa)',
      max: '175 mg/m²/ciclo (q3w)',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 21 dias', 'Semanal'],
      instrucoes: 'PRÉ-MEDICAÇÃO OBRIGATÓRIA 30 min antes: dexametasona 20 mg IV + difenidramina 50 mg IV + ranitidina 50 mg IV (previne reação de hipersensibilidade). Infundir em 3h (q3w) ou 1h (semanal). Usar equipo não PVC (paclitaxel absorve PVC).',
    },
    contraindicacoes_rapidas: [
      'Neutropenia de base < 1500/mm³',
      'Hipersensibilidade grave prévia ao paclitaxel ou óleo de castor polyoxietilado (Cremophor)',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'cetoconazol / inibidores CYP3A4', severidade: 'moderada', descricao: 'Aumenta exposição ao paclitaxel — monitorar toxicidade' },
      { com: 'rifampicina', severidade: 'moderada', descricao: 'Induz CYP3A4/2C8 → reduz eficácia' },
      { com: 'doxorrubicina', severidade: 'moderada', descricao: 'Administrar doxorrubicina ANTES do paclitaxel (sequência altera PK e cardiotoxicidade)' },
    ],
    alertas_especiais: [
      '⚠ REAÇÃO HIPERSENSIBILIDADE: até 3% com pré-medicação (anafilaxia nos primeiros 10 min) — ter epinefrina disponível',
      '⚠ NEUROPATIA: principal toxicidade dose-limitante cumulativa — parestesias, dor neuropática',
      'Alopecia: universal (100%)',
      'Cremophor EL (veículo): causa hipersensibilidade — nab-paclitaxel (Abraxane) dispensa pré-medicação',
      'Neutropenia nadir: D8–D10 (q3w) — monitorar hemograma',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Taxol', laboratorio: 'BMS', concentracoes: ['6 mg/mL'], formas: ['Concentrado IV'] },
      { nome: 'Abraxane (nab-paclitaxel)', laboratorio: 'ABI/BMS', concentracoes: ['5 mg/mL reconstituído'], formas: ['Pó liofilizado IV — sem Cremophor'] },
    ],
  },
  {
    id: 'docetaxel',
    molecula: 'docetaxel',
    nome_generico: 'Docetaxel',
    sinonimos: ['Taxotere', 'DTX'],
    categoria: 'oncologia',
    classe: 'Taxano — estabilizador de microtúbulos',
    indicacoes_principais: ['Câncer de mama', 'CPNPC', 'Câncer de próstata (CRPC)', 'Câncer gástrico (DCF)', 'Câncer de cabeça e pescoço'],
    dose_adulto: {
      habitual: '75–100 mg/m² IV a cada 21 dias | 75 mg/m² em combinação',
      max: '100 mg/m²/ciclo',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 21 dias'],
      instrucoes: 'PRÉ-MEDICAÇÃO: dexametasona 8 mg VO 12/12h × 3 dias iniciando D-1 (previne retenção hídrica e hipersensibilidade). Infundir em 1h.',
    },
    contraindicacoes_rapidas: ['ANC < 1500/mm³', 'TGO/TGP > 3,5× + FA > 6× LSN (falência hepática)', 'Gravidez', 'Hipersensibilidade a polissorbato 80'],
    interacoes_importantes: [
      { com: 'inibidores CYP3A4', severidade: 'moderada', descricao: 'Cetoconazol, eritromicina: aumentam toxicidade do docetaxel' },
    ],
    alertas_especiais: [
      '⚠ RETENÇÃO HÍDRICA CUMULATIVA: edema periférico, derrame pleural/pericárdico — dexametasona 3 dias previne mas não elimina',
      '⚠ HEPATOTÓXICO: ajuste obrigatório se disfunção hepática (bilirrubina, TGO/TGP)',
      'Alopecia: universal',
      'Neutropenia: nadir D7–D9; G-CSF profilático frequentemente necessário',
      'Síndrome ungueal: onicodistrofia, onicólise — esmalte escuro e gelo nos pés durante infusão',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_hepatico: { child_a: 'Reduzir dose 25%', child_b: 'Reduzir 50%; bilirrubina > 1,5× LSN: reduzir 25%', child_c: 'CONTRAINDICADO' },
    marcas: [{ nome: 'Taxotere', laboratorio: 'Sanofi', concentracoes: ['10 mg/mL', '20 mg/mL'], formas: ['Concentrado IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── ANTIMETABÓLITOS ───────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'fluorouracil',
    molecula: 'fluorouracil',
    nome_generico: '5-Fluorouracil (5-FU)',
    sinonimos: ['5-FU', '5FU', 'fluorouracilo', 'FOLFOX', 'FOLFIRI'],
    categoria: 'oncologia',
    classe: 'Antimetabólito — análogo de pirimidina',
    indicacoes_principais: ['CCR (FOLFOX, FOLFIRI, XELOX)', 'Câncer gástrico', 'Câncer de mama', 'Câncer de pâncreas', 'Câncer de cabeça e pescoço (com RT)'],
    dose_adulto: {
      habitual: 'FOLFOX/FOLFIRI: 400 mg/m² IV bolus D1 → 2400 mg/m² IC 46h (a cada 14 dias)',
      max: '2400 mg/m² em infusão contínua (46h)',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 14 dias (biossemanal)', 'Contínuo (IC 5 dias)'],
      instrucoes: 'Infusão contínua (IC) tem menos toxicidade GI que bolus. Proteger da luz. Não misturar com carboplatina/oxaliplatina na mesma linha. Flebite: usar cateter central.',
    },
    contraindicacoes_rapidas: [
      'Deficiência de DPD (diidropirimidina desidrogenase) — toxicidade grave e fatal',
      'Estado geral grave (ECOG ≥ 3)',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'leucovorin', severidade: 'leve', descricao: 'Potencializa eficácia do 5-FU (sinergia intencional em protocolos)' },
      { com: 'metronidazol', severidade: 'moderada', descricao: 'Inibe metabolismo de 5-FU → ↑ toxicidade' },
      { com: 'varfarina', severidade: 'grave', descricao: '↑ INR significativo — monitorar INR semanalmente' },
    ],
    alertas_especiais: [
      '⚠ DEFICIÊNCIA DE DPD: teste DPYD obrigatório antes em países com disponibilidade — toxicidade fatal',
      '⚠ SÍNDROME MÃO-PÉ (eritrodisestesia palmo-plantar): com capecitabina/IC 5-FU — grau 3 exige suspensão',
      'Cardiotoxicidade: espasmo coronariano raro mas grave (dor torácica durante infusão — suspender imediatamente)',
      'Mucosite: frequente com bolus; menor com IC',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: '5-Fluorouracil (genérico)', laboratorio: 'Várias', concentracoes: ['25 mg/mL', '50 mg/mL'], formas: ['Solução injetável IV'] }],
  },
  {
    id: 'capecitabina',
    molecula: 'capecitabina',
    nome_generico: 'Capecitabina',
    sinonimos: ['Xeloda', 'XELOX', 'cape', 'oral 5-FU'],
    categoria: 'oncologia',
    classe: 'Antimetabólito — pró-fármaco oral do 5-FU',
    indicacoes_principais: ['CCR adjuvante e metastático (XELOX)', 'Câncer de mama (combinação ou monoterapia)', 'Câncer gástrico', 'Câncer de pâncreas (GemCap)'],
    dose_adulto: {
      habitual: '1000–1250 mg/m² VO 2×/dia por 14 dias a cada 21 dias (ciclo 14/7)',
      max: '1250 mg/m² 2×/dia',
      unidade: 'mg/m²',
      via: 'VO',
      frequencias: ['2×/dia (12/12h) × 14 dias → 7 dias pausa'],
      instrucoes: 'Tomar APÓS as refeições (30 min) com água. Arredondar para comprimidos disponíveis (150 mg e 500 mg). Calcular dose total diária → dividir por 2 (manhã e noite).',
    },
    contraindicacoes_rapidas: [
      'ClCr < 30 mL/min (CONTRAINDICADO)',
      'Deficiência de DPD',
      'Uso concomitante com sorivudina ou brivudina (interação fatal)',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'varfarina', severidade: 'grave', descricao: 'Inibe CYP2C9 → ↑↑ INR — monitorar INR 2–3× por semana inicialmente' },
      { com: 'fenitoína', severidade: 'grave', descricao: 'Aumenta nível de fenitoína → toxicidade neurológica' },
      { com: 'sorivudina / brivudina', severidade: 'contraindicado', descricao: 'Inibição irreversível de DPD → toxicidade fatal ao 5-FU' },
      { com: 'oxaliplatina', severidade: 'leve', descricao: 'Combinação XELOX/CAPOX — sinergia intencional' },
    ],
    alertas_especiais: [
      '⚠ SÍNDROME MÃO-PÉ (SMP): eritema doloroso palmo-plantar. Grau 2: reduzir 25%; Grau 3: suspender até ≤ grau 1',
      '⚠ VARFARINA: interação muito frequente e grave — checar INR semanalmente',
      'Ajuste renal obrigatório: ClCr 30–50: reduzir 25%. ClCr < 30: CONTRAINDICADO',
      'Hidratação e cremes barreira (ureia 10–20%) previnem SMP',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'ClCr 30–50: reduzir 25% da dose',
      tfg_30_15: 'CONTRAINDICADO',
      tfg_lt_15: 'CONTRAINDICADO',
      dialisavel: false,
    },
    marcas: [{ nome: 'Xeloda', laboratorio: 'Roche', concentracoes: ['150 mg', '500 mg'], formas: ['Comprimido revestido'] }],
  },
  {
    id: 'gencitabina',
    molecula: 'gencitabina',
    nome_generico: 'Gencitabina',
    sinonimos: ['Gemzar', 'GEM', 'gemcitabine'],
    categoria: 'oncologia',
    classe: 'Antimetabólito — análogo de desoxicitidina',
    indicacoes_principais: ['Câncer de pâncreas (1ª linha)', 'CPNPC (GemCis/GemCarbo)', 'Câncer de bexiga (GemCis)', 'Câncer de mama recidivado', 'Câncer de ovário resistente a platina', 'Linfoma de Hodgkin refratário (GVD)'],
    dose_adulto: {
      habitual: '1000–1250 mg/m² IV a cada 7–14 dias (conforme esquema)',
      max: '1250 mg/m²/semana',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['D1 e D8 a cada 21 dias (GemCis)', 'D1, D8, D15 a cada 28 dias (monoterapia pâncreas)'],
      instrucoes: 'Infundir em 30 min (velocidade afeta eficácia). Infusão prolongada > 60 min: ↑ toxicidade hematológica.',
    },
    contraindicacoes_rapidas: ['Gravidez', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'cisplatina', severidade: 'leve', descricao: 'Combinação GemCis — sinergia intencional' },
      { com: 'radioterapia concomitante', severidade: 'grave', descricao: 'Radiosensibilizador — pneumonite e esofagite graves; evitar combinação concomitante fora de protocolos específicos' },
    ],
    alertas_especiais: [
      'Toxicidade pulmonar: pneumonite intersticial rara mas grave (dispneia aguda)',
      'Síndrome hemolítico-urêmica (SHU): rara, associada a altas doses',
      'Flu-like: febre, mialgia, calafrios — comuns, autolimitados; tratar com paracetamol',
      'Trombocitopenia: monitorar nadir D8–D10',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Gemzar', laboratorio: 'Eli Lilly', concentracoes: ['38 mg/mL reconst.'], formas: ['Pó liofilizado IV'] }],
  },
  {
    id: 'pemetrexede',
    molecula: 'pemetrexede',
    nome_generico: 'Pemetrexede',
    sinonimos: ['Alimta', 'PMX', 'antifolato'],
    categoria: 'oncologia',
    classe: 'Antimetabólito — inibidor multialvo de folato',
    indicacoes_principais: ['CPNPC não escamoso (1ª linha com cisplatina, manutenção)', 'Mesotelioma pleural maligno'],
    dose_adulto: {
      habitual: '500 mg/m² IV a cada 21 dias',
      max: '500 mg/m²/ciclo',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 21 dias'],
      instrucoes: 'SUPLEMENTAÇÃO OBRIGATÓRIA 7–14 dias antes: ácido fólico 400 mcg/dia VO + vitamina B12 1000 mcg IM 1× antes (repetir a cada 9 semanas). Dexametasona 4 mg 2×/dia D-1, D0, D+1 (previne rush cutâneo).',
    },
    contraindicacoes_rapidas: ['ClCr < 45 mL/min', 'Gravidez', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'AINEs', severidade: 'moderada', descricao: 'Reduzem clearance renal de pemetrexede → ↑ toxicidade; evitar 2–5 dias antes/após' },
    ],
    alertas_especiais: [
      '⚠ SUPLEMENTAÇÃO OBRIGATÓRIA: sem folato + B12 → toxicidade hematológica grave',
      'ClCr < 45: CONTRAINDICADO (excreção predominantemente renal)',
      'Rash cutâneo: frequente sem dexametasona profilática',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Alimta', laboratorio: 'Eli Lilly', concentracoes: ['25 mg/mL reconst.'], formas: ['Pó liofilizado IV'] }],
  },
  {
    id: 'metotrexato-onco',
    molecula: 'metotrexato',
    nome_generico: 'Metotrexato (Alta Dose)',
    sinonimos: ['MTX-AD', 'MTX alta dose', 'metotrexato HD', 'leucovorin resgate'],
    categoria: 'oncologia',
    classe: 'Antimetabólito — inibidor de DHFR',
    indicacoes_principais: ['Linfoma de SNC / Linfoma de Burkitt', 'Leucemia linfoblástica aguda (LLA)', 'Osteossarcoma (protocolo MAP)', 'Linfoma difuso de grandes células B (RCHOP + MTX-AD)'],
    dose_adulto: {
      habitual: 'Alta dose: 1000–8000 mg/m² IV em infusão de 4–24h (protocolo-dependente)',
      max: '8000 mg/m²/ciclo',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 14–21 dias (protocolo-dependente)'],
      instrucoes: 'LEUCOVORIN RESGATE OBRIGATÓRIO: 15 mg IV/VO 6/6h a partir de 24h do início de MTX. Alcalinização urinária (bicarbonato IV): pH urinário > 7 antes e durante infusão. Hidratação: 3 L/m²/dia. Monitorar nível sérico de MTX às 24h, 48h, 72h.',
    },
    contraindicacoes_rapidas: ['Derrame pleural / ascite significativa (third space — retarda eliminação)', 'ClCr < 60 mL/min', 'Gravidez', 'Disfunção hepática grave'],
    interacoes_importantes: [
      { com: 'AINEs', severidade: 'grave', descricao: 'Reduzem excreção renal de MTX → toxicidade fatal; suspender 48h antes' },
      { com: 'penicilinas', severidade: 'moderada', descricao: 'Competem com secreção tubular → ↑ MTX' },
      { com: 'probenecida', severidade: 'grave', descricao: 'Inibe excreção renal de MTX — evitar' },
      { com: 'cisplatina', severidade: 'moderada', descricao: 'Nefrotóxica → reduz eliminação de MTX → toxicidade' },
    ],
    alertas_especiais: [
      '⚠ PROTOCOLO ESTRITO: MTX-AD requer leucovorin resgate + alcalinização + níveis séricos seriados',
      '⚠ THIRD-SPACE: derrame pleural ou ascite retarda eliminação — drenar antes se volumosos',
      'Mucosites graves: tratar com morfina + leucovorin reforçado',
      'Nefrotoxicidade: principal complicação — hidratação agressiva obrigatória',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Metotrexato (genérico)', laboratorio: 'Várias', concentracoes: ['25 mg/mL'], formas: ['Solução injetável IV/IM'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── ANTRACÍCLINAS ─────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'doxorrubicina',
    molecula: 'doxorrubicina',
    nome_generico: 'Doxorrubicina',
    sinonimos: ['adriamicina', 'ADM', 'AC', 'FAC', 'antracíclina'],
    categoria: 'oncologia',
    classe: 'Antracíclina — inibidor de topoisomerase II',
    indicacoes_principais: ['Câncer de mama (AC-T, FAC)', 'Linfoma (CHOP, RCHOP)', 'Leucemia (AML)', 'Sarcoma de tecidos moles', 'Câncer de ovário'],
    dose_adulto: {
      habitual: '50–75 mg/m² IV a cada 21 dias (monoterapia) | 60 mg/m² em combinação (AC)',
      max: '75 mg/m²/ciclo (dose cumulativa total: 450–550 mg/m²)',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['A cada 21 dias'],
      instrucoes: 'Administrar em veia calibrosa ou cateter central (vesicante grave). Urina avermelhada nas primeiras 24–48h — normal. ECG e ecocardiograma pré-tratamento.',
    },
    contraindicacoes_rapidas: [
      'Dose cumulativa > 550 mg/m² (risco de cardiomiopatia irreversível)',
      'Fração de ejeção < 45%',
      'IAM recente (< 1 mês)',
      'Irradiação cardíaca prévia significativa',
    ],
    interacoes_importantes: [
      { com: 'trastuzumabe', severidade: 'grave', descricao: 'Cardiotoxicidade aditiva — NÃO usar concomitantemente (sequencial)' },
      { com: 'paclitaxel', severidade: 'moderada', descricao: 'Administrar doxorrubicina ANTES do paclitaxel — sequência afeta PK e cardiotoxicidade' },
      { com: 'ciclosporina', severidade: 'moderada', descricao: 'Aumenta exposição à doxorrubicina' },
    ],
    alertas_especiais: [
      '⚠ CARDIOTOXICIDADE: cumulativa e potencialmente irreversível. Dose total máx: 450–550 mg/m². ECO antes e durante.',
      '⚠ VESICANTE GRAVE: extravasamento causa necrose tecidual — usar cateter central. Antídoto: dexrazoxano tópico.',
      'Alopecia: universal',
      'DOXIL (lipossomal): dose máx diferente (500 mg/m²); menos cardiotóxica; SMP frequente',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_hepatico: { child_a: 'Bilirrubina 1,2–3 mg/dL: reduzir 50%', child_b: 'Bilirrubina 3–5 mg/dL: reduzir 75%', child_c: 'Bilirrubina > 5 mg/dL: CONTRAINDICADO' },
    marcas: [
      { nome: 'Adriamicina (genérico)', laboratorio: 'Várias', concentracoes: ['2 mg/mL'], formas: ['Solução injetável IV'] },
      { nome: 'Doxil / Caelyx', laboratorio: 'Janssen', concentracoes: ['2 mg/mL (lipossomal)'], formas: ['Concentrado IV lipossomal'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── IMUNOTERAPIA — CHECKPOINTS ────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'pembrolizumabe',
    molecula: 'pembrolizumabe',
    nome_generico: 'Pembrolizumabe',
    sinonimos: ['Keytruda', 'anti-PD-1', 'ICI', 'imunoterapia', 'pembro'],
    categoria: 'oncologia',
    classe: 'Inibidor de checkpoint imune — anti-PD-1 (IgG4 humanizado)',
    indicacoes_principais: [
      'CPNPC (1ª linha se PD-L1 ≥ 50%; combinação independente de PD-L1)',
      'Melanoma avançado (1ª linha)',
      'Câncer de cabeça e pescoço (CPS ≥ 1)',
      'Câncer de bexiga (CPS ≥ 10)',
      'Câncer gástrico / GEJ (CPS ≥ 1)',
      'Câncer de mama triplo negativo (PD-L1+, KEYTRUDA-522)',
      'Linfoma de Hodgkin refratário',
      'CRC MMR-deficiente / MSI-H (tumor-agnostic)',
    ],
    dose_adulto: {
      habitual: '200 mg IV a cada 21 dias OU 400 mg IV a cada 42 dias',
      max: '400 mg/dose (flat dose)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['A cada 21 dias (200 mg)', 'A cada 42 dias (400 mg)'],
      instrucoes: 'Dose plana (não por peso/m²). Infundir em 30 min com filtro 0,2–5 µm. Pré-medicar apenas se reação de infusão prévia. Monitorar irAE após cada ciclo.',
    },
    contraindicacoes_rapidas: [
      'Doença autoimune ativa grave (lúpus ativo, colite ulcerativa ativa, esclerose múltipla)',
      'Transplante de órgão sólido (risco de rejeição)',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'corticoides crônicos (> 10 mg/dia prednisona)', severidade: 'moderada', descricao: 'Podem reduzir eficácia da imunoterapia (evitar uso preventivo; usar apenas para irAE)' },
      { com: 'ipilimumabe', severidade: 'moderada', descricao: 'Combinação anti-PD-1 + anti-CTLA4 (CheckMate, KEYNOTE): maior eficácia e ↑↑ irAE' },
    ],
    alertas_especiais: [
      '⚠ irAE (Immune-Related Adverse Events): monitorar em CADA consulta — pneumonite, colite, hepatite, endocrinopatias, nefrite',
      'Teste de PD-L1 / MSI-H / TMB antes de prescrever (biomarcadores preditivos)',
      'irAE grau ≥ 3: suspender ICI + corticoide sistêmico (prednisona 1–2 mg/kg/dia)',
      'Pseudo-progressão: tumor pode parecer crescer antes de responder — confirmar com biopsia',
      'Reações de infusão: raras (< 3%) — reduzir velocidade se ocorrer; pré-medicar nos ciclos seguintes',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Keytruda', laboratorio: 'MSD', concentracoes: ['25 mg/mL (4 mL = 100 mg)'], formas: ['Concentrado IV'] }],
    guidelines_referencia: ['ASCO 2023', 'ESMO 2023', 'NCCN 2024'],
  },
  {
    id: 'nivolumabe',
    molecula: 'nivolumabe',
    nome_generico: 'Nivolumabe',
    sinonimos: ['Opdivo', 'anti-PD-1', 'nivo'],
    categoria: 'oncologia',
    classe: 'Inibidor de checkpoint imune — anti-PD-1 (IgG4 humano)',
    indicacoes_principais: ['Melanoma (1ª e 2ª linha)', 'CPNPC (2ª linha)', 'Câncer de células renais (1ª linha + ipilimumabe)', 'Carcinoma hepatocelular', 'Câncer gástrico / GEJ', 'Linfoma de Hodgkin refratário', 'CRC MSI-H'],
    dose_adulto: {
      habitual: '240 mg IV a cada 14 dias OU 480 mg IV a cada 28 dias',
      max: '480 mg/dose (flat dose)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['A cada 14 dias', 'A cada 28 dias'],
      instrucoes: 'Dose plana. Infundir em 30–60 min com filtro. Combinação com ipilimumabe: nivolumabe 1 mg/kg + ipilimumabe 3 mg/kg q3w × 4 → nivolumabe 480 mg q4w.',
    },
    contraindicacoes_rapidas: ['Doença autoimune ativa', 'Gravidez', 'Transplante de órgão sólido'],
    interacoes_importantes: [
      { com: 'ipilimumabe', severidade: 'moderada', descricao: 'Combinação: ↑↑ eficácia e ↑↑ irAE (23% grau 3–4 vs 7% monoterapia)' },
    ],
    alertas_especiais: [
      '⚠ irAE: mesmo perfil que pembrolizumabe — monitorar em cada ciclo',
      'Combinação nivolumabe + ipilimumabe: toxicidade imune mais frequente e grave',
      'Hiperprogessão: raro, mais descrito em pacientes MDM2/MDM4 amplificado, EGFR mutado',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Opdivo', laboratorio: 'BMS', concentracoes: ['10 mg/mL'], formas: ['Concentrado IV'] }],
  },
  {
    id: 'ipilimumabe',
    molecula: 'ipilimumabe',
    nome_generico: 'Ipilimumabe',
    sinonimos: ['Yervoy', 'anti-CTLA-4', 'ipi'],
    categoria: 'oncologia',
    classe: 'Inibidor de checkpoint imune — anti-CTLA-4 (IgG1 humano)',
    indicacoes_principais: ['Melanoma avançado (1ª linha, combinado com nivolumabe)', 'CCR (+ nivolumabe)', 'CPNPC (+ nivolumabe)'],
    dose_adulto: {
      habitual: '3 mg/kg IV q3w × 4 (melanoma) | 1 mg/kg IV q6w (manutenção com nivolumabe)',
      max: '3 mg/kg/dose',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['A cada 21 dias × 4 doses (indução)'],
      instrucoes: 'Infundir em 90 min. NÃO administrar em bolus. Combinação com nivolumabe: nivo 1 mg/kg + ipi 3 mg/kg q3w × 4 ciclos.',
    },
    contraindicacoes_rapidas: ['Doença autoimune ativa grave', 'Transplante de órgão', 'Gravidez'],
    interacoes_importantes: [
      { com: 'Corticosteroides sistêmicos / imunossupressores (basais)', severidade: 'moderada', descricao: 'Evitar ANTES de iniciar — podem reduzir a eficácia antitumoral (inibem ativação de linfócitos T). Após início, podem ser usados para tratar irAE sem prejuízo aparente da eficácia' },
      { com: 'Outros inibidores de checkpoint (ex.: nivolumabe)', severidade: 'grave', descricao: 'Combinação ↑ substancialmente a incidência e gravidade de eventos adversos imunomediados' },
    ],
    alertas_especiais: [
      '⚠ irAE MAIS GRAVE que anti-PD-1: colite (30–40%), hepatite, hipofisit',
      '⚠ DOSE DEPENDENTE DE irAE: 10 mg/kg (não aprovado) tem toxicidade proibitiva',
      'Infliximabe para colite grau 3–4 (anti-TNF)',
      'NÃO usar infliximabe em hepatite imune (hepatotóxico)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Yervoy', laboratorio: 'BMS', concentracoes: ['5 mg/mL'], formas: ['Concentrado IV'] }],
  },
  {
    id: 'rituximabe',
    molecula: 'rituximabe',
    nome_generico: 'Rituximabe',
    sinonimos: ['MabThera', 'Rituxan', 'anti-CD20', 'R-CHOP'],
    categoria: 'oncologia',
    classe: 'Anticorpo monoclonal — anti-CD20 (IgG1 quimérico)',
    indicacoes_principais: ['Linfoma não-Hodgkin de células B (DLBCL, FL, MCL)', 'LLC', 'Artrite reumatoide refratária', 'Granulomatose com poliangiite (GPA)', 'Penfigoide bolhoso'],
    dose_adulto: {
      habitual: '375 mg/m² IV (linfoma) | 500 mg IV (CLL, 2° ciclo em diante)',
      max: '375 mg/m²/ciclo',
      unidade: 'mg/m²',
      via: 'IV',
      frequencias: ['D1 de cada ciclo (R-CHOP: q21d)', 'Manutenção: 375 mg/m² q2–3 meses'],
      instrucoes: 'PRÉ-MEDICAÇÃO 30 min antes: paracetamol 1g + difenidramina 50 mg IV ± dexametasona 8 mg IV. Iniciar infusão lenta (50 mg/h) → aumentar 50 mg/h a cada 30 min (máx 400 mg/h). Monitorar reação de infusão.',
    },
    contraindicacoes_rapidas: [
      'HBsAg+ ou anti-HBc+ sem profilaxia com antiviral (reativação de HBV)',
      'Infecção ativa grave',
      'Gravidez (1º trimestre)',
    ],
    interacoes_importantes: [
      { com: 'cisplatina', severidade: 'grave', descricao: 'NÃO diluir em SF com cisplatina — precipitação; usar SG 5%' },
    ],
    alertas_especiais: [
      '⚠ HBV: triagem sorológica obrigatória antes. HBsAg+ ou anti-HBc+: profilaxia com entecavir obrigatória',
      '⚠ SÍNDROME DE LISE TUMORAL: risco alto em LLC ou linfoma com carga tumoral elevada — profilaxia',
      'Reação de infusão: mais frequente no 1º ciclo (febre, calafrios, broncoespasmo)',
      'PML (Leucoencefalopatia Multifocal Progressiva): rara mas fatal — associada ao vírus JC',
      'Hipogamaglobulinemia: com ciclos prolongados — risco infeccioso aumentado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'MabThera', laboratorio: 'Roche', concentracoes: ['10 mg/mL'], formas: ['Concentrado IV'] },
      { nome: 'Riabni / Ruxience (biossimilar)', laboratorio: 'Pfizer/Amgen', concentracoes: ['10 mg/mL'], formas: ['Concentrado IV'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── TERAPIA-ALVO ──────────────────────────════════════════
  // ══════════════════════════════════════════════════════════
  {
    id: 'imatinibe',
    molecula: 'imatinibe',
    nome_generico: 'Imatinibe',
    sinonimos: ['Gleevec', 'Glivec', 'STI571', 'inibidor BCR-ABL', 'GIST', 'LMC'],
    categoria: 'oncologia',
    classe: 'Inibidor de tirosina quinase (ITK) — BCR-ABL / KIT / PDGFR',
    indicacoes_principais: ['LMC Ph+ (1ª linha)', 'LLA Ph+ (combinado com QT)', 'GIST (c-KIT ou PDGFRA)'],
    dose_adulto: {
      habitual: 'LMC fase crônica: 400 mg/dia VO | LMC fase acelerada/blástica: 600–800 mg/dia | GIST: 400 mg/dia',
      max: '800 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–2×/dia com refeição'],
      instrucoes: 'Tomar com refeição e copo de água grande. 400 mg: dose única manhã. 600–800 mg: 400 mg manhã + restante à noite.',
    },
    contraindicacoes_rapidas: ['Gravidez (especialmente 1T)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'varfarina', severidade: 'grave', descricao: 'Inibe CYP2C9 → ↑↑ INR. Usar HBPM em vez de varfarina se anticoagulação necessária.' },
      { com: 'sinvastatina', severidade: 'grave', descricao: 'Inibe CYP3A4 → rabdomiólise; usar pravastatina ou rosuvastatina' },
      { com: 'cetoconazol', severidade: 'moderada', descricao: 'Aumenta nível de imatinibe (inibidor CYP3A4)' },
      { com: 'rifampicina', severidade: 'grave', descricao: 'Induz CYP3A4 → reduz eficácia em 74%' },
    ],
    alertas_especiais: [
      'Edema periorbital e periférico: muito comum (30–60%) — monitorar peso diariamente',
      'Cãibras musculares: frequentes — tratar com quinino ou eletrólitos',
      'Resistência a imatinibe: mutação T315I → usar ponatinibe. Mutações outras → dasatinibe ou nilotinibe.',
      'Monitorar BCR-ABL quantitativo (PCR) a cada 3 meses — alvo remissão molecular maior (MMR: ≤ 0,1%)',
      'Biossimilares disponíveis e aprovados (interchangeability comprovada)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Glivec', laboratorio: 'Novartis', concentracoes: ['100 mg', '400 mg'], formas: ['Comprimido revestido'] },
      { nome: 'Imatinibe (genérico)', laboratorio: 'Várias', concentracoes: ['100 mg', '400 mg'], formas: ['Comprimido revestido'] },
    ],
    guidelines_referencia: ['ESMO 2023', 'NCCN 2024'],
  },
  {
    id: 'trastuzumabe',
    molecula: 'trastuzumabe',
    nome_generico: 'Trastuzumabe',
    sinonimos: ['Herceptin', 'anti-HER2', 'HER2', 'Herceptin SC'],
    categoria: 'oncologia',
    classe: 'Anticorpo monoclonal — anti-HER2/ErbB2 (IgG1 humanizado)',
    indicacoes_principais: ['Câncer de mama HER2+ (adjuvante e metastático)', 'Câncer gástrico HER2+ (1ª linha com QT)'],
    dose_adulto: {
      habitual: 'Dose de ataque: 8 mg/kg IV → Manutenção: 6 mg/kg IV a cada 21 dias | SC: 600 mg fixo a cada 21 dias',
      max: '8 mg/kg (1ª dose IV)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['A cada 21 dias (q3w)', 'A cada 7 dias (q1w): 4 mg/kg ataque → 2 mg/kg manutenção'],
      instrucoes: 'Dose de ataque: infundir em 90 min. Manutenção: 30 min se 1ª dose bem tolerada. Formulação SC (600 mg): 5 min em abdome — muito mais conveniente. Monitorar FEVE antes e a cada 3 meses.',
    },
    contraindicacoes_rapidas: [
      'FEVE < 45% ou sintomas de IC',
      'Uso concomitante com antraciclinas (cardiotoxicidade aditiva)',
    ],
    interacoes_importantes: [
      { com: 'doxorrubicina', severidade: 'grave', descricao: 'Cardiotoxicidade aditiva grave — usar sequencial (trastuzumabe APÓS AC-T, nunca concomitante com antraciclina)' },
      { com: 'paclitaxel', severidade: 'leve', descricao: 'Combinação sinérgica — HP (pertuzumabe + trastuzumabe + taxano)' },
    ],
    alertas_especiais: [
      '⚠ CARDIOTOXICIDADE: diferente da antraciclina — geralmente reversível. Monitorar FEVE q3m.',
      '⚠ Testar HER2 obrigatoriamente (IHQ 3+ ou FISH amplificado) antes de prescrever',
      'Reação de infusão: 1ª dose (40%) — quase inexistente com formulação SC',
      'Tratar por 1 ano no adjuvante (52 semanas)',
      'Biossimilares aprovados: kanjinti, ogivri, herzuma — interchangeability confirmada',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Herceptin IV', laboratorio: 'Roche', concentracoes: ['21 mg/mL reconst.'], formas: ['Pó liofilizado IV'] },
      { nome: 'Herceptin SC', laboratorio: 'Roche', concentracoes: ['120 mg/mL (5 mL)'], formas: ['Solução SC'] },
    ],
    guidelines_referencia: ['ASCO 2023', 'ESMO 2023'],
  },
  {
    id: 'bevacizumabe',
    molecula: 'bevacizumabe',
    nome_generico: 'Bevacizumabe',
    sinonimos: ['Avastin', 'anti-VEGF', 'antiangiogênico'],
    categoria: 'oncologia',
    classe: 'Anticorpo monoclonal — anti-VEGF-A (IgG1 humanizado)',
    indicacoes_principais: ['CCR metastático (FOLFOX/IFL + bevacizumabe)', 'CPNPC não escamoso', 'Câncer de ovário (1ª linha + platina)', 'Carcinoma renal (1ª linha + IFN)', 'Glioblastoma multiforme (2ª linha)'],
    dose_adulto: {
      habitual: '5–15 mg/kg IV a cada 14–21 dias (protocolo-dependente)',
      max: '15 mg/kg/dose (CCR)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['A cada 14 dias (biossemanal, CCR)', 'A cada 21 dias (q3w)'],
      instrucoes: '1ª dose: infundir em 90 min. 2ª dose se tolerada: 60 min. Doses seguintes: 30 min. NÃO sacudir o frasco. NÃO filtrar (perda de proteína).',
    },
    contraindicacoes_rapidas: [
      'Cirurgia ≤ 28 dias antes ou planejada (comprometimento de cicatrização)',
      'Hemoptise grave recente',
      'HAS não controlada (> 160/100)',
      'Fístula ativa',
      'Tromboembolismo arterial recente (< 6 meses)',
    ],
    interacoes_importantes: [
      { com: 'Sunitinibe', severidade: 'grave', descricao: 'Combinação não recomendada — casos de anemia hemolítica microangiopática (MAHA) com fragmentação de hemácias e trombocitopenia' },
      { com: 'Antraciclinas (± radioterapia torácica)', severidade: 'moderada', descricao: 'Possível aumento de cardiotoxicidade — cautela e monitorização da FEVE' },
    ],
    alertas_especiais: [
      '⚠ PERFURAÇÃO GI: risco 1–3%; dor abdominal aguda → investigar urgência',
      '⚠ HIPERTENSÃO: desenvolve em 30–40% — monitorar PA a cada ciclo; tratar proativamente',
      '⚠ CICATRIZAÇÃO: suspender 28–42 dias antes de cirurgia eletiva',
      'TEV: ↑ risco venoso; bevacizumabe NÃO contraindica anticoagulação se necessária',
      'Proteinúria: monitorar por dipstick; > 2+: urina 24h; > 2g/24h: reduzir dose',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Avastin', laboratorio: 'Roche', concentracoes: ['25 mg/mL'], formas: ['Concentrado IV'] },
      { nome: 'Zirabev / Mvasi (biossimilar)', laboratorio: 'Pfizer / Amgen', concentracoes: ['25 mg/mL'], formas: ['Concentrado IV'] },
    ],
  },
  {
    id: 'osimertinibe',
    molecula: 'osimertinibe',
    nome_generico: 'Osimertinibe',
    sinonimos: ['Tagrisso', 'anti-EGFR 3ª geração', 'T790M', 'EGFR mutado CPNPC'],
    categoria: 'oncologia',
    classe: 'Inibidor de EGFR 3ª geração (ITK) — EGFR mutado e T790M',
    indicacoes_principais: ['CPNPC metastático com mutação EGFR exon 19 del ou L858R (1ª linha)', 'CPNPC após progressão em EGFR ITK 1ª/2ª geração com T790M (2ª linha)', 'CPNPC adjuvante com EGFR mutado (pós-ressecção)'],
    dose_adulto: {
      habitual: '80 mg/dia VO | 40 mg/dia se toxicidade grau 3 inaceitável',
      max: '80 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (com ou sem alimento)'],
      instrucoes: 'Testar mutação EGFR (tissue ou ctDNA) antes. Pode diluir comprimido em água se disfagia. Monitorar ECG (QTc) em pacientes com HiQT de base.',
    },
    contraindicacoes_rapidas: ['Sem mutação EGFR ativante confirmada', 'QTc > 470 ms pré-tratamento', 'Gravidez'],
    interacoes_importantes: [
      { com: 'rifampicina', severidade: 'grave', descricao: 'Induz CYP3A4 → reduz osimertinibe 78% — CONTRAINDICADO' },
      { com: 'itraconazol', severidade: 'moderada', descricao: 'Inibidor CYP3A4 → pode aumentar exposição' },
    ],
    alertas_especiais: [
      'Penetra barreira hematoencefálica (BHE): eficaz em metástases cerebrais de CPNPC EGFR+',
      'Pneumonite intersticial (3%): suspender se grau ≥ 2',
      'QTc: monitorar especialmente em combinação com outros QT-prolongadores',
      'Resistência adquirida: mecanismos heterogêneos (KRAS, MET, C797S) — biopsia líquida na progressão',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Tagrisso', laboratorio: 'AstraZeneca', concentracoes: ['40 mg', '80 mg'], formas: ['Comprimido revestido'] }],
    guidelines_referencia: ['ESMO CPNPC 2023', 'NCCN 2024'],
  },
  {
    id: 'palbociclibe',
    molecula: 'palbociclibe',
    nome_generico: 'Palbociclibe',
    sinonimos: ['Ibrance', 'CDK4/6 inibidor', 'HR+ HER2- mama'],
    categoria: 'oncologia',
    classe: 'Inibidor de CDK4/6',
    indicacoes_principais: ['Câncer de mama HR+ HER2- metastático (1ª linha + letrozol; 2ª linha + fulvestranto)'],
    dose_adulto: {
      habitual: '125 mg/dia VO × 21 dias → 7 dias pausa (ciclo 28 dias)',
      max: '125 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia com alimento × 21 dias/ciclo'],
      instrucoes: 'Tomar com alimento. Ciclo 28 dias: 21 ON + 7 OFF. Iniciar junto com inibidor de aromatase (letrozol ou anastrozol) ou fulvestranto.',
    },
    contraindicacoes_rapidas: ['Gravidez', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'inibidores CYP3A4 potentes (cetoconazol, claritromicina)', severidade: 'grave', descricao: 'Aumentam exposição ao palbociclibe em até 87%' },
      { com: 'rifampicina', severidade: 'grave', descricao: 'Reduz exposição em 85% — evitar' },
    ],
    alertas_especiais: [
      '⚠ NEUTROPENIA: toxicidade dose-limitante (79%). Monitorar hemograma D1 e D15 de cada ciclo.',
      'Não aumenta risco de infecção grave apesar de neutropenia (neutropenia de "curta duração")',
      'Alopecia: leve (17%) — não universal como QT clássica',
      'Tromboembolismo venoso: ↑ risco — atenção em FR para TEV',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Ibrance', laboratorio: 'Pfizer', concentracoes: ['75 mg', '100 mg', '125 mg'], formas: ['Cápsula'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── ANTIEMESE ─────────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'palonossetrona',
    molecula: 'palonossetrona',
    nome_generico: 'Palonossetrona',
    sinonimos: ['Aloxi', '5-HT3', 'antiemético QT', 'antiemese quimio'],
    categoria: 'gastroenterologia',
    classe: 'Antagonista 5-HT3 de 2ª geração (meia-vida longa)',
    indicacoes_principais: ['Prevenção de náusea e vômito induzidos por quimioterapia (CINV) — fase aguda e tardia'],
    dose_adulto: {
      habitual: '0,25 mg IV dose única (30 min antes da QT) ou 0,5 mg VO',
      max: '0,25 mg/dose IV (não repetir em 7 dias)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Dose única por ciclo (meia-vida 40h — 2ª geração)'],
      instrucoes: 'Administrar em bolus IV em 30 segundos. Única dose por ciclo (meia-vida 40h cobre fase tardia). Superior ao ondansetrona em controle tardio.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade a antagonistas 5-HT3'],
    interacoes_importantes: [
      { com: 'apomorfina', severidade: 'contraindicado', descricao: 'Hipotensão profunda' },
    ],
    alertas_especiais: [
      'Superior ao ondansetrona IV em CINV moderado e alto (fase tardia)',
      'QT: prolongamento mínimo (inferior ao ondansetrona e granisetrona)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Aloxi', laboratorio: 'Eisai / Mundipharma', concentracoes: ['0,05 mg/mL (5 mL = 0,25 mg)'], formas: ['Solução injetável IV'] }],
  },
  {
    id: 'aprepitanto',
    molecula: 'aprepitanto',
    nome_generico: 'Aprepitanto / Fosaprepitanto',
    sinonimos: ['Emend', 'NK1 antagonista', 'anti-NK1', 'antiemese 3 drogas'],
    categoria: 'gastroenterologia',
    classe: 'Antagonista de receptor NK1 (neurocinina-1)',
    indicacoes_principais: ['CINV — QT alto emetogênico (em combinação com 5-HT3 + dexametasona)', 'CINV tardio por cisplatina'],
    dose_adulto: {
      habitual: '125 mg VO D1 → 80 mg VO D2 e D3',
      max: '125 mg/dia (D1)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['D1: 1h antes da QT | D2–D3: manhã'],
      instrucoes: 'Fosaprepitanto 150 mg IV é alternativa dose única D1 (dispensa comprimidos D2–D3). NEPA (netupitanto 300 mg + palonossetrona 0,5 mg): comprimido único antes da QT.',
    },
    contraindicacoes_rapidas: ['Uso com pimozida, cisaprida (inibição CYP3A4 → toxicidade cardíaca)'],
    interacoes_importantes: [
      { com: 'varfarina', severidade: 'grave', descricao: 'Inibe CYP3A4: ↑ varfarina e outros substratos — monitorar INR' },
      { com: 'dexametasona', severidade: 'moderada', descricao: 'Reduz metabolismo de dexametasona em 2× — usar meia dose de dex quando combinado com aprepitanto' },
      { com: 'contraceptivos orais', severidade: 'moderada', descricao: 'Reduz eficácia de ACO — usar método de barreira adicional' },
    ],
    alertas_especiais: [
      'Dexametasona com aprepitanto: reduzir dose da dex para 12 mg (D1) e 8 mg (D2–D4) — farmacocinética',
      'Fosaprepitanto: pró-fármaco IV — reações locais frequentes (dor no sítio de infusão)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Emend', laboratorio: 'MSD', concentracoes: ['80 mg', '125 mg'], formas: ['Cápsula'] },
      { nome: 'Emend IV (fosaprepitanto)', laboratorio: 'MSD', concentracoes: ['150 mg/10 mL'], formas: ['Pó para infusão IV'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── FATORES DE CRESCIMENTO ────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'filgrastim',
    molecula: 'filgrastim',
    nome_generico: 'Filgrastim (G-CSF)',
    sinonimos: ['Neupogen', 'G-CSF', 'fator estimulante de colônias', 'neutropenia quimio'],
    categoria: 'oncologia',
    classe: 'Fator de crescimento de granulócitos — G-CSF recombinante humano',
    indicacoes_principais: ['Profilaxia de neutropenia febril pós-QT (primária e secundária)', 'Neutropenia febril grau 4 (terapêutico)', 'Mobilização de células-tronco para transplante'],
    dose_adulto: {
      habitual: '5 mcg/kg/dia SC (arredondado para frasco disponível: 300 ou 480 mcg)',
      max: '10 mcg/kg/dia',
      unidade: 'mcg/kg',
      via: 'SC',
      frequencias: ['1×/dia até ANC > 10.000/mm³ ou pós-nadir'],
      instrucoes: 'Iniciar 24–72h após última dose de QT. NÃO administrar 24h antes ou no dia da QT. Continuar até nadir passado e ANC ≥ 2000/mm³ em recuperação. Refrigerar 2–8°C.',
    },
    contraindicacoes_rapidas: ['LMA/LMC em tratamento ativo (pode estimular células malignas)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Quimioterápicos citotóxicos', severidade: 'grave', descricao: 'Não administrar nas 24h antes até 24h após a QT — precursores mieloides em proliferação ficam mais sensíveis à citotoxicidade (piora a neutropenia)' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Pode potencializar a liberação de neutrófilos — usar com cautela e monitorar leucograma' },
    ],
    alertas_especiais: [
      'Dor óssea: tratamento com paracetamol ± loratadina',
      'Ruptura esplênica rara — dor abdominal esquerda nova: investigar',
      'Mobilização de stem cells: doses mais altas (10 mcg/kg/dia) por 4–5 dias',
      'Biossimilares disponíveis e aprovados (interchangeability)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Neupogen', laboratorio: 'Amgen', concentracoes: ['300 mcg/mL (1 mL)', '480 mcg/1,6 mL'], formas: ['Solução SC'] },
      { nome: 'Granulokine / Filgrastim (biossimilar)', laboratorio: 'Ratiopharm/Teva', concentracoes: ['300 mcg', '480 mcg'], formas: ['Solução SC'] },
    ],
  },
  {
    id: 'pegfilgrastim',
    molecula: 'pegfilgrastim',
    nome_generico: 'Pegfilgrastim',
    sinonimos: ['Neulasta', 'G-CSF peguilado', 'long-acting G-CSF'],
    categoria: 'oncologia',
    classe: 'Fator de crescimento de granulócitos peguilado (meia-vida prolongada)',
    indicacoes_principais: ['Profilaxia de neutropenia febril pós-QT (primária e secundária) em adultos'],
    dose_adulto: {
      habitual: '6 mg SC — dose única por ciclo',
      max: '6 mg/dose',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['Dose única 24–72h após última dose de QT por ciclo'],
      instrucoes: 'Dose fixa (não depende do peso). 1 injeção por ciclo. NÃO usar em ciclos < 14 dias (overlap com próximo ciclo). Dispositivo On-Body Injector (OBI): injeção automática 27h após fixação — conveniência hospitalar/domiciliar.',
    },
    contraindicacoes_rapidas: ['Ciclos de QT < 14 dias', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Quimioterápicos citotóxicos', severidade: 'grave', descricao: 'Não administrar no mesmo dia da QT — dose única ≥24h após; mesma-dia prolonga a neutropenia grave (ECR)' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Pode potencializar a liberação de neutrófilos — usar com cautela e monitorar leucograma' },
    ],
    alertas_especiais: [
      'Equivalência terapêutica ao filgrastim diário demonstrada em múltiplos ECR',
      'Prefira para pacientes com dificuldade de adesão a filgrastim diário',
      'Dor óssea: igual ao filgrastim — paracetamol + loratadina',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Neulasta', laboratorio: 'Amgen', concentracoes: ['10 mg/mL (0,6 mL = 6 mg)'], formas: ['Seringa pré-cheia SC'] },
      { nome: 'Fulphila / Ziextenzo (biossimilar)', laboratorio: 'Mylan / Sandoz', concentracoes: ['10 mg/mL'], formas: ['Seringa pré-cheia SC'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── PROFILAXIAS / SUPORTE ─────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'mesna',
    molecula: 'mesna',
    nome_generico: 'Mesna (2-Mercaptoetanossulfonato de Sódio)',
    sinonimos: ['Uromitexan', 'protetor bexiga', 'cistite hemorrágica ifosfamida'],
    categoria: 'outro',
    classe: 'Uroprotector — inativador de acroleína',
    indicacoes_principais: ['Prevenção de cistite hemorrágica por ifosfamida', 'Prevenção de cistite hemorrágica por ciclofosfamida em altas doses (> 1 g/m²)'],
    dose_adulto: {
      habitual: '20% da dose de ifosfamida IV em 3 bolus: 0h, 4h e 8h após início da ifosfamida (dose total = 60%)',
      max: '100% da dose de ifosfamida (transplante)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['3 doses no dia da ifosfamida: 0h, 4h e 8h'],
      instrucoes: 'Dose: 20% do peso de ifosfamida em cada bolus × 3. Exemplo: ifosfamida 2 g/m² → mesna 400 mg/m² em 3 × IV. Mesna VO disponível: 40% da dose IV (biodisponibilidade ~50%).',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [],
    alertas_especiais: [
      'INATIVA APENAS NA BEXIGA (via renal) — não interfere com ação antineoplásica da ifosfamida',
      'Hidratação vigorosa (2–3 L/dia) obrigatória em conjunto',
      'Cor alaranjada da urina: normal',
      'Falha de mesna não protege se ifosfamida em infusão contínua — usar mesna em infusão contínua concomitante',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Uromitexan', laboratorio: 'Baxter', concentracoes: ['100 mg/mL (10 mL = 1 g)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'alopurinol-onco',
    molecula: 'alopurinol',
    nome_generico: 'Alopurinol (Profilaxia SLT)',
    sinonimos: ['Zyloric', 'profilaxia hiperuricemia', 'síndrome lise tumoral', 'SLT'],
    categoria: 'outro',
    classe: 'Inibidor de xantina oxidase',
    indicacoes_principais: ['Profilaxia de hiperuricemia e síndrome de lise tumoral (SLT) em risco baixo-intermediário', 'Hiperuricemia crônica (gota)'],
    dose_adulto: {
      habitual: '300 mg/dia VO (SLT profilaxia) | 100–300 mg/dia (gota)',
      max: '800 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–3×/dia', 'Iniciar 24–48h antes da QT'],
      instrucoes: 'Iniciar 24–48h antes da QT. Beber ≥ 2 L/dia. Monitorar ácido úrico, creatinina, eletrólitos.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade (DRESS/SJS graves, principalmente em HLA-B*58:01 — populações asiáticas)'],
    interacoes_importantes: [
      { com: 'mercaptopurina / azatioprina', severidade: 'contraindicado', descricao: 'Inibe metabolismo da 6-MP → toxicidade grave. Reduzir dose de 6-MP em 75% ou substituir por rasburicase' },
      { com: 'amoxicilina', severidade: 'leve', descricao: 'Rash cutâneo aumentado (10× com alopurinol)' },
      { com: 'varfarina', severidade: 'moderada', descricao: 'Pode aumentar INR' },
    ],
    alertas_especiais: [
      '⚠ 6-MERCAPTOPURINA / AZATIOPRINA: CONTRAINDICADO sem redução drástica de dose (inibição da XO acumula 6-MP)',
      'HLA-B*58:01 em Han chineses, tailandeses, coreanos: alto risco de SJS/TEN — triagem genética recomendada antes',
      'Rasburicase preferível em alto risco (dissolve UA já formado)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Zyloric', laboratorio: 'Aspen', concentracoes: ['100 mg', '300 mg'], formas: ['Comprimido'] }],
  },
  {
    id: 'leucovorin',
    molecula: 'leucovorin',
    nome_generico: 'Leucovorin (Ácido Folínico)',
    sinonimos: ['folinato de cálcio', 'resgate de metotrexato', 'ácido folínico', 'LV'],
    categoria: 'oncologia',
    classe: 'Vitamina B9 reduzida — antagonista do metotrexato',
    indicacoes_principais: ['Resgate de metotrexato em altas doses (MTX-AD)', 'Potencialização de 5-FU em protocolos de CCR (FOLFOX, FOLFIRI)', 'Overdose de metotrexato'],
    dose_adulto: {
      habitual: 'Resgate MTX: 15 mg IV/VO 6/6h × 8–12 doses (iniciar 24h após MTX). Ajustar conforme nível sérico.',
      max: '150 mg IV 3/3h (se nível MTX elevado às 24h)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['6/6h (resgate padrão)', '3/3h (toxicidade grave)'],
      instrucoes: 'Nível MTX ≤ 0,1 µmol/L às 48h: suspender leucovorin. Nível > 1 µmol/L às 48h: aumentar para 100–150 mg IV 3/3h. Potencialização de 5-FU: leucovorin 200–400 mg/m² IV antes do bolus de 5-FU (FOLFOX/FOLFIRI).',
    },
    contraindicacoes_rapidas: ['Anemia perniciosa (pode mascarar diagnóstico)'],
    interacoes_importantes: [
      { com: 'metotrexato', severidade: 'moderada', descricao: 'Antagonismo intencional (resgate); NÃO administrar junto ou antes (reduz eficácia do MTX)' },
      { com: 'fluorouracil', severidade: 'leve', descricao: 'Potencialização intencional em FOLFOX/FOLFIRI — sinergia' },
      { com: 'fenobarbital', severidade: 'moderada', descricao: 'Leucovorin pode reduzir eficácia do antiepiléptico' },
    ],
    alertas_especiais: [
      'RESGATE: iniciar EXATAMENTE 24h após início da infusão de MTX-AD — atraso aumenta toxicidade',
      'Monitorar nível sérico de MTX às 24, 48 e 72h',
      'Não confundir com ácido fólico (folato) — leucovorin é a forma reduzida ativa (não requer DHFR)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [{ nome: 'Leucovorin (genérico)', laboratorio: 'Várias', concentracoes: ['10 mg/mL', '50 mg/mL'], formas: ['Ampola IV', 'Comprimido 15 mg'] }],
  },
  {
    id: 'rasburicase',
    molecula: 'rasburicase',
    nome_generico: 'Rasburicase',
    sinonimos: ['Fasturtec', 'uricase recombinante', 'SLT alto risco'],
    categoria: 'oncologia',
    classe: 'Uricase recombinante — enzima degradadora de ácido úrico',
    indicacoes_principais: ['SLT estabelecida ou alto risco', 'Hiperuricemia > 7,5 mg/dL em leucemias/linfomas de alto risco'],
    dose_adulto: {
      habitual: '0,2 mg/kg/dia IV em 30 min × 3–7 dias',
      max: '0,2 mg/kg/dia',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['1×/dia'],
      instrucoes: 'Diluir em SF 50 mL. Infundir em 30 min via linha separada (sem filtro). Coletar amostra de ácido úrico em gelo imediatamente — enzima degrada UA à temperatura ambiente.',
    },
    contraindicacoes_rapidas: ['Deficiência de G6PD (hemólise grave / metahemoglobinemia)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Dosagem de ácido úrico (interferência laboratorial)', severidade: 'moderada', descricao: 'Provoca leitura falsamente baixa de ácido úrico — coletar em tubo gelado com heparina e processar em ≤4 h. Sem interação metabólica com quimioterápicos (não induz/inibe CYP)' },
    ],
    alertas_especiais: [
      '⚠ G6PD: triagem obrigatória antes — hemólise fulminante em deficientes',
      '⚠ AMOSTRA DE AU: coletar em tubo pré-gelado imediatamente — rasburicase ativa degrada UA in vitro',
      'Dissolve ácido úrico já formado (vs alopurinol que apenas previne formação)',
      'Anafilaxia: rara (< 1%) — ter epinefrina disponível',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Fasturtec', laboratorio: 'Sanofi', concentracoes: ['1,5 mg/mL reconst.'], formas: ['Pó liofilizado IV (1,5 mg e 7,5 mg)'] }],
  },
];
