// ============================================================
// PRESCREVE-AI â€” ExtensÃ£o FarmacolÃ³gica: NEUROLOGIA + PSIQUIATRIA (Phase 21.7) â€” Parte B
// Anticonvulsivantes Â· Antidemenciais Â· Estabilizadores de humor Â· HipnÃ³ticos Â· AnsiolÃ­ticos
// Campos adicionais: beers_criteria Â· stopp Â· start Â· pgx_genes
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_NEURO_B: QuickDrug[] = [

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ANTICONVULSIVANTES / ANTIEPILÃ‰PTICOS
  // (topiramato e levetiracetam jÃ¡ em PHARMA_DB)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  {
    id: 'fenitoina',
    molecula: 'FenitoÃ­na',
    nome_generico: 'FenitoÃ­na',
    sinonimos: ['hidantal', 'phenytoin', 'fenitoina', 'difenil-hidantoina', 'anticonvulsivante', 'status epilepticus'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'HidantoÃ­na â€” bloqueio de canais de Na+ voltagem-dependentes â€” farmacocinÃ©tica NÃƒO-LINEAR',
    indicacoes_principais: [
      'Epilepsia focal e generalizada (tonico-clÃ´nica)',
      'Status epilepticus (IV â€” 2Âª escolha apÃ³s BZD)',
      'Profilaxia de convulsÃµes pÃ³s-neurocirurgia',
      'Neuralgia do trigÃªmeo (off-label)',
    ],
    dose_adulto: {
      habitual: '300â€“400 mg/dia VO em 1â€“3 tomadas',
      min: '200 mg/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1â€“3Ã—/dia (com alimento)'],
      instrucoes: 'NÃVEL SÃ‰RICO OBRIGATÃ“RIO: alvo 10â€“20 mcg/mL (livre: 1â€“2 mcg/mL). FarmacocinÃ©tica nÃ£o-linear (Michaelis-Menten): pequenos aumentos de dose â†’ grandes aumentos de nÃ­vel. Status epilepticus IV: 15â€“20 mg/kg em 50 mL SF, velocidade mÃ¡x 50 mg/min. NÃƒO usar em glicose (precipita).',
    },
    ajuste_renal: { normal: '300â€“400 mg/dia', tfg_60_30: 'Monitorar nÃ­vel livre (hipoproteÃ­nemia)', tfg_30_15: 'Monitorar nÃ­vel livre', tfg_lt_15: 'Dosar fraÃ§Ã£o livre (albumina reduzida altera)', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose â€” metabolismo hepÃ¡tico reduzido', child_b: 'Monitorar nÃ­veis', child_c: 'Contraindicado ou dose mÃ­nima' },
    contraindicacoes_rapidas: ['Bradicardia sinusal', 'Bloqueio SA ou AV', 'SÃ­ndrome de Adams-Stokes', 'Hipersensibilidade a hidantoÃ­nas'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'InibiÃ§Ã£o/induÃ§Ã£o CYP2C9 â€” efeito bifÃ¡sico: aumenta depois reduz INR â€” monitorar INR intensivamente' },
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'InduÃ§Ã£o CYP3A4 â€” reduz nÃ­veis de contraceptivo â†’ falha contraceptiva' },
      { com: 'Fluconazol / isoniazida', severidade: 'grave', descricao: 'InibiÃ§Ã£o CYP2C9 â†’ fenitoÃ­na aumenta â†’ toxicidade (ataxia, nistagmo, diplopia)' },
      { com: 'Ãcido valproico', severidade: 'moderada', descricao: 'Desloca fenitoÃ­na da albumina â†’ aumenta fraÃ§Ã£o livre; tambÃ©m inibe metabolismo' },
      { com: 'Carbamazepina', severidade: 'moderada', descricao: 'InduÃ§Ã£o recÃ­proca â€” monitorar nÃ­veis de ambos' },
    ],
    alertas_especiais: [
      'FARMACOCINÃ‰TICA NÃƒO-LINEAR: aumentos de dose acima de 350â€“400 mg/dia podem causar toxicidade sÃºbita (nistagmo, ataxia, confusÃ£o)',
      'BEERS 2023: cautela em idosos â€” toxicidade neurolÃ³gica, interaÃ§Ãµes, induÃ§Ã£o enzimÃ¡tica',
      'SÃNDROME DE HIPERSENSIBILIDADE: febre, rash, linfadenopatia, hepatite â€” suspender imediatamente',
      'INDUÃ‡ÃƒO ENZIMÃTICA: reduz eficÃ¡cia de anticoagulantes, ACO, antivirais HIV, corticoides',
      'IV: monitorar PA e ECG â€” infusÃ£o rÃ¡pida causa hipotensÃ£o grave e arritmias',
      'HLA-B*15:02: sÃ­ndrome de Stevens-Johnson em asiÃ¡ticos â€” testar antes em populaÃ§Ãµes de risco',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos â€” toxicidade com doses usuais; farmacocinÃ©tica nÃ£o-linear aumenta risco em idosos',
    stopp: 'STOPP N1: anticonvulsivante de 1Âª geraÃ§Ã£o em idoso â€” maior risco de toxicidade neurolÃ³gica e quedas',
    pgx_genes: ['CYP2C9 (PM: metabolismo reduzido â†’ toxicidade com doses usuais)', 'CYP2C19 (metabolismo)', 'HLA-B*15:02 (Stevens-Johnson em asiÃ¡ticos)', 'HLA-A*31:01 (reaÃ§Ã£o cutÃ¢nea)'],
    marcas: [
      { nome: 'HidantalÂ®', laboratorio: 'Sanofi', concentracoes: ['100 mg comprimido', '50 mg/mL injetÃ¡vel'], formas: ['Comprimido', 'Ampola IV/IM'] },
      { nome: 'FenitoÃ­na EMS', laboratorio: 'EMS', concentracoes: ['100 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'carbamazepina',
    molecula: 'Carbamazepina',
    nome_generico: 'Carbamazepina',
    sinonimos: ['tegretol', 'carbamazepine', 'carbamazepina', 'anticonvulsivante cbz', 'estabilizador bipolar', 'neuralgia trigemeo'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Dibenzazepina â€” bloqueio canais Na+ + estabilizador de humor â€” forte indutor enzimÃ¡tico',
    indicacoes_principais: [
      'Epilepsia focal (1Âª linha) e tonico-clÃ´nica',
      'Transtorno bipolar â€” fase manÃ­aca (2Âª linha apÃ³s lÃ­tio/valproato)',
      'Neuralgia do trigÃªmeo (1Âª linha farmacolÃ³gica)',
      'Neuropatia diabÃ©tica (off-label)',
    ],
    dose_adulto: {
      habitual: '400â€“1200 mg/dia VO em 2â€“4 tomadas',
      min: '200 mg/dia',
      max: '1600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“4Ã—/dia (CR: 2Ã—/dia)'],
      instrucoes: 'Iniciar 100â€“200 mg/dia, aumentar 100â€“200 mg a cada 1â€“2 semanas. NÃ­vel sÃ©rico alvo: 4â€“12 mcg/mL. AUTOINDUTOR: nÃ­veis caem nas primeiras semanas (induz prÃ³prio metabolismo).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['HistÃ³rico de aplasia medular ou agranulocitose', 'IMAO (Ãºltimas 2 semanas)', 'Hipersensibilidade tricÃ­clicos', 'DeficiÃªncia de P450 2C8 (interaÃ§Ã£o severa com voriconazol)'],
    interacoes_importantes: [
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'Forte indutor CYP3A4 â†’ falha contraceptiva. Usar mÃ©todo nÃ£o-hormonal ou DIU' },
      { com: 'Varfarina / anticoagulantes', severidade: 'grave', descricao: 'InduÃ§Ã£o CYP2C9 â†’ reduz INR â†’ trombose' },
      { com: 'Antirretrovirais HIV (IPs, NNRTIs)', severidade: 'grave', descricao: 'InduÃ§Ã£o â†’ falha terapÃªutica antiretroviral' },
      { com: 'Voriconazol', severidade: 'contraindicado', descricao: 'InduÃ§Ã£o de CYP â†’ voriconazol indetectÃ¡vel; voriconazol tambÃ©m inibe metabolismo da CBZ' },
      { com: 'LÃ­tio', severidade: 'moderada', descricao: 'Sinergia terapÃªutica bipolar; neurotoxicidade aditiva' },
    ],
    alertas_especiais: [
      'HLA-B*15:02: sÃ­ndrome de Stevens-Johnson/NET potencialmente fatal em asiÃ¡ticos â€” TESTAR ANTES em populaÃ§Ãµes de risco (tailandeses, chineses, malaios, filipinos)',
      'HLA-A*31:01: DRESS e SJS em europeus',
      'AUTOINDUTOR: nÃ­vel sÃ©rico cai apÃ³s 2â€“4 semanas â†’ reavaliar dose',
      'HIPONATREMIA: SIADH â€” monitorar sÃ³dio, especialmente em idosos',
      'Beers: cautela em idosos â€” SIADH, interaÃ§Ãµes, quedas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos â€” SIADH, interaÃ§Ãµes medicamentosas extensas, sedaÃ§Ã£o, quedas',
    stopp: 'STOPP N1: anticonvulsivante 1Âª geraÃ§Ã£o em idoso com hiponatremia ou risco de queda',
    pgx_genes: ['HLA-B*15:02 (Stevens-Johnson â€” asiÃ¡ticos)', 'HLA-A*31:01 (DRESS/SJS â€” europeus)', 'CYP2C8 (metabolismo do CBZ-epÃ³xido)', 'CYP3A4 (autoindutor)'],
    marcas: [
      { nome: 'TegretolÂ®', laboratorio: 'Novartis', concentracoes: ['200 mg', '400 mg CR'], formas: ['Comprimido', 'Comprimido CR (liberaÃ§Ã£o controlada)'], lab_id: 'novartis' },
      { nome: 'Carbamazepina EMS', laboratorio: 'EMS', concentracoes: ['200 mg', '400 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'acido-valproico',
    molecula: 'Ãcido ValprÃ³ico / Valproato de SÃ³dio',
    nome_generico: 'Ãcido ValprÃ³ico',
    sinonimos: ['depakene', 'depakote', 'valproate', 'valproato', 'valproico', 'anticonvulsivante vpa', 'estabilizador bipolar valproato', 'enxaqueca profilaxia valproato'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Ãcido carboxÃ­lico â€” mecanismo mÃºltiplo: bloqueia canais Na+, aumenta GABA, inibe HDAC',
    indicacoes_principais: [
      'Epilepsia â€” amplo espectro (todas as formas, incluindo ausÃªncia, mioclÃ´nica)',
      'Transtorno bipolar â€” mania aguda e profilaxia (1Âª linha)',
      'Enxaqueca (profilaxia)',
      'DepressÃ£o bipolar (adjuvante)',
    ],
    dose_adulto: {
      habitual: '500â€“1500 mg/dia em 2â€“3 tomadas',
      min: '250 mg/dia',
      max: '3000 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“3Ã—/dia (IR) | 1â€“2Ã—/dia (DR/LP)'],
      instrucoes: 'NÃ­vel sÃ©rico alvo epilepsia: 50â€“100 mcg/mL; bipolar: 50â€“125 mcg/mL. Formas: Ã¡cido valprÃ³ico (Depakene), valproato de sÃ³dio (Epilim), divalproato (Depakote DR). Tomar com alimento.',
    },
    ajuste_renal: { normal: 'Sem ajuste (ligaÃ§Ã£o proteica â€” dosar fraÃ§Ã£o livre em DRC)', tfg_60_30: 'Monitorar nÃ­vel livre', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Reduzir dose', dialisavel: true },
    ajuste_hepatico: { child_a: 'Contraindicado (hepatotÃ³xico â€” suspeita de mitocondriopatia)', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Hepatopatia ou disfunÃ§Ã£o hepÃ¡tica grave',
      'DeficiÃªncia de urea cycle (ciclo da ureia)',
      'GRAVIDEZ â€” especialmente 1Âº trimestre (espinha bÃ­fida, malformaÃ§Ãµes, dÃ©ficit neurocognitivo)',
      'Porfiria',
    ],
    interacoes_importantes: [
      { com: 'Carbamazepina', severidade: 'moderada', descricao: 'Eleva epÃ³xido-CBZ (metabÃ³lito tÃ³xico) â€” toxicidade da carbamazepina' },
      { com: 'Lamotrigina', severidade: 'grave', descricao: 'Inibe glucuronidaÃ§Ã£o da lamotrigina â†’ duplica nÃ­vel â†’ SJS/rash grave â€” reduzir lamotrigina 50% ao combinar' },
      { com: 'FenitoÃ­na', severidade: 'moderada', descricao: 'Desloca fenitoÃ­na da albumina â€” aumenta fraÃ§Ã£o livre' },
      { com: 'Aspirina (altas doses)', severidade: 'moderada', descricao: 'Desloca valproato â€” aumenta fraÃ§Ã£o livre' },
    ],
    alertas_especiais: [
      'TERATOGENICIDADE: BLACK BOX â€” risco de espinha bÃ­fida 1â€“2%, outras malformaÃ§Ãµes cardÃ­acas, neurocognitivas. EVITAR em mulheres em idade fÃ©rtil sem contracepÃ§Ã£o dupla eficaz',
      'HEPATOTOXICIDADE: potencialmente fatal, especialmente em < 2 anos com polifarmÃ¡cia antiepilÃ©ptica â€” monitorar TGO/TGP',
      'PANCREATITE: rara mas grave â€” dor abdominal â†’ suspender',
      'HIPERAMONEMIA: mesmo com TGP normal â€” monitorar em letargia pÃ³s-inÃ­cio',
      'Beers: EVITAR em idosos com trombocitopenia ou hepatopatia',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: cautela em idosos â€” trombocitopenia, hepatotoxicidade, sedaÃ§Ã£o',
    stopp: 'STOPP N2: valproato em mulher em idade fÃ©rtil sem dupla contracepÃ§Ã£o confirmada',
    start: 'START C4: valproato em bipolar com mania grave sem resposta a lÃ­tio',
    pgx_genes: ['POLG (polimerase gama mitocondrial â€” sÃ­ndrome de Alpers: contraindicado)', 'UGT (glucuronidaÃ§Ã£o â€” interaÃ§Ã£o com lamotrigina)'],
    marcas: [
      { nome: 'DepakeneÂ®', laboratorio: 'Abbott/AbbVie', concentracoes: ['250 mg', '500 mg'], formas: ['CÃ¡psula', 'SoluÃ§Ã£o oral'] },
      { nome: 'DepakoteÂ®', laboratorio: 'Abbott/AbbVie', concentracoes: ['250 mg', '500 mg DR'], formas: ['Comprimido DR (divalproato)'] },
      { nome: 'Valproato EMS', laboratorio: 'EMS', concentracoes: ['250 mg', '500 mg'], formas: ['CÃ¡psula'] },
    ],
  },

  {
    id: 'lamotrigina',
    molecula: 'Lamotrigina',
    nome_generico: 'Lamotrigina',
    sinonimos: ['lamictal', 'lamotrigine', 'lamotrigina', 'anticonvulsivante lam', 'bipolar depressÃ£o lamotrigina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Fenilamina â€” bloqueio canais Na+/Ca2+ â€” primeira escolha em epilepsia focal em mulheres em idade fÃ©rtil',
    indicacoes_principais: [
      'Epilepsia focal e generalizada (1Âª linha mulheres em idade fÃ©rtil)',
      'Epilepsia de ausÃªncia (adjuvante)',
      'Transtorno bipolar â€” manutenÃ§Ã£o (especialmente prevenÃ§Ã£o depressÃ£o bipolar)',
      'SÃ­ndrome de Lennox-Gastaut (adjuvante)',
    ],
    dose_adulto: {
      habitual: '100â€“200 mg/dia em monoterapia | 50â€“100 mg/dia com valproato | 300â€“500 mg/dia com indutores enzimÃ¡ticos',
      min: '25 mg/dia',
      max: '700 mg/dia (com indutores)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1â€“2Ã—/dia'],
      instrucoes: 'TITULAÃ‡ÃƒO LENTA OBRIGATÃ“RIA: iniciar 25 mg a cada 2 dias (com valproato) ou 25 mg/dia (monoterapia) Ã— 2 semanas â†’ aumentar MUITO devagar (rash SJS depende da velocidade). InteraÃ§Ã£o valproato: duplica nÃ­vel de lamotrigina â†’ reduzir dose 50%.',
    },
    ajuste_renal: { normal: 'Sem ajuste em DRC leve', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Reduzir dose (acÃºmulo metabÃ³lito)', tfg_lt_15: 'Reduzir dose significativamente', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir 25%', child_c: 'Reduzir 50%' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'HistÃ³rico de rash grave com lamotrigina'],
    interacoes_importantes: [
      { com: 'Valproato', severidade: 'grave', descricao: 'Inibe glucuronidaÃ§Ã£o â†’ dobra nÃ­vel de lamotrigina â†’ SJS. REDUZIR DOSE pela metade ao adicionar valproato' },
      { com: 'Carbamazepina / fenitoÃ­na / rifampicina (indutores)', severidade: 'moderada', descricao: 'Aumentam metabolismo â†’ lamotrigina cai â†’ perda de eficÃ¡cia. Dobrar dose quando associado' },
      { com: 'Contraceptivos orais (estrÃ³geno)', severidade: 'moderada', descricao: 'EstrogÃªnio aumenta glucuronidaÃ§Ã£o â†’ lamotrigina cai 50% â†’ perda de controle de crises' },
    ],
    alertas_especiais: [
      'RASH/SJS: titulaÃ§Ã£o MUITO lenta Ã© mandatÃ³ria â€” rash grave nas primeiras 8 semanas, especialmente com valproato e titulaÃ§Ã£o rÃ¡pida',
      'ANTICONVULSIVANTE PREFERIDO EM MULHERES GRÃVIDAS (menor teratogenicidade vs valproato/carbamazepina) â€” mas monitorar nÃ­veis na gravidez (metabolismo aumenta)',
      'BIPOLAR: melhor evidÃªncia para prevenÃ§Ã£o de depressÃ£o bipolar (vs lÃ­tio que previne mania)',
      'Menor sedaÃ§Ã£o que CBZ/VPA â€” nÃ£o prejudica cogniÃ§Ã£o',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: nÃ£o listado especificamente â€” melhor tolerabilidade em idosos vs CBZ/VPA',
    pgx_genes: ['UGT1A4 (glucuronidaÃ§Ã£o â€” interaÃ§Ãµes com valproato e ACO)', 'SCN1A (resposta â€” epilepsia Dravet)'],
    marcas: [
      { nome: 'LamictalÂ®', laboratorio: 'GSK', concentracoes: ['25 mg', '50 mg', '100 mg', '200 mg'], formas: ['Comprimido', 'Comprimido dispersÃ­vel'] },
      { nome: 'Lamotrigina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '50 mg', '100 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'gabapentina',
    indicacao_contexto: 'Epilepsia / dor neuropática (geral)',
    molecula: 'Gabapentina',
    nome_generico: 'Gabapentina',
    sinonimos: ['neurontin', 'gabapentin', 'gabapentina', 'anticonvulsivante neuropatia', 'dor neuropatica gabapentina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'AnÃ¡logo do GABA â€” liga-se Ã  subunidade Î±2Î´-1 dos canais de Ca2+ voltagem-dependentes',
    indicacoes_principais: [
      'Epilepsia focal (adjuvante)',
      'Neuropatia diabÃ©tica dolorosa',
      'Neuralgia pÃ³s-herpÃ©tica',
      'SÃ­ndrome das pernas inquietas (off-label â€” dose baixa)',
      'Dor crÃ´nica, fibromialgia (off-label)',
      'AbstinÃªncia alcoÃ³lica (off-label)',
    ],
    dose_adulto: {
      habitual: '300â€“1800 mg/dia em 3 tomadas iguais',
      min: '100â€“300 mg/dia',
      max: '3600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3Ã—/dia (TID â€” meia-vida curta)'],
      instrucoes: 'Iniciar 100â€“300 mg 3Ã—/dia. Titular a cada 3â€“7 dias. Neuropatia: 1800â€“3600 mg/dia. Ajuste RENAL OBRIGATÃ“RIO (excreÃ§Ã£o renal intacta). AbsorÃ§Ã£o nÃ£o-linear: doses acima de 600 mg/dose tÃªm absorÃ§Ã£o proporcionalmente menor.',
    },
    ajuste_renal: { normal: '300â€“1200 mg TID', tfg_60_30: '200â€“700 mg TID', tfg_30_15: '200â€“700 mg BID', tfg_lt_15: '100â€“300 mg diÃ¡rio', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste (nÃ£o metabolizada)', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Pancreatite aguda (relatos)'],
    interacoes_importantes: [
      { com: 'Opioides', severidade: 'grave', descricao: 'DepressÃ£o respiratÃ³ria aditiva â€” risco de morte. CombinaÃ§Ã£o cada vez mais associada a overdose fatal' },
      { com: 'AntiÃ¡cidos (alumÃ­nio/magnÃ©sio)', severidade: 'leve', descricao: 'Reduz absorÃ§Ã£o de gabapentina em 20% â€” separar por 2h' },
      { com: 'Ãlcool / BZD / outros depressores SNC', severidade: 'moderada', descricao: 'SedaÃ§Ã£o aditiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: cautela em idosos â€” sedaÃ§Ã£o, tontura, quedas, ataxia',
      'POTENCIAL DE ABUSO: classificada como substÃ¢ncia controlada em vÃ¡rios estados/paÃ­ses â€” uso recreativo crescente',
      'OPIOIDES + GABAPENTINA: combinaÃ§Ã£o de alto risco â€” depressÃ£o respiratÃ³ria fatal documentada',
      'AJUSTE RENAL CRÃTICO: eliminaÃ§Ã£o 100% renal â€” toxicidade em DRC sem ajuste',
      'NÃ£o possui interaÃ§Ãµes CYP (sem metabolismo hepÃ¡tico) â€” vantagem em polifarmÃ¡cia',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos â€” sedaÃ§Ã£o e risco de queda; reduzir dose em DRC',
    stopp: 'STOPP N3: gabapentina/pregabalina em idoso com TFG < 30 sem ajuste de dose',
    pgx_genes: [],
    marcas: [
      { nome: 'NeurontinÂ®', laboratorio: 'Pfizer', concentracoes: ['100 mg', '300 mg', '400 mg'], formas: ['CÃ¡psula'], lab_id: 'pfizer' },
      { nome: 'Gabapentina EMS', laboratorio: 'EMS', concentracoes: ['300 mg', '400 mg'], formas: ['CÃ¡psula'] },
    ],
  },

  {
    id: 'pregabalina',
    molecula: 'Pregabalina',
    nome_generico: 'Pregabalina',
    sinonimos: ['lyrica', 'pregabalin', 'pregabalina', 'anticonvulsivante neuropatia pregabalina', 'fibromialgia lyrica', 'ansiedade pregabalina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'AnÃ¡logo do GABA â€” liga Î±2Î´-1 â€” absorÃ§Ã£o LINEAR (diferente da gabapentina)',
    indicacoes_principais: [
      'Neuropatia diabÃ©tica dolorosa',
      'Neuralgia pÃ³s-herpÃ©tica',
      'Fibromialgia (aprovado FDA)',
      'Epilepsia focal (adjuvante)',
      'Transtorno de ansiedade generalizada (aprovado EMA â€” fora do Brasil oficialmente)',
      'Dor de medula espinhal',
    ],
    dose_adulto: {
      habitual: '75â€“150 mg VO 2Ã—/dia',
      min: '25 mg/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“3Ã—/dia'],
      instrucoes: 'Iniciar 75 mg 2Ã—/dia. Titular a cada semana. Ansiedade: 150â€“600 mg/dia. Vantagem sobre gabapentina: absorÃ§Ã£o linear â†’ mais previsÃ­vel. Desmame gradual (convulsÃµes de retirada).',
    },
    ajuste_renal: { normal: '150â€“600 mg/dia', tfg_60_30: '75â€“300 mg/dia', tfg_30_15: '25â€“150 mg/dia', tfg_lt_15: '25â€“75 mg/dia', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste (nÃ£o metabolizada)', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Angioedema prÃ©vio com pregabalina'],
    interacoes_importantes: [
      { com: 'Opioides', severidade: 'grave', descricao: 'DepressÃ£o respiratÃ³ria aditiva â€” combinaÃ§Ã£o de alto risco' },
      { com: 'BZD / Ã¡lcool', severidade: 'moderada', descricao: 'SedaÃ§Ã£o aditiva' },
      { com: 'Tiazolidinedionas (pioglitazona)', severidade: 'leve', descricao: 'Edema perifÃ©rico aditivo' },
    ],
    alertas_especiais: [
      'SUBSTÃ‚NCIA CONTROLADA: Portaria 344/98 â€” lista C1. Potencial de abuso elevado',
      'BEERS 2023: cautela em idosos â€” sedaÃ§Ã£o e risco de queda; dose reduzida',
      'ANGIOEDEMA: risco de angioedema â€” suspender se inchaÃ§o facial/lÃ­ngua',
      'GANHO DE PESO: efeito adverso frequente com uso crÃ´nico',
      'Vantagem vs gabapentina: 2Ã—/dia, absorÃ§Ã£o linear, mais estudada em TAG',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos â€” sedaÃ§Ã£o, quedas, ajuste renal necessÃ¡rio',
    stopp: 'STOPP N3: pregabalina em idoso com TFG < 30 sem ajuste',
    pgx_genes: [],
    marcas: [
      { nome: 'LyricaÂ®', laboratorio: 'Pfizer', concentracoes: ['25 mg', '75 mg', '150 mg', '300 mg'], formas: ['CÃ¡psula'], lab_id: 'pfizer' },
      { nome: 'Pregabalina EMS', laboratorio: 'EMS', concentracoes: ['75 mg', '150 mg', '300 mg'], formas: ['CÃ¡psula'] },
    ],
  },

  {
    id: 'oxcarbazepina',
    molecula: 'Oxcarbazepina',
    nome_generico: 'Oxcarbazepina',
    sinonimos: ['trileptal', 'oxcarbazepine', 'oxcarbazepina', 'anticonvulsivante trileptal', 'cbz analogia'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Ceto-anÃ¡logo da carbamazepina â€” sem epÃ³xido ativo â€” menos interaÃ§Ãµes que CBZ',
    indicacoes_principais: [
      'Epilepsia focal (mono ou politerapia)',
      'Neuralgia do trigÃªmeo (alternativa Ã  carbamazepina)',
    ],
    dose_adulto: {
      habitual: '600â€“1200 mg/dia em 2 tomadas',
      min: '300 mg/dia',
      max: '2400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2Ã—/dia'],
      instrucoes: 'Iniciar 150â€“300 mg 2Ã—/dia. Aumentar 150â€“300 mg a cada semana. Vantagem sobre carbamazepina: sem metabÃ³lito epÃ³xido ativo, menos interaÃ§Ãµes, sem autoindutor. Monitorar sÃ³dio (SIADH frequente).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Iniciar com 50% da dose usual', tfg_30_15: 'Reduzir 50% â€” cautela', tfg_lt_15: 'NÃ£o recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'NÃ£o recomendado' },
    contraindicacoes_rapidas: ['Hipersensibilidade Ã  carbamazepina (15â€“25% cross-reatividade)', 'HLA-B*15:02 (asiÃ¡ticos â€” risco SJS)'],
    interacoes_importantes: [
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'InduÃ§Ã£o moderada CYP3A4 â†’ falha contraceptiva' },
      { com: 'FenitoÃ­na', severidade: 'moderada', descricao: 'Aumenta nÃ­vel de fenitoÃ­na â€” monitorar' },
    ],
    alertas_especiais: [
      'HIPONATREMIA: mais frequente que com CBZ â€” monitorar Na+ especialmente em idosos e com diurÃ©ticos',
      'HLA-B*15:02: testar em asiÃ¡ticos (SJS) â€” menor risco que CBZ mas existe',
      'Vantagem: sem autoindutor, menos interaÃ§Ãµes CYP que CBZ',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos â€” SIADH/hiponatremia',
    stopp: 'STOPP N1: anticonvulsivante que causa hiponatremia em idoso jÃ¡ hiponatrÃªmico',
    pgx_genes: ['HLA-B*15:02 (SJS em asiÃ¡ticos)', 'HLA-A*31:01 (rash em europeus)'],
    marcas: [
      { nome: 'TrileptalÂ®', laboratorio: 'Novartis', concentracoes: ['150 mg', '300 mg', '600 mg'], formas: ['Comprimido', 'SuspensÃ£o oral'], lab_id: 'novartis' },
      { nome: 'Oxcarbazepina EMS', laboratorio: 'EMS', concentracoes: ['300 mg', '600 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'fenobarbital',
    indicacao_contexto: 'Epilepsia (geral)',
    molecula: 'Fenobarbital',
    nome_generico: 'Fenobarbital',
    sinonimos: ['gardenal', 'phenobarbital', 'fenobarbital', 'barbiturico anticonvulsivante', 'gardenal epilepsia'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'BarbitÃºrico â€” potencializa GABA-A (aumenta duraÃ§Ã£o de abertura do canal Cl-)',
    indicacoes_principais: [
      'Epilepsia â€” amplo espectro (nÃ£o auÃªncia pura)',
      'Status epilepticus (IV â€” 3Âª linha apÃ³s BZD e fenitoÃ­na)',
      'AbstinÃªncia alcoÃ³lica grave',
      'ConvulsÃµes neonatais',
      'Hiperbilirrubinemia neonatal (induÃ§Ã£o UGT)',
    ],
    dose_adulto: {
      habitual: '60â€“180 mg/dia VO (1Ã—/dia Ã  noite)',
      min: '30 mg/dia',
      max: '240 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1Ã—/dia (meia-vida longa 50â€“144h) â€” noite pela sedaÃ§Ã£o'],
      instrucoes: 'NÃ­vel sÃ©rico alvo: 15â€“40 mcg/mL. Status epilepticus IV: 15â€“20 mg/kg em 30 min (mÃ¡x 100 mg/min). TolerÃ¢ncia Ã  sedaÃ§Ã£o em semanas. FORTE indutor enzimÃ¡tico (CYP2C9, 2C19, 3A4, UGT).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: true },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Porfiria intermitente aguda', 'DepressÃ£o respiratÃ³ria grave', 'Hipersensibilidade a barbitÃºricos'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'InduÃ§Ã£o CYP2C9 â†’ reduz INR â†’ trombose' },
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'InduÃ§Ã£o â†’ falha contraceptiva' },
      { com: 'Corticoides', severidade: 'moderada', descricao: 'InduÃ§Ã£o â†’ reduz eficÃ¡cia de corticoide' },
      { com: 'BZD / Ã¡lcool', severidade: 'moderada', descricao: 'DepressÃ£o SNC aditiva â€” perigoso em overdose' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos â€” sedaÃ§Ã£o excessiva, queda, tolerÃ¢ncia e dependÃªncia',
      'FORTE INDUTOR ENZIMÃTICO: mÃºltiplas interaÃ§Ãµes â€” varfarina, ACO, antiretrovirais, antibiÃ³ticos, imunossupressores',
      'DEPENDÃŠNCIA FÃSICA: sÃ­ndrome de abstinÃªncia grave (convulsÃµes) â€” nunca suspender abruptamente',
      'SEDAÃ‡ÃƒO: tolerÃ¢ncia Ã  sedaÃ§Ã£o em 2â€“4 semanas; tolerÃ¢ncia Ã  eficÃ¡cia anticonvulsivante NÃƒO ocorre',
      'DÃ©ficit cognitivo crÃ´nico especialmente em crianÃ§as â€” evitar em pediatria',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos â€” risco de sedaÃ§Ã£o, dependÃªncia, quedas',
    stopp: 'STOPP N1: fenobarbital em idoso com risco de queda ou demÃªncia',
    pgx_genes: ['CYP2C9 (metabolismo e induÃ§Ã£o)', 'CYP2C19 (induÃ§Ã£o)'],
    marcas: [
      { nome: 'GardenalÂ®', laboratorio: 'Sanofi', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
      { nome: 'FenocrisÂ®', laboratorio: 'CristÃ¡lia', concentracoes: ['40 mg/mL soluÃ§Ã£o injetÃ¡vel'], formas: ['Ampola IV'] },
    ],
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ANTIDEMENCIAIS
  // (donepezila e memantina jÃ¡ em PHARMA_DB)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  {
    id: 'rivastigmina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Rivastigmina',
    nome_generico: 'Tartarato de Rivastigmina',
    sinonimos: ['exelon', 'rivastigmine', 'rivastigmina', 'antidemencial patch', 'alzheimer rivastigmina', 'parkinson demencia'],
    categoria: 'neurologico',
    classe: 'Antidemencial',
    subclasse: 'Inibidor da acetilcolinesterase E butirrilcolinesterase (pseudo-irreversÃ­vel)',
    indicacoes_principais: [
      'DoenÃ§a de Alzheimer leve a moderada',
      'DemÃªncia da doenÃ§a de Parkinson (Ãºnica aprovada especificamente)',
      'DemÃªncia com corpos de Lewy (off-label)',
    ],
    dose_adulto: {
      habitual: '4,6 mg/24h patch (iniciar) â†’ 9,5 mg/24h â†’ 13,3 mg/24h | VO: 1,5â€“6 mg 2Ã—/dia',
      min: '4,6 mg/24h patch | 1,5 mg VO 2Ã—/dia',
      max: '13,3 mg/24h patch | 12 mg/dia VO',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['Patch: 1Ã—/dia (trocar a cada 24h) | VO: 2Ã—/dia com alimento'],
      instrucoes: 'PATCH preferÃ­vel: menor incidÃªncia de nÃ¡useas/vÃ´mitos (liberaÃ§Ã£o gradual). Aplicar em costas, ombros ou parte superior do braÃ§o (nÃ£o seios, virilha ou abdome). Titular patch a cada 4 semanas. Rivastigmina: Ãºnica aprovada em demÃªncia de Parkinson.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela â€” reduzir dose', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'ReaÃ§Ã£o cutÃ¢nea grave ao patch anterior', 'DoenÃ§a do nÃ³ sinusal ou bloqueio AV'],
    interacoes_importantes: [
      { com: 'AnticolinÃ©rgicos (biperideno, oxibutinina, amitriptilina)', severidade: 'moderada', descricao: 'Efeito antagonista â€” reduz eficÃ¡cia da rivastigmina' },
      { com: 'Betabloqueadores / outros bradicardizantes', severidade: 'moderada', descricao: 'Bradicardia sinÃ©rgica' },
      { com: 'Succinilcolina (cirurgia)', severidade: 'moderada', descricao: 'Prolonga bloqueio neuromuscular â€” informar anestesista' },
    ],
    alertas_especiais: [
      'ÃšNICA APROVADA EM DEMÃŠNCIA DE PARKINSON â€” donepezila pode piorar sintomas extrapiramidais em Parkinson',
      'NÃUSEAS/VÃ”MITOS: principal motivo de abandono. Patch reduz em 70% vs VO',
      'NÃ£o misturar patches (risco de superdose colinÃ©rgica)',
      'START: considerar IChE em Alzheimer leve-moderado (evidÃªncia forte)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: uso apropriado em Alzheimer/demÃªncia Parkinson â€” nÃ£o listado como inapropriado',
    start: 'START B7: inibidor da colinesterase em demÃªncia de Alzheimer ou Parkinson leve a moderada',
    pgx_genes: ['BCHE (butirrilcolinesterase â€” variante K: reduz eficÃ¡cia; variante A: deficiÃªncia â€” toxicidade)'],
    marcas: [
      { nome: 'ExelonÂ® Patch', laboratorio: 'Novartis', concentracoes: ['4,6 mg/24h', '9,5 mg/24h', '13,3 mg/24h'], formas: ['Adesivo transdÃ©rmico'], lab_id: 'novartis' },
      { nome: 'ExelonÂ® cÃ¡psulas', laboratorio: 'Novartis', concentracoes: ['1,5 mg', '3 mg', '4,5 mg', '6 mg'], formas: ['CÃ¡psula'] },
      { nome: 'Rivastigmina EMS', laboratorio: 'EMS', concentracoes: ['1,5 mg', '3 mg'], formas: ['CÃ¡psula'] },
    ],
  },

  {
    id: 'galantamina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Galantamina',
    nome_generico: 'Bromidrato de Galantamina',
    sinonimos: ['reminyl', 'galantamine', 'galantamina', 'antidemencial galantamina', 'alzheimer galantamina'],
    categoria: 'neurologico',
    classe: 'Antidemencial',
    subclasse: 'Inibidor da AChE + modulador alostÃ©rico dos receptores nicotÃ­nicos (aÃ§Ã£o dupla)',
    indicacoes_principais: [
      'DoenÃ§a de Alzheimer leve a moderada',
    ],
    dose_adulto: {
      habitual: '8â€“16 mg/dia LP (1Ã—/dia) | 4â€“12 mg 2Ã—/dia (IR)',
      min: '4 mg 2Ã—/dia (IR) | 8 mg/dia (LP)',
      max: '24 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['LP: 1Ã—/dia (manhÃ£) | IR: 2Ã—/dia com alimento'],
      instrucoes: 'Titular lentamente (menor risco GI). LP: preferir por comodidade posolÃ³gica. NÃ£o aprovada em demÃªncia vascular ou demÃªncia de Parkinson (ao contrÃ¡rio de rivastigmina).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'MÃ¡x 16 mg/dia', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'MÃ¡x 16 mg/dia', child_b: 'MÃ¡x 8 mg/dia', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['DRC grave (TFG < 9)', 'InsuficiÃªncia hepÃ¡tica grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'AnticolinÃ©rgicos', severidade: 'moderada', descricao: 'Antagonismo â€” reduz eficÃ¡cia' },
      { com: 'Paroxetina / fluoxetina (CYP2D6)', severidade: 'moderada', descricao: 'InibiÃ§Ã£o CYP2D6 e 3A4 â†’ galantamina aumenta â†’ nÃ¡useas/vÃ´mitos' },
      { com: 'Cetoconazol / eritromicina (CYP3A4)', severidade: 'moderada', descricao: 'Aumenta galantamina â†’ mais efeitos GI' },
    ],
    alertas_especiais: [
      'AÃ‡ÃƒO DUAL: IChE + nicotÃ­nico â€” potencialmente sinÃ©rgico, mas diferenÃ§a clÃ­nica vs donepezila Ã© pequena',
      'START: indicado em Alzheimer leve-moderado como antidemencial',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    start: 'START B7: inibidor da colinesterase em demÃªncia de Alzheimer leve-moderada',
    pgx_genes: ['CYP2D6 (PM: galantamina aumenta â†’ mais efeitos GI)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'ReminylÂ®', laboratorio: 'Janssen', concentracoes: ['4 mg', '8 mg', '12 mg'], formas: ['Comprimido'] },
      { nome: 'ReminylÂ® LP', laboratorio: 'Janssen', concentracoes: ['8 mg', '16 mg', '24 mg'], formas: ['CÃ¡psula LP'] },
      { nome: 'Galantamina EMS', laboratorio: 'EMS', concentracoes: ['4 mg', '8 mg'], formas: ['Comprimido'] },
    ],
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // HIPNÃ“TICOS
  // (zolpidem jÃ¡ em PHARMA_DB)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  {
    id: 'zopiclona',
    molecula: 'Zopiclona',
    nome_generico: 'Zopiclona',
    sinonimos: ['imovane', 'zopiclone', 'zopiclona', 'hipnotico z-drug', 'insonia zopiclona'],
    categoria: 'psiquiatria',
    classe: 'HipnÃ³tico',
    subclasse: 'Ciclopirrolona (Z-drug) â€” agonista do receptor GABA-A no sÃ­tio BZD (diferente da estrutura BZD)',
    indicacoes_principais: [
      'InsÃ´nia aguda (â‰¤ 4 semanas)',
    ],
    dose_adulto: {
      habitual: '7,5 mg VO antes de dormir',
      min: '3,75 mg (idosos â€” INICIAR aqui)',
      max: '7,5 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1Ã—/dia (antes de dormir)'],
      instrucoes: 'USO MÃXIMO 4 SEMANAS. Idosos: iniciar 3,75 mg (Beers). Sabor amargo (gosto metÃ¡lico caracterÃ­stico). NÃ£o associar a Ã¡lcool. Efeito residual matutino comum (cautela ao dirigir).',
    },
    ajuste_renal: { normal: '7,5 mg', tfg_60_30: '3,75â€“7,5 mg', tfg_30_15: '3,75 mg', tfg_lt_15: '3,75 mg â€” cautela', dialisavel: false },
    ajuste_hepatico: { child_a: '3,75 mg', child_b: '3,75 mg', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'InsuficiÃªncia respiratÃ³ria grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Ãlcool / BZD / opioides', severidade: 'grave', descricao: 'DepressÃ£o SNC e respiratÃ³ria aditiva â€” overdose' },
      { com: 'Eritromicina / cetoconazol (CYP3A4)', severidade: 'moderada', descricao: 'Aumenta zopiclona â€” sedaÃ§Ã£o excessiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos â€” risco de queda, confusÃ£o, dependÃªncia. Se imprescindÃ­vel: 3,75 mg mÃ¡ximo',
      'DEPENDÃŠNCIA FÃSICA: pode ocorrer em semanas â€” descontinuaÃ§Ã£o gradual',
      'COMPORTAMENTOS COMPLEXOS DO SONO: sonambulismo, alimentaÃ§Ã£o noturna sem memÃ³ria â€” suspender',
      'NÃƒO Ã‰ SUPERIOR A BZD em seguranÃ§a de dependÃªncia â€” benefÃ­cio de marketing superestimado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos â€” Z-drugs causam quedas, fraturas, delirium',
    stopp: 'STOPP D2: hipnÃ³tico Z-drug em idoso â€” risco de queda e dependÃªncia',
    pgx_genes: ['CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'ImovaneÂ®', laboratorio: 'Sanofi', concentracoes: ['7,5 mg'], formas: ['Comprimido'] },
      { nome: 'Zopiclona EMS', laboratorio: 'EMS', concentracoes: ['7,5 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'midazolam',
    indicacao_contexto: 'Sedação / ansiólise (geral)',
    molecula: 'Midazolam',
    nome_generico: 'Maleato de Midazolam',
    sinonimos: ['dormicum', 'midazolam', 'benzodiazepÃ­nico iv', 'sedacao procedimento', 'midazolam status epilepticus'],
    categoria: 'psiquiatria',
    classe: 'BenzodiazepÃ­nico',
    subclasse: 'BZD de aÃ§Ã£o ultracurta â€” agonista GABA-A â€” lipossolÃºvel, IV/IM/intranasal/bucal',
    indicacoes_principais: [
      'SedaÃ§Ã£o para procedimentos (endoscopia, cardioversÃ£o, pequenos procedimentos)',
      'InduÃ§Ã£o anestÃ©sica',
      'Status epilepticus (IM/IV â€” 1Âª linha em prÃ©-hospitalar como alternativa ao diazepam)',
      'SedaÃ§Ã£o em UTI (infusÃ£o contÃ­nua)',
      'Crises convulsivas agudas (intranasal, bucal â€” uso domiciliar em epilepsia refratÃ¡ria)',
    ],
    dose_adulto: {
      habitual: '1â€“5 mg IV lento (sedaÃ§Ã£o procedimento) | 10 mg IM (status epilepticus prÃ©-hospitalar)',
      min: '0,5 mg IV (idoso)',
      max: '0,2 mg/kg IV (induÃ§Ã£o anestÃ©sica)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Dose Ãºnica (procedimento) | InfusÃ£o contÃ­nua (UTI)'],
      instrucoes: 'IV: administrar lentamente (0,5 mg/min) â€” apneia se rÃ¡pido. ANTÃDOTO: flumazenil 0,2 mg IV. IM status: 10 mg adulto (â‰¥ 40 kg). Intranasal: 0,2 mg/kg (crises domiciliares).',
    },
    ajuste_renal: { normal: 'Sem ajuste (dose Ãºnica)', tfg_60_30: 'Cautela em infusÃ£o prolongada', tfg_30_15: 'Reduzir velocidade de infusÃ£o', tfg_lt_15: 'Cautela extrema', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado (insuf grave)' },
    contraindicacoes_rapidas: ['Glaucoma de Ã¢ngulo fechado (sem tratamento)', 'Miastenia grave', 'InsuficiÃªncia respiratÃ³ria grave sem suporte'],
    interacoes_importantes: [
      { com: 'Cetoconazol / eritromicina / grapefruit', severidade: 'grave', descricao: 'InibiÃ§Ã£o CYP3A4 â†’ midazolam aumenta 3â€“16Ã— â†’ sedaÃ§Ã£o excessiva, apneia' },
      { com: 'Opioides / propofol', severidade: 'grave', descricao: 'Apneia e colapso CV aditivos â€” reduzir doses de ambos' },
      { com: 'Fluconazol (CYP3A4)', severidade: 'grave', descricao: 'SedaÃ§Ã£o prolongada' },
    ],
    alertas_especiais: [
      'APNEIA: risco de depressÃ£o respiratÃ³ria grave â€” ter suporte ventilatÃ³rio imediato disponÃ­vel',
      'ANTÃDOTO: flumazenil (0,2 mg IV, repetir a cada 60s atÃ© 1 mg) â€” efeito mais curto que midazolam (vigilÃ¢ncia necessÃ¡ria)',
      'AMNÃ‰SIA ANTERÃ“GRADA: efeito desejado em procedimentos; nÃ£o usar em anamnese importante',
      'UTI: tolerÃ¢ncia e dependÃªncia com uso prolongado â€” desmame gradual ao suspender',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR BZD em idosos â€” depressÃ£o respiratÃ³ria, queda, delirium',
    stopp: 'STOPP D2: benzodiazepÃ­nico em idoso',
    pgx_genes: ['CYP3A4 (metabolismo principal â€” interaÃ§Ãµes crÃ­ticas)'],
    marcas: [
      { nome: 'DormicumÂ®', laboratorio: 'Roche', concentracoes: ['5 mg/mL', '1 mg/mL'], formas: ['Ampola IV/IM'], lab_id: 'roche' },
      { nome: 'Midazolam Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['5 mg/mL'], formas: ['Ampola IV/IM'], lab_id: 'eurofarma' },
    ],
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ANSIOLÃTICOS / BENZODIAZEPÃNICOS
  // (alprazolam jÃ¡ em PHARMA_DB)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  {
    id: 'diazepam',
    molecula: 'Diazepam',
    nome_generico: 'Diazepam',
    sinonimos: ['valium', 'diazepam', 'benzodiazepÃ­nico ansiedade', 'bzd meia vida longa', 'status diazepam'],
    categoria: 'psiquiatria',
    classe: 'BenzodiazepÃ­nico',
    subclasse: 'BZD de longa aÃ§Ã£o (meia-vida 20â€“100h + metabÃ³lito ativo desmetildiazepam)',
    indicacoes_principais: [
      'Transtorno de ansiedade â€” agudo (curto prazo)',
      'Espasmo muscular',
      'AbstinÃªncia alcoÃ³lica grave (protocolo CIWA)',
      'Status epilepticus (IV â€” 1Âª linha junto com lorazepam)',
      'SedaÃ§Ã£o prÃ©-procedimento (VO/IV)',
      'Tenesmo em cuidados paliativos',
    ],
    dose_adulto: {
      habitual: '2â€“10 mg VO 2â€“4Ã—/dia | 5â€“10 mg IV lento (status)',
      min: '2 mg/dia',
      max: '40 mg/dia (abstinÃªncia alcoÃ³lica)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“4Ã—/dia (ansiedade) | Dose Ãºnica IV (status)'],
      instrucoes: 'MEIA-VIDA LONGA: acÃºmulo em uso crÃ´nico â€” especialmente perigoso em idosos. IV: lento (risco apneia). AbstinÃªncia alcoÃ³lica: regime fixo ou CIWA-Ar (10 mg IV/VO se CIWA â‰¥ 8).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela â€” acÃºmulo', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'InsuficiÃªncia respiratÃ³ria grave', 'Glaucoma de Ã¢ngulo fechado', 'DependÃªncia atual de BZD (risco cruzado)'],
    interacoes_importantes: [
      { com: 'Opioides / Ã¡lcool / outros depressores SNC', severidade: 'contraindicado', descricao: 'Apneia e morte â€” FDA black box: opioides + BZD' },
      { com: 'Fluvoxamina / omeprazol (CYP2C19)', severidade: 'moderada', descricao: 'Aumentam diazepam â€” sedaÃ§Ã£o excessiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos â€” meia-vida muito longa â†’ acÃºmulo â†’ quedas, fratura de quadril, delirium',
      'FDA BLACK BOX: opioides + BZD â†’ risco de morte por depressÃ£o respiratÃ³ria',
      'DEPENDÃŠNCIA: fÃ­sica e psicolÃ³gica apÃ³s semanas. SÃ­ndrome de abstinÃªncia grave (convulsÃµes) se suspensÃ£o abrupta',
      'ANTÃDOTO: flumazenil',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: EVITAR em idosos â€” BZD de meia-vida longa tem maior risco de acÃºmulo',
    stopp: 'STOPP D2: benzodiazepÃ­nico de longa aÃ§Ã£o em idoso â€” risco mÃ¡ximo de queda e delirium',
    pgx_genes: ['CYP2C19 (metabolismo â€” PM: maior sedaÃ§Ã£o)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'ValiumÂ®', laboratorio: 'Roche', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'roche' },
      { nome: 'Diazepam EMS', laboratorio: 'EMS', concentracoes: ['5 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'lorazepam',
    indicacao_contexto: 'Ansiedade / status epilepticus (psiquiatria)',
    molecula: 'Lorazepam',
    nome_generico: 'Lorazepam',
    sinonimos: ['ativan', 'lorazepam', 'bzd aÃ§Ã£o intermediÃ¡ria', 'status lorazepam', 'antiemetico quimio'],
    categoria: 'psiquiatria',
    classe: 'BenzodiazepÃ­nico',
    subclasse: 'BZD de aÃ§Ã£o intermediÃ¡ria (meia-vida 10â€“20h) â€” glucuronidaÃ§Ã£o DIRETA (sem CYP)',
    indicacoes_principais: [
      'Ansiedade aguda',
      'Status epilepticus (IV â€” 1Âª linha â€” preferido ao diazepam em UTI pela meia-vida)',
      'SedaÃ§Ã£o prÃ©-procedimento',
      'NÃ¡useas e vÃ´mitos por quimioterapia (adjuvante)',
      'Delirium agitado em cuidados paliativos',
    ],
    dose_adulto: {
      habitual: '1â€“2 mg VO 2â€“3Ã—/dia | 2â€“4 mg IV (status)',
      min: '0,5 mg (idoso)',
      max: '10 mg/dia (ansiedade) | Status: repetir atÃ© controle',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“3Ã—/dia (ansiedade) | Dose Ãºnica IV (status)'],
      instrucoes: 'VANTAGEM: glucuronidaÃ§Ã£o direta â€” sem metabolismo CYP, sem interaÃ§Ãµes de CYP, sem acÃºmulo de metabÃ³lito ativo. PreferÃ­vel em hepatopatas e idosos (vs diazepam). Status IV: 2â€“4 mg em 2 min, repetir 1Ã— se sem resposta.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste (glucuronidaÃ§Ã£o nÃ£o reduzida levemente)', child_b: 'Cautela', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'InsuficiÃªncia respiratÃ³ria grave'],
    interacoes_importantes: [
      { com: 'Opioides / Ã¡lcool / depressores SNC', severidade: 'grave', descricao: 'Apneia â€” FDA black box' },
      { com: 'Ãcido valprÃ³ico', severidade: 'moderada', descricao: 'Inibe glucuronidaÃ§Ã£o â€” aumenta lorazepam' },
    ],
    alertas_especiais: [
      'PREFERÃVEL AO DIAZEPAM em status epilepticus hospitalar (meia-vida mais favorÃ¡vel)',
      'PREFERÃVEL EM IDOSOS entre BZDs por menor risco de acÃºmulo vs diazepam/clordiazepÃ³xido',
      'Ainda assim: Beers recomenda evitar BZDs em idosos de forma geral',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos â€” menos problemÃ¡tico que diazepam mas ainda causa quedas e delirium',
    stopp: 'STOPP D2: benzodiazepÃ­nico em idoso',
    pgx_genes: ['UGT2B15 (glucuronidaÃ§Ã£o â€” variantes afetam metabolismo)'],
    marcas: [
      { nome: 'AtivanÂ®', laboratorio: 'Pfizer', concentracoes: ['1 mg', '2 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'pfizer' },
      { nome: 'Lorazepam Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['1 mg', '2 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'clonazepam',
    molecula: 'Clonazepam',
    nome_generico: 'Clonazepam',
    sinonimos: ['rivotril', 'klonopin', 'clonazepam', 'bzd anticonvulsivante', 'rivotril pÃ¢nico', 'clonazepam ansiedade'],
    categoria: 'psiquiatria',
    classe: 'BenzodiazepÃ­nico',
    subclasse: 'BZD de longa aÃ§Ã£o (meia-vida 20â€“50h) â€” indicaÃ§Ã£o dupla: ansiedade e epilepsia',
    indicacoes_principais: [
      'Transtorno de pÃ¢nico (1Âª linha BZD)',
      'Epilepsia â€” especialmente epilepsia mioclÃ´nica e atÃ´nica',
      'SÃ­ndrome das pernas inquietas (adjuvante)',
      'Transtorno de ansiedade (curto prazo)',
      'Tremor essencial (adjuvante)',
    ],
    dose_adulto: {
      habitual: '0,5â€“2 mg VO 2â€“3Ã—/dia (ansiedade/pÃ¢nico)',
      min: '0,25 mg/dia',
      max: '20 mg/dia (epilepsia) | 4 mg/dia (pÃ¢nico)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“3Ã—/dia'],
      instrucoes: 'Transtorno de pÃ¢nico: 0,25 mg 2Ã—/dia â†’ titular para 1â€“4 mg/dia. Epilepsia: 0,05 mg/kg/dia â†’ atÃ© 20 mg/dia. TOLERÃ‚NCIA ANTICONVULSIVANTE: pode ocorrer em meses â€” planejamento para substituiÃ§Ã£o.',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'InsuficiÃªncia hepÃ¡tica grave', 'Glaucoma de Ã¢ngulo fechado'],
    interacoes_importantes: [
      { com: 'Opioides / Ã¡lcool / depressores SNC', severidade: 'grave', descricao: 'DepressÃ£o respiratÃ³ria â€” FDA black box' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos â€” como todos os BZDs, risco de queda e delirium',
      'TOLERÃ‚NCIA: anticonvulsivante â€” pode perder eficÃ¡cia. AnsiolÃ­tica: persiste mais',
      'DEPENDÃŠNCIA: fÃ­sica grave â€” nunca suspender abruptamente (convulsÃµes, delirium). Desmame 10%/semana',
      'USO NO BRASIL: prescrito excessivamente para insÃ´nia e ansiedade crÃ´nica â€” revisÃ£o obrigatÃ³ria com o paciente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos',
    stopp: 'STOPP D2: benzodiazepÃ­nico em idoso com histÃ³rico de queda ou demÃªncia',
    pgx_genes: ['CYP3A4 (metabolismo principal)'],
    marcas: [
      { nome: 'RivotrilÂ®', laboratorio: 'Roche', concentracoes: ['0,5 mg', '2 mg', '2,5 mg/mL soluÃ§Ã£o'], formas: ['Comprimido', 'SoluÃ§Ã£o oral'], lab_id: 'roche' },
      { nome: 'Clonazepam EMS', laboratorio: 'EMS', concentracoes: ['0,5 mg', '2 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'buspirona',
    molecula: 'Buspirona',
    nome_generico: 'Cloridrato de Buspirona',
    sinonimos: ['buspar', 'buspirone', 'buspirona', 'ansiolÃ­tico nÃ£o bzd', 'tag buspirona', 'buspirona idoso'],
    categoria: 'psiquiatria',
    classe: 'AnsiolÃ­tico',
    subclasse: 'Azaspirodecanodiona â€” agonista parcial 5-HT1A + antagonista D3/D4 â€” SEM dependÃªncia',
    indicacoes_principais: [
      'Transtorno de ansiedade generalizada (TAG) â€” especialmente idosos e pacientes com histÃ³rico de abuso',
      'Ansiedade crÃ´nica (tratamento contÃ­nuo)',
    ],
    dose_adulto: {
      habitual: '15â€“30 mg/dia em 2â€“3 tomadas',
      min: '5 mg 2Ã—/dia',
      max: '60 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2â€“3Ã—/dia (com alimento)'],
      instrucoes: 'LATÃŠNCIA: 2â€“4 semanas para efeito ansiolÃ­tico (diferente de BZD â€” educaÃ§Ã£o do paciente fundamental). NÃƒO age em crise de pÃ¢nico aguda. NÃƒO tem efeito em pacientes jÃ¡ usando BZD cronicamente. Tomar sempre com ou sem alimento (consistÃªncia).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO (Ãºltimas 2 semanas)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'HAS (agonismo D3/D4) â€” crise hipertensiva' },
      { com: 'Cetoconazol / itraconazol / eritromicina', severidade: 'moderada', descricao: 'InibiÃ§Ã£o CYP3A4 â†’ buspirona aumenta 5â€“13Ã—' },
      { com: 'Rifampicina', severidade: 'moderada', descricao: 'InduÃ§Ã£o CYP3A4 â†’ buspirona cai 10Ã— â€” sem efeito' },
    ],
    alertas_especiais: [
      'VANTAGEM: SEM dependÃªncia, SEM sedaÃ§Ã£o, SEM prejudicar cogniÃ§Ã£o â€” IDEAL para idosos vs BZD',
      'INEFICAZ EM PÃ‚NICO AGUDO: nÃ£o usar para sintomas agudos â€” Ã© ansiolÃ­tico de manutenÃ§Ã£o',
      'INEFICAZ SE O PACIENTE USA BZD: competiÃ§Ã£o pelo receptor diminui efeito. Descontinuar BZD antes',
      'Beers: PREFERIDO ao BZD em idosos com TAG',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: alternativa preferÃ­vel a BZDs em idosos com ansiedade',
    start: 'START E2: buspirona ou ISRS preferÃ­vel a BZD em idoso com TAG',
    pgx_genes: ['CYP3A4 (metabolismo â€” interaÃ§Ãµes com azÃ³is e rifampicina)'],
    marcas: [
      { nome: 'AnsicedÂ®', laboratorio: 'Bristol-Myers Squibb', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Buspirona EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'hidroxizina',
    molecula: 'Hidroxizina',
    nome_generico: 'Dicloridrato de Hidroxizina',
    sinonimos: ['atarax', 'hydroxyzine', 'hidroxizina', 'anti-histaminico ansiolÃ­tico', 'prurido hidroxizina', 'urticaria hidroxizina'],
    categoria: 'psiquiatria',
    classe: 'AnsiolÃ­tico',
    subclasse: 'Anti-histamÃ­nico H1 de 1Âª geraÃ§Ã£o â€” antagonista H1, muscarÃ­nico, Î±1, 5-HT2A â€” sedaÃ§Ã£o e ansiedade',
    indicacoes_principais: [
      'Ansiedade aguda (curto prazo)',
      'Prurido alÃ©rgico / urticÃ¡ria',
      'Ansiedade prÃ©-procedimento / prÃ©-anestÃ©sica',
      'SedaÃ§Ã£o em crianÃ§as (procedimentos)',
    ],
    dose_adulto: {
      habitual: '25â€“50 mg VO 3â€“4Ã—/dia',
      min: '25 mg/dia',
      max: '400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3â€“4Ã—/dia'],
      instrucoes: 'Ansiedade aguda: 50â€“100 mg VO (pode repetir). Prurido: 25 mg 3â€“4Ã—/dia. Efeito ansiolÃ­tico mais rÃ¡pido que buspirona mas menor que BZD. SEM dependÃªncia.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Reduzir intervalo', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['QTc prolongado', 'Hipersensibilidade Ã  cetirizina/piperazinas', 'Porfiria'],
    interacoes_importantes: [
      { com: 'QT-prolongadores', severidade: 'moderada', descricao: 'QT aditivo â€” hidroxizina prolonga QT dose-dependente' },
      { com: 'AnticolinÃ©rgicos', severidade: 'moderada', descricao: 'Efeito aditivo â€” retenÃ§Ã£o urinÃ¡ria, constipaÃ§Ã£o' },
      { com: 'Ãlcool / depressores SNC', severidade: 'moderada', descricao: 'SedaÃ§Ã£o aditiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos â€” anti-histamÃ­nico de 1Âª geraÃ§Ã£o â†’ alta carga anticolinÃ©rgica â†’ confusÃ£o, retenÃ§Ã£o urinÃ¡ria, queda',
      'QT: monitorar ECG em cardiopatas e associaÃ§Ã£o com outros QT-prolongadores',
      'Vantagem vs BZD: SEM dependÃªncia e SEM abuso. Bom para ansiedade situacional',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: EVITAR em idosos â€” anticolinÃ©rgico e sedativo de 1Âª geraÃ§Ã£o; QT prolongado',
    stopp: 'STOPP D4: anti-histamÃ­nico de 1Âª geraÃ§Ã£o em idoso',
    pgx_genes: ['CYP2D6 (metabolismo principal â€” PM: maior sedaÃ§Ã£o)'],
    marcas: [
      { nome: 'Atarax®', laboratorio: 'UCB', concentracoes: ['25 mg', '10 mg/5 mL xarope'], formas: ['Comprimido', 'Xarope'] },
      { nome: 'Pergo®', laboratorio: 'Eurofarma', concentracoes: ['2 mg/mL solução oral'], formas: ['Solução Oral'], lab_id: 'eurofarma' },
      { nome: 'Hidroxizina EMS', laboratorio: 'EMS', concentracoes: ['25 mg'], formas: ['Comprimido'] },
    ],
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ANTIPSICÃ“TICO ATÃPICO ADICIONAL
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

  {
    id: 'lurasidona',
    molecula: 'Lurasidona',
    nome_generico: 'Cloridrato de Lurasidona',
    sinonimos: ['latuda', 'lurasidone', 'lurasidona', 'antipsicÃ³tico depressÃ£o bipolar', 'antipsicÃ³tico cognitivo'],
    categoria: 'psiquiatria',
    classe: 'AntipsicÃ³tico AtÃ­pico',
    subclasse: 'Benzisotiazol â€” antagonismo D2/D3, 5-HT2A, 5-HT7 + agonismo parcial 5-HT1A â€” perfil metabÃ³lico favorÃ¡vel',
    indicacoes_principais: [
      'Esquizofrenia',
      'DepressÃ£o bipolar (como monoterapia ou adjuvante a lÃ­tio/valproato)',
    ],
    dose_adulto: {
      habitual: '40â€“80 mg/dia VO (esquizofrenia) | 20â€“60 mg/dia (depressÃ£o bipolar)',
      min: '20 mg/dia',
      max: '160 mg/dia (esquizofrenia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1Ã—/dia COM refeiÃ§Ã£o â‰¥ 350 kcal'],
      instrucoes: 'TOMAR COM ALIMENTO (â‰¥ 350 kcal): absorÃ§Ã£o aumenta 2Ã— vs jejum. Metabolismo CYP3A4 â€” evitar inibidores potentes (cetoconazol) e indutores (rifampicina). Vantagem: menor ganho de peso e sedaÃ§Ã£o vs olanzapina/quetiapina.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'MÃ¡x 80 mg/dia', tfg_30_15: 'MÃ¡x 40 mg/dia', tfg_lt_15: 'MÃ¡x 40 mg/dia', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'MÃ¡x 80 mg/dia', child_c: 'MÃ¡x 40 mg/dia' },
    contraindicacoes_rapidas: ['Uso com CYP3A4 potente inibidor (cetoconazol, claritromicina)', 'CYP3A4 potente indutor (rifampicina, carbamazepina)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Cetoconazol / claritromicina (CYP3A4 inibidores potentes)', severidade: 'contraindicado', descricao: 'Aumenta lurasidona dramaticamente â€” toxicidade' },
      { com: 'Rifampicina / carbamazepina (CYP3A4 indutores potentes)', severidade: 'contraindicado', descricao: 'Reduz lurasidona ao mÃ­nimo â€” ineficaz' },
    ],
    alertas_especiais: [
      'ALIMENTO OBRIGATÃ“RIO: sem refeiÃ§Ã£o, biodisponibilidade cai 50%',
      'MENOR EFEITO METABÃ“LICO: peso neutro ou ganho mÃ­nimo â€” preferÃ­vel em DM2 e obesos',
      'DEPRESSÃƒO BIPOLAR: uma das pouÃ§Ãµes opÃ§Ãµes aprovadas especificamente para depressÃ£o bipolar',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP3A4 (metabolismo exclusivo â€” interaÃ§Ãµes crÃ­ticas)'],
    marcas: [
      { nome: 'LatudaÂ®', laboratorio: 'Sumitomo/Sunovion', concentracoes: ['20 mg', '40 mg', '60 mg', '80 mg', '120 mg'], formas: ['Comprimido'] },
    ],
  },

];