// ============================================================
// PRESCREVE-AI — Banco Farmacológico: UTI + Emergência
// Phase 21.13
// ============================================================

import { QuickDrug } from './pharma-database';

export const PHARMA_DB_ICU: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════
  // ── VASOATIVOS — VASOPRESSORES ────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'norepinefrina',
    molecula: 'norepinefrina',
    nome_generico: 'Norepinefrina (Noradrenalina)',
    sinonimos: ['noradrenalina', 'levophed', 'NE', 'vasopressor 1ª linha', 'NOR'],
    categoria: 'uti',
    classe: 'Catecolamina — agonista α1 predominante + β1 moderado',
    indicacoes_principais: ['Choque séptico / distributivo (1ª linha SSC 2021)', 'Choque hemorrágico (ponte)', 'Hipotensão refratária a volume'],
    dose_adulto: {
      habitual: '0,01–0,5 mcg/kg/min IC (máx relatado 3 mcg/kg/min)',
      max: '3 mcg/kg/min (doses > 1 mcg/kg/min considerar 2ª linha)',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua (IC) — titular PAM ≥ 65 mmHg'],
      instrucoes: 'DILUIÇÃO: 4 mg em 250 mL SG 5% → 16 mcg/mL. Iniciar 0,01 mcg/kg/min. Titular 2–5 min. CVC OBRIGATÓRIO (necrose por extravasamento). Se > 0,25 mcg/kg/min: adicionar vasopressina 0,03 UI/min.',
    },
    contraindicacoes_rapidas: [
      'Hipovolemia não corrigida (tratar volume antes)',
      'Extravasamento: fentolamina 5 mg diluída SC no sítio',
    ],
    interacoes_importantes: [
      { com: 'halotano / anestésicos halogenados', severidade: 'grave', descricao: 'Sensibilização miocárdica → arritmias graves' },
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Crise hipertensiva grave' },
      { com: 'antidepressivos tricíclicos', severidade: 'grave', descricao: 'Potencializam resposta pressora' },
    ],
    alertas_especiais: [
      '⚠ ACESSO CENTRAL OBRIGATÓRIO — extravasamento causa necrose tecidual',
      'Meta hemodinâmica: PAM ≥ 65 mmHg (reduzir dose após estabilidade > 6h)',
      'Associar vasopressina 0,03 UI/min se dose > 0,25 mcg/kg/min (poupa norepinefrina)',
      'Monitorar: isquemia digital, PAM invasiva, lactato seriado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Levophed', laboratorio: 'Pfizer', concentracoes: ['1 mg/mL (4 mL)'], formas: ['Ampola IV para diluição'] },
      { nome: 'Norepinefrina (genérico)', laboratorio: 'Várias', concentracoes: ['1 mg/mL', '2 mg/mL'], formas: ['Ampola IV'] },
    ],
  },
  {
    id: 'epinefrina-uti',
    molecula: 'epinefrina',
    nome_generico: 'Epinefrina (Adrenalina)',
    sinonimos: ['adrenalina', 'epinephrine', 'PCR', 'anafilaxia', 'vasopressor'],
    categoria: 'emergencia',
    classe: 'Catecolamina — agonista α + β1 + β2',
    indicacoes_principais: [
      'PCR — FV/TVsP/AESP/assistolia (dose única 1 mg q3–5 min)',
      'Anafilaxia (1ª linha — IM obrigatório)',
      'Choque séptico refratário (2ª linha)',
      'Broncoespasmo grave/asma quase fatal',
      'Bradicardia refratária à atropina',
    ],
    dose_adulto: {
      habitual: 'PCR: 1 mg IV/IO q3–5 min | Anafilaxia: 0,3–0,5 mg IM vasto lateral da coxa | IC: 0,01–1 mcg/kg/min',
      max: '1 mg/dose (PCR) | Sem dose máxima em IC (titular efeito)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['PCR: q3–5 min (bolus)', 'IC: infusão contínua (choque)', 'Anafilaxia: IM repetir em 5–15 min se necessário'],
      instrucoes: 'PCR: 1 mg IV em bolus + flush SF 20 mL. IC: 4 mg em 250 mL SG 5% (16 mcg/mL). Anafilaxia: IM vasto lateral (não glúteo — absorção errática).',
    },
    contraindicacoes_rapidas: [
      'Angina instável / IAM ativo (relativa — usar se anafilaxia/PCR: risco/benefício favorável)',
      'HAS grave não controlada (relativa)',
    ],
    interacoes_importantes: [
      { com: 'β-bloqueadores', severidade: 'moderada', descricao: 'Antagonismo de efeito β; hipertensão paradoxal por α predominante' },
      { com: 'cocaína', severidade: 'grave', descricao: 'Potencialização de vasoespasmo e arritmias' },
    ],
    alertas_especiais: [
      '⚠ ANAFILAXIA: IM vasto lateral PRIMEIRO (não esperar acesso venoso)',
      '⚠ PCR: dose padrão 1 mg IV — NÃO usar dose alta (3–5 mg) — não melhora sobrevida neurológica (ACLS 2020)',
      'Hiperglicemia: monitorar glicemia durante IC',
      'Arritmias e isquemia miocárdica em doses altas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Adrenalina (genérico)', laboratorio: 'Hipolabor / Farmax', concentracoes: ['1 mg/mL (1:1.000)', '0,1 mg/mL (1:10.000)'], formas: ['Ampola IM/IV'] },
      { nome: 'EpiPen', laboratorio: 'Pfizer', concentracoes: ['0,3 mg/dose (autoinjector)'], formas: ['Dispositivo auto-injetor IM'] },
    ],
  },
  {
    id: 'vasopressina',
    molecula: 'vasopressina',
    nome_generico: 'Vasopressina (ADH)',
    sinonimos: ['ADH', 'hormônio antidiurético', '2ª linha sepse', 'vasopressina endógena'],
    categoria: 'uti',
    classe: 'Análogo de vasopressina — agonista V1R/V2R',
    indicacoes_principais: ['Choque séptico refratário (2ª linha — adjuvante de norepinefrina)', 'Diabetes insipidus central (dose baixa)', 'Hemorragia varicosa (com terlipressina)', 'Parada cardíaca (uso controverso — ACLS 2020 não mais recomenda rotineiramente)'],
    dose_adulto: {
      habitual: '0,03 UI/min IC (choque séptico — dose fixa, NÃO titular)',
      max: '0,04 UI/min',
      unidade: 'UI/min',
      via: 'IV',
      frequencias: ['Infusão contínua — DOSE FIXA (não aumentar)'],
      instrucoes: 'DILUIÇÃO: 20 UI em 100 mL SG 5% → 0,2 UI/mL. Taxa: 9 mL/h = 0,03 UI/min. NÃO titular — dose farmacológica fixa. Associar ao NOR, não substituir.',
    },
    contraindicacoes_rapidas: ['Isquemia coronariana ativa (relativa — vasoconstrição coronária)', 'Doença de Raynaud grave'],
    interacoes_importantes: [
      { com: 'norepinefrina', severidade: 'leve', descricao: 'Combinação intencional — poupador de norepinefrina (sinergismo)' },
    ],
    alertas_especiais: [
      'DOSE FIXA 0,03 UI/min — NÃO aumentar (necrose esplâncnica e isquemia cutânea em doses > 0,04)',
      'Efeito poupador de norepinefrina: adicionar quando NOR > 0,25 mcg/kg/min',
      'Hiponatremia: monitorar sódio (efeito antidiurético V2R)',
      'Isquemia digital/mesentérica: avaliar sinais de isquemia diariamente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Pitressin', laboratorio: 'Pfizer', concentracoes: ['20 UI/mL'], formas: ['Ampola IV'] }],
  },
  {
    id: 'dobutamina',
    molecula: 'dobutamina',
    nome_generico: 'Dobutamina',
    sinonimos: ['dobut', 'inotrópico', 'choque cardiogênico', 'IC descompensada', 'Dobutrex'],
    categoria: 'uti',
    classe: 'Catecolamina sintética — agonista β1 predominante (inotrópico)',
    indicacoes_principais: ['Choque cardiogênico com DC reduzido', 'IC aguda descompensada com hipoperfusão', 'Disfunção VD grave (TEP, HTP)', 'Teste de estresse farmacológico (cardiologia)'],
    dose_adulto: {
      habitual: '2–20 mcg/kg/min IC (iniciar 2–5 mcg/kg/min)',
      max: '20 mcg/kg/min',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua — titular pelo DC/ScVO₂/lactato'],
      instrucoes: 'DILUIÇÃO: 250 mg em 250 mL SG 5% → 1000 mcg/mL (1 mg/mL). Pode usar veia periférica (excepcional). Associar norepinefrina se hipotensão concomitante.',
    },
    contraindicacoes_rapidas: ['Cardiomiopatia hipertrófica obstrutiva (CMHO) — piora obstrução', 'Taquiarritmias graves não controladas'],
    interacoes_importantes: [
      { com: 'β-bloqueadores', severidade: 'moderada', descricao: 'Antagonismo de efeito inotrópico — taquifilaxia acelerada' },
    ],
    alertas_especiais: [
      '⚠ NÃO usar em choque distributivo (piora vasodilatação e hipotensão)',
      'Taquicardia: dose-dependente — limitar a doses eficazes mínimas',
      'Taquifilaxia: após 72h pode necessitar dose crescente — reavaliar necessidade',
      'Melhorar perfusão verificando: lactato, ScVO₂ > 70%, diurese > 0,5 mL/kg/h',
      'Isquemia miocárdica: arritmias e ↑ consumo O₂ — monitorar ECG',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Dobutrex', laboratorio: 'Eli Lilly', concentracoes: ['250 mg/20 mL (12,5 mg/mL)'], formas: ['Concentrado IV'] },
      { nome: 'Dobutamina (genérico)', laboratorio: 'Várias', concentracoes: ['250 mg/20 mL'], formas: ['Concentrado IV'] },
    ],
  },
  {
    id: 'dopamina',
    molecula: 'dopamina',
    nome_generico: 'Dopamina',
    sinonimos: ['Intropin', 'DA', 'vasopresor', 'inotrópico'],
    categoria: 'uti',
    classe: 'Catecolamina endógena — agonista dopaminérgico + β1 + α1 (dose-dependente)',
    indicacoes_principais: ['Choque cardiogênico com bradicardia (β1 + cronotrópico)', '2ª linha em choque (SSC 2021: preferir norepinefrina)'],
    dose_adulto: {
      habitual: '1–20 mcg/kg/min IC (efeito dose-dependente)',
      max: '20 mcg/kg/min',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua'],
      instrucoes: 'DILUIÇÃO: 200 mg em 250 mL SG 5% → 800 mcg/mL. EFEITOS: < 5 mcg/kg/min: dopaminérgico | 5–10: β1 (inotrópico) | > 10: α1 (vasopressor). CVC obrigatório.',
    },
    contraindicacoes_rapidas: ['Feocromocitoma', 'Taquiarritmias (FA, ESV frequentes)'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'grave', descricao: 'Crise hipertensiva grave — reduzir dose para 10% do habitual se uso de IMAO nos últimos 14 dias' },
    ],
    alertas_especiais: [
      '⚠ SSC 2021: norepinefrina PREFERÍVEL à dopamina em choque séptico (SOAP II trial: ↑ FA e mortalidade em subgrupo)',
      '⚠ ARRITMOGÊNICA: mais FA e taquicardia que norepinefrina',
      'Dose "renal" (< 3 mcg/kg/min): NÃO protege rim — não usar com essa finalidade',
      'CVC obrigatório — extravasamento: fentolamina SC no sítio',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Dopamina (genérico)', laboratorio: 'Várias', concentracoes: ['5 mg/mL', '40 mg/mL'], formas: ['Ampola IV para diluição'] }],
  },
  {
    id: 'milrinona',
    molecula: 'milrinona',
    nome_generico: 'Milrinona',
    sinonimos: ['Primacor', 'inodilatador', 'inibidor PDE-3', 'IC refratária'],
    categoria: 'uti',
    classe: 'Inibidor de fosfodiesterase-3 (PDE-3) — inotrópico + vasodilatador',
    indicacoes_principais: ['IC aguda com β-bloqueador em uso (não adrenérgico)', 'Disfunção VD grave (HTP aguda)', 'Bridge to transplant cardíaco', 'Choque cardiogênico refratário a dobutamina'],
    dose_adulto: {
      habitual: '0,125–0,75 mcg/kg/min IC (sem dose de ataque em hipotensão)',
      max: '0,75 mcg/kg/min',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua'],
      instrucoes: 'DILUIÇÃO: 20 mg em 100 mL SG 5% → 200 mcg/mL. ATAQUE: 50 mcg/kg IV em 10 min (evitar se hipotensão). Ajustar dose em IR (ClCr < 30: máx 0,33 mcg/kg/min).',
    },
    contraindicacoes_rapidas: ['Estenose aórtica/pulmonar grave (vasodilatação piora gradiente)', 'Hipotensão grave sem vasopressor'],
    interacoes_importantes: [],
    alertas_especiais: [
      'Hipotensão frequente (vasodilatação sistêmica e pulmonar) — associar vasopressor se necessário',
      'Taquifilaxia menor que dobutamina (mecanismo não-adrenérgico)',
      'Acúmulo em IR: reduzir dose drasticamente',
      'Arritmias supraventriculares e ventriculares — monitorar ECG',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    ajuste_renal: {
      normal: 'Dose plena (0,125–0,75 mcg/kg/min)',
      tfg_60_30: 'Reduzir 30–40% (máx 0,43 mcg/kg/min)',
      tfg_30_15: 'Máx 0,33 mcg/kg/min',
      tfg_lt_15: 'Máx 0,2 mcg/kg/min',
      dialisavel: false,
    },
    marcas: [{ nome: 'Primacor', laboratorio: 'Sanofi', concentracoes: ['1 mg/mL (10 mL)'], formas: ['Ampola IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── SEDAÇÃO ───────────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'propofol-uti',
    molecula: 'propofol',
    nome_generico: 'Propofol',
    sinonimos: ['Diprivan', 'sedação UTI', 'TIVA', 'anestesia IV'],
    categoria: 'uti',
    classe: 'Anestésico geral IV — modulador GABA-A',
    indicacoes_principais: ['Sedação em UTI durante VM (RASS -1 a -3)', 'Indução anestésica (TIVA)', 'Sedação para procedimentos curtos', 'Status epiléptico refratário (altas doses)'],
    dose_adulto: {
      habitual: 'Sedação UTI: 5–50 mcg/kg/min IC | Indução: 1–2,5 mg/kg IV bolus',
      max: '4 mg/kg/h (66 mcg/kg/min) — SÍNDROME DE INFUSÃO DE PROPOFOL acima disso',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua (sedação)', 'Bolus (indução)'],
      instrucoes: 'DILUIÇÃO: pronto para uso (formulação 10 mg/mL). Usar linha dedicada. Trocar equipo a cada 12h (emulsão lipídica sujeita a contaminação). Monitorar triglicerídeos e CK se uso > 48h.',
    },
    contraindicacoes_rapidas: [
      'Hipersensibilidade a ovo / soja (excipiente — emulsão lipídica)',
      'Síndrome de infusão de propofol: dose > 4 mg/kg/h por > 48h',
      'Crianças < 3 anos em sedação prolongada',
    ],
    interacoes_importantes: [
      { com: 'opioides', severidade: 'moderada', descricao: 'Sinergismo sedativo — reduzir dose de propofol (analgesia-first)' },
      { com: 'fenitoína', severidade: 'moderada', descricao: 'Reduz eficácia do propofol' },
    ],
    alertas_especiais: [
      '⚠ SÍNDROME DE INFUSÃO DE PROPOFOL (PRIS): dose > 4 mg/kg/h → acidose metabólica, rabdomiólise, IR, arritmias. FATAL. Monitorar CK e TG se uso > 48h ou dose alta.',
      '⚠ CONTAGEM CALÓRICA: 1,1 kcal/mL (lipídio 10%) — subtrair da nutrição parenteral',
      'Hipotensão: comum na indução (vasodilatação + efeito inotrópico negativo)',
      'Dor na injeção: diluir em SG ou pré-medicar com lidocaína',
      'PADIS 2018: prefere propofol/dexmedetomidina sobre midazolam em VM',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Diprivan', laboratorio: 'AstraZeneca', concentracoes: ['10 mg/mL (20 mL, 50 mL, 100 mL)'], formas: ['Emulsão IV'] },
      { nome: 'Propofol (genérico)', laboratorio: 'Cristália / Eurofarma', concentracoes: ['10 mg/mL'], formas: ['Emulsão IV'] },
    ],
  },
  {
    id: 'dexmedetomidina',
    molecula: 'dexmedetomidina',
    nome_generico: 'Dexmedetomidina',
    sinonimos: ['Precedex', 'dex', 'alfa-2 agonista', 'sedação consciente UTI'],
    categoria: 'uti',
    classe: 'Agonista α2-adrenérgico central — sedativo-analgésico-ansiolítico',
    indicacoes_principais: ['Sedação leve em VM (RASS -1 a -2) — favorece desmame', 'Prevenção e tratamento de delirium', 'Sedação em procedimentos com necessidade de cooperação', 'Tratamento de abstinência a opioides/álcool (off-label)'],
    dose_adulto: {
      habitual: '0,2–1,5 mcg/kg/h IC (sem dose de ataque — causa hipotensão/bradicardia)',
      max: '1,5 mcg/kg/h',
      unidade: 'mcg/kg/h',
      via: 'IV',
      frequencias: ['Infusão contínua'],
      instrucoes: 'DILUIÇÃO: 200 mcg em 48 mL SF → 4 mcg/mL (ou 400 mcg em 96 mL SF). NÃO dose de ataque (bradicardia/hipotensão). Iniciar 0,2 mcg/kg/h e titular.',
    },
    contraindicacoes_rapidas: ['BAV grau 2–3 sem marca-passo', 'Hipotensão grave', 'Bradicardia < 50 bpm'],
    interacoes_importantes: [
      { com: 'β-bloqueadores', severidade: 'moderada', descricao: 'Bradicardia aditiva — monitorar FC' },
      { com: 'antihipertensivos', severidade: 'moderada', descricao: 'Hipotensão aditiva' },
    ],
    alertas_especiais: [
      'ÚNICO sedativo que mantém paciente colaborativo e orientado (RASS 0 a -2)',
      'Não deprime respiração — útil no desmame (SBT mais fácil)',
      'Bradicardia e hipotensão: frequentes (25%) — tratar com atropina/efedrina se grave',
      'MENDS2 trial: dexmedetomidina vs propofol em VM — sem diferença em delirium; mais bradicardia com dex',
      'Custo: mais caro que propofol/midazolam; usar quando benefício clínico claro',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Precedex', laboratorio: 'Pfizer', concentracoes: ['200 mcg/2 mL (100 mcg/mL)'], formas: ['Concentrado IV para diluição'] }],
  },
  {
    id: 'midazolam-uti',
    molecula: 'midazolam',
    nome_generico: 'Midazolam',
    sinonimos: ['dormicum', 'BZD', 'benzodiazepínico', 'sedação', 'MDZ'],
    categoria: 'uti',
    classe: 'Benzodiazepínico de meia-vida intermediária — potenciador GABA-A',
    indicacoes_principais: ['Sedação em VM (uso limitado — 2ª linha PADIS 2018)', 'Controle de convulsões agudas / status epiléptico', 'Sedação em procedimentos', 'Abstinência alcoólica grave (CIWA)'],
    dose_adulto: {
      habitual: 'IC sedação: 0,02–0,1 mg/kg/h | Status: 0,1–0,2 mg/kg IV bolus → IC 0,05–0,4 mg/kg/h',
      max: '0,2 mg/kg/h (IC) | 0,2 mg/kg bolus (convulsão)',
      unidade: 'mg/kg/h',
      via: 'IV',
      frequencias: ['Infusão contínua (sedação) ou bolus (convulsão)'],
      instrucoes: 'DILUIÇÃO IC: 50 mg em 250 mL SF → 0,2 mg/mL. Bolus convulsão: 5–10 mg IV lento. Limitar uso IC a < 48h em UTI (acúmulo, delirium, desmame difícil).',
    },
    contraindicacoes_rapidas: [
      'Glaucoma de ângulo fechado não tratado',
      'Insuficiência respiratória grave sem suporte ventilatório',
    ],
    interacoes_importantes: [
      { com: 'opioide + BZD', severidade: 'grave', descricao: 'Depressão respiratória fatal — combinação requer monitorização contínua' },
      { com: 'inibidores CYP3A4 (fluconazol, eritromicina)', severidade: 'grave', descricao: 'Sedação prolongada e intensa — reduzir dose 50%' },
    ],
    alertas_especiais: [
      '⚠ PADIS 2018: EVITAR midazolam IC em VM (associado a mais delirium e desmame mais difícil vs propofol/dex)',
      '⚠ ACÚMULO: meia-vida ativa de 1-OH-midazolam acumula em IR e IH → sedação prolongada',
      'Antídoto: flumazenil 0,2 mg IV (onset 1 min; meia-vida < 60 min — repetir ou IC)',
      'Idosos e hepatopatas: reduzir dose 50–70%',
      'Abstinência alcoólica (CIWA): protocolo guiado por CIWA-Ar (escala)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Dormicum', laboratorio: 'Roche', concentracoes: ['5 mg/mL (5 mL e 10 mL)', '1 mg/mL (5 mL)'], formas: ['Ampola IV'] },
      { nome: 'Midazolam (genérico)', laboratorio: 'Cristália / Hipolabor', concentracoes: ['5 mg/mL'], formas: ['Ampola IV'] },
    ],
  },
  {
    id: 'ketamina-uti',
    molecula: 'ketamina',
    nome_generico: 'Ketamina',
    sinonimos: ['cetamina', 'ketamine', 'NMDA antagonista', 'anestesia dissociativa'],
    categoria: 'uti',
    classe: 'Antagonista de receptor NMDA — anestésico dissociativo',
    indicacoes_principais: ['Indução anestésica em SRI (paciente hemodinamicamente instável)', 'Analgesia/sedação em procedimentos (broncoescopia, curativo, redução ortopédica)', 'Sedação adjuvante poupadora de opioides', 'Status epiléptico refratário (altas doses)', 'Broncoespasmo refratário (broncodilatador)'],
    dose_adulto: {
      habitual: 'Indução: 1–2 mg/kg IV | Dissociativa (procedimento): 0,5–1 mg/kg IV | IC analgesia: 0,1–0,5 mg/kg/h',
      max: '2 mg/kg IV (indução)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['Bolus (procedimento/indução)', 'IC (analgesia/sedação adjuvante)'],
      instrucoes: 'Indução SRI: 1,5 mg/kg IV lento. Pré-medicar midazolam 1–2 mg IV (reduz disforia e sonhos desagradáveis). Não causa depressão respiratória na dose dissociativa.',
    },
    contraindicacoes_rapidas: [
      'HAS grave não controlada (relativa — ↑ PA e FC)',
      'Hipertensão intracraniana (controvérsia — estudos recentes questionam contraindicação absoluta)',
      'Esquizofrenia ativa',
      'Insuficiência coronariana grave',
    ],
    interacoes_importantes: [
      { com: 'opioides', severidade: 'leve', descricao: 'Sinergismo analgésico (baixas doses IC — poupador de opioide)' },
    ],
    alertas_especiais: [
      'MANTÉM reflexos de via aérea — vantagem em intubação de emergência',
      'Broncodilatador: útil em broncoespasmo grave/asma quase fatal',
      'Efeitos simpaticomimético: ↑ FC e PA — vantagem no instável, desvantagem no coronariopata',
      'Disforia/sonhos: pré-medicar com BZD para reduzir (benzodiazepínico não necessário em IC baixa)',
      'Dissociação: não responde a estímulos mas não está anestesiado profundamente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Ketalar', laboratorio: 'Pfizer', concentracoes: ['50 mg/mL', '10 mg/mL'], formas: ['Frasco IV'] },
      { nome: 'Ketamina (genérico)', laboratorio: 'Cristália', concentracoes: ['50 mg/mL', '500 mg/10 mL'], formas: ['Frasco IV'] },
    ],
  },
  {
    id: 'etomidato',
    molecula: 'etomidato',
    nome_generico: 'Etomidato',
    sinonimos: ['Amidate', 'hipnótico SRI', 'indução ISH'],
    categoria: 'emergencia',
    classe: 'Hipnótico não barbitúrico — modulador GABA-A (imidazol)',
    indicacoes_principais: ['Indução em SRI (sequência rápida de intubação) — preferencial no instável hemodinamicamente', 'Indução anestésica de curta duração'],
    dose_adulto: {
      habitual: '0,3 mg/kg IV bolus (20–30 mg adulto típico)',
      max: '0,3 mg/kg/dose',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['Dose única (indução)'],
      instrucoes: 'Administrar em 30–60 s. Efeito onset em 30 s, duração 5–10 min. NÃO usa para manutenção (adrenocortical suppression). Pré-medicar fentanil 1–2 mcg/kg para atenuar reflexo laríngeo.',
    },
    contraindicacoes_rapidas: [
      'Sepse (relativa — supressão adrenal 6–24h → mortalidade ↑ em sepse — preferir ketamina)',
      'Insuficiência adrenal conhecida',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      '⚠ SUPRESSÃO ADRENAL: dose única bloqueia síntese cortisol por 6–24h (inibição 11β-hidroxilase). Em sepse: preferir ketamina.',
      'VANTAGEM: menor hipotensão que propofol/midazolam — hemodinamicamente neutro',
      'Mioclonias: frequentes (30%) — pré-medicar BZD ou fentanil reduz',
      'Dor na injeção: usar veia antecubital; pré-medicar lidocaína 40 mg IV',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Etomidato (genérico)', laboratorio: 'Cristália / BMS', concentracoes: ['2 mg/mL (10 mL)'], formas: ['Ampola IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── ANALGESIA UTI ─────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'fentanil-uti',
    molecula: 'fentanil',
    nome_generico: 'Fentanil (Infusão Contínua — UTI)',
    sinonimos: ['fentanil IC', 'opioide UTI', 'analgesia-first', 'Fentanest'],
    categoria: 'uti',
    classe: 'Opioide — agonista µ (altamente lipofílico, curta duração em bolus)',
    indicacoes_principais: ['Analgesia em paciente intubado (1ª linha — sem acúmulo em IR)', 'Sedoanalgesia em procedimentos', 'Dor aguda intensa (IV)'],
    dose_adulto: {
      habitual: 'IC: 25–200 mcg/h (0,5–2 mcg/kg/h) | Bolus: 25–100 mcg IV lento',
      max: '400 mcg/h (IC) — titular pelo CPOT ≤ 2',
      unidade: 'mcg/h',
      via: 'IV',
      frequencias: ['Infusão contínua + bolus se dor irruptiva'],
      instrucoes: 'DILUIÇÃO: 500 mcg em 100 mL SF → 5 mcg/mL. Titular pelo CPOT (≤ 2 = bem controlado). PADIS 2018: analgesia ANTES de sedação (analgesia-first).',
    },
    contraindicacoes_rapidas: [
      'Hipersensibilidade a fentanila ou outros opioides',
      'Depressão respiratória grave sem suporte ventilatório',
      'Uso de IMAO nos últimos 14 dias (risco de síndrome serotoninérgica)',
      'Íleo paralítico / obstrução gastrointestinal conhecida ou suspeita',
    ],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'grave', descricao: 'Síndrome serotoninérgica — intervalo ≥ 14 dias' },
      { com: 'BZD / propofol', severidade: 'moderada', descricao: 'Depressão respiratória aditiva — titular cuidadosamente' },
    ],
    alertas_especiais: [
      'VANTAGEM: sem acúmulo em IR (glucuronidação hepática + excreção renal de metabólitos inativos)',
      'Tolerância: após 5–7 dias → síndrome de abstinência ao desmamar (redução gradual 10–25%/dia)',
      'Rigidez torácica (síndrome do tórax rígido): bolus rápido IV em altas doses — NMB reverte',
      'Antídoto: naloxona 0,04–0,4 mg IV (repetir q2–3 min se necessário)',
      'Meia-vida em UTI é prolongada por acúmulo em gordura (lipofílico) — atenção em obesos',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Fentanest', laboratorio: 'Cristália', concentracoes: ['50 mcg/mL (2 mL e 10 mL)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'remifentanil',
    molecula: 'remifentanil',
    nome_generico: 'Remifentanil',
    sinonimos: ['Ultiva', 'opioide ultracurto', 'desmame VM', 'opioide contexto-insensível'],
    categoria: 'uti',
    classe: 'Opioide — agonista µ de ultra-curta duração (éster — hidrólise por esterases)',
    indicacoes_principais: ['Analgesia-sedação em VM com desmame frequente', 'Procedimentos que requerem avaliação neurológica seriada', 'Analgesia intraoperatória (TIVA)'],
    dose_adulto: {
      habitual: '0,05–0,3 mcg/kg/min IC (titular)',
      max: '0,5 mcg/kg/min',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['Infusão contínua — NÃO bolus (hipotensão grave)'],
      instrucoes: 'DILUIÇÃO: 5 mg em 50 mL SF → 100 mcg/mL. Linha dedicada. Remifentanil é contexto-insensível: meia-vida 3–10 min INDEPENDENTE da duração da infusão. Suspender ao final — analgesia rapidamente perdida.',
    },
    contraindicacoes_rapidas: ['NÃO usar em bolus (hipotensão/bradicardia grave)', 'NÃO para pós-operatório (efeito zero em minutos após suspensão — planejar analgesia oral)'],
    interacoes_importantes: [
      { com: 'propofol', severidade: 'moderada', descricao: 'Hipotensão aditiva — reduzir doses de ambos' },
    ],
    alertas_especiais: [
      'HIPERALGESIA: uso prolongado (> 24–48h) associado a hiperalgesia pós-infusão (mecanismo NMDA) — ketamina pode prevenir',
      'Custo: significativamente mais caro que fentanil — use quando benefício clínico justifica',
      'NÃO tem reserva analgésica: planejar analgesia multimodal ao desmamar',
      'Meia-vida verdadeiramente 3–10 min — ideal para avaliar nível de consciência a qualquer momento',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Ultiva', laboratorio: 'GSK', concentracoes: ['1 mg, 2 mg, 5 mg (pó)'], formas: ['Pó liofilizado IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── BLOQUEADORES NEUROMUSCULARES (BNM) ────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'succinilcolina',
    molecula: 'succinilcolina',
    nome_generico: 'Succinilcolina (Suxametônio)',
    sinonimos: ['sux', 'suxametônio', 'BNM despolarizante', 'SRI rápida', 'Quelicin'],
    categoria: 'emergencia',
    classe: 'Bloqueador neuromuscular despolarizante — agonista nicotínico persistente',
    indicacoes_principais: ['SRI (sequência rápida de intubação) — 1ª linha pela rapidez de onset e offset', 'Laringospasmo refratário'],
    dose_adulto: {
      habitual: '1–1,5 mg/kg IV bolus (onset 45–60 s, duração 10–15 min)',
      max: '2 mg/kg/dose',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['Dose única (SRI)'],
      instrucoes: 'SRI: succinilcolina 1,5 mg/kg IV bolus 60 s após indutor. Aguardar 45–60 s para laringoscopia. Não precisa de reversão (curta duração).',
    },
    contraindicacoes_rapidas: [
      'Hipercalemia (K+ > 5,5 ou risco: queimaduras > 24h, imobilização > 5 dias, denervação, crush syndrome)',
      'Distrofia muscular / miopatias (rabdomiólise)',
      'Hipertermia maligna (pessoal ou familiar)',
      'Pseudocolinesterase deficiente (apneia prolongada)',
      'Trauma globe aberto (↑ PIO)',
    ],
    interacoes_importantes: [
      { com: 'aminoglicosídeos', severidade: 'moderada', descricao: 'Potencialização do bloqueio' },
    ],
    alertas_especiais: [
      '⚠ HIPERCALEMIA: succinilcolina eleva K+ em 0,5–1 mEq/L (fatal em hipercalêmicos) — usar rocurônio',
      '⚠ HIPERTERMIA MALIGNA: succinilcolina é gatilho — história familiar contraindica',
      'Fasciculações: mialgias pós-operatórias frequentes',
      'NÃO antagonizável: deve aguardar recuperação espontânea',
      'Em criança < 10 anos: aumenta risco de hipercalemia/parada cardíaca em miopatias ocultas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Quelicin', laboratorio: 'Pfizer', concentracoes: ['200 mg/10 mL (20 mg/mL)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'rocurônio',
    molecula: 'rocurônio',
    nome_generico: 'Rocurônio',
    sinonimos: ['Esmeron', 'BNM não-despolarizante', 'SRI', 'ICU BNM', 'reversível sugamadex'],
    categoria: 'uti',
    classe: 'Bloqueador neuromuscular não-despolarizante (aminoesteroide)',
    indicacoes_principais: ['SRI (alternativa à succinilcolina — dose alta 1,2 mg/kg)', 'BNM de manutenção em UTI', 'ARDS grave (× 48h)'],
    dose_adulto: {
      habitual: 'SRI: 1,2 mg/kg IV | Manutenção: 0,3–0,6 mg/kg/h IC ou bolus q20–30 min (TOF-guiado)',
      max: '1,2 mg/kg (SRI) | IC: titular pelo TOF (1–2 respostas/4)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['SRI: dose única | Manutenção: IC ou bolus intermitente'],
      instrucoes: 'SRI com rocurônio: 1,2 mg/kg IV → onset 60–75 s (comparável à succinilcolina em dose alta). Antídoto: sugamadex 16 mg/kg (reversão imediata). Manutenção UTI: titular pelo TOF (aceleromiografia).',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade ao rocurônio ou bromo'],
    interacoes_importantes: [
      { com: 'aminoglicosídeos / polimixinas', severidade: 'moderada', descricao: 'Potencialização de bloqueio neuromuscular' },
      { com: 'magnésio', severidade: 'moderada', descricao: 'Potencialização do BNM (MgSO4 IC reduz necessidade de rocurônio)' },
    ],
    alertas_especiais: [
      'REVERSÃO IMEDIATA: sugamadex 16 mg/kg — ÚNICO antídoto confiável para rocurônio',
      'SRI: dose alta (1,2 mg/kg) equipara onset ao da succinilcolina',
      'TOF-guiado em UTI: monitor obrigatório para evitar bloqueio excessivo',
      'Acúmulo em IH (metabolismo hepático/bile) — reduzir dose de manutenção',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    ajuste_hepatico: { child_a: 'Usar com cautela — acúmulo', child_b: 'Reduzir dose e monitorar TOF', child_c: 'CONTRAINDICADO em dose alta — usar atracúrio/cisatracúrio' },
    marcas: [{ nome: 'Esmeron', laboratorio: 'MSD', concentracoes: ['10 mg/mL (5 mL e 10 mL)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'cisatracúrio',
    molecula: 'cisatracúrio',
    nome_generico: 'Cisatracúrio',
    sinonimos: ['Nimbex', 'BNM ARDS', 'degradação de Hofmann', 'ICU BNM'],
    categoria: 'uti',
    classe: 'Bloqueador neuromuscular não-despolarizante (benzilisoquinolínico)',
    indicacoes_principais: ['BNM de manutenção em UTI — ARDS grave × 48h (ACURASYS)', 'Pacientes com IR e IH (eliminação órgão-independente)', 'Status epiléptico refratário'],
    dose_adulto: {
      habitual: 'Ataque: 0,1–0,15 mg/kg IV | Manutenção IC: 1–3 mcg/kg/min (0,06–0,18 mg/kg/h)',
      max: '0,15 mg/kg (ataque) | 3 mcg/kg/min (IC)',
      unidade: 'mcg/kg/min',
      via: 'IV',
      frequencias: ['IC contínua em UTI'],
      instrucoes: 'DILUIÇÃO: 200 mg em 200 mL SF → 1 mg/mL. Titular TOF 1–2 respostas/4 em ARDS. ARDS trial: 37,5 mg/h de cisatracúrio × 48h.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'magnésio', severidade: 'moderada', descricao: 'Potencialização do BNM' },
      { com: 'aminoglicosídeos', severidade: 'moderada', descricao: 'Potencialização' },
    ],
    alertas_especiais: [
      'DEGRADAÇÃO DE HOFMANN: eliminação espontânea por pH e temperatura — ideal em IR+IH',
      'ARDS grave: cisatracúrio × 48h melhora sobrevida (ACURASYS) — iniciar dentro de 48h do diagnóstico de ARDS < PaO2/FiO2 150',
      'Monitorar TOF: alvo 1–2/4 twitch (bloqueio moderado)',
      'Menor liberação de histamina que atracúrio',
      'Sem reversão enzimática confiável — neostigmina após TOF ≥ 2/4',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Nimbex', laboratorio: 'GSK', concentracoes: ['2 mg/mL (5 mL e 25 mL)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'sugamadex',
    molecula: 'sugamadex',
    nome_generico: 'Sugamadex',
    sinonimos: ['Bridion', 'reversão BNM', 'antídoto rocurônio', 'ciclo-dextrina'],
    categoria: 'emergencia',
    classe: 'Ciclodextrina modificada — agente de encapsulação seletiva de BNM aminosteroidal',
    indicacoes_principais: ['Reversão de bloqueio neuromuscular por rocurônio ou vecurônio', 'Emergência "cannot intubate / cannot oxygenate" (reversão imediata rocurônio)'],
    dose_adulto: {
      habitual: 'Bloqueio moderado (TOF 1–2): 2 mg/kg IV | Bloqueio profundo (TOF 0): 4 mg/kg IV | Emergência (RSI rocurônio 1,2 mg/kg): 16 mg/kg IV',
      max: '16 mg/kg (emergência)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['Dose única IV bolus'],
      instrucoes: 'Bolus IV em 10 s. Reversão em 3 min (TOF moderado) ou < 3 min (emergência com 16 mg/kg). Aguardar TOF ≥ 4/4 para extubação segura.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'contraceptivos hormonais', severidade: 'moderada', descricao: 'Sugamadex liga-se ao progestogênio — usar método de barreira adicional por 7 dias' },
      { com: 'toremifeno', severidade: 'moderada', descricao: 'Deslocamento competitivo do sugamadex' },
    ],
    alertas_especiais: [
      'GOLD STANDARD para reversão de rocurônio/vecurônio',
      'Emergência CICV (cannot intubate/cannot ventilate): 16 mg/kg IV → reversão completa em < 3 min',
      'NÃO funciona para atracúrio/cisatracúrio/succinilcolina (mecanismo específico para aminosteroides)',
      'Bradicardia transitória: rara (< 1%)',
      'Recurarização: rara; se ocorrer → nova dose de sugamadex',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Bridion', laboratorio: 'MSD', concentracoes: ['200 mg/2 mL (100 mg/mL)'], formas: ['Ampola IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── CHOQUE / SEPSE ────────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'hidrocortisona-choque',
    molecula: 'hidrocortisona',
    nome_generico: 'Hidrocortisona (Choque Séptico Refratário)',
    sinonimos: ['Solu-Cortef', 'corticoide sepse', 'hidrocortisona IC', 'insuficiência adrenal relativa'],
    categoria: 'uti',
    classe: 'Corticosteroide — glicocorticoide + mineralocorticoide',
    indicacoes_principais: ['Choque séptico refratário a vasopressores (SSC 2021 — recomendação fraca)', 'Insuficiência adrenal primária ou crise adrenal', 'ARDS moderado-grave (dexametasona preferida)', 'Tempestade tireoidiana (bloqueia conversão T4→T3)'],
    dose_adulto: {
      habitual: 'Choque séptico: 200 mg/dia IV (50 mg 6/6h OU IC 200 mg/24h) × 7 dias ou até desmame vasopressor',
      max: '300 mg/dia (crise adrenal grave)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['50 mg 6/6h IV (bolus) ou IC 200 mg/24h — conforme protocolo institucional'],
      instrucoes: 'SSC 2021: iniciar se NOR > 0,25 mcg/kg/min por > 4h. NÃO testar ACTH (não atrasa início). Desmame: reduzir gradualmente após desmame do vasopressor.',
    },
    contraindicacoes_rapidas: ['Infecção fúngica sistêmica sem cobertura antifúngica'],
    interacoes_importantes: [
      { com: 'insulina / antidiabéticos', severidade: 'moderada', descricao: 'Hiperglicemia — aumentar monitorização glicêmica' },
      { com: 'AINE', severidade: 'moderada', descricao: 'Risco GI aditivo — IBP profilático' },
    ],
    alertas_especiais: [
      'SSC 2021: indicar APENAS em choque refratário (NOR > 0,25 mcg/kg/min) — não rotineiramente',
      'Hiperglicemia: controle glicêmico intensificado (alvo 140–180 mg/dL)',
      'Hipernatremia: monitorar sódio (efeito mineralocorticoide)',
      'Desmame gradual após retirada do vasopressor (rebote hemodinâmico)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Solu-Cortef', laboratorio: 'Pfizer', concentracoes: ['100 mg', '500 mg (pó)'], formas: ['Frasco IV liofilizado'] },
      { nome: 'Hidrocortisona (genérico)', laboratorio: 'Eurofarma', concentracoes: ['100 mg/2 mL'], formas: ['Ampola IV'] },
    ],
  },
  {
    id: 'acido-tranexamico',
    molecula: 'ácido tranexâmico',
    nome_generico: 'Ácido Tranexâmico',
    sinonimos: ['Transamin', 'TXA', 'antifibrinolítico', 'trauma hemorrágico', 'hemorragia pós-parto'],
    categoria: 'emergencia',
    classe: 'Antifibrinolítico — inibidor da plasmina e ativadores do plasminogênio',
    indicacoes_principais: ['Trauma com hemorragia (CRASH-2) — iniciar < 3h', 'Hemorragia pós-parto (HPP) — 1ª linha junto a ocitocina', 'Hemorragia digestiva alta (benefício incerto — HALT-IT)', 'Hemoptise maciça', 'Epistaxe grave', 'Cirurgia com alto risco hemorrágico'],
    dose_adulto: {
      habitual: 'Trauma/HPP: 1 g IV em 10 min → 1 g IV em 8h (total 2 g) | Epistaxe: 500 mg IV ou 1 g VO',
      max: '2 g/dose (bolus) | 4 g/dia',
      unidade: 'g',
      via: 'IV',
      frequencias: ['1ª dose: bolus + 2ª dose: 8h após'],
      instrucoes: 'Trauma: INICIAR EM < 3h DO TRAUMA (após 3h: sem benefício, possível dano — CRASH-2). HPP: 1 g IV logo após diagnóstico + repetir se hemorragia persistente em 30 min.',
    },
    contraindicacoes_rapidas: ['TEV ativo (trombose venosa profunda, embolia pulmonar)', 'Hematúria macroscópica (pode causar obstrução ureteral por coágulo)'],
    interacoes_importantes: [
      { com: 'fator IX concentrado', severidade: 'grave', descricao: 'Risco trombótico aumentado' },
    ],
    alertas_especiais: [
      '⚠ JANELA TERAPÊUTICA: eficaz apenas se < 3h do trauma (CRASH-2) — após 3h piora mortalidade',
      'HPP: adicionado ao protocolo FIGO 2022 como 1ª linha junto a uterotônicos',
      'Convulsões: dose-dependente em neurocirurgia (atravessa BHE) — doses < 2 g: risco mínimo',
      'TEV: pequeno risco — avaliar em pacientes com FR',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    ajuste_renal: {
      normal: 'Dose habitual',
      tfg_60_30: 'Reduzir dose 50%',
      tfg_30_15: 'Reduzir 66% (1/3 da dose)',
      tfg_lt_15: 'Reduzir 75%',
      dialisavel: true,
    },
    marcas: [
      { nome: 'Transamin', laboratorio: 'Daiichi Sankyo', concentracoes: ['500 mg/5 mL (100 mg/mL)'], formas: ['Ampola IV'] },
      { nome: 'Ácido Tranexâmico (genérico)', laboratorio: 'Várias', concentracoes: ['500 mg/5 mL'], formas: ['Ampola IV', 'Comprimido 500 mg'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── PCR — FARMACOLOGIA ────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'amiodarona-pcr',
    molecula: 'amiodarona',
    nome_generico: 'Amiodarona (PCR / Arritmia Ventricular)',
    sinonimos: ['Ancoron', 'Cordarone', 'antiarrítmico Classe III', 'FV refratária'],
    categoria: 'emergencia',
    classe: 'Antiarrítmico Classe III — bloqueia canais K+ (prolongamento QT)',
    indicacoes_principais: ['PCR — FV/TVsP refratária a choque (3° choque)', 'TV hemodinamicamente estável (cardioversão farmacológica)', 'FA/Flutter com alta resposta ventricular', 'Profilaxia de TV/FV recorrente'],
    dose_adulto: {
      habitual: 'PCR: 300 mg IV bolus (após 3° choque) → 150 mg se TV/FV persistente | Arritmia estável: 150 mg IV em 10 min → 1 mg/min × 6h → 0,5 mg/min × 18h',
      max: '2,2 g/dia (IV)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['PCR: bolus único | Arritmia estável: ataque + manutenção IC'],
      instrucoes: 'PCR: 300 mg diluído em 20–30 mL SG 5% (bolus rápido). Manutenção: 900 mg em 500 mL SG 5% (1,8 mg/mL) — usar equipo âmbar (fotossensível). Sempre CVC para IC prolongada (flebite em periférico).',
    },
    contraindicacoes_rapidas: [
      'Bradicardia sinusal grave ou BAV sem MP',
      'Choque cardiogênico (relativa)',
      'Gravidez (relativo — usar se ameaça à vida)',
    ],
    interacoes_importantes: [
      { com: 'varfarina', severidade: 'grave', descricao: 'Inibe CYP2C9 → ↑↑ INR — reduzir varfarina 30–50%' },
      { com: 'digoxina', severidade: 'grave', descricao: 'Dobra nível sérico de digoxina — reduzir dose de digoxina 50%' },
      { com: 'sotalol / outros antiarrítmicos', severidade: 'grave', descricao: 'Torsade de pointes por QT muito longo' },
    ],
    alertas_especiais: [
      'Hipotensão na infusão rápida: pelo veículo polissorbato 80 (não pela amiodarona) — infundir lentamente fora de PCR',
      'Toxicidade crônica (uso VO prolongado): pulmonar (fibrose), tireoidiana (hiper/hipotireoidismo), hepática, ocular, fotossensibilidade',
      'Amiodarona IV aguda: monitorar PA e ECG continuamente',
      'Antídoto para WPW + FA: NÃO usar amiodarona (pode acelerar condução acessória) — cardioversão elétrica',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Ancoron', laboratorio: 'Sanofi', concentracoes: ['150 mg/3 mL (50 mg/mL)'], formas: ['Ampola IV'] },
      { nome: 'Amiodarona (genérico)', laboratorio: 'Eurofarma', concentracoes: ['150 mg/3 mL'], formas: ['Ampola IV'] },
    ],
  },
  {
    id: 'adenosina',
    molecula: 'adenosina',
    nome_generico: 'Adenosina',
    sinonimos: ['Adenocard', 'TSV', 'conversão sinusal', 'AV bloqueio'],
    categoria: 'emergencia',
    classe: 'Nucleosídeo endógeno — agonista de receptor A1 (bloqueia nó AV transitoriamente)',
    indicacoes_principais: ['TSV paroxística (com reentrada no nó AV — reversão a sinusal)', 'Diagnóstico diferencial de taquicardia de QRS largo (diagnóstico)'],
    dose_adulto: {
      habitual: '6 mg IV bolus rápido → sem resposta em 1–2 min: 12 mg → repetir 12 mg se necessário',
      max: '12 mg/dose (total máx 30 mg)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Bolus único — repetir conforme resposta'],
      instrucoes: 'TÉCNICA CRÍTICA: bolus IV rápido em 1–2 s em veia antecubital + flush imediato com 20 mL SF rápido (empurrar). Meia-vida < 10 s — atraso na técnica = falha. Avisar paciente de desconforto torácico transitório (5–10 s).',
    },
    contraindicacoes_rapidas: [
      'Asma / DPOC grave (broncoespasmo)',
      'Bloqueio AV 2° ou 3° sem MP',
      'Síndrome do nó sinusal',
      'WPW com FA/flutter (pode acelerar via acessória → FV)',
      'Uso de dipiridamol (potencializa muito — reduzir dose para 1–3 mg)',
    ],
    interacoes_importantes: [
      { com: 'dipiridamol', severidade: 'grave', descricao: 'Inibe recaptação de adenosina → potencialização 4–8× — usar 1–3 mg' },
      { com: 'teofilina / cafeína', severidade: 'moderada', descricao: 'Antagonistas do receptor A1 → bloqueiam efeito da adenosina (dose maior necessária)' },
    ],
    alertas_especiais: [
      '⚠ TÉCNICA: bolus em 1–2 s + flush SF imediato — sem isso o fármaco não chega ao coração (meia-vida < 10 s)',
      '⚠ WPW + FA/flutter: CONTRAINDICADO (pode facilitar condução acessória → FV)',
      'Desconforto torácico, flushing, dispneia: transitórios (< 30 s) — informar paciente',
      'Pausa sinusal: normal após conversão — dura segundos',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Adenocard', laboratorio: 'Pfizer', concentracoes: ['3 mg/mL (2 mL = 6 mg)'], formas: ['Ampola IV'] }],
  },
  {
    id: 'bicarbonato-sodio-pcr',
    molecula: 'bicarbonato de sódio',
    nome_generico: 'Bicarbonato de Sódio (PCR / Acidose)',
    sinonimos: ['NaHCO3', 'bicarb', 'PCR hipercalemia', 'acidose grave'],
    categoria: 'emergencia',
    classe: 'Tampão — alcalinizante sistêmico',
    indicacoes_principais: ['PCR por hipercalemia grave', 'PCR por intoxicação por antidepressivos tricíclicos (TCA) ou salicilatos', 'Acidose metabólica grave (pH < 7,1) sintomática', 'Alcalinização urinária (rabdomiólise, toxicidade por MTX)'],
    dose_adulto: {
      habitual: 'PCR: 1 mEq/kg IV (50–100 mEq = 50–100 mL NaHCO3 8,4%) | Acidose: conforme déficit de base',
      max: '1–2 mEq/kg por dose em emergência',
      unidade: 'mEq/kg',
      via: 'IV',
      frequencias: ['PCR: bolus | Acidose: IC em 30–60 min'],
      instrucoes: 'CONCENTRAÇÕES: 8,4% = 1 mEq/mL | 4,2% = 0,5 mEq/mL. NÃO misturar na mesma linha com Ca²⁺ (precipitação de CaCO3). Flush generoso de SF entre administrações.',
    },
    contraindicacoes_rapidas: ['Alcalose metabólica / respiratória pré-existente', 'Hipocalcemia (piora alcalose → ↓ Ca²⁺ ionizado)'],
    interacoes_importantes: [
      { com: 'cálcio IV', severidade: 'grave', descricao: 'Precipitação de carbonato de cálcio na mesma linha — flush obrigatório entre eles' },
      { com: 'catecolaminas', severidade: 'moderada', descricao: 'Alcalose inativa catecolaminas (não misturar)' },
    ],
    alertas_especiais: [
      '⚠ PCR ACLS 2020: NÃO usar rotineiramente (sem benefício — CO2 gerado piora acidose intracelular)',
      'INDICAÇÕES ESPECÍFICAS em PCR: hipercalemia, TCA, acidose pré-existente documentada, bicarbonato-dependente',
      'Hipernatremia e hiperosmolaridade: monitorar sódio sérico (8,4% = 1000 mOsm/L)',
      'Hipocalemia: gerada pela alcalose (K entra na célula)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'seguro',
    marcas: [{ nome: 'Bicarbonato de Sódio (genérico)', laboratorio: 'Várias', concentracoes: ['8,4% (1 mEq/mL)', '4,2% (0,5 mEq/mL)'], formas: ['Frasco IV 250 mL', 'Ampola 10 mL'] }],
  },
  {
    id: 'gluconato-calcio',
    molecula: 'gluconato de cálcio',
    nome_generico: 'Gluconato de Cálcio',
    sinonimos: ['Calciguard', 'Ca²⁺ IV', 'estabilizador membrana', 'hipercalemia', 'hipocalcemia'],
    categoria: 'emergencia',
    classe: 'Eletrólito — cálcio iônico divalente',
    indicacoes_principais: ['Hipercalemia com ECG alterado (estabilização da membrana)', 'Hipocalcemia sintomática (pós-paratireidectomia, transfusão maciça)', 'Toxicidade por bloqueadores de canal de cálcio (BCC)', 'Toxicidade por sulfato de magnésio (antídoto)', 'Síndrome de lise tumoral (hipocalcemia)', 'Fluoreto (intoxicação)'],
    dose_adulto: {
      habitual: 'Hipercalemia com ECG: 1 g IV (10 mL da solução 10%) em 2–3 min — repetir em 5 min se ECG persistir | Hipocalcemia sintomática: 1–2 g IV em 10–20 min',
      max: '3 g/dose',
      unidade: 'g',
      via: 'IV',
      frequencias: ['Bolus IV lento (2–3 min) — repetir conforme resposta'],
      instrucoes: 'Gluconato 10%: 1 g = 90 mg de cálcio elementar. Cloreto de cálcio 10%: 1 g = 270 mg elementar (mais potente, mas causa necrose em periférico — CVC). Administrar em linha sem bicarbonato.',
    },
    contraindicacoes_rapidas: ['Hipercalcemia', 'Digoxina (relativa — pode precipitar toxicidade em hipercalemia + digoxina)', 'Administração rápida (arritmias graves)'],
    interacoes_importantes: [
      { com: 'digoxina', severidade: 'grave', descricao: 'Cálcio + digoxina em hipercalemia: risco de toxicidade digitálica grave — usar com extrema cautela (monitorar ECG)' },
      { com: 'bicarbonato de sódio', severidade: 'grave', descricao: 'Precipitação na mesma linha — flush obrigatório' },
    ],
    alertas_especiais: [
      'HIPERCALEMIA + ECG ALTERADO: gluconato/cloreto de Ca²⁺ NÃO reduz calemia — estabiliza membrana (efeito em 2–3 min, dura 30–60 min). Tratar calemia em paralelo.',
      'Extravascular periférico: gluconato 10% menos irritante que cloreto 10% (preferir CVC para cloreto)',
      'BCC toxicidade: altas doses de gluconato (2–3 g IV) + alta dose insulina (1 UI/kg IV) + glicose',
      'Antídoto MgSO4: gluconato 1 g IV (reverte depressão respiratória e bloqueio NM por Mg)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Gluconato de Cálcio 10%', laboratorio: 'Várias', concentracoes: ['100 mg/mL (10 mL = 1 g)'], formas: ['Ampola IV'] },
      { nome: 'Cloreto de Cálcio 10%', laboratorio: 'Várias', concentracoes: ['100 mg/mL (10 mL)'], formas: ['Ampola IV (CVC)'] },
    ],
  },
  {
    id: 'atropina',
    molecula: 'atropina',
    nome_generico: 'Atropina',
    sinonimos: ['anticolinérgico', 'bradicardia', 'PCR assistolia AESP (histórico)'],
    categoria: 'emergencia',
    classe: 'Anticolinérgico — antagonista muscarínico',
    indicacoes_principais: ['Bradicardia sintomática hemodinamicamente instável (1ª linha)', 'Intoxicação colinérgica (organofosforados, carbamatos) — altas doses', 'Bloqueio AV sintomático (temporário)'],
    dose_adulto: {
      habitual: 'Bradicardia: 1 mg IV — repetir q3–5 min (máx 3 mg = dose vagolítica total) | Organofosforado: 1–6 mg IV repetir q5–10 min até secreções secas',
      max: '3 mg (bradicardia) | Ilimitado em organofosforado (guiado por secreções)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Bolus IV — repetir conforme resposta'],
      instrucoes: 'ATENÇÃO: doses < 0,5 mg causam bradicardia paradoxal (estímulo central do vago). Dose mínima: 0,5 mg IV em adultos.',
    },
    contraindicacoes_rapidas: ['Glaucoma de ângulo fechado (relativa — em emergência usar)', 'Íleo paralítico / retenção urinária (relativa)'],
    interacoes_importantes: [
      { com: 'antidepressivos tricíclicos', severidade: 'moderada', descricao: 'Efeitos anticolinérgicos aditivos' },
    ],
    alertas_especiais: [
      '⚠ DOSE MÍNIMA 0,5 mg IV — doses menores causam bradicardia paradoxal (efeito central parassimpático)',
      'BAV infranodal (BAV 2° tipo 2, BAV total com QRS largo): atropina INEFICAZ — MP imediato',
      'ACLS 2020: atropina REMOVIDA do algoritmo de AESP/assistolia (sem benefício — não recomendada rotineiramente)',
      'Organofosforado: titular atropina pela secreção brônquica (não pela FC ou pupila)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Atropina (genérico)', laboratorio: 'Hipolabor / Farmace', concentracoes: ['0,5 mg/mL', '1 mg/mL'], formas: ['Ampola IV/IM/SC'] }],
  },
  {
    id: 'alteplase-tep',
    molecula: 'alteplase',
    nome_generico: 'Alteplase (rtPA — Trombólise)',
    sinonimos: ['Actilyse', 'rtPA', 'trombolítico', 'TEP maciço', 'AVC isquêmico', 'fibrinolítico'],
    categoria: 'emergencia',
    classe: 'Trombolítico — ativador de plasminogênio tecidual recombinante (rtPA)',
    indicacoes_principais: ['TEP maciço com instabilidade hemodinâmica (1ª linha)', 'AVC isquêmico agudo (NIHSS ≥ 4, < 4,5h do onset)', 'IAM com CSST sem cateterismo disponível < 2h (primária) ou > 2h (resgate)', 'Trombose de prótese valvar', 'Oclusão de CVC (dose baixa)'],
    dose_adulto: {
      habitual: 'TEP maciço: 100 mg IV em 2h (10 mg bolus + 90 mg em 2h) | TEP colapso: 50 mg IV bolus | AVC: 0,9 mg/kg (máx 90 mg) — 10% bolus + 90% em 1h',
      max: '100 mg/dose (TEP) | 90 mg (AVC)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Dose única (AVC, TEP) — IC em 1–2h'],
      instrucoes: 'TEP parada: alteplase 50 mg IV bolus em 2 min + continuar RCP × 60–90 min pós-trombólise. Anticoagulação: suspender durante infusão, retomar UFH sem ataque 1h após término. Contraindicação absoluta: AVC hemorrágico, sangramento ativo.',
    },
    contraindicacoes_rapidas: [
      'AVC hemorrágico prévio (qualquer tempo)',
      'AVC isquêmico ou TCE grave < 3 meses',
      'Cirurgia intracraniana ou espinhal < 3 meses',
      'Sangramento ativo (exceto menstruação)',
      'Neoplasia intracraniana / MAV / aneurisma',
      'Dissecção de aorta suspeita',
      'Hipertensão grave não controlada (> 185/110 no AVC)',
    ],
    interacoes_importantes: [
      { com: 'anticoagulantes', severidade: 'grave', descricao: 'Risco de sangramento aditivo — suspender durante trombólise' },
    ],
    alertas_especiais: [
      '⚠ SANGRAMENTO: risco de hemorragia intracraniana 1–6% (AVC) — seleção rigorosa de candidatos',
      'TEP maciço com parada: benefício supera riscos — iniciar mesmo sem certeza diagnóstica se provável',
      'AVC: janela 4,5h (início dos sintomas) — confirmar NIHSS, PAS < 185, TC sem hemorragia',
      'Pós-trombólise: NÃO fazer punções venosas desnecessárias × 24h',
      'Antídoto hemorragia por alteplase: ácido tranexâmico 1 g IV + crioprecipitado (fibrinogênio)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Actilyse', laboratorio: 'Boehringer Ingelheim', concentracoes: ['50 mg (pó)', '100 mg (pó)'], formas: ['Frasco liofilizado IV'] }],
  },
  {
    id: 'naloxona',
    molecula: 'naloxona',
    nome_generico: 'Naloxona',
    sinonimos: ['Narcan', 'antídoto opioide', 'reversão opioide', 'NLX'],
    categoria: 'emergencia',
    classe: 'Antagonista opioide — bloqueador µ/κ/δ competitivo',
    indicacoes_principais: ['Reversão de depressão respiratória por opioides (overdose)', 'Prurido por opioides intratecais (dose baixa IV)', 'Diagnóstico de dependência a opioides'],
    dose_adulto: {
      habitual: 'Reversão: 0,04–0,4 mg IV q2–3 min até FR > 10 e SpO₂ > 90% | Overdose grave: 0,4–2 mg IV/IM/IN | IC pós-reversão: 2/3 da dose efetiva por hora',
      max: '10 mg (titulado — sem limite estrito em overdose maciça)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Bolus q2–3 min até efeito | IC se necessário'],
      instrucoes: 'TITULAR CUIDADOSAMENTE: evitar despertar abrupto e precipitação de síndrome de abstinência aguda. Em UTI: 0,04 mg q2 min até FR > 10/min (antagonismo parcial — manter analgesia). Meia-vida 60–90 min (< opioides de longa ação) — repetir ou IC.',
    },
    contraindicacoes_rapidas: ['Dependência a opioides (precipita abstinência grave) — titular cuidadosamente'],
    interacoes_importantes: [],
    alertas_especiais: [
      '⚠ MEIA-VIDA CURTA: naloxona 60–90 min < maioria dos opioides → ressedação e nova depressão respiratória possível após 1h — manter monitorização',
      'IC: necessária se opioide de longa ação (metadona, morfina LP) — 2/3 da dose efetiva/hora',
      'Abstinência precipitada: taquicardia, HAS, agitação, síndrome de abstinência aguda — evitar doses altas sem necessidade',
      'Via IM/IN: alternativas válidas em emergência pré-hospitalar (kit comunitário de reversão)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Narcan', laboratorio: 'Indivior', concentracoes: ['0,4 mg/mL (1 mL)'], formas: ['Ampola IV/IM'] },
      { nome: 'Narcan Nasal', laboratorio: 'Indivior', concentracoes: ['4 mg/0,1 mL'], formas: ['Spray nasal'] },
    ],
  },
  {
    id: 'flumazenil',
    molecula: 'flumazenil',
    nome_generico: 'Flumazenil',
    sinonimos: ['Lanexat', 'antídoto BZD', 'reversão benzodiazepínico'],
    categoria: 'emergencia',
    classe: 'Antagonista competitivo de receptor GABA-A benzodiazepínico',
    indicacoes_principais: ['Reversão de sedação excessiva por benzodiazepínicos', 'Diagnóstico de encefalopatia hepática (reduz efeito de BZD endógenos)', 'Overdose de BZD isolada'],
    dose_adulto: {
      habitual: '0,2 mg IV em 15 s → repetir 0,1 mg q1 min (máx 1 mg por episódio) | IC: 0,1–0,4 mg/h se sedação recorrente',
      max: '1 mg por episódio (3 mg/h)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Bolus titulado q1 min | IC pós-reversão se necessário'],
      instrucoes: 'Onset: 1–2 min. Meia-vida: 30–60 min (< maioria dos BZD). Risco de ressedação após 1h. NÃO usar em dependente de BZD (convulsões de abstinência).',
    },
    contraindicacoes_rapidas: [
      'Dependência crônica a BZD (precipita convulsões por abstinência)',
      'Overdose mista com TCA (remove proteção anticonvulsivante do BZD → convulsões)',
      'Controle de convulsões por BZD (epiléptico em uso de BZD para status)',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      '⚠ RESSEDAÇÃO: meia-vida curta → paciente pode ressedir após 30–60 min — IC ou observação mínima 2h',
      '⚠ DEPENDÊNCIA: precipita síndrome de abstinência aguda grave (convulsões) — NÃO usar rotineiramente em usuários crônicos',
      'Overdose BZD com CO2: tratar a hipercapnia/hipóxia primeiro (O₂, suporte ventilatório)',
      'Encefalopatia hepática: uso diagnóstico/terapêutico (BZD endógenos nos hepatopatas)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Lanexat', laboratorio: 'Roche', concentracoes: ['0,1 mg/mL (5 mL = 0,5 mg)'], formas: ['Ampola IV'] }],
  },
];
