// ============================================================
// PRESCREVE-AI — Extensão Farmacológica: GASTROENTEROLOGIA (Phase 21.8) — Parte A
// IBP · Bloqueadores H2 · Antieméticos · Laxativos · Antidiarreicos · Imunossupressores
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_GASTRO_A: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════════
  // IBP — Inibidores da Bomba de Prótons
  // (omeprazol e esomeprazol já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'pantoprazol',
    molecula: 'Pantoprazol',
    nome_generico: 'Sódio de Pantoprazol',
    sinonimos: ['pantoprazol', 'pantozol', 'protonix', 'ibp pantoprazol', 'ulcera pantoprazol', 'drge pantoprazol', 'pantoprazol clopidogrel'],
    categoria: 'gastroenterologia',
    classe: 'IBP',
    subclasse: 'Inibidor da Bomba de Prótons — menor inibição CYP2C19 que omeprazol/esomeprazol — preferível com clopidogrel',
    indicacoes_principais: [
      'DRGE / esofagite erosiva',
      'Úlcera péptica gástrica e duodenal',
      'Erradicação H. pylori (esquemas tríplices)',
      'Síndrome de Zollinger-Ellison',
      'Prevenção de úlcera por AINEs (em coronariopatas usando clopidogrel — preferível ao omeprazol)',
      'Profilaxia de úlcera de estresse em UTI (IV)',
    ],
    dose_adulto: {
      habitual: '40 mg VO 1×/dia (30 min antes café da manhã)',
      min: '20 mg/dia',
      max: '160 mg/dia (Zollinger-Ellison)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (manhã, em jejum) | IV: 40 mg 1–2×/dia'],
      instrucoes: 'H. pylori: 40 mg 2×/dia + amoxicilina 1 g 2×/dia + claritromicina 500 mg 2×/dia × 14 dias. IV (UTI): 40 mg/dia (diluir em SF). VANTAGEM vs omeprazol: menor inibição CYP2C19 → menor interação com clopidogrel.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste (excreção biliar)', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Máx 20 mg/dia', child_c: 'Máx 20 mg/dia' },
    contraindicacoes_rapidas: ['Hipersensibilidade a benzimidazóis substituídos', 'Uso com rilpivirina/atazanavir (necessita acidez gástrica)'],
    interacoes_importantes: [
      { com: 'Clopidogrel', severidade: 'leve', descricao: 'Menor inibição CYP2C19 que omeprazol — IBP de escolha em coronariopatas com clopidogrel' },
      { com: 'Metotrexato (altas doses)', severidade: 'moderada', descricao: 'IBP reduz excreção renal do metotrexato — toxicidade' },
      { com: 'Atazanavir / rilpivirina', severidade: 'contraindicado', descricao: 'IBP aumenta pH → absorção do antirretroviral cai drasticamente' },
    ],
    alertas_especiais: [
      'USO PROLONGADO > 1 ANO: risco de hipomagnesemia (monitorar Mg2+ a cada 6 meses), deficiência B12, fraturas (osteoporose), infecção por C. difficile',
      'PREFERÍVEL ao omeprazol em: coronariopatas com clopidogrel, pacientes CYP2C19 ultra-metabolizadores',
      'REVER indicação anualmente: muitos pacientes usam IBP sem indicação formal',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: IBP > 8 semanas sem indicação formal — risco de hipomagnesemia, C. difficile, fraturas',
    stopp: 'STOPP A4: IBP em dose máxima por > 8 semanas sem tentativa de desmame',
    marcas: [
      { nome: 'Pantozol®', laboratorio: 'Takeda', concentracoes: ['20 mg', '40 mg VO', '40 mg IV'], formas: ['Comprimido gastrorresistente', 'Pó injetável'] },
      { nome: 'Pantoprazol EMS', laboratorio: 'EMS', concentracoes: ['20 mg', '40 mg'], formas: ['Comprimido'] },
      { nome: 'Pantoprazol Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['40 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'lansoprazol',
    molecula: 'Lansoprazol',
    nome_generico: 'Lansoprazol',
    sinonimos: ['lanzol', 'prevacid', 'lansoprazol', 'ibp lansoprazol', 'ulcera lansoprazol'],
    categoria: 'gastroenterologia',
    classe: 'IBP',
    subclasse: 'IBP — disponível em cápsulas que podem ser abertas (útil em SNG) e comprimidos dispersíveis',
    indicacoes_principais: [
      'DRGE e esofagite erosiva',
      'Úlcera péptica',
      'Erradicação H. pylori',
      'Dispepsia funcional (curto prazo)',
    ],
    dose_adulto: {
      habitual: '30 mg VO 1×/dia (DRGE) | 30 mg 2×/dia (H. pylori)',
      min: '15 mg/dia',
      max: '60 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–2×/dia (30 min antes da refeição)'],
      instrucoes: 'Cápsulas podem ser abertas e misturadas em suco de maçã (não água quente). Comprimido dispersível (SolTab) dissolve na boca. Útil em pacientes com SNG.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir para 15 mg/dia', child_b: 'Máx 15 mg/dia', child_c: 'Máx 15 mg/dia' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Atazanavir / rilpivirina'],
    interacoes_importantes: [
      { com: 'Metotrexato', severidade: 'moderada', descricao: 'IBP retarda excreção renal do MTX' },
      { com: 'Clopidogrel', severidade: 'moderada', descricao: 'Inibição CYP2C19 — menor que omeprazol mas existe' },
    ],
    alertas_especiais: ['CÁPSULAS EM SNG: abrir e misturar em 40 mL de suco de maçã para administração'],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    stopp: 'STOPP A4: IBP sem indicação formal > 8 semanas',
    marcas: [
      { nome: 'Lanzol®', laboratorio: 'Takeda', concentracoes: ['15 mg', '30 mg'], formas: ['Cápsula gastrorresistente', 'Comprimido dispersível (SolTab)'] },
      { nome: 'Lansoprazol EMS', laboratorio: 'EMS', concentracoes: ['15 mg', '30 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'rabeprazol',
    molecula: 'Rabeprazol Sódico',
    nome_generico: 'Rabeprazol Sódico',
    sinonimos: ['pariet', 'aciphex', 'rabeprazol', 'ibp rabeprazol', 'ibp independente cyp2c19'],
    categoria: 'gastroenterologia',
    classe: 'IBP',
    subclasse: 'IBP — menor dependência de CYP2C19 que omeprazol — mais consistente entre genótipos',
    indicacoes_principais: ['DRGE', 'Úlcera péptica', 'H. pylori (erradicação)', 'Dispepsia'],
    dose_adulto: {
      habitual: '20 mg VO 1×/dia',
      min: '10 mg/dia',
      max: '40 mg/dia (2×/dia em H. pylori)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (antes do café da manhã)'],
      instrucoes: 'Não mastigar ou partir (gastrorresistente). Vantagem teórica: menor variação de efeito entre UM/PM de CYP2C19.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Máx 10 mg/dia', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Atazanavir'],
    interacoes_importantes: [
      { com: 'Metotrexato', severidade: 'moderada', descricao: 'Redução da excreção renal do MTX' },
    ],
    alertas_especiais: ['Menor variabilidade farmacogenômica vs omeprazol — opção em populações com alta prevalência de EM CYP2C19'],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP2C19 (menor dependência que outros IBPs — mais previsível em PM/UM)'],
    marcas: [
      { nome: 'Pariet®', laboratorio: 'Janssen', concentracoes: ['10 mg', '20 mg'], formas: ['Comprimido gastrorresistente'] },
      { nome: 'Rabeprazol EMS', laboratorio: 'EMS', concentracoes: ['20 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // BLOQUEADORES H2
  // ══════════════════════════════════════════════════════════════

  {
    id: 'ranitidina',
    molecula: 'Ranitidina',
    nome_generico: 'Cloridrato de Ranitidina',
    sinonimos: ['zantac', 'ranitidine', 'ranitidina', 'bloqueador h2 ranitidina', 'antagonista h2'],
    categoria: 'gastroenterologia',
    classe: 'Bloqueador H2',
    subclasse: 'Antagonista H2 — RETIRADO DO MERCADO em 2020 (ANVISA/FDA/EMA) por contaminação com NDMA (carcinógeno)',
    indicacoes_principais: [
      'DRGE leve (histórica — ATUALMENTE FORA DO MERCADO BRASILEIRO e EUA)',
      'Úlcera péptica (histórica)',
    ],
    dose_adulto: {
      habitual: '150 mg VO 2×/dia ou 300 mg à noite (RETIRADO)',
      min: '75 mg/dia',
      max: '300 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia ou 1×/dia noite'],
      instrucoes: 'IMPORTANTE: Ranitidina foi retirada do mercado global em 2020 por contaminação com NDMA (nitrosamina carcinógena). Usar FAMOTIDINA como alternativa H2.',
    },
    ajuste_renal: { normal: '150 mg 2×/dia', tfg_60_30: '150 mg 1×/dia', tfg_30_15: '150 mg 1×/dia', tfg_lt_15: '75 mg 1×/dia', dialisavel: true },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['RETIRADA DO MERCADO — NDMA (carcinógeno)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'leve', descricao: 'Pode aumentar INR levemente' },
    ],
    alertas_especiais: [
      'RETIRADA GLOBAL: FDA/ANVISA/EMA retiraram ranitidina do mercado em 2020 — níveis de NDMA inaceitáveis.',
      'SUBSTITUTO: usar famotidina (sem contaminação por NDMA) se bloqueador H2 for necessário.',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Zantac® (RETIRADO)', laboratorio: 'GSK/Sanofi', concentracoes: ['150 mg', '300 mg'], formas: ['Comprimido — FORA DO MERCADO'] },
    ],
  },

  {
    id: 'famotidina',
    molecula: 'Famotidina',
    nome_generico: 'Famotidina',
    sinonimos: ['famotidina', 'pepcid', 'famotidine', 'bloqueador h2 famotidina', 'h2 alternativa ranitidina'],
    categoria: 'gastroenterologia',
    classe: 'Bloqueador H2',
    subclasse: 'Antagonista H2 — sem contaminação por NDMA — potência 20–40× maior que cimetidina',
    indicacoes_principais: [
      'DRGE leve a moderada',
      'Úlcera péptica (gástrica e duodenal)',
      'Dispepsia (alívio de sintomas)',
      'Síndrome de Zollinger-Ellison (altas doses)',
      'Alternativa ao IBP em COVID-19 associada a hiperinflamação (off-label — dados emergentes)',
    ],
    dose_adulto: {
      habitual: '20–40 mg VO 1–2×/dia',
      min: '20 mg/dia',
      max: '160 mg/dia (Zollinger-Ellison)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (noite — úlcera) | 2×/dia (DRGE)'],
      instrucoes: 'Pode ser tomado com ou sem alimento. Disponível sem receita em muitos países (20 mg). IV: 20 mg a cada 12h. Ajuste RENAL obrigatório (excreção renal).',
    },
    ajuste_renal: { normal: '20–40 mg 1–2×/dia', tfg_60_30: '20 mg 1–2×/dia', tfg_30_15: '20 mg 1×/dia ou 20 mg a cada 36–48h', tfg_lt_15: '20 mg a cada 36–48h', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Sem ajuste (mínimo metabolismo hepático)' },
    contraindicacoes_rapidas: ['Hipersensibilidade a H2 bloqueadores'],
    interacoes_importantes: [
      { com: 'Atazanavir', severidade: 'grave', descricao: 'Aumento do pH gástrico reduz absorção do atazanavir' },
      { com: 'Dasatinibe / erlotinibe', severidade: 'moderada', descricao: 'Redução de absorção por aumento de pH' },
    ],
    alertas_especiais: [
      'AJUSTE RENAL OBRIGATÓRIO: excreção predominantemente renal — acumulação em DRC',
      'PREFERÍVEL À RANITIDINA: sem risco de NDMA',
      'Menos interações que cimetidina (não inibe CYP)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: H2 bloqueadores — ajuste de dose obrigatório em DRC; cautela em idosos (confusão em doses altas)',
    marcas: [
      { nome: 'Famotidina EMS', laboratorio: 'EMS', concentracoes: ['20 mg', '40 mg'], formas: ['Comprimido'] },
      { nome: 'Famotidina Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['20 mg', '40 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'cimetidina',
    molecula: 'Cimetidina',
    nome_generico: 'Cimetidina',
    sinonimos: ['tagamet', 'cimetidine', 'cimetidina', 'bloqueador h2 interacoes', 'h2 primeiro geração'],
    categoria: 'gastroenterologia',
    classe: 'Bloqueador H2',
    subclasse: 'Antagonista H2 de 1ª geração — MÚLTIPLAS interações por inibição de CYP1A2, 2C9, 2D6, 3A4',
    indicacoes_principais: [
      'Úlcera péptica (uso histórico — preterida por famotidina/IBP)',
      'DRGE leve',
      'Verrugas (off-label — imunomodulação)',
    ],
    dose_adulto: {
      habitual: '800 mg VO à noite (úlcera) | 400 mg 2×/dia',
      min: '200 mg/dia',
      max: '1600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–4×/dia ou 1×/dia à noite'],
      instrucoes: 'Praticamente substituída por famotidina/IBP. Se usada: atentar para extensas interações CYP. Inibe CYP1A2, 2C9, 2D6, 3A4 — aumenta nível de varfarina, fenitoína, teofilina, lidocaína, amitriptilina.',
    },
    ajuste_renal: { normal: '800 mg/dia', tfg_60_30: '400 mg/dia', tfg_30_15: '200 mg/dia', tfg_lt_15: '200 mg/dia', dialisavel: true },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Múltiplas interações medicamentosas críticas', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'Inibe CYP2C9 — INR aumenta dramaticamente' },
      { com: 'Fenitoína', severidade: 'grave', descricao: 'Inibe CYP2C9 — fenitoína aumenta — toxicidade' },
      { com: 'Teofilina', severidade: 'grave', descricao: 'Inibe CYP1A2 — teofilina triplica — toxicidade' },
      { com: 'Amitriptilina / nortriptilina', severidade: 'moderada', descricao: 'Inibe CYP2D6 — TCA aumenta' },
    ],
    alertas_especiais: [
      'INIBIDOR MULTI-CYP: evitar sempre que possível — famotidina não inibe CYP. Causa interações com > 70 medicamentos',
      'Beers 2023: EVITAR em idosos — confusão mental, especialmente em DRC',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — confusão mental, múltiplas interações',
    stopp: 'STOPP A5: cimetidina com múltiplas interações críticas — substituir por famotidina',
    pgx_genes: ['CYP2D6 (inibidor)', 'CYP2C9 (inibidor)', 'CYP1A2 (inibidor)', 'CYP3A4 (inibidor moderado)'],
    marcas: [
      { nome: 'Tagamet®', laboratorio: 'GSK', concentracoes: ['200 mg', '400 mg', '800 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIEMÉTICOS
  // (domperidona já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'ondansetrona',
    molecula: 'Ondansetrona',
    nome_generico: 'Cloridrato de Ondansetrona',
    sinonimos: ['zofran', 'ondansetron', 'ondansetrona', 'antiemetico oncologia', '5ht3 antagonista', 'nauseias quimioterapia'],
    categoria: 'gastroenterologia',
    classe: 'Antiemético',
    subclasse: 'Antagonista 5-HT3 seletivo — 1ª linha para náuseas por quimioterapia e pós-operatório',
    indicacoes_principais: [
      'Náuseas e vômitos induzidos por quimioterapia (NVIQ) — 1ª linha altamente emetizante',
      'Náuseas e vômitos pós-operatórios (NVPO)',
      'Náuseas e vômitos da radioterapia',
      'Náuseas por gastrenterite (off-label — uso cada vez mais comum)',
    ],
    dose_adulto: {
      habitual: '8 mg VO ou IV 30 min antes da quimio | 4–8 mg 8/8h por 1–2 dias',
      min: '4 mg',
      max: '32 mg/dia (IV) | 24 mg/dia (VO) — FDA limitou IV a 16 mg/dose por QT',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–3×/dia | IV: em 15 min'],
      instrucoes: 'QT: FDA limita dose única IV a 16 mg (máx 32 mg/dia). Esquemas oncológicos: 8 mg IV/VO 30 min pré-quimio + 8 mg a cada 8h. NVPO: 4 mg IV ao final da cirurgia. Comprimido bucodispersível (Zofran Zydis) não necessita água.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Máx 8 mg/dia', child_c: 'Máx 8 mg/dia' },
    contraindicacoes_rapidas: ['QTc prolongado', 'Uso concomitante de apomorfina (hipotensão grave)'],
    interacoes_importantes: [
      { com: 'Apomorfina', severidade: 'contraindicado', descricao: 'Hipotensão profunda e perda de consciência' },
      { com: 'QT-prolongadores (antiarrítmicos, antipsicóticos, macrolídeos)', severidade: 'moderada', descricao: 'QT aditivo — torsades de pointes' },
      { com: 'Tramadol / SSRIs', severidade: 'leve', descricao: 'Risco teórico de síndrome serotoninérgica (raro)' },
    ],
    alertas_especiais: [
      'QT PROLONGADO: dose-dependente. FDA 2011: limitar IV a 16 mg/dose (não administrar 32 mg de uma vez)',
      'CONSTIPAÇÃO: efeito adverso frequente (3–10%) — orientar paciente',
      'EFICÁCIA EM GASTRENTERITE: dados crescentes apoiam uso VO em crianças/adultos — evita hospitalização',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    pgx_genes: ['CYP2D6 (metabolismo — PM: exposição aumentada)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Zofran®', laboratorio: 'GSK/Novartis', concentracoes: ['4 mg', '8 mg', '4 mg/2 mL IV'], formas: ['Comprimido', 'Bucodispersível (Zydis)', 'Ampola IV', 'Xarope'] },
      { nome: 'Ondansetrona EMS', laboratorio: 'EMS', concentracoes: ['4 mg', '8 mg'], formas: ['Comprimido', 'Ampola IV'] },
      { nome: 'Ondansetrona Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['4 mg', '8 mg', '2 mg/mL IV'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'metoclopramida',
    molecula: 'Metoclopramida',
    nome_generico: 'Cloridrato de Metoclopramida',
    sinonimos: ['plasil', 'metoclopramide', 'metoclopramida', 'antiemetico plasil', 'procinético plasil', 'antagonista dopamina gástrica'],
    categoria: 'gastroenterologia',
    classe: 'Antiemético',
    subclasse: 'Antagonista D2 + 5-HT3 + 5-HT4 agonista — procinético e antiemético central/periférico',
    indicacoes_principais: [
      'Náuseas e vômitos agudos (gastroenterite, pós-operatório)',
      'Gastroparesia diabética',
      'Aceleração de esvaziamento gástrico pré-endoscopia',
      'Enxaqueca com náuseas (IV — aumenta absorção de analgésicos orais)',
    ],
    dose_adulto: {
      habitual: '10 mg VO/IM/IV a cada 8h',
      min: '5 mg 3×/dia',
      max: '30 mg/dia (VO) | 40 mg/dia (IV hospital)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3×/dia (30 min antes das refeições)'],
      instrucoes: 'IV: administrar em 15 min (bolus rápido → agitação, reação discinética aguda). USO MÁXIMO 5 DIAS (ANVISA/EMA): risco de discinesia tardia com uso prolongado. Gastroparesia: 10 mg antes das 3 refeições + ao deitar.',
    },
    ajuste_renal: { normal: '10 mg 3×/dia', tfg_60_30: '10 mg 2×/dia', tfg_30_15: '5 mg 3×/dia', tfg_lt_15: '5 mg 2×/dia', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Obstrução mecânica / perfuração GI', 'Feocromocitoma', 'Epilepsia (diminui limiar)', 'Histórico de discinesia tardia'],
    interacoes_importantes: [
      { com: 'Antipsicóticos / levodopa', severidade: 'grave', descricao: 'Antagonismo dopaminérgico aditivo — piora de parkinsonismo; reduz efeito da levodopa' },
      { com: 'IMAO', severidade: 'grave', descricao: 'Crise hipertensiva (liberação de catecolaminas)' },
      { com: 'Ciclosporina', severidade: 'moderada', descricao: 'Aumenta absorção da ciclosporina (pró-cinético)' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Reduz absorção de digoxina de liberação lenta' },
    ],
    alertas_especiais: [
      'DISCINESIA TARDIA: risco com uso > 5 dias. EMA/ANVISA limitam a 5 dias de uso contínuo. Idosos e crianças têm risco maior',
      'REAÇÃO DISCINÉTICA AGUDA: torcicolos, crise oculógira (espasmo ocular) — tratamento: biperideno IV ou difenidramina IV',
      'NÃO USAR EM DOENÇA DE PARKINSON: antagonista D2 piora parkinsonismo',
      'Beers 2023: EVITAR em idosos — discinesia, parkinsonismo medicamentoso',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — discinesia tardia, parkinsonismo medicamentoso',
    stopp: 'STOPP C3: metoclopramida em idoso com Parkinson ou parkinsonismo',
    pgx_genes: ['CYP2D6 (metabolismo — PM: maior exposição)'],
    marcas: [
      { nome: 'Plasil®', laboratorio: 'Sanofi', concentracoes: ['10 mg comprimido', '5 mg/mL IV'], formas: ['Comprimido', 'Ampola IV'] },
      { nome: 'Metoclopramida EMS', laboratorio: 'EMS', concentracoes: ['10 mg'], formas: ['Comprimido'] },
      { nome: 'Metoclopramida Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['10 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'granisetrona',
    molecula: 'Granisetrona',
    nome_generico: 'Cloridrato de Granisetrona',
    sinonimos: ['kytril', 'granisetron', 'granisetrona', '5ht3 antagonista granisetron', 'antiemetico quimio granisetron'],
    categoria: 'gastroenterologia',
    classe: 'Antiemético',
    subclasse: 'Antagonista 5-HT3 — meia-vida mais longa que ondansetrona (9–12h) — 1 dose/dia na maioria dos esquemas',
    indicacoes_principais: [
      'NVIQ — náuseas por quimioterapia (alta e moderada emetogenicidade)',
      'NVPO',
      'Náuseas por radioterapia',
    ],
    dose_adulto: {
      habitual: '1 mg VO 2×/dia | 3 mg IV 30 min pré-quimio | Patch transdérmico: 3,1 mg/24h (7 dias)',
      min: '1 mg/dia',
      max: '9 mg/dia (IV)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['VO: 1–2×/dia | IV: 1 dose pré-quimio'],
      instrucoes: 'IV: 3 mg em 5 min (ou diluído em 50 mL SF em 30 min) 30 min antes da quimioterapia. Patch (Sancuso): aplicar 24–48h antes da quimio, manter até 7 dias.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'QTc prolongado'],
    interacoes_importantes: [
      { com: 'QT-prolongadores', severidade: 'moderada', descricao: 'QT aditivo — menor risco que ondansetrona mas existe' },
    ],
    alertas_especiais: [
      'MEIA-VIDA LONGA: 1 dose/dia suficiente vs ondansetrona (3×/dia) — melhor comodidade',
      'PATCH: Sancuso 3,1 mg/24h — opção para pacientes que não conseguem tomar VO (náuseas intensas)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    pgx_genes: ['CYP3A4 (metabolismo)', 'CYP1A1 (metabolismo)'],
    marcas: [
      { nome: 'Kytril®', laboratorio: 'Roche', concentracoes: ['1 mg VO', '3 mg/3 mL IV'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'roche' },
      { nome: 'Granisetrona EMS', laboratorio: 'EMS', concentracoes: ['1 mg', '3 mg/3 mL'], formas: ['Comprimido', 'Ampola IV'] },
    ],
  },


  // ══════════════════════════════════════════════════════════════
  // LAXATIVOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'lactulose',
    molecula: 'Lactulose',
    nome_generico: 'Lactulose',
    sinonimos: ['lactulose', 'lactulona', 'laevolac', 'laxativo osmotico lactulose', 'encefalopatia hepatica lactulose'],
    categoria: 'gastroenterologia',
    classe: 'Laxativo',
    subclasse: 'Dissacarídeo sintético — osmótico + acidificador colônico — 1ª linha em encefalopatia hepática',
    indicacoes_principais: [
      'Constipação intestinal (laxante osmótico)',
      'Encefalopatia hepática (reduz amônia colônica) — 1ª linha',
      'Preparo intestinal pré-coloscopia (alternativa)',
    ],
    dose_adulto: {
      habitual: '15–30 mL VO 1–3×/dia (constipação) | 30–45 mL 3–4×/dia (encefalopatia)',
      min: '10 mL/dia',
      max: '90 mL/dia',
      unidade: 'mL',
      via: 'VO',
      frequencias: ['1–4×/dia'],
      instrucoes: 'ENCEFALOPATIA HEPÁTICA: alvo de 2–3 evacuações/dia com fezes amolecidas. Pode ser administrada via enema retentivo (300 mL em 700 mL água) na encefalopatia aguda grave. Diluir em água ou suco para melhorar palatabilidade.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Uso principal é em hepatopatas', child_b: 'Indicação primária', child_c: 'Indicação primária — dose conforme resposta' },
    contraindicacoes_rapidas: ['Galactosemia', 'Obstrução intestinal', 'Dor abdominal de causa desconhecida'],
    interacoes_importantes: [
      { com: 'Antibióticos orais (neomicina, rifaximina)', severidade: 'leve', descricao: 'Sinérgicos na encefalopatia hepática (mecanismo complementar)' },
    ],
    alertas_especiais: [
      'ENCEFALOPATIA HEPÁTICA: alvo de 2–3 evacuações/dia (pH fecal ácido = NH3 → NH4+ não absorvível)',
      'DIABÉTICOS: contém açúcares — monitorar glicemia (uso prolongado em altas doses)',
      'FLATULÊNCIA: efeito adverso frequente (fermentação colônica) — tende a reduzir com o uso',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Lactulona®', laboratorio: 'Marjan', concentracoes: ['667 mg/mL'], formas: ['Xarope'] },
      { nome: 'Laevolac®', laboratorio: 'Merck', concentracoes: ['667 mg/mL'], formas: ['Xarope'] },
      { nome: 'Lactulose EMS', laboratorio: 'EMS', concentracoes: ['667 mg/mL'], formas: ['Xarope'] },
    ],
  },

  {
    id: 'bisacodil',
    molecula: 'Bisacodil',
    nome_generico: 'Bisacodil',
    sinonimos: ['dulcolax', 'bisacodyl', 'bisacodil', 'laxativo estimulante', 'supositório bisacodil'],
    categoria: 'gastroenterologia',
    classe: 'Laxativo',
    subclasse: 'Laxante estimulante/contact — ativa plexos mioentéricos e aumenta secreção de água',
    indicacoes_principais: [
      'Constipação funcional aguda',
      'Preparo intestinal pré-procedimento (colonoscopia, cirurgia)',
      'Constipação em pacientes acamados ou pós-operatório',
    ],
    dose_adulto: {
      habitual: '5–10 mg VO à noite | 10 mg supositório',
      min: '5 mg',
      max: '20 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (à noite) | Supositório: 1 dose matinal'],
      instrucoes: 'VO: efeito em 6–12h (tomar à noite para evacuação matinal). Supositório: efeito em 15–60 min. NÃO partir comprimido (revestimento entérico). NÃO tomar com leite ou antiácidos (dissolve antes do cólon → cólicas).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Cautela (uso limitado)', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['Obstrução intestinal', 'Apendicite aguda', 'Íleo paralítico', 'Dor abdominal de causa desconhecida'],
    interacoes_importantes: [
      { com: 'Antiácidos / leite', severidade: 'moderada', descricao: 'Dissolve revestimento entérico prematuramente → cólicas intensas e irritação gástrica' },
    ],
    alertas_especiais: [
      'USO MÁXIMO 7 DIAS: uso crônico causa dependência do cólon (cólon catártico — perda do reflexo natural)',
      'NÃO PARTIR: revestimento entérico essencial — comprimido inteiro',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'seguro',
    beers_criteria: 'Beers 2023: laxante estimulante preferível em idosos com opioides (vs osmóticos em DRC)',
    marcas: [
      { nome: 'Dulcolax®', laboratorio: 'Boehringer Ingelheim', concentracoes: ['5 mg comprimido', '10 mg supositório'], formas: ['Comprimido revestido', 'Supositório'] },
      { nome: 'Bisacodil EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '10 mg supositório'], formas: ['Comprimido', 'Supositório'] },
    ],
  },

  {
    id: 'polietilenoglicol',
    molecula: 'Macrogol / Polietilenoglicol 3350 (PEG 3350)',
    nome_generico: 'Macrogol 3350',
    sinonimos: ['peg 3350', 'macrogol', 'miralax', 'movicol', 'polietilenoglicol', 'polyethylene glycol', 'laxativo osmotico peg', 'constipação crônica peg'],
    categoria: 'gastroenterologia',
    classe: 'Laxativo',
    subclasse: 'Laxante osmótico macromolecular — não absorvido, não metabolizado, não fermentado — 1ª linha constipação crônica',
    indicacoes_principais: [
      'Constipação crônica (1ª linha — evidence-based)',
      'Desimpactação fecal (doses altas por 3 dias)',
      'Preparo intestinal para colonoscopia (PEG 4000/GoLytely — 4 litros)',
      'Constipação induzida por opioides',
    ],
    dose_adulto: {
      habitual: '17 g (1 sachê) VO em 120 mL água 1×/dia',
      min: '8,5 g/dia',
      max: '34 g/dia (desimpactação: até 68 g/dia × 3 dias)',
      unidade: 'g',
      via: 'VO',
      frequencias: ['1–2×/dia'],
      instrucoes: 'Constipação crônica: 17 g/dia em água. Desimpactação: 34 g 2×/dia × 3 dias. Preparo colonoscopia: 4 L de solução PEG-4000 (Nulytely/GoLytely). VANTAGEM: não fermentado → sem flatulência (vs lactulose); seguro em DRC (não absorvido); pode ser usado em crianças.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Preferível (não absorvido) — Monitorar eletrólitos em preparo de colonoscopia', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: ['Obstrução intestinal', 'Perfuração GI', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Medicamentos orais concomitantes', severidade: 'leve', descricao: 'Não tem interação sistêmica (não absorvido, sem CYP), mas o efeito osmótico/laxativo pode reduzir a absorção de outros fármacos VO — espaçar a administração' },
    ],
    alertas_especiais: [
      'LAXANTE PREFERIDO em DRC/hemodiálise: não absorvido, não altera eletrólitos',
      'SEM FERMENTAÇÃO: não causa flatulência excessiva (diferente de lactulose)',
      'Seguro em gravidez e lactação',
      'PREPARO COLONOSCOPIA: formulação isotônica com eletrólitos (Nulytely) é preferível em cardiopatas/nefropatas',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    start: 'START F2: laxante osmótico em paciente com constipação induzida por opioides',
    marcas: [
      { nome: 'Movicol®', laboratorio: 'Norgine', concentracoes: ['13,8 g sachê'], formas: ['Sachê'] },
      { nome: 'Muvinlax®', laboratorio: 'Hypermarcas', concentracoes: ['17 g sachê'], formas: ['Sachê'] },
      { nome: 'Lacday®', laboratorio: 'EMS', concentracoes: ['17 g sachê'], formas: ['Sachê'] },
    ],
  },

  {
    id: 'picossulfato-sodio',
    molecula: 'Picossulfato de Sódio',
    nome_generico: 'Picossulfato de Sódio',
    sinonimos: ['laxavit', 'dulcolax gotas', 'picossulfato', 'sodium picosulfate', 'laxativo gotas pediatrico'],
    categoria: 'gastroenterologia',
    classe: 'Laxativo',
    subclasse: 'Laxante estimulante (pró-droga → ativado por bactérias colônicas) — início em 6–12h',
    indicacoes_principais: [
      'Constipação funcional',
      'Preparo intestinal (em combinação com citrato de magnésio — Picoprep)',
      'Constipação em pediatria (gotas)',
    ],
    dose_adulto: {
      habitual: '5–10 mg VO à noite (2,5–5 mg/mL — 10–20 gotas)',
      min: '2,5 mg/dia',
      max: '20 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (noite)'],
      instrucoes: 'Solução oral (gotas): 7,5 mg/mL. 10–20 gotas à noite. Efeito em 6–12h. Preparo Picoprep: sachê (picossulfato 10 mg + óxido de magnésio + ácido cítrico) — 2 sachês espaçados × 1 dia antes da colonoscopia.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Obstrução intestinal', 'Desidratação grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Diuréticos e corticosteroides', severidade: 'moderada', descricao: 'Risco aumentado de distúrbio eletrolítico/hipocalemia, sobretudo em doses excessivas' },
      { com: 'Antibióticos', severidade: 'leve', descricao: 'Podem reduzir a ação laxativa (dependem da flora colônica para ativar o picossulfato)' },
      { com: 'Fármacos que prolongam QT (ondansetrona, haloperidol, macrolídeos, quinolonas)', severidade: 'moderada', descricao: 'A hipocalemia resultante aumenta o risco de torsades de pointes' },
    ],
    alertas_especiais: ['Uso pediátrico em gotas: cálculo de dose por kg necessário', 'Não usar cronicamente (estimulante — cólon catártico)'],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Laxavit®', laboratorio: 'EMS', concentracoes: ['7,5 mg/mL solução'], formas: ['Gotas'] },
      { nome: 'Dulcolax® Gotas', laboratorio: 'Boehringer', concentracoes: ['7,5 mg/mL'], formas: ['Gotas'] },
      { nome: 'Picoprep®', laboratorio: 'Ferring', concentracoes: ['10 mg sachê'], formas: ['Sachê efervescente (preparo colonoscopia)'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIDIARREICOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'loperamida',
    molecula: 'Loperamida',
    nome_generico: 'Cloridrato de Loperamida',
    sinonimos: ['imosec', 'imodium', 'loperamide', 'loperamida', 'antidiarreico loperamida', 'diarreia loperamida'],
    categoria: 'gastroenterologia',
    classe: 'Antidiarreico',
    subclasse: 'Agonista opioide periférico (μ) — não atravessa BHE em doses terapêuticas — sem dependência central',
    indicacoes_principais: [
      'Diarreia aguda (não infecciosa ou leve-moderada)',
      'Diarreia crônica (doença inflamatória intestinal — adjuvante)',
      'Diarreia por ileostomia / ressecção intestinal',
      'Diarreia associada a quimioterapia (irinotecano)',
    ],
    dose_adulto: {
      habitual: '4 mg inicial + 2 mg após cada evacuação líquida',
      min: '2 mg',
      max: '16 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['Conforme evacuações'],
      instrucoes: 'Diarreia aguda: 4 mg dose inicial → 2 mg após cada evacuação. Máx 16 mg/dia. Suspender se sem melhora em 48h. CONTRAINDICADO em diarreia com sangue, febre alta ou suspeita de colite por C. difficile (retém toxina).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado (reduz motilidade em encefalopatia)' },
    contraindicacoes_rapidas: ['Diarreia com sangue (disenteria)', 'Diarreia por C. difficile', 'Febre alta (> 38,5°C) associada', 'Colite ulcerativa aguda grave (megacólon tóxico)', 'Crianças < 2 anos'],
    interacoes_importantes: [
      { com: 'Inibidores CYP3A4 (cetoconazol, itraconazol)', severidade: 'moderada', descricao: 'Aumenta loperamida — risco de arritmia em altas doses' },
      { com: 'Quinidina / ritonavir (P-gp inibidores)', severidade: 'grave', descricao: 'Aumenta penetração de loperamida no SNC — risco de depressão respiratória em altas doses' },
    ],
    alertas_especiais: [
      'CONTRAINDICADO EM DIARREIA INFECCIOSA INVASIVA: retém toxinas e bactérias — risco de megacólon',
      'ALTAS DOSES: relatados casos de arritmia com superdosagem voluntária (uso recreativo) — FDA alerta',
      'DIARREIA POR IRINOTECANO: 4 mg + 2 mg a cada 2h até 12h sem diarreia (protocolo oncológico)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Imosec®', laboratorio: 'Janssen', concentracoes: ['2 mg'], formas: ['Cápsula', 'Comprimido'] },
      { nome: 'Loperamida EMS', laboratorio: 'EMS', concentracoes: ['2 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'racecadotrila',
    molecula: 'Racecadotrila',
    nome_generico: 'Racecadotrila',
    sinonimos: ['tiorfan', 'racecadotril', 'racecadotrila', 'encefalinase inibidor', 'antidiarreico secretor'],
    categoria: 'gastroenterologia',
    classe: 'Antidiarreico',
    subclasse: 'Inibidor da encefalinase (neprilisina) — reduz hipersecreção de água e eletrólitos SEM inibir motilidade',
    indicacoes_principais: [
      'Diarreia secretora aguda (crianças e adultos)',
      'Diarreia infantil com desidratação moderada (adjuvante a SRO)',
    ],
    dose_adulto: {
      habitual: '100 mg VO 3×/dia antes das refeições',
      min: '100 mg 3×/dia',
      max: '300 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3×/dia (antes das refeições)'],
      instrucoes: 'VANTAGEM vs loperamida: não inibe motilidade intestinal → sem risco de megacólon em diarreia infecciosa. Pediátrico: 1,5 mg/kg/dose 3×/dia. Usar por no máximo 7 dias.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Não recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Uso prolongado > 7 dias'],
    interacoes_importantes: [
      { com: 'Inibidores da ECA (enalapril, captopril, lisinopril)', severidade: 'grave', descricao: 'Risco aumentado de angioedema (ambos afetam metabolismo de peptídeos — bradicinina + encefalinase). Não recomendado em quem já teve angioedema por IECA' },
    ],
    alertas_especiais: [
      'MECANISMO DIFERENTE: não inibe motilidade → pode ser usado em diarreia infecciosa (diferente de loperamida)',
      'Pró-droga → tiorfano (metabólito ativo)',
      'OMS recomenda como adjuvante à SRO em diarreia secretora pediátrica',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Tiorfan®', laboratorio: 'Alfasigma', concentracoes: ['100 mg', '10 mg/sachê (pediátrico)'], formas: ['Cápsula', 'Sachê pediátrico'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // IMUNOSSUPRESSORES — Gastroenterologia / DII / Transplante
  // ══════════════════════════════════════════════════════════════

  {
    id: 'azatioprina',
    molecula: 'Azatioprina',
    nome_generico: 'Azatioprina',
    sinonimos: ['imuran', 'azathioprine', 'azatioprina', 'imunossupressor azatioprina', 'dii manutencao', 'crohn azatioprina'],
    categoria: 'imunossupressor',
    classe: 'Imunossupressor',
    subclasse: 'Análogo de purina — pró-droga da 6-mercaptopurina — inibe síntese de purinas → suprime linfócitos',
    indicacoes_principais: [
      'Doença de Crohn — manutenção da remissão (após corticoide)',
      'Retocolite ulcerativa — manutenção',
      'Artrite reumatoide (2ª linha)',
      'Lúpus eritematoso sistêmico',
      'Prevenção de rejeição em transplantes (adjuvante)',
      'Hepatite autoimune',
    ],
    dose_adulto: {
      habitual: '1,5–2,5 mg/kg/dia VO em 1–2 tomadas',
      min: '1 mg/kg/dia',
      max: '3 mg/kg/dia',
      unidade: 'mg/kg',
      via: 'VO',
      frequencias: ['1–2×/dia com alimento'],
      instrucoes: 'TESTAR TPMT ANTES: poor metabolizers acumulam tiopurinas → mielossupressão grave com doses usuais. Monitorar hemograma quinzenal por 3 meses → mensal. Efeito terapêutico após 3–6 meses (lento). Iniciar alopurinol: reduzir azatioprina 75% (interação fatal).',
    },
    ajuste_renal: { normal: '1,5–2,5 mg/kg/dia', tfg_60_30: 'Reduzir 25–50%', tfg_30_15: 'Reduzir 50%', tfg_lt_15: 'Evitar ou dose mínima monitorada', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose — hepatotóxico', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Alopurinol sem redução de dose (toxicidade fatal)', 'Hipersensibilidade', 'Infecção ativa grave'],
    interacoes_importantes: [
      { com: 'Alopurinol', severidade: 'contraindicado', descricao: 'Inibe xantina oxidase → acúmulo de tiopurina ativa 4× → pancitopenia grave/fatal. Se obrigatório: reduzir AZA 75% + monitorar hemograma' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Reduz efeito da varfarina — mecanismo incerto' },
      { com: 'Inibidores ECA', severidade: 'moderada', descricao: 'Anemia e leucopenia aditivos' },
    ],
    alertas_especiais: [
      'TPMT ANTES DE INICIAR: tiopurina metiltransferase — PM homozigotos: CONTRAINDICADO (risco de pancitopenia fatal). PM heterozigotos: usar 50% da dose',
      'ALOPURINOL: interação potencialmente fatal — reduzir AZA 75% ou SUBSTITUIR por mercaptopurina',
      'CARCINOGÊNESE: risco aumentado de linfoma (especialmente EBV+) e câncer de pele com uso prolongado',
      'HEMOGRAMA QUINZENAL: por 3 meses, depois mensal',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['TPMT (metabolismo tiopurinas — PM: pancitopenia grave com doses usuais)', 'NUDT15 (alternativa ao TPMT — especialmente em asiáticos)'],
    marcas: [
      { nome: 'Imuran®', laboratorio: 'Aspen', concentracoes: ['50 mg'], formas: ['Comprimido'] },
      { nome: 'Azatioprina EMS', laboratorio: 'EMS', concentracoes: ['50 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'ciclosporina',
    molecula: 'Ciclosporina',
    nome_generico: 'Ciclosporina A',
    sinonimos: ['sandimmun', 'neoral', 'ciclosporin', 'ciclosporina', 'imunossupressor calcineurina', 'transplante ciclosporina'],
    categoria: 'imunossupressor',
    classe: 'Imunossupressor',
    subclasse: 'Inibidor da calcineurina — inibe IL-2 (ativação linfócitos T) — múltiplas interações CYP3A4/P-gp',
    indicacoes_principais: [
      'Prevenção de rejeição em transplante renal, hepático, cardíaco',
      'Doença de Crohn refratária / retocolite ulcerativa grave aguda',
      'Síndrome nefrótica resistente a esteroides',
      'Psoríase grave refratária',
      'Artrite reumatoide refratária',
    ],
    dose_adulto: {
      habitual: '3–5 mg/kg/dia VO em 2 tomadas (transplante) | 2,5 mg/kg/dia (autoimune)',
      min: '2,5 mg/kg/dia',
      max: '5 mg/kg/dia (transplante) | 5 mg/kg/dia (autoimune)',
      unidade: 'mg/kg',
      via: 'VO',
      frequencias: ['2×/dia (a cada 12h, consistente em horário e relação com alimento)'],
      instrucoes: 'NÍVEL SÉRICO OBRIGATÓRIO (C0/C2): C0 alvo: 150–400 ng/mL (transplante precoce) → 100–200 ng/mL (manutenção). NEORAL (emulsão micro) ≠ SANDIMMUN (óleo): NÃO intercambiar sem ajuste de dose (biodisponibilidade diferente). Tomar sempre no mesmo horário com relação consistente ao alimento.',
    },
    ajuste_renal: { normal: 'Monitorar creatinina e TFG mensalmente', tfg_60_30: 'Reduzir dose — nefrotóxica', tfg_30_15: 'Evitar ou dose muito baixa monitorada', tfg_lt_15: 'Contraindicado em DRC avançada exceto transplante', dialisavel: false },
    ajuste_hepatico: { child_a: 'Monitorar nível — metabolismo aumentado', child_b: 'Reduzir dose (metabolismo hepático)', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['HAS não controlada', 'DRC grave (nefrotoxicidade)', 'Infecção ativa não controlada', 'Malignidade (exceto basoceluloma)', 'Hipersensibilidade ao óleo de rícino (Sandimmun IV)'],
    interacoes_importantes: [
      { com: 'Fluconazol / voriconazol / itraconazol', severidade: 'grave', descricao: 'Inibição CYP3A4 → ciclosporina aumenta 2–5× → nefrotoxicidade. Reduzir dose 50% e monitorar nível' },
      { com: 'Rifampicina / carbamazepina / fenitoína', severidade: 'grave', descricao: 'Indução CYP3A4 → ciclosporina cai 3–5× → rejeição' },
      { com: 'Estatinas (especialmente lovastatina, sinvastatina)', severidade: 'grave', descricao: 'Inibição CYP3A4 → estatina aumenta dramaticamente → miopatia/rabdomiólise' },
      { com: 'AINEs / aminoglicosídeos', severidade: 'grave', descricao: 'Nefrotoxicidade aditiva — evitar' },
      { com: 'Grapefruit (suco)', severidade: 'moderada', descricao: 'Inibição CYP3A4 intestinal → ciclosporina aumenta — evitar' },
    ],
    alertas_especiais: [
      'NEFROTÓXICA: principal limitação. Monitorar creatinina e eletrólitos semanalmente no início, depois mensalmente',
      'NEORAL ≠ SANDIMMUN: formulações NÃO intercambiáveis sem reajuste de dose (Neoral 20–30% mais biodisponível)',
      'HAS: efeito adverso em > 50% dos pacientes — tratar com IECA ou BCC (not diltiazem/verapamil — inibem CYP3A4)',
      'HIPERTRICOSE, hiperplasia gengival, tremor: efeitos adversos típicos',
      'MALIGNIDADE: risco aumentado de linfoma e carcinoma espinocelular com uso prolongado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    pgx_genes: ['CYP3A4 (metabolismo extenso — múltiplas interações)', 'CYP3A5 (metabolismo — polimorfismo afeta dose)', 'ABCB1/P-gp (transporte — afeta biodisponibilidade)'],
    marcas: [
      { nome: 'Neoral®', laboratorio: 'Novartis', concentracoes: ['25 mg', '50 mg', '100 mg', '100 mg/mL solução'], formas: ['Cápsula mole', 'Solução oral'], lab_id: 'novartis' },
      { nome: 'Sandimmun®', laboratorio: 'Novartis', concentracoes: ['50 mg/mL IV'], formas: ['Concentrado injetável'] },
    ],
  },

  {
    id: 'tacrolimo',
    molecula: 'Tacrolimo',
    nome_generico: 'Tacrolimo (FK506)',
    sinonimos: ['prograf', 'advagraf', 'tacrolimus', 'tacrolimo', 'fk506', 'imunossupressor transplante', 'calcineurina tacrolimo'],
    categoria: 'imunossupressor',
    classe: 'Imunossupressor',
    subclasse: 'Inibidor da calcineurina (macrólido — não antibiótico) — 10–100× mais potente que ciclosporina',
    indicacoes_principais: [
      'Prevenção de rejeição — transplante renal (1ª linha), hepático, cardíaco, pulmonar',
      'Dermatite atópica grave (uso tópico 0,03% e 0,1%)',
      'DII refratária (off-label)',
    ],
    dose_adulto: {
      habitual: '0,1–0,2 mg/kg/dia VO em 2 tomadas (imediata) | 0,1–0,2 mg/kg/dia 1×/dia (Advagraf LP)',
      min: '0,05 mg/kg/dia',
      max: 'Guiado por nível sérico',
      unidade: 'mg/kg',
      via: 'VO',
      frequencias: ['2×/dia (IR — Prograf) | 1×/dia (LP — Advagraf)'],
      instrucoes: 'NÍVEL SÉRICO (C0) OBRIGATÓRIO: Rim: 8–12 ng/mL (1º ano) → 5–8 ng/mL (manutenção). Fígado: 5–15 ng/mL. Em jejum consistente (2h antes e 1h depois). ADVAGRAF (LP) ≠ PROGRAF (IR): NÃO intercambiar 1:1. Alimento reduz absorção.',
    },
    ajuste_renal: { normal: 'Guiado por nível', tfg_60_30: 'Reduzir dose — nefrotóxico', tfg_30_15: 'Nível sérico estrito', tfg_lt_15: 'Uso em transplante apenas — guiado por nível', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela — metabolismo hepático', child_b: 'Reduzir dose', child_c: 'Reduzir dose significativamente' },
    contraindicacoes_rapidas: ['Hipersensibilidade a macrólidos (reação cruzada)', 'Sirolimo concomitante (nefrotoxicidade aditiva severa)', 'Infecção ativa grave'],
    interacoes_importantes: [
      { com: 'Fluconazol / voriconazol / posaconazol', severidade: 'grave', descricao: 'Inibição CYP3A4 → tacrolimo aumenta 5–10× → nefrotoxicidade. Reduzir 50–80% da dose' },
      { com: 'Rifampicina / carbamazepina', severidade: 'grave', descricao: 'Indução CYP3A4 → tacrolimo cai → rejeição' },
      { com: 'Eritromicina / claritromicina', severidade: 'grave', descricao: 'Inibição CYP3A4 → tacrolimo aumenta' },
      { com: 'Grapefruit / tangerina pomelo', severidade: 'moderada', descricao: 'Inibição CYP3A4 intestinal' },
    ],
    alertas_especiais: [
      'NÍVEL SÉRICO: monitorar diariamente no início, semanal no 1º mês, mensal depois',
      'NEFROTOXICIDADE: principal limitação — monitorar creatinina, K+, Mg2+ semanalmente',
      'NEUROTOXICIDADE: tremor, cefaleia, alterações visuais — relacionado ao nível sérico elevado',
      'DIABETE PÓS-TRANSPLANTE: mais frequente que com ciclosporina (PTDM) — monitorar glicemia',
      'PROGRAF ≠ ADVAGRAF: substituição requer ajuste de dose e monitoramento rigoroso de nível',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    pgx_genes: ['CYP3A4 (metabolismo — múltiplas interações críticas)', 'CYP3A5 (polimorfismo — afeta dose: *3/*3 PM: dose 30–50% menor)', 'ABCB1/P-gp (transporte)'],
    marcas: [
      { nome: 'Prograf®', laboratorio: 'Astellas', concentracoes: ['0,5 mg', '1 mg', '5 mg', '5 mg/mL IV'], formas: ['Cápsula', 'Concentrado injetável'] },
      { nome: 'Advagraf®', laboratorio: 'Astellas', concentracoes: ['0,5 mg', '1 mg', '3 mg', '5 mg'], formas: ['Cápsula LP'] },
    ],
  },

  {
    id: 'micofenolato-mofetil',
    molecula: 'Micofenolato Mofetil',
    nome_generico: 'Micofenolato Mofetil',
    sinonimos: ['cellcept', 'mycophenolate', 'micofenolato', 'mmf', 'imunossupressor transplante mmf', 'lupus micofenolato'],
    categoria: 'imunossupressor',
    classe: 'Imunossupressor',
    subclasse: 'Pró-droga do ácido micofenólico (MPA) — inibidor da IMPDH — inibe proliferação de linfócitos T e B',
    indicacoes_principais: [
      'Prevenção de rejeição em transplante renal, hepático, cardíaco (adjuvante a tacrolimo/ciclosporina)',
      'Nefrite lúpica (indução e manutenção)',
      'Vasculites sistêmicas (ANCA — Wegener, microscópica)',
      'Doenças autoimunes refratárias (miosite, SSc, etc.)',
    ],
    dose_adulto: {
      habitual: '1,5–3 g/dia VO em 2 tomadas (transplante) | 2–3 g/dia (nefrite lúpica)',
      min: '500 mg 2×/dia',
      max: '3 g/dia',
      unidade: 'g',
      via: 'VO',
      frequencias: ['2×/dia (12/12h — consistência essencial)'],
      instrucoes: 'Tomar em jejum (1h antes ou 2h após alimento) — alimento reduz Cmax mas não AUC (aceitável). MMF (Cellcept) = pró-droga. Micofenolato sódico gastrorresistente (Myfortic) tem menor GI adverso. Teratogênico — contracepção dupla OBRIGATÓRIA.',
    },
    ajuste_renal: { normal: 'Sem ajuste (dose guiada por clínica)', tfg_60_30: 'Sem ajuste formal', tfg_30_15: 'Máx 2 g/dia (acúmulo de glucuronídeo)', tfg_lt_15: 'Máx 2 g/dia — cautela', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela (hepatite D pode interferir)', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['GRAVIDEZ (teratogênico — FDA D)', 'Hipersensibilidade ao ácido micofenólico'],
    interacoes_importantes: [
      { com: 'Antiácidos (magnésio/alumínio)', severidade: 'moderada', descricao: 'Reduz absorção do MMF em 33% — separar por 2h' },
      { com: 'Colestiramina / sevelamer', severidade: 'moderada', descricao: 'Interrompe ciclo entero-hepático do MPA → reduz exposição 40%' },
      { com: 'Rifampicina', severidade: 'moderada', descricao: 'Indução glucuronidação → MPA cai → risco de rejeição' },
    ],
    alertas_especiais: [
      'TERATOGENICIDADE: BLACK BOX — defeitos faciais, malformações cardíacas, microtia. CONTRACEPÇÃO DUPLA obrigatória em mulheres em idade fértil. Suspender 6 semanas antes de tentativa de gravidez',
      'GASTROINTESTINAL: diarreia, náuseas frequentes — Myfortic (gastrorresistente) tem menos efeito GI',
      'IMUNOSSUPRESSÃO: monitorar infecções oportunistas (CMV, BK vírus, PCP)',
      'HEMOGRAMA: monitorar mensalmente — leucopenia e anemia',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    pgx_genes: ['UGT (glucuronidação do MPA — polimorfismos afetam nível)', 'IMPDH1/IMPDH2 (alvo — variantes associadas a resposta)'],
    marcas: [
      { nome: 'Cellcept®', laboratorio: 'Roche', concentracoes: ['250 mg', '500 mg', '1 g/5 mL pó IV'], formas: ['Cápsula', 'Comprimido', 'Pó injetável'], lab_id: 'roche' },
      { nome: 'Myfortic®', laboratorio: 'Novartis', concentracoes: ['180 mg', '360 mg'], formas: ['Comprimido gastrorresistente (menor GI adverso)'], lab_id: 'novartis' },
    ],
  },

];
