// ============================================================
// PRESCREVE-AI — Extensão Farmacológica: NEUROLOGIA + PSIQUIATRIA (Phase 21.7) — Parte A
// ISRS · IRSN · TCA · IMAO · Antipsicóticos Típicos e Atípicos
// Campos adicionais: beers_criteria · stopp · start · pgx_genes
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_NEURO_A: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════════
  // ISRS — Inibidores Seletivos da Recaptação de Serotonina
  // (sertralina, escitalopram, paroxetina já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'fluoxetina',
    molecula: 'Fluoxetina',
    nome_generico: 'Cloridrato de Fluoxetina',
    sinonimos: ['prozac', 'fluoxetine', 'fluoxetina', 'isrs', 'antidepressivo', 'fluoxetina prozac'],
    categoria: 'psiquiatria',
    classe: 'ISRS',
    subclasse: 'Inibidor Seletivo da Recaptação de Serotonina — meia-vida longa (1–4 dias + metabólito ativo 4–16 dias)',
    indicacoes_principais: [
      'Depressão maior (1ª linha)',
      'Transtorno obsessivo-compulsivo (TOC)',
      'Bulimia nervosa (único ISRS aprovado FDA)',
      'Transtorno de pânico',
      'Disforia pré-menstrual (TDPM)',
    ],
    dose_adulto: {
      habitual: '20 mg VO 1×/dia (manhã)',
      min: '10 mg/dia',
      max: '80 mg/dia (TOC/bulimia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (manhã — evita insônia)'],
      instrucoes: 'Iniciar 10–20 mg/dia. Titular a cada 4 semanas. TOC/bulimia: até 60–80 mg/dia. Meia-vida longa → desmame menos abrupto. Não necessita titulação na suspensão em curso curto.',
    },
    ajuste_renal: { normal: '20 mg/dia', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Cautela — dados limitados', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir 50% ou dias alternados', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO nas últimas 5 semanas (fluoxetina — washout longo!)', 'Pimozida (QT)', 'Tioridazina'],
    interacoes_importantes: [
      { com: 'IMAO (selegilina, fenelzina, tranilcipromina)', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica fatal — washout obrigatório: 5 semanas após fluoxetina antes de IMAO' },
      { com: 'Tamoxifeno', severidade: 'grave', descricao: 'Inibe CYP2D6 — reduz conversão tamoxifeno→endoxifeno (metabólito ativo) em 60–75% — falha terapêutica no câncer de mama' },
      { com: 'Tramadol / Triptanos', severidade: 'grave', descricao: 'Síndrome serotoninérgica' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Inibe CYP2C9 — aumenta INR' },
      { com: 'Antipsicóticos metabolizados por CYP2D6 (haloperidol, risperidona)', severidade: 'moderada', descricao: 'Aumenta nível do antipsicótico' },
    ],
    alertas_especiais: [
      'WASHOUT DE IMAO: 5 semanas após suspender fluoxetina antes de iniciar IMAO (meia-vida muito longa)',
      'TAMOXIFENO: contraindicação relativa em câncer de mama HR+ — preferir sertralina ou citalopram (menor inibição CYP2D6)',
      'BLACK BOX FDA: risco de ideação suicida em < 25 anos nas primeiras 4 semanas — monitorar',
      'Inibidor potente de CYP2D6 e moderado de CYP2C9/3A4',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    beers_criteria: 'Não listado (ISRS em geral: cautela em quedas em idosos — risco de hiponatremia e sangramento GI)',
    stopp: 'STOPP H2: ISRS em paciente com queda recente — risco de hiponatremia e hipotensão ortostática',
    start: 'START C1: antidepressivo indicado em depressão maior moderada-grave quando sintomas ≥ 3 meses',
    pgx_genes: ['CYP2D6 (metabolismo — PM: concentração aumentada 2–3×)', 'CYP2C19 (metabolismo secundário)', 'SLC6A4 (resposta clínica — 5-HTTLPR)'],
    marcas: [
      { nome: 'Prozac®', laboratorio: 'Lilly', concentracoes: ['10 mg', '20 mg'], formas: ['Cápsula', 'Comprimido'] },
      { nome: 'Fluoxetina EMS', laboratorio: 'EMS', concentracoes: ['10 mg', '20 mg'], formas: ['Cápsula'] },
      { nome: 'Fluoxetina Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['20 mg'], formas: ['Cápsula'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'citalopram',
    molecula: 'Citalopram',
    nome_generico: 'Hidrobrometo de Citalopram',
    sinonimos: ['cipramil', 'celexa', 'citalopram', 'isrs qt', 'citalopram qt'],
    categoria: 'psiquiatria',
    classe: 'ISRS',
    subclasse: 'ISRS — alta seletividade serotoninérgica + risco de prolongamento QT dose-dependente',
    indicacoes_principais: [
      'Depressão maior',
      'Transtorno de pânico',
      'TOC (off-label)',
    ],
    dose_adulto: {
      habitual: '20 mg VO 1×/dia',
      min: '10 mg/dia',
      max: '40 mg/dia (20 mg em > 60 anos ou hepatopatas — FDA)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia'],
      instrucoes: 'FDA limitou dose máxima a 40 mg/dia (20 mg em idosos, hepatopatas, CYP2C19 poor metabolizers) por risco de QT. Escitalopram é o enantiômero ativo com melhor perfil.',
    },
    ajuste_renal: { normal: '20–40 mg/dia', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Não recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: '20 mg/dia máximo', child_b: '20 mg/dia máximo', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['QTc > 450 ms (homens) / > 470 ms (mulheres)', 'IMAO', 'Pimozida', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica' },
      { com: 'QT-prolongadores (antiarrítmicos, antipsicóticos, azóis)', severidade: 'grave', descricao: 'QT aditivo — torsades de pointes' },
      { com: 'Omeprazol / Esomeprazol', severidade: 'moderada', descricao: 'Inibição CYP2C19 — aumenta citalopram → QT' },
    ],
    alertas_especiais: [
      'QT DOSE-DEPENDENTE: FDA Black Box — máx 20 mg em > 60 anos. Escitalopram tem melhor tolerância e sem limite de 20 mg em idosos (preferível)',
      'ECG antes e após titulação em cardiopatas',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: cautela em idosos — QT prolongado dose-dependente; preferir escitalopram',
    stopp: 'STOPP J1: citalopram > 20 mg/dia em idoso',
    pgx_genes: ['CYP2C19 (PM: duplica concentração — reduzir dose)', 'CYP2D6 (metabolismo secundário)'],
    marcas: [
      { nome: 'Cipramil®', laboratorio: 'Lundbeck', concentracoes: ['20 mg', '40 mg'], formas: ['Comprimido'] },
      { nome: 'Citalopram EMS', laboratorio: 'EMS', concentracoes: ['20 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'fluvoxamina',
    molecula: 'Fluvoxamina',
    nome_generico: 'Maleato de Fluvoxamina',
    sinonimos: ['luvox', 'fluvoxamine', 'fluvoxamina', 'isrs toc', 'isrs crianca'],
    categoria: 'psiquiatria',
    classe: 'ISRS',
    subclasse: 'ISRS — potente inibidor CYP1A2 e CYP2C19',
    indicacoes_principais: [
      'TOC (1ª escolha pediátrica ≥ 8 anos)',
      'Fobia social',
      'TEPT',
      'Depressão maior',
    ],
    dose_adulto: {
      habitual: '100–200 mg/dia dividido 2×/dia',
      min: '50 mg/dia',
      max: '300 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia (doses > 100 mg)'],
      instrucoes: 'Iniciar 50 mg/dia à noite. Aumentar 50 mg a cada 7 dias. Doses > 100 mg: dividir 2×/dia. Tomar à noite (sedação).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO', 'Tizanidina', 'Alosetron', 'Pimozida', 'Tioridazina'],
    interacoes_importantes: [
      { com: 'Teofilina', severidade: 'grave', descricao: 'Inibe CYP1A2 — teofilina triplica — toxicidade grave' },
      { com: 'Clozapina', severidade: 'grave', descricao: 'Inibe CYP1A2 — aumenta clozapina dramaticamente — agranulocitose e convulsões' },
      { com: 'Varfarina', severidade: 'grave', descricao: 'Inibe CYP2C9 — INR aumenta' },
      { com: 'Benzodiazepínicos (diazepam, alprazolam)', severidade: 'moderada', descricao: 'Inibe CYP3A4/2C19 — aumenta BZD' },
    ],
    alertas_especiais: [
      'INIBIDOR POTENTE CYP1A2: múltiplas interações — teofilina, clozapina, caffeine, olanzapina',
      'INIBIDOR CYP2C19: afeta omeprazol, clopidogrel, fenitoína',
      'Sedação: tomar à noite',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    pgx_genes: ['CYP2D6 (metabolismo)', 'CYP1A2 (inibição — interações)'],
    marcas: [
      { nome: 'Luvox®', laboratorio: 'Solvay/Abbott', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
      { nome: 'Fluvoxamina EMS', laboratorio: 'EMS', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // IRSN — Inibidores da Recaptação de Serotonina e Noradrenalina
  // (venlafaxina e duloxetina já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'desvenlafaxina',
    molecula: 'Desvenlafaxina',
    nome_generico: 'Succinato de Desvenlafaxina',
    sinonimos: ['pristiq', 'desvenlafaxine', 'desvenlafaxina', 'irsn metabolito venlafaxina'],
    categoria: 'psiquiatria',
    classe: 'IRSN',
    subclasse: 'Metabólito ativo da venlafaxina — sem metabolização por CYP2D6 (vantagem em PM)',
    indicacoes_principais: [
      'Depressão maior',
      'Fogachos da menopausa (off-label — evidência B)',
    ],
    dose_adulto: {
      habitual: '50 mg VO 1×/dia',
      min: '50 mg/dia',
      max: '100 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (com ou sem alimento)'],
      instrucoes: 'Dose fixa 50 mg/dia — sem necessidade de titulação. Não partir ou mastigar (LP). Vantagem sobre venlafaxina: menor variabilidade por polimorfismo CYP2D6.',
    },
    ajuste_renal: { normal: '50 mg/dia', tfg_60_30: '50 mg/dia', tfg_30_15: '50 mg a cada 2 dias', tfg_lt_15: '50 mg a cada 2 dias', dialisavel: false },
    ajuste_hepatico: { child_a: '50 mg/dia', child_b: '50 mg/dia máximo', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: ['IMAO', 'Hipersensibilidade à venlafaxina ou desvenlafaxina'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Risco serotoninérgico aditivo' },
    ],
    alertas_especiais: [
      'VANTAGEM FARMACOGENÔMICA: não é substrato de CYP2D6 — concentração mais previsível vs venlafaxina',
      'HAS: monitorar PA — efeito noradrenérgico dose-dependente',
      'DESMAME: reduzir gradualmente — síndrome de descontinuação',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['SLC6A4 (resposta clínica)', 'BDNF Val66Met (resposta)'],
    marcas: [
      { nome: 'Pristiq®', laboratorio: 'Pfizer', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido LP'], lab_id: 'pfizer' },
      { nome: 'Desve®', laboratorio: 'Eurofarma', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido LP'], lab_id: 'eurofarma' },
      { nome: 'Desvenlafaxina EMS', laboratorio: 'EMS', concentracoes: ['50 mg'], formas: ['Comprimido LP'] },
    ],
  },

  {
    id: 'levomilnaciprano',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Levomilnaciprano',
    nome_generico: 'Cloridrato de Levomilnaciprano',
    sinonimos: ['fetzima', 'levomilnacipran', 'levomilnaciprano', 'irsn noradrenergico'],
    categoria: 'psiquiatria',
    classe: 'IRSN',
    subclasse: 'Enantiômero ativo do milnaciprano — maior seletividade noradrenérgica que outros IRSNs',
    indicacoes_principais: ['Depressão maior (aprovado FDA 2013 — disponibilidade limitada Brasil)'],
    dose_adulto: {
      habitual: '40–80 mg 1×/dia (LP)',
      min: '20 mg/dia',
      max: '120 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (manhã, com alimento)'],
      instrucoes: 'Iniciar 20 mg/dia × 2 dias → 40 mg/dia. Titular a cada 2 semanas.',
    },
    ajuste_renal: { normal: '40–120 mg/dia', tfg_60_30: 'Máximo 80 mg/dia', tfg_30_15: 'Máximo 40 mg/dia', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: ['IMAO', 'TFG < 15 mL/min'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica' },
    ],
    alertas_especiais: ['Maior componente noradrenérgico — útil em fadiga, dificuldade de concentração', 'Monitorar PA e FC'],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Fetzima®', laboratorio: 'Allergan', concentracoes: ['20 mg', '40 mg', '80 mg', '120 mg'], formas: ['Cápsula LP'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // OUTROS ANTIDEPRESSIVOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'mirtazapina',
    molecula: 'Mirtazapina',
    nome_generico: 'Mirtazapina',
    sinonimos: ['remeron', 'mirtazapine', 'mirtazapina', 'noradrenergico serotoninergico', 'nassa antidepressivo', 'antidepressivo sono'],
    categoria: 'psiquiatria',
    classe: 'NaSSA',
    subclasse: 'Antidepressivo noradrenérgico e serotoninérgico específico (NaSSA) — antagonista α2 + antagonista 5-HT2/3/H1',
    indicacoes_principais: [
      'Depressão maior — especialmente com insônia, ansiedade, anorexia associadas',
      'Depressão com sintomas vegetativos (perda de peso, insônia)',
      'Prevenção de náuseas pós-quimioterapia (off-label — antagonista 5-HT3)',
    ],
    dose_adulto: {
      habitual: '15–30 mg VO à noite',
      min: '7,5 mg/dia',
      max: '45 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (noite — sedação intensa)'],
      instrucoes: 'Sedação PARADOXAL: 7,5–15 mg → mais sedativo que 30–45 mg (bloqueio H1 proporcionalmente maior em doses baixas). Para insônia severa: manter 15 mg. Ganho de peso: frequente (estimulo apetite via H1 e 5-HT2C).',
    },
    ajuste_renal: { normal: '15–45 mg/dia', tfg_60_30: 'Sem ajuste formal — cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica' },
      { com: 'Álcool / benzodiazepínicos', severidade: 'moderada', descricao: 'SNC depressão aditiva' },
      { com: 'Clonidina', severidade: 'moderada', descricao: 'Antagoniza efeito anti-hipertensivo da clonidina (bloqueio α2)' },
    ],
    alertas_especiais: [
      'EFEITO PARADOXAL DA DOSE: doses baixas (7,5 mg) mais sedativas que doses altas (30–45 mg) — não aumentar dose para melhorar sono',
      'GANHO DE PESO: estimula apetite e carboidratos — problema em obesos e diabéticos',
      'AGRANULOCITOSE: rara (1:1000) — monitorar hemograma se febre/infecção de repetição',
      'Sem atividade sexual adversa (diferente de ISRS) — útil em disfunção sexual por ISRS',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: cautela em idosos — sedação, hipotensão ortostática, ganho de peso',
    stopp: 'STOPP D3: mirtazapina em idoso com obesidade ou DM2 (ganho de peso)',
    pgx_genes: ['CYP2D6 (metabolismo)', 'CYP3A4 (metabolismo)', 'CYP1A2 (metabolismo)'],
    marcas: [
      { nome: 'Remeron®', laboratorio: 'MSD', concentracoes: ['15 mg', '30 mg', '45 mg'], formas: ['Comprimido', 'Comprimido bucodispersível'], lab_id: 'msd' },
      { nome: 'Mirtazapina EMS', laboratorio: 'EMS', concentracoes: ['15 mg', '30 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'agomelatina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Agomelatina',
    nome_generico: 'Agomelatina',
    sinonimos: ['valdoxan', 'agomelatine', 'agomelatina', 'melatonina antidepressivo', 'mt1 mt2'],
    categoria: 'psiquiatria',
    classe: 'Antidepressivo',
    subclasse: 'Agonista melatoninérgico (MT1/MT2) + antagonista 5-HT2C — sem ação em receptores monoaminérgicos clássicos',
    indicacoes_principais: ['Depressão maior — especialmente com distúrbio do sono e ritmo circadiano alterado'],
    dose_adulto: {
      habitual: '25 mg VO à noite',
      min: '25 mg/dia',
      max: '50 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (noite — antes de dormir)'],
      instrucoes: 'Tomar na hora do sono. Monitorar ALT/TGP: antes, semanas 3, 6, 12, 24 e depois anualmente. Não associar a fluvoxamina (inibe CYP1A2 → agomelatina ×60).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Não recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Contraindicado', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Hepatopatia (qualquer grau)', 'Fluvoxamina (inibidor CYP1A2 potente)', 'ALT > 3× LSN', 'IMAO'],
    interacoes_importantes: [
      { com: 'Fluvoxamina', severidade: 'contraindicado', descricao: 'Inibição CYP1A2 → aumenta agomelatina 60× — hepatotoxicidade' },
      { com: 'Ciprofloxacino', severidade: 'grave', descricao: 'Inibe CYP1A2 — aumenta agomelatina significativamente' },
      { com: 'Rifampicina', severidade: 'moderada', descricao: 'Induz CYP1A2 — reduz agomelatina — perda de efeito' },
    ],
    alertas_especiais: [
      'HEPATOTOXICIDADE: monitoramento ALT/TGP obrigatório — suspender se > 3× LSN',
      'ÚNICO antidepressivo sem disfunção sexual, sem ganho de peso e sem síndrome de descontinuação',
      'SEM síndrome serotoninérgica (sem ação serotoninérgica direta)',
      'Meia-vida curta (1–2h) — necessita tomar na hora certa (ritmo circadiano)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP1A2 (metabolismo — fumantes têm metabolismo acelerado)', 'CYP2C9 (metabolismo secundário)'],
    marcas: [
      { nome: 'Valdoxan®', laboratorio: 'Servier', concentracoes: ['25 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // TCA — Antidepressivos Tricíclicos
  // (nortriptilina já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'amitriptilina',
    indicacao_contexto: 'Depressão / dor neuropática (psiquiatria)',
    molecula: 'Amitriptilina',
    nome_generico: 'Cloridrato de Amitriptilina',
    sinonimos: ['tryptanol', 'amitriptyline', 'amitriptilina', 'tca', 'antidepressivo triclico', 'neuropatia dor'],
    categoria: 'psiquiatria',
    classe: 'TCA',
    subclasse: 'Antidepressivo tricíclico terciário — maior ação anticolinérgica que nortriptilina',
    indicacoes_principais: [
      'Depressão maior (eficaz mas 2ª linha por perfil adverso)',
      'Dor neuropática crônica (neuralgia, fibromialgia, neuropatia diabética) — doses baixas (10–25 mg)',
      'Cefaleia tensional / enxaqueca (profilaxia)',
      'Enurese noturna (crianças > 6 anos)',
      'Síndrome do intestino irritável (off-label)',
    ],
    dose_adulto: {
      habitual: '25–75 mg VO à noite (depressão) | 10–25 mg/dia (dor/profilaxia cefaleia)',
      min: '10 mg/dia (dor neuropática)',
      max: '150 mg/dia (depressão) | 75 mg/dia (idosos)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia à noite (depressão) | Pode ser 2–3×/dia em doses altas'],
      instrucoes: 'Dor neuropática/cefaleia: iniciar 10 mg à noite, aumentar 10–25 mg a cada 2 semanas. Níveis séricos guiam depressão (100–250 ng/mL). Evitar overdose (janela terapêutica estreita — cardiotóxico).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO (últimas 2 semanas)', 'IAM recente', 'Glaucoma de ângulo fechado', 'Retenção urinária', 'Bloqueio AV'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica fatal' },
      { com: 'Antiarrítmicos classe Ia (quinidina, procainamida)', severidade: 'grave', descricao: 'QT prolongado aditivo — arritmia ventricular' },
      { com: 'Anticolinérgicos (biperideno, oxibutinina, atropina)', severidade: 'moderada', descricao: 'Efeitos anticolinérgicos aditivos — retenção urinária, íleo, confusão' },
      { com: 'Fluoxetina / paroxetina', severidade: 'moderada', descricao: 'Inibição CYP2D6 — aumenta amitriptilina 2–4× — toxicidade' },
      { com: 'Álcool', severidade: 'moderada', descricao: 'Depressão SNC aditiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — alta carga anticolinérgica → confusão, retenção urinária, quedas, constipação',
      'OVERDOSE: arritmias ventriculares e convulsões — janela terapêutica estreita. Antídoto: bicarbonato IV (alcalinização)',
      'QT PROLONGADO: monitorar ECG em doses > 75 mg/dia',
      'NORTRIPTILINA: metabólito ativo — preferível em idosos (menos anticolinérgico)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — antidepressivo mais anticolinérgico. Alta evidência, recomendação forte',
    stopp: 'STOPP D1: TCA em idoso — anticolinérgico, risco de hipotensão ortostática, quedas, confusão',
    pgx_genes: ['CYP2D6 (PM: concentração 4–5× maior — reduzir dose)', 'CYP2C19 (metabolismo)', 'HLA-A*31:01 (reação cutânea — carbamazepina cross)'],
    marcas: [
      { nome: 'Tryptanol®', laboratorio: 'Aspen', concentracoes: ['10 mg', '25 mg', '75 mg'], formas: ['Comprimido'] },
      { nome: 'Amitriptilina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '75 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'imipramina',
    molecula: 'Imipramina',
    nome_generico: 'Cloridrato de Imipramina',
    sinonimos: ['tofranil', 'imipramine', 'imipramina', 'tca enurese', 'antidepressivo triclico imipramina'],
    categoria: 'psiquiatria',
    classe: 'TCA',
    subclasse: 'Primeiro TCA desenvolvido (1957) — amina terciária, alta anticolin + simpatomimético',
    indicacoes_principais: [
      'Depressão maior (2ª linha)',
      'Enurese noturna em crianças > 6 anos',
      'Transtorno de pânico',
      'Dor neuropática crônica (off-label)',
    ],
    dose_adulto: {
      habitual: '75–150 mg/dia VO (depressão)',
      min: '25 mg/dia',
      max: '300 mg/dia (hospitalar, monitorado)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–3×/dia'],
      instrucoes: 'Enurese: 25–50 mg 1h antes de dormir (crianças > 6 anos). Depressão: iniciar 25 mg/dia, aumentar gradualmente. Monitorar ECG em doses altas.',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO', 'IAM recente', 'Glaucoma de ângulo fechado', 'Bloqueio AV'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica' },
      { com: 'QT-prolongadores', severidade: 'grave', descricao: 'QT aditivo' },
    ],
    alertas_especiais: [
      'Beers 2023: EVITAR em idosos — mesmo perfil que amitriptilina',
      'MORTE SÚBITA PEDIÁTRICA: relatos com TCAs em crianças — monitorar ECG antes e durante enurese',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — alta carga anticolinérgica',
    stopp: 'STOPP D1: TCA em idoso',
    pgx_genes: ['CYP2D6 (PM: toxicidade — reduzir 50%)', 'CYP2C19'],
    marcas: [
      { nome: 'Tofranil®', laboratorio: 'Novartis', concentracoes: ['10 mg', '25 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'clomipramina',
    molecula: 'Clomipramina',
    nome_generico: 'Cloridrato de Clomipramina',
    sinonimos: ['anafranil', 'clomipramine', 'clomipramina', 'tca toc', 'anafranil toc'],
    categoria: 'psiquiatria',
    classe: 'TCA',
    subclasse: 'TCA com maior ação serotoninérgica — padrão-ouro para TOC (1ª escolha farmacológica histórica)',
    indicacoes_principais: [
      'TOC — padrão-ouro para casos graves ou refratários a ISRS',
      'Depressão maior',
      'Síndrome do pânico com ou sem agorafobia',
      'Cataplexia/narcolepsia (off-label)',
    ],
    dose_adulto: {
      habitual: '75–150 mg/dia VO',
      min: '25 mg/dia',
      max: '250 mg/dia (300 mg em TOC grave hospitalar)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia ou 1×/dia (noite)'],
      instrucoes: 'TOC: titular até 150–250 mg. Latência de resposta 8–12 semanas. Monitorar ECG (QT). Nível sérico alvo: 150–450 ng/mL (clomipramina + desmetilclomipramina).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO', 'IAM recente', 'QTc prolongado', 'Glaucoma de ângulo fechado'],
    interacoes_importantes: [
      { com: 'ISRS (fluoxetina, paroxetina)', severidade: 'grave', descricao: 'Inibição CYP2D6 → clomipramina aumenta → QT e síndrome serotoninérgica' },
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica fatal' },
    ],
    alertas_especiais: [
      'MELHOR EVIDÊNCIA em TOC: resposta superior a ISRS em metanálises — mas perfil adverso pior',
      'QT: monitorar ECG especialmente em combinação com ISRS',
      'Beers: evitar em idosos',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos',
    stopp: 'STOPP D1: TCA em idoso',
    pgx_genes: ['CYP2D6 (metabolismo — PM: risco de toxicidade)'],
    marcas: [
      { nome: 'Anafranil®', laboratorio: 'Novartis', concentracoes: ['25 mg', '75 mg'], formas: ['Comprimido', 'Cápsula'] },
      { nome: 'Clomipramina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '75 mg'], formas: ['Cápsula'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // IMAO — Inibidores da Monoaminoxidase
  // ══════════════════════════════════════════════════════════════

  {
    id: 'tranilcipromina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Tranilcipromina',
    nome_generico: 'Sulfato de Tranilcipromina',
    sinonimos: ['parnate', 'tranylcypromine', 'tranilcipromina', 'imao nao seletivo', 'imao irreversivel'],
    categoria: 'psiquiatria',
    classe: 'IMAO',
    subclasse: 'IMAO não seletivo irreversível — inibe MAO-A e MAO-B',
    indicacoes_principais: [
      'Depressão atípica refratária (especialmente hipersonia, reatividade de humor, fobia social)',
      'Depressão resistente a múltiplos antidepressivos (uso especializado)',
      'Fobia social grave refratária',
    ],
    dose_adulto: {
      habitual: '10 mg VO 2×/dia (manhã e tarde)',
      min: '10 mg/dia',
      max: '60 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (NÃO à noite — insônia intensa)'],
      instrucoes: 'Iniciar 10 mg 2×/dia. Aumentar 10 mg a cada 1–3 semanas. DIETA TIRAMÍNICA obrigatória: evitar queijos curados, embutidos, vinho tinto, fígado, extrato de levedura.',
    },
    ajuste_renal: { normal: 'Cautela', tfg_60_30: 'Reduzir dose', tfg_30_15: 'Não recomendado', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Contraindicado', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Associação com QUALQUER antidepressivo serotoninérgico',
      'Simpaticomiméticos (pseudoefedrina, anfetaminas)',
      'Meperidina/petidina (ópio — morte súbita)',
      'Alimentos com tiramina elevada (crise hipertensiva)',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'ISRS/IRSN/TCA/outros antidepressivos', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica potencialmente fatal. Washout de 14 dias (fluoxetina: 5 semanas)' },
      { com: 'Tiramina dietética (queijo curado, vinho tinto, embutidos)', severidade: 'contraindicado', descricao: 'Crise hipertensiva hipertensiva emergência — cefaleia, sudorese, rigidez de nuca, AVC' },
      { com: 'Meperidina / tramadol / dextromefetamina', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica ou hipertensiva — relatos de morte' },
      { com: 'Simpaticomiméticos (pseudoefedrina, fenilefrina, dopamina)', severidade: 'contraindicado', descricao: 'Crise hipertensiva grave' },
      { com: 'Insulina / hipoglicemiantes', severidade: 'moderada', descricao: 'IMAO potencializa hipoglicemia' },
    ],
    alertas_especiais: [
      'CRISE HIPERTENSIVA POR TIRAMINA: MAO intestinal e hepática inibida → tiramina dietética entra na corrente sanguínea → liberação de catecolaminas → PA > 200/130 mmHg → AVC, IAM',
      'WASHOUT OBRIGATÓRIO: 14 dias após IMAO antes de iniciar QUALQUER outro antidepressivo',
      'USO ESPECIALIZADO: prescrever somente com conhecimento detalhado de interações. Educação rigorosa do paciente sobre dieta',
      'Disponibilidade limitada no Brasil (uso em psiquiatria de referência)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: EVITAR em idosos',
    pgx_genes: ['MAO-A (polimorfismos — resposta clínica variável)'],
    marcas: [
      { nome: 'Parnate®', laboratorio: 'GSK', concentracoes: ['10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'moclobemida',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Moclobemida',
    nome_generico: 'Moclobemida',
    sinonimos: ['aurorix', 'moclobemide', 'moclobemida', 'imao reversivel', 'rima'],
    categoria: 'psiquiatria',
    classe: 'IMAO',
    subclasse: 'RIMA — Inibidor Reversível da MAO-A (menor risco de crise hipertensiva e interações)',
    indicacoes_principais: [
      'Depressão maior (especialmente com sintomas atípicos)',
      'Fobia social',
      'Depressão resistente (alternativa mais segura que IMAOs irreversíveis)',
    ],
    dose_adulto: {
      habitual: '300–600 mg/dia VO em 2 tomadas',
      min: '150 mg/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia (após refeições)'],
      instrucoes: 'Iniciar 150 mg 2×/dia. Tomar APÓS refeições (tiramina dietética deslocada do receptor). RIMA: inibição reversível — tiramina pode deslocar moclobemida. Menos restrição dietética que IMAO irreversível, mas manter cautela.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir 50%', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Estado confusional agudo', 'Feocromocitoma', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'ISRS / outros serotoninérgicos', severidade: 'grave', descricao: 'Síndrome serotoninérgica — washout 2 dias (vs 14 dias de IMAOs irreversíveis)' },
      { com: 'Cimetidina', severidade: 'moderada', descricao: 'Aumenta moclobemida — reduzir dose à metade' },
      { com: 'Opioídes (tramadol, petidina)', severidade: 'grave', descricao: 'Síndrome serotoninérgica' },
    ],
    alertas_especiais: [
      'VANTAGEM vs IMAOs clássicos: reversível → tiramina dietética desloca moclobemida → crise hipertensiva muito menos frequente',
      'Washout: apenas 2 dias (vs 14 dias para tranilcipromina)',
      'Menos interações: mas ainda requer cautela com serotoninérgicos',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP2C19 (PM: aumenta moclobemida — reduzir dose)'],
    marcas: [
      { nome: 'Aurorix®', laboratorio: 'Roche', concentracoes: ['150 mg', '300 mg'], formas: ['Comprimido'], lab_id: 'roche' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIPSICÓTICOS TÍPICOS (1ª Geração)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'haloperidol',
    indicacao_contexto: 'Psicose / agitação (psiquiatria)',
    molecula: 'Haloperidol',
    nome_generico: 'Haloperidol',
    sinonimos: ['haldol', 'haloperidol', 'antipsicótico tipico', 'dopaminergico d2', 'butirofenona'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Típico',
    subclasse: 'Butirofenona — antagonista D2 potente e seletivo',
    indicacoes_principais: [
      'Esquizofrenia — episódio agudo e manutenção (especialmente formas paranoides)',
      'Agitação psicomotora aguda (IM)',
      'Delirium (especialmente pós-operatório e em UTI)',
      'Síndrome de Tourette (tiques)',
      'Náuseas e vômitos refratários (off-label)',
      'Haloperidol decanoato: esquizofrenia — formulação de depósito mensal',
    ],
    dose_adulto: {
      habitual: '2–5 mg VO 2–3×/dia | 5–10 mg IM (agitação aguda)',
      min: '0,5–1 mg/dia (idoso/delirium)',
      max: '20 mg/dia (VO) | 20 mg (IM agudamente)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (VO)', 'Dose única IM (agitação)', 'Decanoato: 1×/mês IM'],
      instrucoes: 'Agitação IM: 5 mg IM + lorazepam 2 mg IM (protocolo padrão). Delirium: 0,5–1 mg q4–6h VO. Decanoato: 10–15× dose oral diária IM a cada 4 semanas.',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['QTc > 500 ms', 'Doença de Parkinson (piora drasticamente)', 'Corpos de Lewy (risco de síndrome neuroléptica maligna)', 'Estado comatoso', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'QT-prolongadores', severidade: 'grave', descricao: 'Torsades de pointes — monitorar ECG' },
      { com: 'Lítio (altas doses)', severidade: 'grave', descricao: 'Neurotoxicidade — confusão, tremor, febre' },
      { com: 'Fluoxetina / paroxetina', severidade: 'moderada', descricao: 'Inibição CYP2D6 → haloperidol aumenta → DEP e QT' },
      { com: 'Carbamazepina / rifampicina', severidade: 'moderada', descricao: 'Indução CYP3A4 → haloperidol cai → perda de eficácia' },
    ],
    alertas_especiais: [
      'DISCINESIA TARDIA: risco cumulativo 20–30% com uso prolongado — revisar necessidade anualmente',
      'SÍNDROME NEUROLÉPTICA MALIGNA (SNM): febre, rigidez muscular, instabilidade autonômica, CPK elevada — EMERGÊNCIA. Suspender, dantrolene, bromocriptina',
      'PARKISONISMO: efeito adverso frequente — tratar com biperideno (cautela em idosos)',
      'BEERS: evitar em delirium (agrava), mas pode ser usado em dose baixa se agitação grave',
      'ECG antes de iniciar em cardiopatas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — EVITAR em delirium exceto agitação perigosa; risco de DEP e SNM',
    stopp: 'STOPP C1: antipsicótico em idoso com queda recente — aumenta risco',
    pgx_genes: ['CYP2D6 (PM: concentração duplica — reduzir dose)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Haldol®', laboratorio: 'Janssen', concentracoes: ['1 mg', '5 mg', '2 mg/mL solução', '5 mg/mL IM'], formas: ['Comprimido', 'Solução oral', 'Injetável'] },
      { nome: 'Haloperidol Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['1 mg', '5 mg'], formas: ['Comprimido', 'Solução oral'], lab_id: 'eurofarma' },
      { nome: 'Haldol® Decanoato', laboratorio: 'Janssen', concentracoes: ['50 mg/mL', '100 mg/mL'], formas: ['Injetável depósito (mensal)'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIPSICÓTICOS ATÍPICOS (2ª Geração)
  // (risperidona já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'olanzapina',
    molecula: 'Olanzapina',
    nome_generico: 'Olanzapina',
    sinonimos: ['zyprexa', 'olanzapine', 'olanzapina', 'antipsicótico atipico', 'zyprexa metabolico'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Tienobenzodiazepina — antagonismo D2, 5-HT2A, H1, M1, α1 — alta incidência de síndrome metabólica',
    indicacoes_principais: [
      'Esquizofrenia (manutenção — eficácia robusta)',
      'Transtorno bipolar — fase maníaca aguda (1ª linha)',
      'Depressão bipolar (combinada com fluoxetina — Symbyax)',
      'Agitação aguda (IM de ação rápida)',
      'Antieméticos em quimioterapia (off-label)',
    ],
    dose_adulto: {
      habitual: '10–15 mg/dia VO',
      min: '5 mg/dia',
      max: '20 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (noite)'],
      instrucoes: 'Iniciar 5–10 mg/dia. Titular em 5 mg a cada 1 semana. IM de ação rápida (ZYDIS): 10 mg IM — NÃO coadministrar com benzodiazepínico IV (colapso cardiorrespiratório). Comprimidos bucodispersíveis (Zyprexa Zydis).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Cautela', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Glaucoma de ângulo fechado', 'IM + BZD IV (colapso)'],
    interacoes_importantes: [
      { com: 'Benzodiazepínicos IV (diazepam IV) + olanzapina IM', severidade: 'contraindicado', descricao: 'Depressão respiratória grave — colapso cardiovascular' },
      { com: 'Fluvoxamina', severidade: 'grave', descricao: 'Inibição CYP1A2 → olanzapina aumenta 2–3× → toxicidade' },
      { com: 'Tabagismo / carbamazepina', severidade: 'moderada', descricao: 'Indução CYP1A2 → olanzapina cai → perda de eficácia. Fumantes precisam de 30% mais dose' },
    ],
    alertas_especiais: [
      'SÍNDROME METABÓLICA: maior risco de todos os antipsicóticos — ganho de peso médio 4–6 kg/ano, DM2, dislipidemia. Monitorar glicemia, lipídeos, peso mensalmente',
      'TABAGISMO: fumantes precisam ~30% mais dose (CYP1A2 indução) — ao parar de fumar, reduzir dose ou haverá toxicidade',
      'IM + BZD IV: contraindicação absoluta pela depressão respiratória',
      'Beers: cautela em idosos — sedação, hipotensão, síndrome metabólica',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — sedação, hipotensão ortostática, síndrome metabólica, DM2',
    stopp: 'STOPP C2: antipsicótico atípico em idoso com DM2 (piora controle glicêmico)',
    pgx_genes: ['CYP1A2 (principal — fumantes: indução; fluvoxamina: inibição)', 'CYP2D6 (metabolismo secundário)', 'ABCB1 (transporte)'],
    marcas: [
      { nome: 'Zyprexa®', laboratorio: 'Lilly', concentracoes: ['2,5 mg', '5 mg', '7,5 mg', '10 mg', '15 mg', '20 mg'], formas: ['Comprimido', 'Bucodispersível Zydis', 'Injetável IM'], lab_id: 'lilly' },
      { nome: 'Olanzapina EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'quetiapina',
    molecula: 'Quetiapina',
    nome_generico: 'Fumarato de Quetiapina',
    sinonimos: ['seroquel', 'quetiapine', 'quetiapina', 'seroquel bipolar', 'antipsicótico sono'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Dibenzotiazepina — antagonismo D2, 5-HT2A, H1 (sedação), M1 — amplo espectro de indicações',
    indicacoes_principais: [
      'Esquizofrenia',
      'Transtorno bipolar — mania aguda e depressão bipolar (doses > 300 mg)',
      'Depressão maior resistente (adjuvante baixa dose 50–150 mg)',
      'Insônia (off-label — uso muito frequente, doses 25–100 mg)',
      'Ansiedade generalizada (off-label)',
    ],
    dose_adulto: {
      habitual: '300–600 mg/dia (esquizofrenia/mania) | 150–300 mg/dia (depressão bipolar) | 25–100 mg/dia (sono/adjuvante)',
      min: '25 mg/dia',
      max: '800 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia (IR) | 1×/dia à noite (LP/Seroquel XR)'],
      instrucoes: 'Esquizofrenia: 150 mg D1 → 300 mg D2 → 400–800 mg/dia. Depressão bipolar: 300 mg/dia (BOLDER I/II). LP: 1×/dia à noite.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Cautela', dialisavel: false },
    ajuste_hepatico: { child_a: 'Iniciar 25 mg, titular devagar', child_b: 'Reduzir dose', child_c: 'Reduzir dose' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'QTc prolongado significativo'],
    interacoes_importantes: [
      { com: 'Cetoconazol / eritromicina / outros inibidores CYP3A4', severidade: 'moderada', descricao: 'Aumentam quetiapina — reduzir dose para 1/6' },
      { com: 'Rifampicina / carbamazepina / fenitoína', severidade: 'moderada', descricao: 'Indução CYP3A4 → quetiapina cai 5× — aumentar dose' },
      { com: 'Lítio', severidade: 'leve', descricao: 'Monitorar sinais de toxicidade — sinergia terapêutica na mania' },
    ],
    alertas_especiais: [
      'USO OFF-LABEL PARA SONO: FDA não aprovou para insônia — mas é uma das prescrições mais comuns. Risco de síndrome metabólica mesmo em baixas doses com uso crônico',
      'SEDAÇÃO: H1 forte — mais sedativo que olanzapina. Motoristas: contraindicado',
      'SÍNDROME METABÓLICA: menor que olanzapina mas significativa. Monitorar peso/glicemia',
      'Cataratas: exame oftalmológico semestral recomendado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — sedação, hipotensão ortostática, DM, quedas',
    stopp: 'STOPP C1: antipsicótico em idoso com queda ou hipotensão ortostática',
    pgx_genes: ['CYP3A4 (principal — grande variabilidade por indutores/inibidores)', 'CYP2D6 (metabolismo secundário)'],
    marcas: [
      { nome: 'Seroquel®', laboratorio: 'AstraZeneca', concentracoes: ['25 mg', '100 mg', '200 mg', '300 mg'], formas: ['Comprimido IR'], lab_id: 'astrazeneca' },
      { nome: 'Seroquel® XR', laboratorio: 'AstraZeneca', concentracoes: ['50 mg', '200 mg', '300 mg', '400 mg'], formas: ['Comprimido LP'], lab_id: 'astrazeneca' },
      { nome: 'Quetiapina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '100 mg', '200 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'aripiprazol',
    molecula: 'Aripiprazol',
    nome_generico: 'Aripiprazol',
    sinonimos: ['abilify', 'aripiprazole', 'aripiprazol', 'agonista parcial d2', 'antipsicótico atipico metabolico'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Agonista parcial D2/D3 e 5-HT1A + antagonista 5-HT2A — menor efeito metabólico',
    indicacoes_principais: [
      'Esquizofrenia',
      'Transtorno bipolar — fase maníaca',
      'Depressão maior como adjuvante (2ª linha)',
      'Irritabilidade em autismo (> 6 anos)',
      'Síndrome de Tourette',
    ],
    dose_adulto: {
      habitual: '10–15 mg/dia VO',
      min: '2 mg/dia (adjuvante depressão)',
      max: '30 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (manhã ou noite)'],
      instrucoes: 'Vantagem: menor ganho de peso e síndrome metabólica. Agonismo parcial D2: pode causar ativação (insônia, agitação) em início — tomar de manhã. Disponível IM de longa ação (Abilify Maintena — mensal).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Fluoxetina / paroxetina (CYP2D6)', severidade: 'moderada', descricao: 'Inibição CYP2D6 → aripiprazol aumenta → reduzir dose para metade' },
      { com: 'Carbamazepina / rifampicina (CYP3A4)', severidade: 'moderada', descricao: 'Indução → aripiprazol cai → dobrar dose' },
      { com: 'Cetoconazol / itraconazol (CYP3A4)', severidade: 'moderada', descricao: 'Aumenta aripiprazol → reduzir dose para metade' },
    ],
    alertas_especiais: [
      'MENOR SÍNDROME METABÓLICA: preferível em pacientes com DM2, obesidade ou dislipidemia',
      'ATIVAÇÃO/ACATISIA: agonismo parcial pode causar inquietação motora (acatisia) — dose baixa ou mudar horário para manhã',
      'LONGA AÇÃO: Abilify Maintena (mensal) ou Aristada (mensal/bimensal) — melhora adesão na esquizofrenia',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — queda, AVC. Melhor perfil metabólico que olanzapina/quetiapina',
    pgx_genes: ['CYP2D6 (principal — PM: reduzir dose 50%)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Abilify®', laboratorio: 'Otsuka/Lundbeck', concentracoes: ['5 mg', '10 mg', '15 mg', '20 mg', '30 mg'], formas: ['Comprimido', 'Solução oral', 'Bucodispersível'] },
      { nome: 'Aripiprazol EMS', laboratorio: 'EMS', concentracoes: ['10 mg', '15 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'clozapina',
    molecula: 'Clozapina',
    nome_generico: 'Clozapina',
    sinonimos: ['leponex', 'clozaril', 'clozapine', 'clozapina', 'antipsicótico esquizofrenia resistente', 'esquizofrenia refratária'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Dibenzodiazepina — único antipsicótico com eficácia comprovada em esquizofrenia resistente',
    indicacoes_principais: [
      'Esquizofrenia resistente (sem resposta a ≥ 2 antipsicóticos adequados) — ÚNICA indicação primária',
      'Risco suicida persistente em esquizofrenia/schizoaffective disorder',
      'Discinesia tardia grave refratária',
      'Psicose em doença de Parkinson (baixas doses — melhor tolerância dopaminérgica)',
    ],
    dose_adulto: {
      habitual: '200–450 mg/dia VO (esquizofrenia resistente)',
      min: '12,5 mg/dia (titulação D1)',
      max: '900 mg/dia (casos excepcionais)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (2/3 à noite pela sedação)'],
      instrucoes: 'TITULAÇÃO OBRIGATÓRIA: D1: 12,5 mg → D2: 25 mg → D7: 50 mg → aumentar 25–50 mg a cada 3–7 dias. Nível sérico alvo: 350–600 ng/mL. MONITORAR HEMOGRAMA: semanal × 18 semanas → quinzenal × 1 ano → mensal (indefinidamente).',
    },
    ajuste_renal: { normal: 'Sem ajuste (excreção hepática)', tfg_60_30: 'Cautela', tfg_30_15: 'Cautela', tfg_lt_15: 'Não recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Cautela extrema', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Neutrófilos < 1500/mm³ (ou < 1000 em pacientes com etnia sub-saariana — neutropenia benigna)',
      'Histórico de agranulocitose por clozapina',
      'Epilepsia não controlada',
      'Mielossupressão ativa',
      'Uso concomitante com outros mielossupressores',
    ],
    interacoes_importantes: [
      { com: 'Fluvoxamina', severidade: 'grave', descricao: 'Inibe CYP1A2 → clozapina aumenta 5–10× — toxicidade grave (convulsões, sedação extrema)' },
      { com: 'Tabagismo (cessação)', severidade: 'grave', descricao: 'Parar de fumar induz CYP1A2 redução → clozapina aumenta 50% → toxicidade' },
      { com: 'Carbamazepina', severidade: 'contraindicado', descricao: 'Mielossupressão aditiva (agranulocitose)' },
      { com: 'Benzodiazepínicos', severidade: 'moderada', descricao: 'Colapso cardiorrespiratório (especialmente IM BZD) — não usar IM junto' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Neurotoxicidade aditiva — monitorar nível de lítio' },
    ],
    alertas_especiais: [
      'AGRANULOCITOSE: 0,5–1,5% — potencialmente fatal. HEMOGRAMA OBRIGATÓRIO: semanal por 18 semanas, depois quinzenal. Suspender se neutrófilos < 1000',
      'CONVULSÕES: dose-dependente (> 450 mg/dia — risco 5%). Profilaxia com ácido valproico se dose alta',
      'MIOCARDITE/CARDIOMIOPATIA: nas primeiras 4–8 semanas — troponina, ECG semanal no início',
      'TABAGISMO: fumante precisa de dose maior. Ao parar de fumar: reduzir dose imediatamente (50%)',
      'CADASTRO OBRIGATÓRIO: sistema de monitoramento (REMS no EUA; similar na ANVISA)',
      'CONSTIPAÇÃO GRAVE: pode evoluir para íleo/obstrução — monitorar e tratar proativamente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: uso apenas quando essencial — risco de agranulocitose, sedação, hipotensão',
    pgx_genes: ['CYP1A2 (principal — fumantes: indução; fluvoxamina: inibição intensa)', 'CYP2D6', 'CYP3A4', 'HLA-DQB1 (agranulocitose)'],
    marcas: [
      { nome: 'Leponex®', laboratorio: 'Novartis', concentracoes: ['25 mg', '100 mg'], formas: ['Comprimido'], lab_id: 'novartis' },
      { nome: 'Clozapina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '100 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'ziprasidona',
    molecula: 'Ziprasidona',
    nome_generico: 'Cloridrato de Ziprasidona',
    sinonimos: ['geodon', 'ziprasidone', 'ziprasidona', 'antipsicótico qt', 'geodon qt'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Benzisoxazol — antagonismo D2, 5-HT2A + inibição recaptação 5-HT/NE + agonismo 5-HT1A',
    indicacoes_principais: [
      'Esquizofrenia',
      'Transtorno bipolar — mania aguda e manutenção',
    ],
    dose_adulto: {
      habitual: '40–80 mg VO 2×/dia com alimento',
      min: '20 mg 2×/dia',
      max: '160 mg/dia (80 mg 2×/dia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia — OBRIGATORIAMENTE com alimento (↑absorção 100%)'],
      instrucoes: 'TOMAR COM REFEIÇÃO (≥ 500 kcal): aumenta absorção 2× vs jejum — eficácia e segurança dependem disso. Menor ganho de peso e síndrome metabólica. Monitorar QTc — descontinuar se QTc > 500 ms.',
    },
    ajuste_renal: { normal: 'Sem ajuste (excreção fecal/hepática)', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Sem ajuste', tfg_lt_15: 'Sem ajuste (IM: não usar — excipiente ciclodextrina acumula)', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['QTc > 500 ms', 'IAM recente', 'Insuficiência cardíaca descompensada', 'Bradiarritmia', 'Uso com QT-prolongadores', 'Hipopotassemia/hipomagnesemia não corrigidas'],
    interacoes_importantes: [
      { com: 'QT-prolongadores (sotalol, amiodarona, eritromicina, fluorquinolonas)', severidade: 'contraindicado', descricao: 'QT aditivo — torsades de pointes' },
      { com: 'Cetoconazol', severidade: 'moderada', descricao: 'Aumenta ziprasidona — monitorar QT' },
    ],
    alertas_especiais: [
      'TOMAR COM ALIMENTO — sem alimento a absorção cai 50% e a eficácia é comprometida',
      'QT PROLONGADO: maior risco entre antipsicóticos atípicos. ECG obrigatório antes de iniciar e em cardiopatas',
      'MENOR EFEITO METABÓLICO: vantagem em obesos/DM2',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — QT prolongado',
    pgx_genes: ['CYP3A4 (metabolismo principal)', 'CYP1A2'],
    marcas: [
      { nome: 'Geodon®', laboratorio: 'Pfizer', concentracoes: ['20 mg', '40 mg', '60 mg', '80 mg'], formas: ['Cápsula', 'Pó injetável IM'], lab_id: 'pfizer' },
      { nome: 'Ziprasidona EMS', laboratorio: 'EMS', concentracoes: ['40 mg', '80 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'paliperidona',
    molecula: 'Paliperidona',
    nome_generico: 'Palmitato de Paliperidona',
    sinonimos: ['invega', 'xeplion', 'paliperidone', 'paliperidona', '9-oh-risperidona', 'depósito mensal antipsicótico'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Metabólito ativo da risperidona — formulação de liberação prolongada e depósito mensal/trimestral',
    indicacoes_principais: [
      'Esquizofrenia (oral LP ou depósito mensal/trimestral)',
      'Transtorno esquizoafetivo',
    ],
    dose_adulto: {
      habitual: '6 mg/dia VO LP | 150 mg IM D1, 100 mg IM D8 → 75 mg IM/mês (Xeplion)',
      min: '3 mg/dia (VO LP)',
      max: '12 mg/dia (VO LP)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (VO LP) | 1×/mês (IM depósito)'],
      instrucoes: 'VO LP: tomar com ou sem alimento, engolir inteiro. IM MENSAL (Xeplion): 1ª injeção deltoide (D1), 2ª deltóide (D8) → manutenção deltóide ou glúteo mensalmente. Não é necessário suplementar com oral na maioria.',
    },
    ajuste_renal: { normal: '6 mg/dia', tfg_60_30: '3 mg/dia', tfg_30_15: '1,5 mg/dia VO (sem depósito IM em DRC moderada)', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Dados limitados' },
    contraindicacoes_rapidas: ['Hipersensibilidade à paliperidona ou risperidona', 'TFG < 50 mL/min (depósito IM)'],
    interacoes_importantes: [
      { com: 'Carbamazepina', severidade: 'moderada', descricao: 'Indução CYP3A4 — reduz paliperidona em 37% — aumentar dose' },
    ],
    alertas_especiais: [
      'VANTAGEM POSOLÓGICA: formulação mensal (Xeplion) e trimestral (Trevicta) — melhora adesão na esquizofrenia',
      'Excreção RENAL: ajuste necessário em DRC (diferente da risperidona)',
      'Envelope da cápsula LP: pode aparecer nas fezes (shell inerte) — tranquilizar paciente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['P-gp ABCB1 (transporte — polimorfismos afetam concentração)'],
    marcas: [
      { nome: 'Invega®', laboratorio: 'Janssen', concentracoes: ['3 mg', '6 mg', '9 mg LP'], formas: ['Comprimido LP'] },
      { nome: 'Xeplion®', laboratorio: 'Janssen', concentracoes: ['25 mg', '50 mg', '75 mg', '100 mg', '150 mg'], formas: ['Injetável depósito mensal'] },
    ],
  },

];