// ============================================================
// PRESCREVE-AI — Extensão Farmacológica: CARDIOLOGIA (Phase 21.3)
// 24 moléculas: IECA · BRA · ARNI · BB · BCC · Diuréticos · ARM
//               Antiarrítmicos · Antianginosos · Anticoagulantes
//               Antiagregantes · Hipolipemiantes · iSGLT2-CV
// Integração automática: Dose Calculator · Risk Engine · Trust Score
//                        Explainable AI · Guidelines · Knowledge Graph
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_CARDIO: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════════
  // IECA — Inibidores da Enzima Conversora de Angiotensina
  // ══════════════════════════════════════════════════════════════

  {
    id: 'ramipril',
    molecula: 'Ramipril',
    nome_generico: 'Ramipril',
    sinonimos: ['altace', 'triatec', 'ramipril', 'ieca', 'ramipril ic', 'ramipril pos-iam'],
    categoria: 'antihipertensivo',
    classe: 'IECA',
    subclasse: 'Pró-droga (Ramiprilato ativo)',
    indicacoes_principais: ['HAS', 'IC-FEr pós-IAM', 'Redução de risco CV (DCV estabelecida — HOPE trial)', 'Nefropatia diabética', 'Microalbuminúria'],
    dose_adulto: {
      habitual: '5 mg 1x/dia',
      min: '1,25 mg 1x/dia',
      max: '10 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia', '2x/dia'],
      instrucoes: 'Iniciar 2,5 mg 1x/dia em IC pós-IAM. HAS: 5 mg → 10 mg 1x/dia. Titular conforme PA. Tomar com ou sem alimento.',
    },
    ajuste_renal: {
      normal: '5–10 mg 1x/dia',
      tfg_60_30: 'Iniciar 1,25 mg. Máximo 5 mg 1x/dia',
      tfg_30_15: '1,25 mg 1x/dia. Monitorar K+ e creatinina',
      tfg_lt_15: 'Contraindicado ou uso com extrema cautela. Consultar nefrologista.',
      dialisavel: true,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Iniciar com dose menor', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Histórico de angioedema por IECA',
      'Gravidez (2º e 3º trimestres — categoria D)',
      'Uso concomitante com Sacubitril/Valsartana (intervalo mínimo 36h)',
      'Hipercalemia grave (K+ > 5,5 mEq/L)',
      'Estenose bilateral de artérias renais',
    ],
    interacoes_importantes: [
      { com: 'Losartana/BRA', severidade: 'contraindicado', descricao: 'Duplo bloqueio SRAA — hipercalemia, IRA, hipotensão' },
      { com: 'Alisquireno', severidade: 'contraindicado', descricao: 'Duplo bloqueio SRAA em diabéticos' },
      { com: 'Sacubitril/Valsartana', severidade: 'contraindicado', descricao: 'Angioedema — intervalo mínimo 36h após IECA' },
      { com: 'Espironolactona', severidade: 'moderada', descricao: 'Hipercalemia — monitorar K+ e função renal' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Redução do efeito anti-hipertensivo e risco de IRA' },
      { com: 'Lítio', severidade: 'grave', descricao: 'IECA reduz excreção de lítio — toxicidade' },
      { com: 'Heparina', severidade: 'moderada', descricao: 'Risco aditivo de hipercalemia' },
    ],
    alertas_especiais: [
      'Tosse seca em ~10–20% — mecanismo: acúmulo de bradicinina. Substituir por BRA se intolerável.',
      'HOPE trial: redução de 22% em eventos CV maiores em pacientes de alto risco (sem IC)',
      'Angioedema: raro (0,1–0,3%), mais frequente em afro-descendentes — orientar paciente',
      'Monitorar: K+, creatinina e PA nas primeiras 2 semanas e após cada ajuste de dose',
      'Contraindicado em gravidez: substituir por metildopa ou nifedipino imediatamente',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Triatec®', laboratorio: 'Sanofi', concentracoes: ['2,5 mg', '5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Ramipril EMS', laboratorio: 'EMS', concentracoes: ['2,5 mg', '5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Ramipril Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['2,5 mg', '5 mg', '10 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'perindopril',
    molecula: 'Perindopril',
    nome_generico: 'Erbutamina de Perindopril',
    sinonimos: ['coversyl', 'perindopril', 'ieca', 'perindopril europa'],
    categoria: 'antihipertensivo',
    classe: 'IECA',
    subclasse: 'Pró-droga (Perindoprilato ativo) — alta lipossolubilidade',
    indicacoes_principais: ['HAS', 'DCV estabelecida (EUROPA trial)', 'IC-FEr', 'Prevenção de AVC recorrente (PROGRESS — + indapamida)'],
    dose_adulto: {
      habitual: '5 mg 1x/dia',
      min: '2,5 mg 1x/dia',
      max: '10 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'Tomar pela manhã, em jejum ou antes da refeição. HAS: iniciar 2,5–5 mg, titular para 10 mg.',
    },
    ajuste_renal: {
      normal: '5–10 mg 1x/dia',
      tfg_60_30: '2,5 mg 1x/dia',
      tfg_30_15: '2,5 mg em dias alternados',
      tfg_lt_15: 'Contraindicado',
      dialisavel: true,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Angioedema por IECA prévio',
      'Gravidez',
      'Associação com sacubitril/valsartana',
      'Hipercalemia > 5,5 mEq/L',
    ],
    interacoes_importantes: [
      { com: 'BRA/Alisquireno', severidade: 'contraindicado', descricao: 'Duplo SRAA' },
      { com: 'Sacubitril/Valsartana', severidade: 'contraindicado', descricao: 'Angioedema — aguardar 36h' },
      { com: 'Diuréticos poupadores de K+', severidade: 'moderada', descricao: 'Hipercalemia' },
      { com: 'Lítio', severidade: 'grave', descricao: 'Toxicidade por lítio' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Redução do efeito anti-hipertensivo' },
    ],
    alertas_especiais: [
      'EUROPA trial: redução de 20% em eventos CV maiores em doença coronariana estável',
      'PROGRESS: perindopril + indapamida reduz AVC recorrente em 43%',
      'Tosse seca: igual a outros IECAs — trocar por BRA se necessário',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Coversyl®', laboratorio: 'Servier', concentracoes: ['2,5 mg', '5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Perindopril EMS', laboratorio: 'EMS', concentracoes: ['4 mg', '8 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // BRA — Bloqueador do Receptor de Angiotensina II
  // ══════════════════════════════════════════════════════════════

  {
    id: 'telmisartana',
    molecula: 'Telmisartana',
    nome_generico: 'Telmisartana',
    sinonimos: ['micardis', 'telmisartana', 'bra', 'ara-ii'],
    categoria: 'antihipertensivo',
    classe: 'BRA',
    subclasse: 'Antagonista AT1 — meia-vida mais longa (24h), atividade PPARγ parcial',
    indicacoes_principais: ['HAS', 'Redução de risco CV (ONTARGET — não inferior a ramipril)', 'Nefropatia diabética', 'Prevenção CV em intolerantes a IECA'],
    dose_adulto: {
      habitual: '40 mg 1x/dia',
      min: '20 mg 1x/dia',
      max: '80 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'Dose única diária. Máxima duração de ação entre os BRAs (T½ ~24h). Independente de refeições.',
    },
    ajuste_renal: {
      normal: '40–80 mg 1x/dia',
      tfg_60_30: 'Sem ajuste (excreção biliar predominante)',
      tfg_30_15: 'Cautela — excreção biliar dominante',
      tfg_lt_15: 'Dados limitados — cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Máximo 40 mg/dia', child_b: 'Máximo 40 mg/dia — cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Gravidez (2º e 3º trimestres)',
      'Uso concomitante com IECA (duplo SRAA)',
      'Hipercalemia grave',
      'Colestase e obstrução biliar',
    ],
    interacoes_importantes: [
      { com: 'IECA', severidade: 'contraindicado', descricao: 'Duplo SRAA — IRA, hipercalemia (ONTARGET mostrou maior risco sem benefício)' },
      { com: 'Alisquireno', severidade: 'contraindicado', descricao: 'Duplo SRAA em diabéticos' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Pode aumentar pico e vale da digoxina — monitorar' },
      { com: 'Lítio', severidade: 'grave', descricao: 'Aumento do lítio sérico' },
    ],
    alertas_especiais: [
      'Vantagem: sem tosse (diferente dos IECAs)',
      'ONTARGET: igual ao ramipril em DCV estabelecida; combinação IECA+BRA → mais eventos adversos, sem benefício adicional',
      'Metabolismo hepático (CYP nenhum — excreção biliar) — vantagem em insuficiência renal leve-moderada',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Micardis®', laboratorio: 'Boehringer Ingelheim', concentracoes: ['40 mg', '80 mg'], formas: ['Comprimido'] },
      { nome: 'Telmisartana EMS', laboratorio: 'EMS', concentracoes: ['40 mg', '80 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ARNI — Inibidor da Neprilisina + BRA
  // ══════════════════════════════════════════════════════════════

  {
    id: 'sacubitril_valsartana',
    molecula: 'Sacubitril/Valsartana',
    nome_generico: 'Sacubitril + Valsartana (LCZ696)',
    sinonimos: ['entresto', 'arni', 'sacubitril valsartana', 'lbq657', 'sacubitril', 'neprilisina'],
    categoria: 'cardiovascular',
    classe: 'ARNI',
    subclasse: 'Inibidor de Neprilisina + Antagonista AT1 (PRÓ-FÁRMACO duplo)',
    indicacoes_principais: ['IC-FEr (FE ≤ 40%) sintomática NYHA II–IV — redução de mortalidade (PARADIGM-HF)', 'Substituição de IECA/BRA em IC-FEr tolerante'],
    dose_adulto: {
      habitual: '49/51 mg 2x/dia',
      min: '24/26 mg 2x/dia',
      max: '97/103 mg 2x/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia'],
      instrucoes: 'Iniciar 49/51 mg 2x/dia. Titular a cada 2–4 semanas até 97/103 mg 2x/dia. Em pacientes com PAS < 100 mmHg, IH ou virgem de IECA/BRA: iniciar 24/26 mg. AGUARDAR 36h após suspender IECA.',
    },
    ajuste_renal: {
      normal: '97/103 mg 2x/dia (dose alvo)',
      tfg_60_30: 'Iniciar com dose menor (24/26 mg 2x/dia) e titular',
      tfg_30_15: '24/26 mg 2x/dia — cautela',
      tfg_lt_15: 'Dados muito limitados — usar com extrema cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Iniciar com 24/26 mg 2x/dia', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'IECA nas últimas 36 horas (risco de angioedema — washout obrigatório)',
      'Histórico de angioedema por IECA ou BRA',
      'Gravidez',
      'IH grave (Child-Pugh C) com coagulopatia',
      'Uso simultâneo com alisquireno em diabéticos',
    ],
    interacoes_importantes: [
      { com: 'IECA (Enalapril, Ramipril, Perindopril)', severidade: 'contraindicado', descricao: 'Angioedema — intervalo MÍNIMO 36h após suspender IECA' },
      { com: 'Alisquireno', severidade: 'contraindicado', descricao: 'Duplo SRAA — contraindicado em diabéticos' },
      { com: 'Espironolactona/Eplerenona', severidade: 'moderada', descricao: 'Hipercalemia — monitorar K+' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Redução do efeito e risco de IRA' },
      { com: 'Estatinas (atorvastatina)', severidade: 'leve', descricao: 'Sacubitril eleva atorvastatina em ~36% — sem relevância clínica comprovada' },
    ],
    alertas_especiais: [
      'PARADIGM-HF: redução de 20% em morte CV e 21% em hospitalização por IC vs enalapril',
      'MECANISMO: valsartana bloqueia AT1; sacubitril inibe neprilisina → acúmulo de peptídeos natriuréticos (BNP), bradicinina, adrenomodulina',
      'ANGIOEDEMA: risco 0,5% (3× maior em negros) — washout IECA obrigatório (36h)',
      'Hipotensão sintomática: monitorar PA — reduzir diuréticos antes de iniciar',
      'Monitorar K+: especialmente com espironolactona ou eplerenona',
      'Medir peptídeos natriuréticos (NT-proBNP/BNP) no seguimento — entresto eleva BNP; usar NT-proBNP para monitoramento',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Entresto®', laboratorio: 'Novartis', concentracoes: ['24/26 mg', '49/51 mg', '97/103 mg'], formas: ['Comprimido'], lab_id: 'novartis' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // BETABLOQUEADORES
  // ══════════════════════════════════════════════════════════════

  {
    id: 'nebivolol',
    molecula: 'Nebivolol',
    nome_generico: 'Cloridrato de Nebivolol',
    sinonimos: ['nebilet', 'nebivolol', 'bb3', 'betabloqueador vasodilatador', 'beta1 seletivo'],
    categoria: 'cardiovascular',
    classe: 'Betabloqueador',
    subclasse: 'BB3 — β1-seletivo + liberação de NO endotelial (vasodilatação)',
    indicacoes_principais: ['HAS', 'IC-FEr estável (SENIORS trial — benefício em idosos ≥ 70 anos)', 'Angina'],
    dose_adulto: {
      habitual: '5 mg 1x/dia',
      min: '1,25 mg 1x/dia',
      max: '10 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'IC: iniciar 1,25 mg 1x/dia, titular a cada 2 semanas (1,25 → 2,5 → 5 → 10 mg). HAS: 5 mg 1x/dia.',
    },
    ajuste_renal: {
      normal: '5 mg 1x/dia',
      tfg_60_30: '2,5 mg 1x/dia e titular com cautela',
      tfg_30_15: '2,5 mg 1x/dia',
      tfg_lt_15: '1,25 mg — cautela extrema',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela — metabolismo CYP2D6', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'BAV 2º e 3º graus sem marcapasso',
      'IC descompensada (NYHA IV aguda)',
      'Bradicardia sinusal < 50 bpm',
      'Hipotensão PAS < 90 mmHg',
      'Asma grave / broncoespasmo ativo',
    ],
    interacoes_importantes: [
      { com: 'Verapamil/Diltiazem', severidade: 'grave', descricao: 'Bradicardia severa e BAV — combinação geralmente contraindicada' },
      { com: 'Amiodarona', severidade: 'moderada', descricao: 'Bradicardia e BAV' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Efeito aditivo no nódulo AV — bradicardia' },
      { com: 'Insulina/Hipoglicemiantes', severidade: 'moderada', descricao: 'Mascara taquicardia hipoglicêmica' },
      { com: 'Clonidina', severidade: 'moderada', descricao: 'Rebound hipertensivo ao suspender clonidina' },
    ],
    alertas_especiais: [
      'SENIORS: único BB com evidência em IC-FEr em idosos (≥ 70 anos) — redução de mortalidade/hospitalização',
      'Vasodilatação via NO: perfil hemodinâmico superior em idosos, DPOC leve e disfunção erétil',
      'CYP2D6: metabolizadores lentos têm T½ estendida — ajuste empírico',
      'Não interromper abruptamente: rebote de angina/hipertensão — retirada gradual em 2 semanas',
      'Menor mascaramento de hipoglicemia vs betabloqueadores não seletivos',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Nebilet®', laboratorio: 'Menarini', concentracoes: ['5 mg'], formas: ['Comprimido'] },
      { nome: 'Nebivolol EMS', laboratorio: 'EMS', concentracoes: ['5 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // BCC — Bloqueadores dos Canais de Cálcio
  // ══════════════════════════════════════════════════════════════

  {
    id: 'nifedipino',
    molecula: 'Nifedipino',
    nome_generico: 'Nifedipino',
    sinonimos: ['adalat', 'nifedipino', 'bcc diidropiridinco', 'nifedipino retard'],
    categoria: 'antihipertensivo',
    classe: 'BCC',
    subclasse: 'Di-hidropiridínico — ação predominante vascular',
    indicacoes_principais: ['HAS', 'Angina estável', 'Fenômeno de Raynaud', 'Crise hipertensiva em gestante (VO)', 'HAS na gestação (2ª linha após metildopa)'],
    dose_adulto: {
      habitual: '30 mg 1x/dia (LP)',
      min: '10 mg 2x/dia',
      max: '90 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (LP)', '2x/dia (LP)', '3x/dia (imediata — evitar)'],
      instrucoes: 'USAR APENAS formulação de liberação prolongada (LP/OROS) para HAS — a formulação de ação imediata aumenta risco CV. Engolir inteiro, não mastigar. Crise hipertensiva gestacional: 10–20 mg VO a cada 20–30 min conforme PA.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste — cautela com hipotensão',
      tfg_lt_15: 'Sem ajuste — maior risco de hipotensão',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir dose', child_c: 'Reduzir dose significativamente' },
    contraindicacoes_rapidas: [
      'Formulação de ação imediata para HAS crônica (risco aumentado de IAM)',
      'Choque cardiogênico',
      'Angina instável (sem associação com betabloqueador)',
      'Estenose aórtica grave',
    ],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'leve', descricao: 'Hipotensão aditiva — combinação usada para angina' },
      { com: 'CYP3A4 inibidores (cetoconazol, claritromicina)', severidade: 'moderada', descricao: 'Aumento dos níveis de nifedipino' },
      { com: 'Rifampicina', severidade: 'grave', descricao: 'Induz CYP3A4 — reduz nifedipino > 90%' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Pode aumentar concentrações de digoxina' },
    ],
    alertas_especiais: [
      'Formulação LP é a ÚNICA segura para uso crônico — ação imediata está contraindicada em HAS',
      'Edema de tornozelo por vasodilatação capilar — não é IC: não responde a diuréticos; responde a redução de dose ou troca para outro BCC',
      'Gestação: fármaco de escolha para crises hipertensivas (10–20 mg VO)',
      'Rubor facial e cefaleia pulsátil são comuns no início do tratamento — geralmente regridem',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Adalat® OROS', laboratorio: 'Bayer', concentracoes: ['20 mg', '30 mg', '60 mg'], formas: ['Comprimido LP'] },
      { nome: 'Nifedipino LP EMS', laboratorio: 'EMS', concentracoes: ['20 mg', '30 mg'], formas: ['Comprimido LP'] },
    ],
  },

  {
    id: 'diltiazem',
    molecula: 'Diltiazem',
    nome_generico: 'Cloridrato de Diltiazem',
    sinonimos: ['cardizem', 'diltiazem', 'bcc nao-diidropiridinco', 'benzotiazepina'],
    categoria: 'cardiovascular',
    classe: 'BCC',
    subclasse: 'Não-di-hidropiridínico (Benzotiazepina) — efeito cardíaco e vascular',
    indicacoes_principais: ['Angina estável', 'HAS', 'FA crônica (controle de frequência)', 'Taquicardia supraventricular paroxística (IV)'],
    dose_adulto: {
      habitual: '120–180 mg 1x/dia (LP)',
      min: '60 mg 2x/dia',
      max: '360 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (LP)', '2x/dia', '3x/dia (imediata)'],
      instrucoes: 'HAS/angina: formulação LP 120–360 mg 1x/dia. FA: ajustar conforme FC alvo (60–80 bpm repouso).',
    },
    ajuste_renal: {
      normal: 'Sem ajuste necessário',
      tfg_60_30: 'Sem ajuste — cautela',
      tfg_30_15: 'Cautela — reduzir dose',
      tfg_lt_15: 'Dados limitados — usar com cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'BAV 2º e 3º graus sem marcapasso',
      'Disfunção ventricular grave (FE < 40%)',
      'Síndrome do nó sinusal sem marcapasso',
      'Uso concomitante com betabloqueador IV',
      'FA/Flutter com via acessória (WPW)',
    ],
    interacoes_importantes: [
      { com: 'Betabloqueadores (VO)', severidade: 'moderada', descricao: 'Bradicardia e BAV — combinação possível com cautela; IV: contraindicado' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Diltiazem aumenta digoxinemia em ~20–40% (inibe P-gp)' },
      { com: 'Estatinas (sinvastatina, lovastatina)', severidade: 'moderada', descricao: 'Inibição de CYP3A4 — risco de miopatia' },
      { com: 'Ciclosporina', severidade: 'grave', descricao: 'Inibição CYP3A4 — nefrotoxicidade' },
      { com: 'Amiodarona', severidade: 'grave', descricao: 'BAV completo — evitar combinação' },
    ],
    alertas_especiais: [
      'Diferente dos di-hidropiridínicos: tem ação cronotrópica e dromotrópica negativa — útil em FA para controle de FC',
      'Monitorar ECG: PR, FC e sinais de BAV',
      'Não usar como único agente em FA com disfunção sistólica grave — preferir amiodarona',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Cardizem® CD', laboratorio: 'Bausch Health', concentracoes: ['120 mg', '180 mg', '240 mg', '360 mg'], formas: ['Cápsula LP'] },
      { nome: 'Diltiazem EMS', laboratorio: 'EMS', concentracoes: ['60 mg', '90 mg', '120 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'verapamil',
    molecula: 'Verapamil',
    nome_generico: 'Cloridrato de Verapamil',
    sinonimos: ['isoptin', 'verapamil', 'bcc fenilalquilamina', 'bloqueador canal calcio'],
    categoria: 'cardiovascular',
    classe: 'BCC',
    subclasse: 'Não-di-hidropiridínico (Fenilalquilamina) — maior efeito cardíaco',
    indicacoes_principais: ['Angina variante (Prinzmetal) e estável', 'HAS', 'FA/Flutter (controle de FC)', 'TSVP (IV — cardioversão)'],
    dose_adulto: {
      habitual: '80 mg 3x/dia ou 120–480 mg/dia LP',
      min: '40 mg 3x/dia',
      max: '480 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3x/dia (imediata)', '1–2x/dia (LP)'],
      instrucoes: 'HAS: 120–480 mg LP 1x/dia. FA (controle FC): 240–480 mg/dia divididos. Angina: 80–120 mg 3x/dia.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste — cautela',
      tfg_30_15: 'Reduzir 25–50%',
      tfg_lt_15: 'Reduzir 50% — cautela extrema',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Reduzir 30–50%', child_b: 'Reduzir 50–70%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'IC sistólica com FE reduzida',
      'BAV 2º/3º grau sem marcapasso',
      'FA/Flutter com WPW (risco de fibrilação ventricular)',
      'Betabloqueador IV concomitante',
      'Taquicardia ventricular',
    ],
    interacoes_importantes: [
      { com: 'Betabloqueadores (VO)', severidade: 'moderada', descricao: 'BAV e bradicardia — monitorar; IV: contraindicado' },
      { com: 'Digoxina', severidade: 'grave', descricao: 'Verapamil aumenta digoxinemia em 50–75% (inibe P-gp e CYP3A4) — reduzir digoxina 50%' },
      { com: 'Sinvastatina', severidade: 'grave', descricao: 'Inibição CYP3A4 — rabdomiólise (sinvastatina máximo 10 mg/dia)' },
      { com: 'Colchicina', severidade: 'grave', descricao: 'Verapamil inibe P-gp — toxicidade de colchicina' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Neurotoxicidade — monitorar' },
    ],
    alertas_especiais: [
      'Constipação intestinal: efeito adverso mais frequente (~30%) — orientar fibras e hidratação',
      'NUNCA associar com betabloqueador IV — risco de colapso hemodinâmico',
      'IC: contraindicado em FE reduzida (efeito inotrópico negativo acentuado)',
      'Inibidor potente de CYP3A4 e P-gp — múltiplas interações medicamentosas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Isoptin® SR', laboratorio: 'Abbott', concentracoes: ['120 mg', '240 mg'], formas: ['Comprimido LP'] },
      { nome: 'Verapamil EMS', laboratorio: 'EMS', concentracoes: ['80 mg', '120 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // DIURÉTICOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'clortalidona',
    molecula: 'Clortalidona',
    nome_generico: 'Clortalidona',
    sinonimos: ['higrotona', 'chlortalidone', 'clortalidona', 'diuretico tiazidico', 'allhat diuretico'],
    categoria: 'antihipertensivo',
    classe: 'Diurético',
    subclasse: 'Tiazídico-símile — T½ longa (40–60h), potência superior à HCTZ',
    indicacoes_principais: ['HAS (1ª linha — ALLHAT mostrou superioridade CV vs amlodipino e lisinopril em subgrupos)', 'IC (retenção volêmica leve)'],
    dose_adulto: {
      habitual: '12,5 mg 1x/dia',
      min: '12,5 mg 1x/dia',
      max: '50 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (manhã)'],
      instrucoes: 'Tomar pela manhã para evitar nictúria. Iniciar 12,5 mg — evitar doses > 25 mg (maior risco de hipocalemia sem benefício adicional).',
    },
    ajuste_renal: {
      normal: '12,5–25 mg 1x/dia',
      tfg_60_30: 'Reduzir eficácia. Cautela',
      tfg_30_15: 'Ineficaz como anti-hipertensivo — considerar furosemida',
      tfg_lt_15: 'Ineficaz — contraindicado como anti-hipertensivo',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Cuidado com desequilíbrio eletrolítico', child_c: 'Evitar' },
    contraindicacoes_rapidas: [
      'Anúria',
      'Hipocalemia refratária (K+ < 3,0 mEq/L)',
      'Hiponatremia grave',
      'Gota aguda (relativa — precipita hiperuricemia)',
    ],
    interacoes_importantes: [
      { com: 'IECA/BRA', severidade: 'moderada', descricao: 'Hipotensão de primeira dose — monitorar ao iniciar' },
      { com: 'Digoxina', severidade: 'grave', descricao: 'Hipocalemia induzida por tiazídico aumenta toxicidade digitálica' },
      { com: 'Lítio', severidade: 'grave', descricao: 'Tiazídicos reduzem excreção renal do lítio — toxicidade' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Redução do efeito diurético e anti-hipertensivo' },
      { com: 'Antidiabéticos', severidade: 'moderada', descricao: 'Hiperglicemia — monitorar glicemia' },
    ],
    alertas_especiais: [
      'Preferida sobre HCTZ em HAS: T½ mais longa = maior redução de PA noturna e redução de eventos CV (ACCOMPLISH, MRFIT)',
      'Monitorar K+, Na+, glicemia, ácido úrico e lipídeos após iniciar',
      'Hipocalemia: suplementar K+ ou associar poupador se K+ < 3,5 mEq/L',
      'Crise de gota: risco aumentado — cautela em gotosos',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Higrotona®', laboratorio: 'Novartis', concentracoes: ['25 mg'], formas: ['Comprimido'] },
      { nome: 'Clortalidona EMS', laboratorio: 'EMS', concentracoes: ['12,5 mg', '25 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'indapamida',
    molecula: 'Indapamida',
    nome_generico: 'Indapamida',
    sinonimos: ['natrilix', 'indapamida', 'diuretico tiazidico-simile', 'indapamide'],
    categoria: 'antihipertensivo',
    classe: 'Diurético',
    subclasse: 'Tiazídico-símile com ação vasodilatadora adicional',
    indicacoes_principais: ['HAS', 'IC leve (edema)'],
    dose_adulto: {
      habitual: '1,5 mg LP 1x/dia ou 2,5 mg 1x/dia',
      min: '1,5 mg 1x/dia',
      max: '2,5 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (manhã)'],
      instrucoes: 'Tomar pela manhã. LP 1,5 mg é a formulação preferida (menor incidência de efeitos metabólicos).',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Cautela — reduzir eficácia',
      tfg_30_15: 'Contraindicado em insuficiência renal grave',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Anúria', 'IH grave', 'Hipocalemia refratária'],
    interacoes_importantes: [
      { com: 'Digoxina', severidade: 'grave', descricao: 'Hipocalemia → toxicidade digitálica' },
      { com: 'Lítio', severidade: 'grave', descricao: 'Reduz excreção renal do lítio' },
      { com: 'IECA', severidade: 'leve', descricao: 'Hipotensão de 1ª dose — monitorar' },
    ],
    alertas_especiais: [
      'PROGRESS trial: indapamida + perindopril reduz AVC recorrente em 43%',
      'Perfil metabólico mais favorável que HCTZ (menor impacto em glicemia e lipídeos)',
      'Monitorar eletrólitos: K+, Na+, Mg2+',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Natrilix® SR', laboratorio: 'Servier', concentracoes: ['1,5 mg LP', '2,5 mg'], formas: ['Comprimido'] },
      { nome: 'Indapamida EMS', laboratorio: 'EMS', concentracoes: ['2,5 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ARM — Antagonistas do Receptor de Mineralocorticoide
  // ══════════════════════════════════════════════════════════════

  {
    id: 'eplerenona',
    molecula: 'Eplerenona',
    nome_generico: 'Eplerenona',
    sinonimos: ['inspra', 'eplerenona', 'arm seletivo', 'arm2', 'aldosterona antagonista seletivo'],
    categoria: 'cardiovascular',
    classe: 'ARM',
    subclasse: 'Antagonista seletivo do receptor de mineralocorticoide — sem ação androgênica/progestacional',
    indicacoes_principais: ['IC-FEr pós-IAM (FE ≤ 40%) — EPHESUS trial', 'IC-FEr NYHA II (FE ≤ 35%) — EMPHASIS-HF', 'HAS (off-label em associação)'],
    dose_adulto: {
      habitual: '25 mg 1x/dia → 50 mg 1x/dia',
      min: '25 mg 1x/dia',
      max: '50 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'Iniciar 25 mg 1x/dia. Aumentar para 50 mg após 4 semanas se K+ ≤ 5,0 mEq/L e TFG ≥ 30.',
    },
    ajuste_renal: {
      normal: '50 mg 1x/dia',
      tfg_60_30: '25 mg em dias alternados → 25 mg 1x/dia',
      tfg_30_15: 'Contraindicado (risco de hipercalemia)',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Dados insuficientes' },
    contraindicacoes_rapidas: [
      'TFG < 30 (IC) ou < 50 (HAS)',
      'K+ > 5,0 mEq/L no início',
      'Diabetes tipo 2 com microalbuminúria + IECA',
      'Inibidores potentes de CYP3A4 (cetoconazol, itraconazol, nelfinavir, ritonavir)',
    ],
    interacoes_importantes: [
      { com: 'IECA/BRA', severidade: 'moderada', descricao: 'Hipercalemia — monitorar K+ rigorosamente (semanal × 4 semanas → mensal)' },
      { com: 'Inibidores CYP3A4 potentes', severidade: 'contraindicado', descricao: 'Aumentam exposição à eplerenona em até 5× — contraindicado' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Hipercalemia e redução de efeito' },
      { com: 'Suplementos de K+', severidade: 'moderada', descricao: 'Hipercalemia — monitorar' },
    ],
    alertas_especiais: [
      'Vantagem vs espironolactona: SEM ginecomastia, mastalgia, disfunção erétil ou irregularidade menstrual',
      'EPHESUS: redução de 15% em mortalidade pós-IAM com FE ≤ 40%',
      'EMPHASIS-HF: redução de 37% em morte/hospitalização em IC leve (NYHA II)',
      'Monitorar K+ e creatinina: 1ª semana, 1ª e 3ª meses, depois 6/6 meses',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Inspra®', laboratorio: 'Pfizer', concentracoes: ['25 mg', '50 mg'], formas: ['Comprimido'], lab_id: 'pfizer' },
      { nome: 'Eplerenona EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '50 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIARRÍTMICOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'amiodarona',
    molecula: 'Amiodarona',
    nome_generico: 'Cloridrato de Amiodarona',
    sinonimos: ['cordarone', 'amiodarona', 'antiarritmico', 'classe iii', 'vaughan-williams iii'],
    categoria: 'cardiovascular',
    classe: 'Antiarrítmico',
    subclasse: 'Classe III (Vaughan-Williams) — bloqueio de canais K+/Na+/Ca2+ + ação beta-bloqueante',
    indicacoes_principais: ['FA (manutenção do ritmo e controle de FC)', 'Flutter atrial', 'TV sustentada / FV (emergência IV)', 'Taquicardias supraventriculares refratárias'],
    dose_adulto: {
      habitual: '200 mg 1x/dia (manutenção)',
      min: '100 mg 1x/dia',
      max: '1200 mg/dia (fase de ataque)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (manutenção)', 'Ataque: 3x/dia por 10 dias', 'IV: protocolo específico'],
      instrucoes: 'Ataque VO: 600–1200 mg/dia por 1–4 semanas. Manutenção: 200 mg 1x/dia (mínimo eficaz). IV ACLS FV/TV: 300 mg em bolus, repetir 150 mg se necessário.',
    },
    ajuste_renal: {
      normal: '200 mg 1x/dia',
      tfg_60_30: 'Sem ajuste necessário (excreção biliar)',
      tfg_30_15: 'Sem ajuste',
      tfg_lt_15: 'Sem ajuste — metabolismo biliar',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela — hepatotoxicidade inerente', child_b: 'Reduzir dose', child_c: 'Contraindicado — hepatotóxico' },
    contraindicacoes_rapidas: [
      'BAV 2º e 3º graus sem marcapasso',
      'Hipotensão grave',
      'Disfunção tireoidiana pré-existente não tratada',
      'Hipersensibilidade ao iodo',
      'Toxicidade pulmonar por amiodarona prévia',
    ],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'Amiodarona aumenta INR em 30–50% — reduzir varfarina em 30–50% ao iniciar; monitorar INR semanalmente' },
      { com: 'Digoxina', severidade: 'grave', descricao: 'Amiodarona aumenta digoxinemia em 70% (inibe P-gp) — reduzir digoxina à metade' },
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Bradicardia severa e BAV' },
      { com: 'Estatinas (sinvastatina)', severidade: 'moderada', descricao: 'Inibição CYP3A4 — risco de miopatia (sinvastatina máx 20 mg)' },
      { com: 'Diltiazem/Verapamil', severidade: 'grave', descricao: 'BAV completo — evitar combinação' },
      { com: 'QT prolongadores (haloperidol, citalopram, azitromicina)', severidade: 'grave', descricao: 'Prolongamento QT aditivo — torsades de pointes' },
    ],
    alertas_especiais: [
      'T½ EXTREMAMENTE LONGA: 40–55 dias — efeitos adversos persistem semanas após suspensão',
      'TIREOIDE: hipo (5–10%) ou hiper (2%) — TSH a cada 6 meses',
      'PULMÃO: pneumonite/fibrose em 1–5% — RX/TC anual; dispneia nova = investigar imediatamente',
      'FÍGADO: hepatotoxicidade — enzimas hepáticas a cada 6 meses',
      'CÓRNEA: microdepósitos (>90% com uso crônico) — geralmente assintomáticos; neuropatia óptica rara',
      'PELE: fotossensibilidade (evitar sol); pigmentação azul-acinzentada (cinza amiodarónico) com uso > 2 anos',
      'MONITORAMENTO: ECG (QTc), TFT, enzimas hepáticas, RX tórax — todos a cada 6 meses',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Cordarone®', laboratorio: 'Sanofi', concentracoes: ['100 mg', '200 mg'], formas: ['Comprimido'] },
      { nome: 'Amiodarona Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['100 mg', '200 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
      { nome: 'Amiodarona EMS', laboratorio: 'EMS', concentracoes: ['200 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'digoxina',
    molecula: 'Digoxina',
    nome_generico: 'Digoxina',
    sinonimos: ['lanoxin', 'digoxin', 'glicosideo cardiaco', 'digitálico'],
    categoria: 'cardiovascular',
    classe: 'Glicosídeo Cardíaco',
    subclasse: 'Inibidor da Na+/K+-ATPase — inotrópico positivo e cronotrópico negativo',
    indicacoes_principais: ['IC-FEr sintomática (FE ≤ 40%) — controle de sintomas + redução de hospitalização (DIG trial)', 'FA crônica — controle de FC em repouso'],
    dose_adulto: {
      habitual: '0,125 mg 1x/dia',
      min: '0,0625 mg 1x/dia',
      max: '0,25 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'Dose inicial: 0,125 mg 1x/dia. Idosos, DRC, baixo peso: 0,0625 mg 1x/dia. Nível sérico alvo: 0,5–0,9 ng/mL (IC); evitar > 1,2 ng/mL.',
    },
    ajuste_renal: {
      normal: '0,125–0,25 mg 1x/dia',
      tfg_60_30: '0,0625–0,125 mg 1x/dia — monitorar nível sérico',
      tfg_30_15: '0,0625 mg 1x/dia ou em dias alternados',
      tfg_lt_15: 'Contraindicado ou usar com extrema cautela com monitorização sérica rigorosa',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste (excreção renal)', child_b: 'Sem ajuste', child_c: 'Sem ajuste — monitorar' },
    contraindicacoes_rapidas: [
      'Intoxicação digitálica',
      'BAV 2º/3º grau (sem marcapasso)',
      'Fibrilação ventricular',
      'Cardiomiopatia hipertrófica obstrutiva',
      'Síndrome de Wolff-Parkinson-White',
    ],
    interacoes_importantes: [
      { com: 'Amiodarona', severidade: 'grave', descricao: 'Aumenta digoxinemia em 70% — reduzir digoxina 50% ao iniciar amiodarona' },
      { com: 'Verapamil', severidade: 'grave', descricao: 'Aumenta digoxinemia em 50–75% — reduzir digoxina 50%' },
      { com: 'Diltiazem', severidade: 'moderada', descricao: 'Aumenta digoxinemia em 20–40%' },
      { com: 'Quinidina', severidade: 'grave', descricao: 'Dobra a digoxinemia' },
      { com: 'Diuréticos (furosemida, HCTZ, clortalidona)', severidade: 'grave', descricao: 'Hipocalemia/hipomagnesemia → toxicidade digitálica (aumenta ligação ao receptor)' },
      { com: 'Eritromicina/Claritromicina', severidade: 'moderada', descricao: 'Inibição flora intestinal que metaboliza digoxina → aumento sérico' },
    ],
    alertas_especiais: [
      'JANELA TERAPÊUTICA ESTREITA — margem tóxica/terapêutica pequena',
      'Nível sérico alvo IC: 0,5–0,9 ng/mL (JACC 2013). Nível > 1,2 ng/mL associado a maior mortalidade',
      'INTOXICAÇÃO: náuseas, vômitos, visão com halos amarelo-esverdeados, bradicardia, BAV, TV bidirecional',
      'FATOR DE RISCO PARA INTOXICAÇÃO: hipocalemia, hipomagnesemia, hipercalcemia, hipotireoidismo',
      'Antídoto: anticorpos antidigoxina (Digibind®/DigiFab®) — reservado a intoxicações graves',
      'Monitorar: K+, Mg2+, Cr, FC e nível sérico a cada 6–12 meses (ou após mudança de dose)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Lanoxin®', laboratorio: 'Aspen', concentracoes: ['0,25 mg'], formas: ['Comprimido'] },
      { nome: 'Digoxina EMS', laboratorio: 'EMS', concentracoes: ['0,25 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTICOAGULANTES ORAIS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'varfarina',
    molecula: 'Varfarina',
    nome_generico: 'Varfarina Sódica',
    sinonimos: ['coumadin', 'varfarin', 'warfarin', 'avk', 'antagonista vitamina k', 'anticoagulante oral'],
    categoria: 'cardiovascular',
    classe: 'Anticoagulante',
    subclasse: 'Antagonista da Vitamina K (AVK) — inibe fatores II, VII, IX, X e proteínas C e S',
    indicacoes_principais: [
      'FA VALVULAR (estenose mitral moderada/grave) — ÚNICA indicação onde DOAC não substitui',
      'Prótese valvular mecânica — ÚNICO anticoagulante oral eficaz',
      'FA não-valvular (alternativa quando DOAC contraindicado)',
      'TEP/TVP (alternativa a DOACs)',
      'Trombofilia com anticorpo antifosfolipídeo (SAAF)',
    ],
    dose_adulto: {
      habitual: 'Individualizar conforme INR',
      min: '1 mg 1x/dia',
      max: '15 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (mesmo horário)'],
      instrucoes: 'Dose ajustada pelo INR. INR alvo: 2–3 (FA/TEP/TVP); 2,5–3,5 (prótese mecânica). Algoritmo inicial: 5 mg 1x/dia × 3 dias → medir INR → ajustar. Genômica: CYP2C9 e VKORC1 influenciam a dose necessária.',
    },
    ajuste_renal: {
      normal: 'Dose ajustada pelo INR',
      tfg_60_30: 'Cautela — maior risco de sangramento. Ajustar pelo INR',
      tfg_30_15: 'DOACs preferíveis quando possível. Se varfarina: INR rigoroso, alvo 2–2,5',
      tfg_lt_15: 'Considerar DOAC (apixabana) — varfarina com risco hemorrágico muito elevado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela — INR basal alterado', child_b: 'Ajuste difícil — INR não reflete anticoagulação real', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Sangramento ativo ou alto risco (cirurgia SNC recente < 4 semanas)',
      'Gravidez (teratogênico — embriopatia vafarínica no 1º tri; risco fetal no 3º tri)',
      'Hipertensão grave não controlada (> 180/110)',
      'Trombocitopenia grave (< 50.000)',
    ],
    interacoes_importantes: [
      { com: 'Amiodarona', severidade: 'grave', descricao: 'Aumenta INR em 30–50% — reduzir varfarina 30–50% ao iniciar amiodarona; monitorar semanalmente' },
      { com: 'Fluconazol/Metronidazol', severidade: 'grave', descricao: 'Inibem CYP2C9 — dobram ou triplicam INR' },
      { com: 'Rifampicina', severidade: 'grave', descricao: 'Induz CYP2C9/CYP3A4 — reduz INR drasticamente' },
      { com: 'AAS/AINEs', severidade: 'grave', descricao: 'Risco hemorrágico aditivo' },
      { com: 'Vitamina K (alimentos)', severidade: 'moderada', descricao: 'Alface, couve, brócolis — reduzem INR. Consumo CONSTANTE é a chave, não zero' },
      { com: 'Antibióticos (amplo espectro)', severidade: 'moderada', descricao: 'Eliminam flora intestinal que produz Vit K — INR sobe' },
    ],
    alertas_especiais: [
      'MONITORAMENTO obrigatório de INR — instabilidade requer coletas frequentes',
      'ÚNICO anticoagulante oral eficaz em FA valvular e prótese mecânica',
      'ANTÍDOTO: Vitamina K1 IV/VO (ação em 6–12h VO, 1–2h IV); Concentrado de Complexo Protrombínico (CCP) para reversão de emergência',
      'Interações ALIMENTARES: orientar consumo CONSISTENTE de vegetais verdes (não eliminar — estabilizar)',
      'Farmacogenômica: CYP2C9 e VKORC1 — polimorfismos afetam 30–50% da variação de dose',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'avaliar',
    marcas: [
      { nome: 'Coumadin®', laboratorio: 'Aché', concentracoes: ['1 mg', '2,5 mg', '5 mg'], formas: ['Comprimido'], lab_id: 'ache' },
      { nome: 'Varfarina Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['5 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'apixabana',
    molecula: 'Apixabana',
    nome_generico: 'Apixabana',
    sinonimos: ['eliquis', 'apixaban', 'doac', 'xoa', 'fator xa direto', 'anticoagulante oral direto'],
    categoria: 'cardiovascular',
    classe: 'Anticoagulante',
    subclasse: 'DOAC — Inibidor direto do Fator Xa',
    indicacoes_principais: ['FA não-valvular (redução de AVC)', 'TEP/TVP tratamento', 'Profilaxia TEP pós-cirurgia ortopédica'],
    dose_adulto: {
      habitual: '5 mg 2x/dia (FA)',
      min: '2,5 mg 2x/dia',
      max: '10 mg 2x/dia (tratamento inicial TEP)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia'],
      instrucoes: 'FA: 5 mg 2x/dia padrão; reduzir para 2,5 mg 2x/dia se ≥ 2 dos critérios: idade ≥ 80a, peso ≤ 60kg, Cr ≥ 1,5 mg/dL. TEP/TVP: 10 mg 2x/dia × 7 dias, depois 5 mg 2x/dia.',
    },
    ajuste_renal: {
      normal: '5 mg 2x/dia',
      tfg_60_30: '5 mg 2x/dia (sem ajuste, exceto critérios de redução)',
      tfg_30_15: '2,5 mg 2x/dia — cautela (dados limitados)',
      tfg_lt_15: 'Dados insuficientes — apixabana é o DOAC com mais dados em DRC avançada',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'FA valvular ou prótese mecânica',
      'Sangramento ativo significativo',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'Inibidores CYP3A4 + P-gp (cetoconazol, ritonavir, claritromicina)', severidade: 'grave', descricao: 'Aumentam apixabana 2× — evitar ou reduzir dose' },
      { com: 'Indutores CYP3A4 + P-gp (rifampicina, fenitoína, carbamazepina)', severidade: 'grave', descricao: 'Reduzem apixabana em 50% — evitar' },
      { com: 'AAS/AINEs', severidade: 'moderada', descricao: 'Risco hemorrágico aditivo' },
    ],
    alertas_especiais: [
      'ARISTOTLE: menor sangramento intracraniano vs varfarina (50% de redução)',
      'Menor risco de interações vs varfarina — não requer monitoramento de INR rotineiro',
      'DOAC preferido em DRC avançada (maior excreção não-renal vs dabigatrana)',
      'Suspender 24–48h antes de procedimentos (48h se alto risco hemorrágico)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Eliquis®', laboratorio: 'BMS/Pfizer', concentracoes: ['2,5 mg', '5 mg'], formas: ['Comprimido'], lab_id: 'bms' },
    ],
  },

  {
    id: 'rivaroxabana',
    molecula: 'Rivaroxabana',
    nome_generico: 'Rivaroxabana',
    sinonimos: ['xarelto', 'rivaroxaban', 'doac', 'fator xa', 'xoa direto'],
    categoria: 'cardiovascular',
    classe: 'Anticoagulante',
    subclasse: 'DOAC — Inibidor direto do Fator Xa',
    indicacoes_principais: ['FA não-valvular', 'TEP/TVP tratamento e profilaxia', 'Profilaxia TEP pós-cirurgia ortopédica', 'SCA (2,5 mg 2x/dia + antiplaquetários — COMPASS trial)'],
    dose_adulto: {
      habitual: '20 mg 1x/dia com jantar (FA)',
      min: '2,5 mg 2x/dia',
      max: '20 mg/dia (FA)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (FA)', '2x/dia (2,5 mg — DCV)'],
      instrucoes: 'FA: 20 mg 1x/dia com jantar (TFG > 50) ou 15 mg 1x/dia (TFG 15–50). TEP/TVP: 15 mg 2x/dia × 21 dias → 20 mg 1x/dia. Comprimidos ≥ 15 mg: OBRIGATÓRIO tomar com alimento (absorção incompleta em jejum).',
    },
    ajuste_renal: {
      normal: '20 mg 1x/dia com jantar',
      tfg_60_30: '15 mg 1x/dia (FA) — monitorar',
      tfg_30_15: '15 mg 1x/dia — com cautela',
      tfg_lt_15: 'Contraindicado para FA',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela — coagulopatia aumenta risco', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['FA valvular/prótese mecânica', 'TFG < 15', 'IH grave', 'Sangramento ativo'],
    interacoes_importantes: [
      { com: 'Inibidores CYP3A4 + P-gp', severidade: 'grave', descricao: 'Aumento de exposição — contraindicado com cetoconazol/ritonavir' },
      { com: 'Indutores CYP3A4 + P-gp (rifampicina)', severidade: 'grave', descricao: 'Redução drástica da exposição' },
      { com: 'AINEs/AAS', severidade: 'moderada', descricao: 'Risco hemorrágico aditivo' },
    ],
    alertas_especiais: [
      'ROCKET-AF: não-inferior à varfarina em AVC. Igual sangramento geral, MENOS intracraniano, MAIS GI',
      'Comprimidos 15–20 mg: tomar COM REFEIÇÃO — criticamente importante para absorção',
      'COMPASS: 2,5 mg 2x/dia + AAS reduz eventos CV em DCV aterosclerótica (SCA, DAC)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Xarelto®', laboratorio: 'Bayer', concentracoes: ['2,5 mg', '10 mg', '15 mg', '20 mg'], formas: ['Comprimido'], lab_id: 'bayer' },
    ],
  },

  {
    id: 'dabigatrana',
    molecula: 'Dabigatrana',
    nome_generico: 'Etexilato de Dabigatrana',
    sinonimos: ['pradaxa', 'dabigatran', 'doac', 'inibidor trombina direta', 'fator iia direto'],
    categoria: 'cardiovascular',
    classe: 'Anticoagulante',
    subclasse: 'DOAC — Inibidor direto da Trombina (Fator IIa)',
    indicacoes_principais: ['FA não-valvular', 'TEP/TVP tratamento (após 5–10 dias de heparina)', 'Profilaxia TEP pós-cirurgia ortopédica'],
    dose_adulto: {
      habitual: '150 mg 2x/dia (< 80 anos)',
      min: '110 mg 2x/dia',
      max: '300 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia'],
      instrucoes: 'FA < 80 anos: 150 mg 2x/dia. FA ≥ 80 anos: 110 mg 2x/dia. TFG 30–50: 110 mg 2x/dia. Não abrir cápsula (reduz biodisponibilidade em 75%). Tomar com água, com ou sem alimento.',
    },
    ajuste_renal: {
      normal: '150 mg 2x/dia',
      tfg_60_30: '110 mg 2x/dia — monitorar função renal a cada 6 meses',
      tfg_30_15: 'Contraindicado para FA (80% de excreção renal)',
      tfg_lt_15: 'Contraindicado',
      dialisavel: true,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'TFG < 30 para FA',
      'FA valvular / prótese mecânica',
      'Sangramento ativo',
      'Inibidores P-gp potentes (cetoconazol, ciclosporina, itraconazol, dronedarona)',
    ],
    interacoes_importantes: [
      { com: 'Inibidores P-gp (cetoconazol, dronedarona, ciclosporina, itraconazol)', severidade: 'contraindicado', descricao: 'Aumentam dabigatrana significativamente — contraindicado' },
      { com: 'Verapamil', severidade: 'moderada', descricao: 'Verapamil inibe P-gp — aumenta dabigatrana. Se usar: tomar verapamil 2h DEPOIS de dabigatrana' },
      { com: 'Rifampicina', severidade: 'grave', descricao: 'Induz P-gp — reduz dabigatrana 66%' },
      { com: 'AAS/AINEs', severidade: 'moderada', descricao: 'Risco hemorrágico' },
    ],
    alertas_especiais: [
      'ÚNICO DOAC com antídoto específico disponível no Brasil: IDARUCIZUMABE (Praxbind®) — reversão imediata em sangramento grave/cirurgia de emergência',
      'RE-LY 150 mg: maior redução de AVC vs varfarina; RE-LY 110 mg: igual eficácia, menos sangramento grave',
      'MAIOR dependência renal entre todos os DOACs — monitorar TFG a cada 6 meses (ou 4× TFG se TFG < 60)',
      'NÃO abrir cápsula — reduz biodisponibilidade em 75%',
      'Dispepsia: efeito adverso frequente (~15%) — tomar com alimento ou trocar para outro DOAC',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Pradaxa®', laboratorio: 'Boehringer Ingelheim', concentracoes: ['75 mg', '110 mg', '150 mg'], formas: ['Cápsula'], lab_id: 'boehringer' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIAGREGANTES PLAQUETÁRIOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'clopidogrel',
    molecula: 'Clopidogrel',
    nome_generico: 'Bissulfato de Clopidogrel',
    sinonimos: ['plavix', 'clopidogrel', 'antiplaquetario', 'p2y12', 'tienopiridina'],
    categoria: 'cardiovascular',
    classe: 'Antiplaquetário',
    subclasse: 'Tienopiridina — inibidor irreversível do receptor P2Y12 (pró-fármaco, metabolizado por CYP2C19)',
    indicacoes_principais: ['SCA (dupla antiplaquetação com AAS por 12 meses)', 'Pós-stent coronariano', 'AVC/AIT isquêmico', 'DAP (doença arterial periférica)'],
    dose_adulto: {
      habitual: '75 mg 1x/dia (manutenção)',
      min: '75 mg 1x/dia',
      max: '300–600 mg (dose de ataque)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'SCA: ataque 300 mg (ou 600 mg em IAMCSST < 75 anos), manutenção 75 mg 1x/dia. AVC/DAP: 75 mg 1x/dia. SEMPRE associar a AAS 100 mg/dia em SCA. Com ou sem alimento.',
    },
    ajuste_renal: {
      normal: '75 mg 1x/dia',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste — cautela com sangramento',
      tfg_lt_15: 'Dados limitados — cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Sangramento ativo (úlcera péptica, hemorragia intracraniana)',
      'IH grave',
      'Hipersensibilidade ao clopidogrel',
    ],
    interacoes_importantes: [
      { com: 'Omeprazol/Esomeprazol', severidade: 'moderada', descricao: 'Inibem CYP2C19 — reduzem ativação do clopidogrel em ~40%. Preferir pantoprazol ou rabeprazol em coronariopatas' },
      { com: 'AAS', severidade: 'leve', descricao: 'Dupla antiagregação: indicada em SCA; aumenta risco GI — associar IBP' },
      { com: 'Varfarina/DOACs', severidade: 'grave', descricao: 'Tripla terapia: risco hemorrágico elevado — individualizar' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Risco hemorrágico GI aditivo' },
    ],
    alertas_especiais: [
      'CYP2C19 POOR METABOLIZERS (PM): ~25% de asiáticos, 2–5% de caucasianos — resposta reduzida/nula. Considerar ticagrelor ou prasugrel em SCA',
      'Suspender 5–7 dias antes de cirurgia eletiva (não emergência)',
      'Pantoprazol ou rabeprazol: IBPs de escolha em pacientes em uso de clopidogrel',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Plavix®', laboratorio: 'Sanofi', concentracoes: ['75 mg', '300 mg'], formas: ['Comprimido'], lab_id: 'sanofi' },
      { nome: 'Clopidogrel EMS', laboratorio: 'EMS', concentracoes: ['75 mg'], formas: ['Comprimido'], lab_id: 'ems' },
      { nome: 'Clopidogrel Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['75 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'ticagrelor',
    molecula: 'Ticagrelor',
    nome_generico: 'Ticagrelor',
    sinonimos: ['brilique', 'ticagrelor', 'antiplaquetario', 'p2y12 reversivel', 'ciclopentrole'],
    categoria: 'cardiovascular',
    classe: 'Antiplaquetário',
    subclasse: 'Ciclopentiltriazolopirimidina — inibidor reversível direto do P2Y12 (NÃO é pró-fármaco)',
    indicacoes_principais: ['SCA (IAM com ou sem supra) — preferido sobre clopidogrel (PLATO trial)', 'Prevenção secundária tardia pós-IAM (60 mg 2x/dia — PEGASUS)'],
    dose_adulto: {
      habitual: '90 mg 2x/dia (SCA agudo)',
      min: '60 mg 2x/dia (prevenção secundária tardia)',
      max: '180 mg (dose de ataque)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia'],
      instrucoes: 'SCA: ataque 180 mg + AAS, manutenção 90 mg 2x/dia por 12 meses. Pós-IAM > 1 ano: 60 mg 2x/dia (PEGASUS). AAS: MÁXIMO 100 mg/dia (doses maiores reduzem eficácia do ticagrelor).',
    },
    ajuste_renal: {
      normal: '90 mg 2x/dia',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste — pode ser usado em diálise',
      tfg_lt_15: 'Sem ajuste — dados limitados',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela — metabolismo hepático', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'AVC hemorrágico prévio',
      'Sangramento ativo',
      'IH grave',
      'Inibidores potentes de CYP3A4 (cetoconazol, claritromicina, ritonavir, nefazodona)',
    ],
    interacoes_importantes: [
      { com: 'AAS > 100 mg/dia', severidade: 'grave', descricao: 'Doses altas de AAS REDUZEM eficácia do ticagrelor — manter AAS ≤ 100 mg/dia' },
      { com: 'Inibidores CYP3A4 potentes', severidade: 'contraindicado', descricao: 'Aumentam ticagrelor — contraindicado' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Ticagrelor pode aumentar digoxinemia' },
      { com: 'Anticoagulantes', severidade: 'moderada', descricao: 'Risco hemorrágico aditivo' },
    ],
    alertas_especiais: [
      'PLATO trial: redução de 16% em morte CV vs clopidogrel em SCA — INDEPENDENTE do status CYP2C19',
      'NÃO é pró-fármaco — não depende de CYP2C19 (vantagem sobre clopidogrel em PMs)',
      'DISPNEIA: efeito adverso em ~14% — por acúmulo de adenosina (transitória, geralmente não requer suspensão)',
      'Suspender 5 dias antes de cirurgia eletiva (não 7 como clopidogrel)',
      'Pausas doses: risco de trombose de stent — importância de adesão',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Brilique®', laboratorio: 'AstraZeneca', concentracoes: ['60 mg', '90 mg'], formas: ['Comprimido'], lab_id: 'astrazeneca' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // HIPOLIPEMIANTES
  // ══════════════════════════════════════════════════════════════

  {
    id: 'ezetimiba',
    molecula: 'Ezetimiba',
    nome_generico: 'Ezetimiba',
    sinonimos: ['ezetrol', 'ezetimibe', 'hipolipemiante', 'inibidor absorcao colesterol', 'niemann-pick c1l1'],
    categoria: 'cardiovascular',
    classe: 'Hipolipemiante',
    subclasse: 'Inibidor seletivo da absorção intestinal de colesterol (NPC1L1)',
    indicacoes_principais: ['Hipercolesterolemia (em adição ou substituição à estatina)', 'Hipercolesterolemia familiar', 'Prevenção CV secundária (IMPROVE-IT — ezetimiba + sinvastatina)'],
    dose_adulto: {
      habitual: '10 mg 1x/dia',
      min: '10 mg 1x/dia',
      max: '10 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (qualquer horário)'],
      instrucoes: 'Dose fixa. Pode ser tomado com ou sem alimento. Reduz LDL em 15–20% em monoterapia. Em combinação com estatina: redução adicional de 20–25%.',
    },
    ajuste_renal: {
      normal: '10 mg 1x/dia',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste',
      tfg_lt_15: 'Sem ajuste',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IH moderada a grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Ciclosporina', severidade: 'grave', descricao: 'Ciclosporina aumenta ezetimiba 12× — monitorar' },
      { com: 'Fibratos (fenofibrato)', severidade: 'moderada', descricao: 'Aumento de ezetimiba — risco de colelitíase' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Pode potencializar o efeito anticoagulante — monitorar INR' },
      { com: 'Colestiramina', severidade: 'leve', descricao: 'Reduz absorção de ezetimiba — tomar 2h antes ou 4h depois' },
    ],
    alertas_especiais: [
      'IMPROVE-IT: ezetimiba + sinvastatina reduz eventos CV (IAM não-fatal e AVC isquêmico) vs sinvastatina isolada em pós-SCA',
      'Mecanismo complementar às estatinas — combinação é mais eficaz que dobrar dose da estatina',
      'Hepatotoxicidade: muito rara — miopatia/rabdomiólise em monoterapia: extremamente raro',
      'Tolerância: bem tolerada. Preferível como add-on antes de iniciar inibidor PCSK9 (custo-efetividade)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Ezetrol®', laboratorio: 'MSD/Organon', concentracoes: ['10 mg'], formas: ['Comprimido'] },
      { nome: 'Ezetimiba EMS', laboratorio: 'EMS', concentracoes: ['10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'fenofibrato',
    molecula: 'Fenofibrato',
    nome_generico: 'Fenofibrato',
    sinonimos: ['lipanthyl', 'lipliner', 'fenofibrate', 'fibrato', 'ppar-alfa'],
    categoria: 'cardiovascular',
    classe: 'Hipolipemiante',
    subclasse: 'Fibrato — agonista PPARα — redução de TG + aumento de HDL',
    indicacoes_principais: ['Hipertrigliceridemia grave (> 500 mg/dL — prevenção de pancreatite)', 'Dislipidemia mista (↑ TG + ↓ HDL)', 'Complemento a estatina em DM2 com TG alto'],
    dose_adulto: {
      habitual: '145–160 mg 1x/dia (nanoparticulado)',
      min: '67 mg 1x/dia',
      max: '200 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia'],
      instrucoes: 'Fenofibrato 145/160 mg nanoparticulado ou micronizado: 1 comprimido 1x/dia com refeição. Reduz TG em 30–50%, aumenta HDL em 5–20%, redução modesta de LDL.',
    },
    ajuste_renal: {
      normal: '145 mg 1x/dia',
      tfg_60_30: 'Reduzir para 67–100 mg 1x/dia',
      tfg_30_15: 'Contraindicado',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'TFG < 30',
      'IH grave',
      'Colelitíase',
      'Pancreatite crônica ativa',
      'Hipersensibilidade a fibratos',
    ],
    interacoes_importantes: [
      { com: 'Estatinas', severidade: 'moderada', descricao: 'Risco de miopatia/rabdomiólise aumentado — monitorar CK; preferir rosuvastatina (menor interação)' },
      { com: 'Varfarina', severidade: 'grave', descricao: 'Aumenta INR — reduzir varfarina e monitorar frequentemente' },
      { com: 'Ezetimiba', severidade: 'moderada', descricao: 'Colelitíase' },
      { com: 'Ciclosporina', severidade: 'grave', descricao: 'Nefrotoxicidade aditiva' },
    ],
    alertas_especiais: [
      'ACCORD Lipid: em DM2 em uso de sinvastatina, fenofibrato NÃO reduziu eventos CV adicionais (exceto subgrupo TG > 204 + HDL < 34)',
      'Indicação primária atual: TG > 500 mg/dL (risco de pancreatite aguda)',
      'Miopatia: risco aumentado com estatinas, especialmente genfibrozila — fenofibrato tem interação farmacocinética menor',
      'Colelitíase: incidência aumentada com fibratos — monitorar sintomas',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Lipanthyl®', laboratorio: 'Abbott', concentracoes: ['100 mg', '145 mg', '160 mg', '200 mg'], formas: ['Comprimido', 'Cápsula'] },
      { nome: 'Fenofibrato EMS', laboratorio: 'EMS', concentracoes: ['100 mg', '145 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIANGINOSOS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'nitroglicerina',
    molecula: 'Nitroglicerina',
    nome_generico: 'Nitroglicerina',
    sinonimos: ['ntg', 'nitroglicerina', 'nitrato', 'nitroglicerin', 'trinitrato de glicerila', 'angina sl'],
    categoria: 'cardiovascular',
    classe: 'Antianginoso',
    subclasse: 'Nitrato orgânico — doador de NO — vasodilatação venoarterial',
    indicacoes_principais: ['Angina estável (alívio agudo)', 'Síndrome coronariana aguda (IV em UTI)', 'Crise hipertensiva com isquemia (IV)'],
    dose_adulto: {
      habitual: '0,4 mg SL em crise (spray/comprimido)',
      min: '0,4 mg SL',
      max: '1,2 mg SL (3 doses)',
      unidade: 'mg',
      via: 'Sublingual',
      frequencias: ['1 dose SL a cada 5 min (máx. 3 doses)', 'Adesivo: 0,2–0,8 mg/h (12h/dia)'],
      instrucoes: 'Crise de angina: 1 spray SL (0,4 mg) a cada 5 min. Se não aliviar em 15 min ou 3 doses: acionar SAMU/emergência (considerar SCA). Adesivo transdérmico: remover à noite (tolerância).',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste',
      tfg_lt_15: 'Sem ajuste — cautela com hipotensão',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Cautela' },
    contraindicacoes_rapidas: [
      'Uso de inibidores de PDE-5 (sildenafil, tadalafil, vardenafil) nas últimas 24–48h — hipotensão grave',
      'Hipotensão (PAS < 90 mmHg)',
      'IAM de VD (dependente de pré-carga)',
      'Glaucoma de ângulo fechado',
      'Anemia grave (metahemoglobinemia)',
    ],
    interacoes_importantes: [
      { com: 'Sildenafil/Tadalafil/Vardenafil (iPDE5)', severidade: 'contraindicado', descricao: 'Hipotensão grave, potencialmente fatal — intervalo mínimo: 24h sildenafil/vardenafil; 48h tadalafil' },
      { com: 'Álcool', severidade: 'moderada', descricao: 'Hipotensão aditiva' },
      { com: 'Anti-hipertensivos', severidade: 'moderada', descricao: 'Hipotensão aditiva — sentar/deitar ao usar' },
    ],
    alertas_especiais: [
      'TOLERÂNCIA: evitar com adesivos transdérmicos — necessário "intervalo livre de nitrato" de 8–12h (remover à noite)',
      'Cefaleia pulsátil: efeito adverso frequente — avisar paciente, desaparece com uso contínuo',
      'Preservar em frasco escuro, fechado (sensível à luz e calor)',
      'SCA: se não aliviar com 3 doses SL → acionar emergência médica',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Nitradisc® adesivo', laboratorio: 'Nycomed', concentracoes: ['0,2 mg/h', '0,4 mg/h', '0,8 mg/h'], formas: ['Adesivo'] },
      { nome: 'Nitroglicerina spray SL', laboratorio: 'Recordati', concentracoes: ['0,4 mg/dose'], formas: ['Spray sublingual'] },
    ],
  },

  {
    id: 'isossorbida_mononitrato',
    molecula: 'Isossorbida Mononitrato',
    nome_generico: 'Isossorbida Mononitrato (ISMN)',
    sinonimos: ['monocordil', 'isossorbida', 'ismn', 'nitrato prolongado', 'isosorbide mononitrate'],
    categoria: 'cardiovascular',
    classe: 'Antianginoso',
    subclasse: 'Nitrato orgânico — não necessita de conversão hepática (diferente do dinitrato)',
    indicacoes_principais: ['Angina estável crônica (profilaxia)', 'IC (redução de pré-carga)', 'HAS pulmonar (off-label)'],
    dose_adulto: {
      habitual: '20 mg 2x/dia (convencional) ou 60 mg LP 1x/dia',
      min: '10 mg 2x/dia',
      max: '120 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia (7h e 14h — intervalo assimétrico evita tolerância)', '1x/dia (LP)'],
      instrucoes: 'CONVENCIONAL: tomar às 7h e 14h (intervalo assimétrico de 7h garante período livre de nitrato noturno). LP 60 mg: 1x/dia pela manhã.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste',
      tfg_lt_15: 'Cautela com hipotensão',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['iPDE5 (sildenafil, tadalafil)', 'Hipotensão', 'Hipovolemia grave', 'Cardiomiopatia obstrutiva'],
    interacoes_importantes: [
      { com: 'iPDE5 (sildenafil, tadalafil)', severidade: 'contraindicado', descricao: 'Hipotensão grave — contraindicado' },
      { com: 'Anti-hipertensivos', severidade: 'moderada', descricao: 'Hipotensão aditiva' },
    ],
    alertas_especiais: [
      'Vantagem vs dinitrato: biodisponibilidade quase completa (> 95%) — sem "first-pass" hepático',
      'TOLERÂNCIA: intervalo assimétrico é obrigatório para formulação convencional',
      'Cefaleia pulsátil: muito comum nas primeiras 1–2 semanas — geralmente cede',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Monocordil®', laboratorio: 'Sanofi', concentracoes: ['20 mg', '40 mg'], formas: ['Comprimido'] },
      { nome: 'ISMN EMS', laboratorio: 'EMS', concentracoes: ['20 mg', '40 mg', '60 mg LP'], formas: ['Comprimido', 'Comprimido LP'] },
    ],
  },

  {
    id: 'ivabradina',
    molecula: 'Ivabradina',
    nome_generico: 'Cloridrato de Ivabradina',
    sinonimos: ['procoralan', 'corlanor', 'ivabradina', 'inibidor if', 'cronotrópico negativo puro'],
    categoria: 'cardiovascular',
    classe: 'Antianginoso',
    subclasse: 'Inibidor da corrente If (canais HCN) no nódulo SA — reduz FC sem inotropia negativa',
    indicacoes_principais: [
      'IC-FEr (FE ≤ 35%, FC ≥ 70 bpm em RS, em dose máxima tolerada de BB) — SHIFT trial',
      'Angina estável crônica sintomática em RS com FC ≥ 70 bpm (intolerante a BB)',
    ],
    dose_adulto: {
      habitual: '5 mg 2x/dia',
      min: '2,5 mg 2x/dia',
      max: '7,5 mg 2x/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2x/dia (com refeições)'],
      instrucoes: 'Iniciar 5 mg 2x/dia. Titular após 2 semanas: FC repouso 50–60 bpm = manutenção; FC > 60 = aumentar para 7,5 mg; FC < 50 ou bradicardia sintomática = reduzir para 2,5 mg.',
    },
    ajuste_renal: {
      normal: '5–7,5 mg 2x/dia',
      tfg_60_30: 'Sem ajuste formal — cautela',
      tfg_30_15: 'Cautela',
      tfg_lt_15: 'Dados insuficientes — usar com cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'FC repouso < 70 bpm antes de iniciar',
      'FA/Flutter (não age em fibrilo) — SÓ funciona em ritmo sinusal',
      'BAV 3º grau',
      'IC aguda descompensada',
      'Inibidores potentes CYP3A4 (cetoconazol, claritromicina, nefazodona)',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'Inibidores CYP3A4 (cetoconazol, claritromicina)', severidade: 'contraindicado', descricao: 'Aumentam ivabradina — bradicardia grave' },
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Bradicardia aditiva — monitorar FC' },
      { com: 'Diltiazem/Verapamil', severidade: 'moderada', descricao: 'Bradicardia — evitar combinação' },
      { com: 'QT-prolongadores', severidade: 'moderada', descricao: 'Bradicardia pode amplificar risco de torsades' },
    ],
    alertas_especiais: [
      'SHIFT trial: redução de 18% em morte CV + hospitalização por IC vs placebo (em adição a beta-bloqueador + IECA + ARM)',
      'FOSFENOS: fenômenos visuais transitórios (flashes luminosos) em ~15% — geralmente benignos, reversíveis',
      'SÓ funciona em ritmo sinusal — completamente ineficaz em FA/Flutter',
      'FC alvo IC: 50–60 bpm em repouso',
      'Metabolismo CYP3A4: evitar suco de toranja (grapefruit)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Procoralan®', laboratorio: 'Servier', concentracoes: ['5 mg', '7,5 mg'], formas: ['Comprimido'] },
      { nome: 'Ivabradina EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '7,5 mg'], formas: ['Comprimido'] },
    ],
  },

];
