// ============================================================
// PRESCREVE-AI — Banco Farmacológico: Neonatologia + Pediatria
// Phase 21.9
// ============================================================

import { QuickDrug } from './pharma-database';

export const PHARMA_DB_PEDIATRIA: QuickDrug[] = [
  // ─── CAFEÍNA CITRATO ──────────────────────────────────────
  {
    id: 'cafeina-citrato',
    molecula: 'cafeína citrato',
    nome_generico: 'Cafeína Citrato',
    sinonimos: ['cafeina', 'caffeine citrate', 'cafeína prematura', 'apneia prematuridade'],
    categoria: 'neonatologia',
    classe: 'Metilxantina',
    indicacoes_principais: ['Apneia da prematuridade', 'Desmame ventilatório em prematuros'],
    dose_adulto: {
      habitual: 'Não aplicável — uso exclusivamente neonatal',
      max: 'Ver dose neonatal',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['1×/dia (manutenção)'],
    },
    dose_pediatrica: {
      calculo: 'mg/kg (cafeína citrato)',
      dose_por_kg: 20,
      unidade: 'mg/kg ataque IV, depois 5–10 mg/kg/dia manutenção',
      frequencia_divisoes: 1,
      max_dose_dia: 20,
      max_dose_dia_unidade: 'mg/kg (ataque único)',
      faixa_etaria: 'Neonatos prematuros 23–32 semanas IG',
      observacao: 'Ataque: 20 mg/kg IV em 30 min. Manutenção a partir de 24h: 5–10 mg/kg/dia. Nível sérico alvo 8–20 mg/L.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade à cafeína'],
    interacoes_importantes: [
      { com: 'fenobarbital', severidade: 'moderada', descricao: 'Fenobarbital induz CYP1A2 → reduz nível de cafeína' },
      { com: 'fluconazol', severidade: 'moderada', descricao: 'Inibe CYP1A2 → aumenta nível de cafeína' },
    ],
    alertas_especiais: [
      'Taquicardia > 180 bpm: reduzir dose',
      'Monitorar glicemia — pode causar hipoglicemia',
      'Retirar gradualmente após 34–36 semanas de idade corrigida',
      'Monitorar nível sérico no D3–D5',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Cafcit (manipulado no Brasil)', laboratorio: 'Manipulação', concentracoes: ['20 mg/mL'], formas: ['Solução injetável'] }],
  },

  // ─── PORACTANT ALFA (SURFACTANTE) ────────────────────────
  {
    id: 'poractant-alfa',
    molecula: 'poractant alfa',
    nome_generico: 'Poractant Alfa',
    sinonimos: ['Curosurf', 'surfactante', 'surfactante pulmonar', 'SDR prematuro', 'surfatante'],
    categoria: 'neonatologia',
    classe: 'Surfactante pulmonar exógeno',
    indicacoes_principais: ['SDR do RN prematuro (tratamento e profilaxia)', 'Síndrome de aspiração de mecônio'],
    dose_adulto: {
      habitual: 'Não aplicável — uso exclusivo neonatal',
      max: '400 mg/kg/dia',
      unidade: 'mg/kg',
      via: 'Intratraqueal',
      frequencias: ['Dose única (+ dose de resgate se necessário)'],
    },
    dose_pediatrica: {
      calculo: 'mg/kg',
      dose_por_kg: 200,
      unidade: 'mg/kg intratraqueal (dose inicial)',
      frequencia_divisoes: 1,
      max_dose_dia: 400,
      max_dose_dia_unidade: 'mg/kg/24h (ataque + 1 resgate)',
      faixa_etaria: 'Neonatos prematuros — primeiras 2h de vida em SDR grave',
      observacao: 'Dose inicial: 100–200 mg/kg. Dose de resgate: 100 mg/kg após 12h se necessário. Técnica LISA/MIST preferível.',
    },
    contraindicacoes_rapidas: ['Malformação congênita incompatível com a vida', 'Hemorragia pulmonar ativa'],
    interacoes_importantes: [
      { com: '(sem interação medicamentosa)', severidade: 'leve', descricao: 'Surfactante pulmonar de uso intratraqueal exclusivo — ação local; nenhuma interação medicamentosa relatada' },
    ],
    alertas_especiais: [
      'Aquecer ao TA por 15–20 min antes de administrar (não agitar)',
      'Bradicardia e dessaturação transitórias: normais, regridem em segundos',
      'Monitorar SpO₂ contínua e raio-X 1–2h após',
      'Instabilidade hemodinâmica: monitorar PA e FC durante administração',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Curosurf', laboratorio: 'Chiesi', concentracoes: ['80 mg/mL'], formas: ['Suspensão intratraqueal 1,5 mL (120 mg) e 3 mL (240 mg)'] }],
  },

  // ─── VITAMINA K1 NEONATAL ────────────────────────────────
  {
    id: 'vitamina-k1-neonatal',
    molecula: 'fitomenadiona',
    nome_generico: 'Fitomenadiona (Vitamina K1)',
    sinonimos: ['vitamina K1', 'kanakion', 'fitomenadiona neonatal', 'profilaxia hemorrágica RN', 'DHRN'],
    categoria: 'neonatologia',
    classe: 'Vitamina lipossolúvel / coagulante',
    indicacoes_principais: ['Profilaxia da Doença Hemorrágica do Recém-Nascido (DHRN)', 'Deficiência de vitamina K neonatal'],
    dose_adulto: {
      habitual: '10 mg/mL — 1 mg IM (profilaxia neonatal)',
      max: '1 mg (dose única profilática RN)',
      unidade: 'mg',
      via: 'IM',
      frequencias: ['Dose única nas primeiras 6h de vida'],
    },
    dose_pediatrica: {
      calculo: 'dose fixa',
      dose_por_kg: 0,
      unidade: 'mg (dose fixa)',
      frequencia_divisoes: 1,
      max_dose_dia: 1,
      max_dose_dia_unidade: 'mg (dose única profilática)',
      faixa_etaria: 'RN a termo: 1 mg IM. Prematuro < 1500 g: 0,5 mg IM',
      observacao: 'Aplicar no vasto lateral da coxa. VO (menor eficácia): 2 mg nas datas D0, D7 e 1 mês.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade conhecida'],
    interacoes_importantes: [
      { com: 'varfarina', severidade: 'moderada', descricao: 'Antagonismo direto (efeito esperado — evitar combinação desnecessária)' },
    ],
    alertas_especiais: [
      'Profilaxia universal obrigatória em todos os RN (SBP/AAP)',
      'IM é superior ao VO para prevenir DHRN de início tardio',
      'Vitamina K1 IM NÃO causa hemólise nas doses recomendadas',
      'Amamentação exclusiva: reservas maternas passam minimamente pelo leite',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Kanakion MM Pediátrico', laboratorio: 'Roche', concentracoes: ['10 mg/mL (2 mg/0,2 mL)'], formas: ['Solução injetável IM/IV'] },
    ],
  },

  // ─── PALIVIZUMABE ────────────────────────────────────────
  {
    id: 'palivizumabe',
    molecula: 'palivizumabe',
    nome_generico: 'Palivizumabe',
    sinonimos: ['Synagis', 'VSR', 'bronquiolite prematuro', 'anti-VSR', 'anti-RSV'],
    categoria: 'neonatologia',
    classe: 'Anticorpo monoclonal humanizado IgG1 anti-VSR',
    indicacoes_principais: [
      'Profilaxia de bronquiolite por VSR em prematuros < 29 sem (1º ano de vida)',
      'DBP em uso de O₂ ou medicação últimas 6 semanas',
      'Cardiopatia congênita hemodinamicamente significativa',
    ],
    dose_adulto: {
      habitual: 'Não aplicável — uso pediátrico',
      max: '15 mg/kg/dose IM mensal',
      unidade: 'mg/kg',
      via: 'IM',
      frequencias: ['1×/mês durante temporada de VSR (5 doses)'],
    },
    dose_pediatrica: {
      calculo: 'mg/kg',
      dose_por_kg: 15,
      unidade: 'mg/kg/dose IM mensal',
      frequencia_divisoes: 1,
      max_dose_dia: 15,
      max_dose_dia_unidade: 'mg/kg/mês',
      faixa_etaria: 'Prematuros < 32 sem (1º ano de vida) | Cardiopatas/DBP (1º ano)',
      observacao: 'Volume > 1 mL: dividir em 2 sítios. Refrigerar 2–8°C. Aplicar no vasto lateral.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade grave a anticorpos monoclonais humanizados'],
    interacoes_importantes: [
      { com: '(sem interação farmacocinética relevante)', severidade: 'leve', descricao: 'Anticorpo monoclonal anti-VSR — sem estudos formais de interação; não interfere na resposta às vacinas de rotina (pode ser coadministrado). Pode interferir em ensaios de cultura viral' },
    ],
    alertas_especiais: [
      'Não é vacina — não confere imunidade ativa',
      'Seguir critérios CONITEC/RENAME para acesso SUS',
      'IMpact Trial 1998: reduz hospitalização por VSR em 55% em prematuros',
      'Dose única mensal — não usar doses adicionais na mesma temporada',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'avaliar',
    marcas: [{ nome: 'Synagis', laboratorio: 'AstraZeneca', concentracoes: ['100 mg/mL'], formas: ['Solução injetável 50 mg e 100 mg'] }],
  },

  // ─── SILDENAFIL NEONATAL (HPPRN) ─────────────────────────
  {
    id: 'sildenafil-neonatal',
    molecula: 'sildenafil',
    nome_generico: 'Sildenafil (Neonatal/Pediátrico)',
    sinonimos: ['Revatio', 'HPPRN', 'hipertensão pulmonar persistente RN', 'HAP pediátrica', 'sildenafil neonatal'],
    categoria: 'neonatologia',
    classe: 'Inibidor da fosfodiesterase-5 (IPDE-5)',
    indicacoes_principais: [
      'Hipertensão Pulmonar Persistente do RN (HPPRN) — off-label',
      'Hipertensão arterial pulmonar pediátrica (Revatio — aprovado)',
    ],
    dose_adulto: {
      habitual: 'HAP: 20 mg 3×/dia (Revatio)',
      max: '20 mg 3×/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3×/dia'],
    },
    dose_pediatrica: {
      calculo: 'mg/kg/dose',
      dose_por_kg: 1,
      unidade: 'mg/kg/dose a cada 6h (neonatal off-label)',
      frequencia_divisoes: 4,
      max_dose_dia: 8,
      max_dose_dia_unidade: 'mg/kg/dia',
      faixa_etaria: 'Neonatos (HPPRN): 0,5–3 mg/kg/dose 6/6h | Crianças (HAP): 10 mg 3×/dia independente do peso > 20 kg',
      observacao: 'HPPRN: iniciar 0,5 mg/kg/dose e titular. Ecocardiograma obrigatório antes. FDA Black Box: dose alta pediátrica (> 2 mg/kg 3×/dia) associada a maior mortalidade.',
    },
    contraindicacoes_rapidas: ['Nitratos (hipotensão grave — contraindicação absoluta)', 'Hipotensão grave', 'Disfunção hepática grave'],
    interacoes_importantes: [
      { com: 'nitratos', severidade: 'contraindicado', descricao: 'Hipotensão grave potencialmente fatal' },
      { com: 'bosentan', severidade: 'moderada', descricao: 'Bosentan reduz nível sérico de sildenafil' },
    ],
    alertas_especiais: [
      'FDA Black Box (Revatio pediátrico): doses altas ↑ mortalidade em HAP pediátrica',
      'HPPRN: uso sob supervisão de neonatologista experiente',
      'Monitorar PA — hipotensão sistêmica é efeito adverso frequente',
      'Ecocardiograma seriado para avaliar resposta ao tratamento',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Revatio', laboratorio: 'Pfizer', concentracoes: ['20 mg'], formas: ['Comprimido', 'Pó para suspensão oral 10 mg/mL'] },
    ],
  },

  // ─── IBUPROFENO (standalone adulto + pediátrico) ─────────
  {
    id: 'ibuprofeno',
    molecula: 'ibuprofeno',
    nome_generico: 'Ibuprofeno',
    sinonimos: ['ibuprofen', 'ibuprofeno pediátrico', 'ibuprofeno gotas', 'Advil', 'Alivium', 'Motrin', 'Caldofen'],
    categoria: 'analgesico',
    classe: 'AINE — Anti-inflamatório Não Esteroidal / Inibidor não seletivo COX-1 e COX-2',
    indicacoes_principais: [
      'Febre (adultos e crianças ≥ 6 meses)',
      'Dor leve a moderada',
      'Dismenorreia',
      'Artrite reumatoide e Artrite Juvenil Idiopática (AJI)',
      'Osteoartrite',
      'Fechamento do canal arterial patente (PCA) — neonatal IV',
    ],
    dose_adulto: {
      habitual: '400–600 mg/dose',
      max: '2400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['6/6h', '8/8h'],
      instrucoes: 'Tomar com alimento. Uso ambulatorial: 200–400 mg SOS. Dose máxima anti-inflamatória: 2400 mg/dia.',
    },
    dose_pediatrica: {
      calculo: 'mg/kg/dose',
      dose_por_kg: 7.5,
      unidade: 'mg/kg/dose',
      frequencia_divisoes: 3,
      max_dose_dia: 40,
      max_dose_dia_unidade: 'mg/kg/dia',
      faixa_etaria: '≥ 6 meses VO | Neonatal: apenas IV em protocolo PCA (D1: 10 mg/kg → D2: 5 mg/kg → D3: 5 mg/kg)',
      observacao: 'Febre: 5–10 mg/kg/dose 6–8/8h (máx 400 mg/dose). AJI: 30–40 mg/kg/dia em 4 doses. CONTRAINDICADO em < 3 meses VO.',
    },
    contraindicacoes_rapidas: [
      '< 3 meses VO',
      'Síndrome de Widal (asma + pólipo + intolerância AINE)',
      'Úlcera péptica ativa / sangramento GI',
      'DRC (ClCr < 30 mL/min)',
      'ICC descompensada',
      'Varicela ativa',
      'Dengue suspeita ou confirmada',
      '3º trimestre de gestação',
    ],
    interacoes_importantes: [
      { com: 'AAS', severidade: 'moderada', descricao: 'Ibuprofeno antagoniza o efeito antiagregante do AAS de baixa dose — tomar AAS ao menos 2h antes' },
      { com: 'metotrexato', severidade: 'grave', descricao: 'Reduz excreção renal de metotrexato → toxicidade aumentada' },
      { com: 'lítio', severidade: 'moderada', descricao: 'Reduz excreção de lítio → toxicidade por lítio' },
      { com: 'anticoagulante', severidade: 'grave', descricao: 'Potencializa efeito anticoagulante + risco GI' },
      { com: 'IECA / BRA', severidade: 'moderada', descricao: 'Reduz eficácia anti-hipertensiva; risco de IRA em DRC' },
    ],
    alertas_especiais: [
      'Varicela: risco de fasceíte necrotizante — CONTRAINDICADO',
      'Dengue: risco de sangramento grave — CONTRAINDICADO',
      'Desidratação: risco de IRA — garantir hidratação adequada',
      'Formulação neonatal IV (PCA): usar apenas em NICU com protocolo específico',
      'Doses pediátricas: gotas 50 mg/mL (1 gota = 2,5 mg); suspensão 100 mg/5 mL',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'seguro',
    ajuste_renal: {
      normal: 'Dose habitual',
      tfg_60_30: 'Usar com cautela — monitorar função renal',
      tfg_30_15: 'Evitar',
      tfg_lt_15: 'CONTRAINDICADO',
      dialisavel: false,
    },
    marcas: [
      { nome: 'Alivium', laboratorio: 'Hypera', concentracoes: ['50 mg/mL gotas', '100 mg/5 mL suspensão', '200 mg', '400 mg', '600 mg'], formas: ['Gotas', 'Suspensão oral', 'Comprimido', 'Cápsula gel'] },
      { nome: 'Advil', laboratorio: 'Haleon (GSK)', concentracoes: ['200 mg', '400 mg', '600 mg'], formas: ['Comprimido revestido', 'Cápsula gel'] },
      { nome: 'Caldofen', laboratorio: 'EMS', concentracoes: ['50 mg/mL gotas', '100 mg/5 mL', '200 mg', '400 mg'], formas: ['Gotas', 'Suspensão oral', 'Comprimido'] },
      { nome: 'Motrin', laboratorio: 'Johnson & Johnson', concentracoes: ['100 mg/5 mL', '200 mg'], formas: ['Suspensão oral', 'Comprimido'] },
    ],
  },

  // ─── FENOBARBITAL NEONATAL IV ─────────────────────────────
  {
    id: 'fenobarbital-neonatal',
    molecula: 'fenobarbital',
    nome_generico: 'Fenobarbital (Convulsão Neonatal)',
    sinonimos: ['gardenal', 'phenobarbital', 'convulsão neonatal', 'EHI', 'epilepsia neonatal', 'fenobarbital IV neonato'],
    categoria: 'neonatologia',
    classe: 'Barbitúrico anticonvulsivante',
    indicacoes_principais: [
      'Convulsões neonatais (1ª linha)',
      'Estado de mal epiléptico neonatal',
      'Encefalopatia hipóxico-isquêmica (EHI) com convulsões',
    ],
    dose_adulto: {
      habitual: 'Ver dose de ataque neonatal — uso off-label',
      max: '40–50 mg/kg (dose total de ataque)',
      unidade: 'mg/kg',
      via: 'IV',
      frequencias: ['Dose de ataque única + manutenção'],
    },
    dose_pediatrica: {
      calculo: 'mg/kg (ataque IV)',
      dose_por_kg: 20,
      unidade: 'mg/kg ataque IV',
      frequencia_divisoes: 1,
      max_dose_dia: 40,
      max_dose_dia_unidade: 'mg/kg/dia (dose total de ataque)',
      faixa_etaria: 'Neonatos (0–28 dias): ataque 20 mg/kg IV → manutenção 3–5 mg/kg/dia em 1–2 doses',
      observacao: 'Velocidade máxima: 1 mg/kg/min IV. Doses adicionais se crise persiste: 5–10 mg/kg (máx 40–50 mg/kg total ataque). DIFERENTE do regime oral de epilepsia em criança maior.',
    },
    contraindicacoes_rapidas: ['Porfiria aguda intermitente', 'Hipersensibilidade a barbitúricos', 'Depressão respiratória grave sem suporte ventilatório'],
    interacoes_importantes: [
      { com: 'valproato', severidade: 'moderada', descricao: 'Valproato inibe metabolismo do fenobarbital → acúmulo' },
      { com: 'fenitoína', severidade: 'moderada', descricao: 'Interação bidirecional complexa — monitorar níveis séricos de ambos' },
    ],
    alertas_especiais: [
      'DEPRESSÃO RESPIRATÓRIA: ter equipamento de ventilação disponível antes de administrar',
      'Extravasamento IV: necrose tecidual grave (pH 9,5) — verificar acesso antes da infusão',
      'Nível sérico alvo: 20–40 mcg/mL (neonatal)',
      'Hipotensão: infundir lentamente (máx 1 mg/kg/min)',
      'Descontinuação gradual — síndrome de abstinência se retirada brusca',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Gardenal', laboratorio: 'Sanofi', concentracoes: ['40 mg/mL IV', '100 mg/mL IV'], formas: ['Solução injetável'] },
    ],
  },
];
