// ============================================================
// PRESCREVE-AI — Extensão Farmacológica: NEUROLOGIA + PSIQUIATRIA (Phase 21.7) — Parte B
// Anticonvulsivantes · Antidemenciais · Estabilizadores de humor · Hipnóticos · Ansiolíticos
// Campos adicionais: beers_criteria · stopp · start · pgx_genes
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_NEURO_B: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════════
  // ANTICONVULSIVANTES / ANTIEPILÉPTICOS
  // (topiramato e levetiracetam já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'fenitoina',
    guidelines_referencia: ['ILAE — antiepileptico; status epilepticus'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Fenitoína',
    nome_generico: 'Fenitoína',
    sinonimos: ['hidantal', 'phenytoin', 'fenitoina', 'difenil-hidantoina', 'anticonvulsivante', 'status epilepticus'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Hidantoína — bloqueio de canais de Na+ voltagem-dependentes — farmacocinética NÃO-LINEAR',
    indicacoes_principais: [
      'Epilepsia focal e generalizada (tonico-clônica)',
      'Status epilepticus (IV — 2ª escolha após BZD)',
      'Profilaxia de convulsões pós-neurocirurgia',
      'Neuralgia do trigêmeo (off-label)',
    ],
    dose_adulto: {
      habitual: '300–400 mg/dia VO em 1–3 tomadas',
      min: '200 mg/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–3×/dia (com alimento)'],
      instrucoes: 'NÍVEL SÉRICO OBRIGATÓRIO: alvo 10–20 mcg/mL (livre: 1–2 mcg/mL). Farmacocinética não-linear (Michaelis-Menten): pequenos aumentos de dose → grandes aumentos de nível. Status epilepticus IV: 15–20 mg/kg em 50 mL SF, velocidade máx 50 mg/min. NÃO usar em glicose (precipita).',
    },
    ajuste_renal: { normal: '300–400 mg/dia', tfg_60_30: 'Monitorar nível livre (hipoproteínemia)', tfg_30_15: 'Monitorar nível livre', tfg_lt_15: 'Dosar fração livre (albumina reduzida altera)', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose — metabolismo hepático reduzido', child_b: 'Monitorar níveis', child_c: 'Contraindicado ou dose mínima' },
    contraindicacoes_rapidas: ['Bradicardia sinusal', 'Bloqueio SA ou AV', 'Síndrome de Adams-Stokes', 'Hipersensibilidade a hidantoínas'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'Inibição/indução CYP2C9 — efeito bifásico: aumenta depois reduz INR — monitorar INR intensivamente' },
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'Indução CYP3A4 — reduz níveis de contraceptivo → falha contraceptiva' },
      { com: 'Fluconazol / isoniazida', severidade: 'grave', descricao: 'Inibição CYP2C9 → fenitoína aumenta → toxicidade (ataxia, nistagmo, diplopia)' },
      { com: 'Ácido valproico', severidade: 'moderada', descricao: 'Desloca fenitoína da albumina → aumenta fração livre; também inibe metabolismo' },
      { com: 'Carbamazepina', severidade: 'moderada', descricao: 'Indução recíproca — monitorar níveis de ambos' },
    ],
    alertas_especiais: [
      'FARMACOCINÉTICA NÃO-LINEAR: aumentos de dose acima de 350–400 mg/dia podem causar toxicidade súbita (nistagmo, ataxia, confusão)',
      'BEERS 2023: cautela em idosos — toxicidade neurológica, interações, indução enzimática',
      'SÍNDROME DE HIPERSENSIBILIDADE: febre, rash, linfadenopatia, hepatite — suspender imediatamente',
      'INDUÇÃO ENZIMÁTICA: reduz eficácia de anticoagulantes, ACO, antivirais HIV, corticoides',
      'IV: monitorar PA e ECG — infusão rápida causa hipotensão grave e arritmias',
      'HLA-B*15:02: síndrome de Stevens-Johnson em asiáticos — testar antes em populações de risco',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — toxicidade com doses usuais; farmacocinética não-linear aumenta risco em idosos',
    stopp: 'STOPP N1: anticonvulsivante de 1ª geração em idoso — maior risco de toxicidade neurológica e quedas',
    pgx_genes: ['CYP2C9 (PM: metabolismo reduzido → toxicidade com doses usuais)', 'CYP2C19 (metabolismo)', 'HLA-B*15:02 (Stevens-Johnson em asiáticos)', 'HLA-A*31:01 (reação cutânea)'],
    marcas: [
      { nome: 'Hidantal®', laboratorio: 'Sanofi', concentracoes: ['100 mg comprimido', '50 mg/mL injetável'], formas: ['Comprimido', 'Ampola IV/IM'] },
      { nome: 'Fenitoína EMS', laboratorio: 'EMS', concentracoes: ['100 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'carbamazepina',
    guidelines_referencia: ['ILAE — 1a linha na epilepsia focal'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Carbamazepina',
    nome_generico: 'Carbamazepina',
    sinonimos: ['tegretol', 'carbamazepine', 'carbamazepina', 'anticonvulsivante cbz', 'estabilizador bipolar', 'neuralgia trigemeo'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Dibenzazepina — bloqueio canais Na+ + estabilizador de humor — forte indutor enzimático',
    indicacoes_principais: [
      'Epilepsia focal (1ª linha) e tonico-clônica',
      'Transtorno bipolar — fase maníaca (2ª linha após lítio/valproato)',
      'Neuralgia do trigêmeo (1ª linha farmacológica)',
      'Neuropatia diabética (off-label)',
    ],
    dose_adulto: {
      habitual: '400–1200 mg/dia VO em 2–4 tomadas',
      min: '200 mg/dia',
      max: '1600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–4×/dia (CR: 2×/dia)'],
      instrucoes: 'Iniciar 100–200 mg/dia, aumentar 100–200 mg a cada 1–2 semanas. Nível sérico alvo: 4–12 mcg/mL. AUTOINDUTOR: níveis caem nas primeiras semanas (induz próprio metabolismo).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Cautela', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Histórico de aplasia medular ou agranulocitose', 'IMAO (últimas 2 semanas)', 'Hipersensibilidade tricíclicos', 'Deficiência de P450 2C8 (interação severa com voriconazol)'],
    interacoes_importantes: [
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'Forte indutor CYP3A4 → falha contraceptiva. Usar método não-hormonal ou DIU' },
      { com: 'Varfarina / anticoagulantes', severidade: 'grave', descricao: 'Indução CYP2C9 → reduz INR → trombose' },
      { com: 'Antirretrovirais HIV (IPs, NNRTIs)', severidade: 'grave', descricao: 'Indução → falha terapêutica antiretroviral' },
      { com: 'Voriconazol', severidade: 'contraindicado', descricao: 'Indução de CYP → voriconazol indetectável; voriconazol também inibe metabolismo da CBZ' },
      { com: 'Lítio', severidade: 'moderada', descricao: 'Sinergia terapêutica bipolar; neurotoxicidade aditiva' },
    ],
    alertas_especiais: [
      'HLA-B*15:02: síndrome de Stevens-Johnson/NET potencialmente fatal em asiáticos — TESTAR ANTES em populações de risco (tailandeses, chineses, malaios, filipinos)',
      'HLA-A*31:01: DRESS e SJS em europeus',
      'AUTOINDUTOR: nível sérico cai após 2–4 semanas → reavaliar dose',
      'HIPONATREMIA: SIADH — monitorar sódio, especialmente em idosos',
      'Beers: cautela em idosos — SIADH, interações, quedas',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — SIADH, interações medicamentosas extensas, sedação, quedas',
    stopp: 'STOPP N1: anticonvulsivante 1ª geração em idoso com hiponatremia ou risco de queda',
    pgx_genes: ['HLA-B*15:02 (Stevens-Johnson — asiáticos)', 'HLA-A*31:01 (DRESS/SJS — europeus)', 'CYP2C8 (metabolismo do CBZ-epóxido)', 'CYP3A4 (autoindutor)'],
    marcas: [
      { nome: 'Tegretol®', laboratorio: 'Novartis', concentracoes: ['200 mg', '400 mg CR'], formas: ['Comprimido', 'Comprimido CR (liberação controlada)'], lab_id: 'novartis' },
      { nome: 'Carbamazepina EMS', laboratorio: 'EMS', concentracoes: ['200 mg', '400 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'acido-valproico',
    guidelines_referencia: ['ILAE — 1a linha na epilepsia generalizada (evitar em gestante)'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Ácido Valproico / Valproato de Sódio',
    nome_generico: 'Ácido Valproico',
    sinonimos: ['depakene', 'depakote', 'valproate', 'valproato', 'valproico', 'anticonvulsivante vpa', 'estabilizador bipolar valproato', 'enxaqueca profilaxia valproato'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Ácido carboxílico — mecanismo múltiplo: bloqueia canais Na+, aumenta GABA, inibe HDAC',
    indicacoes_principais: [
      'Epilepsia — amplo espectro (todas as formas, incluindo ausência, mioclônica)',
      'Transtorno bipolar — mania aguda e profilaxia (1ª linha)',
      'Enxaqueca (profilaxia)',
      'Depressão bipolar (adjuvante)',
    ],
    dose_adulto: {
      habitual: '500–1500 mg/dia em 2–3 tomadas',
      min: '250 mg/dia',
      max: '3000 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (IR) | 1–2×/dia (DR/LP)'],
      instrucoes: 'Nível sérico alvo epilepsia: 50–100 mcg/mL; bipolar: 50–125 mcg/mL. Formas: ácido valpróico (Depakene), valproato de sódio (Epilim), divalproato (Depakote DR). Tomar com alimento.',
    },
    ajuste_renal: { normal: 'Sem ajuste (ligação proteica — dosar fração livre em DRC)', tfg_60_30: 'Monitorar nível livre', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Reduzir dose', dialisavel: true },
    ajuste_hepatico: { child_a: 'Contraindicado (hepatotóxico — suspeita de mitocondriopatia)', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Hepatopatia ou disfunção hepática grave',
      'Deficiência de urea cycle (ciclo da ureia)',
      'GRAVIDEZ — especialmente 1º trimestre (espinha bífida, malformações, déficit neurocognitivo)',
      'Porfiria',
    ],
    interacoes_importantes: [
      { com: 'Carbamazepina', severidade: 'moderada', descricao: 'Eleva epóxido-CBZ (metabólito tóxico) — toxicidade da carbamazepina' },
      { com: 'Lamotrigina', severidade: 'grave', descricao: 'Inibe glucuronidação da lamotrigina → duplica nível → SJS/rash grave — reduzir lamotrigina 50% ao combinar' },
      { com: 'Fenitoína', severidade: 'moderada', descricao: 'Desloca fenitoína da albumina — aumenta fração livre' },
      { com: 'Aspirina (altas doses)', severidade: 'moderada', descricao: 'Desloca valproato — aumenta fração livre' },
    ],
    alertas_especiais: [
      'TERATOGENICIDADE: BLACK BOX — risco de espinha bífida 1–2%, outras malformações cardíacas, neurocognitivas. EVITAR em mulheres em idade fértil sem contracepção dupla eficaz',
      'HEPATOTOXICIDADE: potencialmente fatal, especialmente em < 2 anos com polifarmácia antiepiléptica — monitorar TGO/TGP',
      'PANCREATITE: rara mas grave — dor abdominal → suspender',
      'HIPERAMONEMIA: mesmo com TGP normal — monitorar em letargia pós-início',
      'Beers: EVITAR em idosos com trombocitopenia ou hepatopatia',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: cautela em idosos — trombocitopenia, hepatotoxicidade, sedação',
    stopp: 'STOPP N2: valproato em mulher em idade fértil sem dupla contracepção confirmada',
    start: 'START C4: valproato em bipolar com mania grave sem resposta a lítio',
    pgx_genes: ['POLG (polimerase gama mitocondrial — síndrome de Alpers: contraindicado)', 'UGT (glucuronidação — interação com lamotrigina)'],
    marcas: [
      { nome: 'Depakene®', laboratorio: 'Abbott/AbbVie', concentracoes: ['250 mg', '500 mg'], formas: ['Cápsula', 'Solução oral'] },
      { nome: 'Depakote®', laboratorio: 'Abbott/AbbVie', concentracoes: ['250 mg', '500 mg DR'], formas: ['Comprimido DR (divalproato)'] },
      { nome: 'Valproato EMS', laboratorio: 'EMS', concentracoes: ['250 mg', '500 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'lamotrigina',
    guidelines_referencia: ['ILAE — antiepileptico (focal; estabilizador no TB)'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Lamotrigina',
    nome_generico: 'Lamotrigina',
    sinonimos: ['lamictal', 'lamotrigine', 'lamotrigina', 'anticonvulsivante lam', 'bipolar depressão lamotrigina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Fenilamina — bloqueio canais Na+/Ca2+ — primeira escolha em epilepsia focal em mulheres em idade fértil',
    indicacoes_principais: [
      'Epilepsia focal e generalizada (1ª linha mulheres em idade fértil)',
      'Epilepsia de ausência (adjuvante)',
      'Transtorno bipolar — manutenção (especialmente prevenção depressão bipolar)',
      'Síndrome de Lennox-Gastaut (adjuvante)',
    ],
    dose_adulto: {
      habitual: '100–200 mg/dia em monoterapia | 50–100 mg/dia com valproato | 300–500 mg/dia com indutores enzimáticos',
      min: '25 mg/dia',
      max: '700 mg/dia (com indutores)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–2×/dia'],
      instrucoes: 'TITULAÇÃO LENTA OBRIGATÓRIA: iniciar 25 mg a cada 2 dias (com valproato) ou 25 mg/dia (monoterapia) × 2 semanas → aumentar MUITO devagar (rash SJS depende da velocidade). Interação valproato: duplica nível de lamotrigina → reduzir dose 50%.',
    },
    ajuste_renal: { normal: 'Sem ajuste em DRC leve', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Reduzir dose (acúmulo metabólito)', tfg_lt_15: 'Reduzir dose significativamente', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir 25%', child_c: 'Reduzir 50%' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Histórico de rash grave com lamotrigina'],
    interacoes_importantes: [
      { com: 'Valproato', severidade: 'grave', descricao: 'Inibe glucuronidação → dobra nível de lamotrigina → SJS. REDUZIR DOSE pela metade ao adicionar valproato' },
      { com: 'Carbamazepina / fenitoína / rifampicina (indutores)', severidade: 'moderada', descricao: 'Aumentam metabolismo → lamotrigina cai → perda de eficácia. Dobrar dose quando associado' },
      { com: 'Contraceptivos orais (estrógeno)', severidade: 'moderada', descricao: 'Estrogênio aumenta glucuronidação → lamotrigina cai 50% → perda de controle de crises' },
    ],
    alertas_especiais: [
      'RASH/SJS: titulação MUITO lenta é mandatória — rash grave nas primeiras 8 semanas, especialmente com valproato e titulação rápida',
      'ANTICONVULSIVANTE PREFERIDO EM MULHERES GRÁVIDAS (menor teratogenicidade vs valproato/carbamazepina) — mas monitorar níveis na gravidez (metabolismo aumenta)',
      'BIPOLAR: melhor evidência para prevenção de depressão bipolar (vs lítio que previne mania)',
      'Menor sedação que CBZ/VPA — não prejudica cognição',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    beers_criteria: 'Beers 2023: não listado especificamente — melhor tolerabilidade em idosos vs CBZ/VPA',
    pgx_genes: ['UGT1A4 (glucuronidação — interações com valproato e ACO)', 'SCN1A (resposta — epilepsia Dravet)'],
    marcas: [
      { nome: 'Lamictal®', laboratorio: 'GSK', concentracoes: ['25 mg', '50 mg', '100 mg', '200 mg'], formas: ['Comprimido', 'Comprimido dispersível'] },
      { nome: 'Lamotrigina EMS', laboratorio: 'EMS', concentracoes: ['25 mg', '50 mg', '100 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'gabapentina',
    guidelines_referencia: ['NeuPSIG — 1a linha na dor neuropatica'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    indicacao_contexto: 'Epilepsia / dor neuropática (geral)',
    molecula: 'Gabapentina',
    nome_generico: 'Gabapentina',
    sinonimos: ['neurontin', 'gabapentin', 'gabapentina', 'anticonvulsivante neuropatia', 'dor neuropatica gabapentina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Análogo do GABA — liga-se à subunidade α2δ-1 dos canais de Ca2+ voltagem-dependentes',
    indicacoes_principais: [
      'Epilepsia focal (adjuvante)',
      'Neuropatia diabética dolorosa',
      'Neuralgia pós-herpética',
      'Síndrome das pernas inquietas (off-label — dose baixa)',
      'Dor crônica, fibromialgia (off-label)',
      'Abstinência alcoólica (off-label)',
    ],
    dose_adulto: {
      habitual: '300–1800 mg/dia em 3 tomadas iguais',
      min: '100–300 mg/dia',
      max: '3600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3×/dia (TID — meia-vida curta)'],
      instrucoes: 'Iniciar 100–300 mg 3×/dia. Titular a cada 3–7 dias. Neuropatia: 1800–3600 mg/dia. Ajuste RENAL OBRIGATÓRIO (excreção renal intacta). Absorção não-linear: doses acima de 600 mg/dose têm absorção proporcionalmente menor.',
    },
    ajuste_renal: { normal: '300–1200 mg TID', tfg_60_30: '200–700 mg TID', tfg_30_15: '200–700 mg BID', tfg_lt_15: '100–300 mg diário', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste (não metabolizada)', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Pancreatite aguda (relatos)'],
    interacoes_importantes: [
      { com: 'Opioides', severidade: 'grave', descricao: 'Depressão respiratória aditiva — risco de morte. Combinação cada vez mais associada a overdose fatal' },
      { com: 'Antiácidos (alumínio/magnésio)', severidade: 'leve', descricao: 'Reduz absorção de gabapentina em 20% — separar por 2h' },
      { com: 'Álcool / BZD / outros depressores SNC', severidade: 'moderada', descricao: 'Sedação aditiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: cautela em idosos — sedação, tontura, quedas, ataxia',
      'POTENCIAL DE ABUSO: classificada como substância controlada em vários estados/países — uso recreativo crescente',
      'OPIOIDES + GABAPENTINA: combinação de alto risco — depressão respiratória fatal documentada',
      'AJUSTE RENAL CRÍTICO: eliminação 100% renal — toxicidade em DRC sem ajuste',
      'Não possui interações CYP (sem metabolismo hepático) — vantagem em polifarmácia',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — sedação e risco de queda; reduzir dose em DRC',
    stopp: 'STOPP N3: gabapentina/pregabalina em idoso com TFG < 30 sem ajuste de dose',
    pgx_genes: [],
    marcas: [
      { nome: 'Neurontin®', laboratorio: 'Pfizer', concentracoes: ['100 mg', '300 mg', '400 mg'], formas: ['Cápsula'], lab_id: 'pfizer' },
      { nome: 'Gabapentina EMS', laboratorio: 'EMS', concentracoes: ['300 mg', '400 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'pregabalina',
    guidelines_referencia: ['NeuPSIG — 1a linha na dor neuropatica'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Pregabalina',
    nome_generico: 'Pregabalina',
    sinonimos: ['lyrica', 'pregabalin', 'pregabalina', 'anticonvulsivante neuropatia pregabalina', 'fibromialgia lyrica', 'ansiedade pregabalina'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Análogo do GABA — liga α2δ-1 — absorção LINEAR (diferente da gabapentina)',
    indicacoes_principais: [
      'Neuropatia diabética dolorosa',
      'Neuralgia pós-herpética',
      'Fibromialgia (aprovado FDA)',
      'Epilepsia focal (adjuvante)',
      'Transtorno de ansiedade generalizada (aprovado EMA — fora do Brasil oficialmente)',
      'Dor de medula espinhal',
    ],
    dose_adulto: {
      habitual: '75–150 mg VO 2×/dia',
      min: '25 mg/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia'],
      instrucoes: 'Iniciar 75 mg 2×/dia. Titular a cada semana. Ansiedade: 150–600 mg/dia. Vantagem sobre gabapentina: absorção linear → mais previsível. Desmame gradual (convulsões de retirada).',
    },
    ajuste_renal: { normal: '150–600 mg/dia', tfg_60_30: '75–300 mg/dia', tfg_30_15: '25–150 mg/dia', tfg_lt_15: '25–75 mg/dia', dialisavel: true },
    ajuste_hepatico: { child_a: 'Sem ajuste (não metabolizada)', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Angioedema prévio com pregabalina'],
    interacoes_importantes: [
      { com: 'Opioides', severidade: 'grave', descricao: 'Depressão respiratória aditiva — combinação de alto risco' },
      { com: 'BZD / álcool', severidade: 'moderada', descricao: 'Sedação aditiva' },
      { com: 'Tiazolidinedionas (pioglitazona)', severidade: 'leve', descricao: 'Edema periférico aditivo' },
    ],
    alertas_especiais: [
      'SUBSTÂNCIA CONTROLADA: Portaria 344/98 — lista C1. Potencial de abuso elevado',
      'BEERS 2023: cautela em idosos — sedação e risco de queda; dose reduzida',
      'ANGIOEDEMA: risco de angioedema — suspender se inchaço facial/língua',
      'GANHO DE PESO: efeito adverso frequente com uso crônico',
      'Vantagem vs gabapentina: 2×/dia, absorção linear, mais estudada em TAG',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — sedação, quedas, ajuste renal necessário',
    stopp: 'STOPP N3: pregabalina em idoso com TFG < 30 sem ajuste',
    pgx_genes: [],
    marcas: [
      { nome: 'Lyrica®', laboratorio: 'Pfizer', concentracoes: ['25 mg', '75 mg', '150 mg', '300 mg'], formas: ['Cápsula'], lab_id: 'pfizer' },
      { nome: 'Pregabalina EMS', laboratorio: 'EMS', concentracoes: ['75 mg', '150 mg', '300 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'oxcarbazepina',
    guidelines_referencia: ['ILAE — epilepsia focal'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Oxcarbazepina',
    nome_generico: 'Oxcarbazepina',
    sinonimos: ['trileptal', 'oxcarbazepine', 'oxcarbazepina', 'anticonvulsivante trileptal', 'cbz analogia'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Ceto-análogo da carbamazepina — sem epóxido ativo — menos interações que CBZ',
    indicacoes_principais: [
      'Epilepsia focal (mono ou politerapia)',
      'Neuralgia do trigêmeo (alternativa à carbamazepina)',
    ],
    dose_adulto: {
      habitual: '600–1200 mg/dia em 2 tomadas',
      min: '300 mg/dia',
      max: '2400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/dia'],
      instrucoes: 'Iniciar 150–300 mg 2×/dia. Aumentar 150–300 mg a cada semana. Vantagem sobre carbamazepina: sem metabólito epóxido ativo, menos interações, sem autoindutor. Monitorar sódio (SIADH frequente).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Iniciar com 50% da dose usual', tfg_30_15: 'Reduzir 50% — cautela', tfg_lt_15: 'Não recomendado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: ['Hipersensibilidade à carbamazepina (15–25% cross-reatividade)', 'HLA-B*15:02 (asiáticos — risco SJS)'],
    interacoes_importantes: [
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'Indução moderada CYP3A4 → falha contraceptiva' },
      { com: 'Fenitoína', severidade: 'moderada', descricao: 'Aumenta nível de fenitoína — monitorar' },
    ],
    alertas_especiais: [
      'HIPONATREMIA: mais frequente que com CBZ — monitorar Na+ especialmente em idosos e com diuréticos',
      'HLA-B*15:02: testar em asiáticos (SJS) — menor risco que CBZ mas existe',
      'Vantagem: sem autoindutor, menos interações CYP que CBZ',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: cautela em idosos — SIADH/hiponatremia',
    stopp: 'STOPP N1: anticonvulsivante que causa hiponatremia em idoso já hiponatrêmico',
    pgx_genes: ['HLA-B*15:02 (SJS em asiáticos)', 'HLA-A*31:01 (rash em europeus)'],
    marcas: [
      { nome: 'Trileptal®', laboratorio: 'Novartis', concentracoes: ['150 mg', '300 mg', '600 mg'], formas: ['Comprimido', 'Suspensão oral'], lab_id: 'novartis' },
      { nome: 'Oxcarbazepina EMS', laboratorio: 'EMS', concentracoes: ['300 mg', '600 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'fenobarbital',
    indicacao_contexto: 'Epilepsia (geral)',
    molecula: 'Fenobarbital',
    nome_generico: 'Fenobarbital',
    sinonimos: ['gardenal', 'phenobarbital', 'fenobarbital', 'barbiturico anticonvulsivante', 'gardenal epilepsia'],
    categoria: 'neurologico',
    classe: 'Anticonvulsivante',
    subclasse: 'Barbitúrico — potencializa GABA-A (aumenta duração de abertura do canal Cl-)',
    indicacoes_principais: [
      'Epilepsia — amplo espectro (não auência pura)',
      'Status epilepticus (IV — 3ª linha após BZD e fenitoína)',
      'Abstinência alcoólica grave',
      'Convulsões neonatais',
      'Hiperbilirrubinemia neonatal (indução UGT)',
    ],
    dose_adulto: {
      habitual: '60–180 mg/dia VO (1×/dia à noite)',
      min: '30 mg/dia',
      max: '240 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (meia-vida longa 50–144h) — noite pela sedação'],
      instrucoes: 'Nível sérico alvo: 15–40 mcg/mL. Status epilepticus IV: 15–20 mg/kg em 30 min (máx 100 mg/min). Tolerância à sedação em semanas. FORTE indutor enzimático (CYP2C9, 2C19, 3A4, UGT).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: true },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Porfiria intermitente aguda', 'Depressão respiratória grave', 'Hipersensibilidade a barbitúricos'],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'grave', descricao: 'Indução CYP2C9 → reduz INR → trombose' },
      { com: 'Contraceptivos orais', severidade: 'grave', descricao: 'Indução → falha contraceptiva' },
      { com: 'Corticoides', severidade: 'moderada', descricao: 'Indução → reduz eficácia de corticoide' },
      { com: 'BZD / álcool', severidade: 'moderada', descricao: 'Depressão SNC aditiva — perigoso em overdose' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — sedação excessiva, queda, tolerância e dependência',
      'FORTE INDUTOR ENZIMÁTICO: múltiplas interações — varfarina, ACO, antiretrovirais, antibióticos, imunossupressores',
      'DEPENDÊNCIA FÍSICA: síndrome de abstinência grave (convulsões) — nunca suspender abruptamente',
      'SEDAÇÃO: tolerância à sedação em 2–4 semanas; tolerância à eficácia anticonvulsivante NÃO ocorre',
      'Déficit cognitivo crônico especialmente em crianças — evitar em pediatria',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — risco de sedação, dependência, quedas',
    stopp: 'STOPP N1: fenobarbital em idoso com risco de queda ou demência',
    pgx_genes: ['CYP2C9 (metabolismo e indução)', 'CYP2C19 (indução)'],
    marcas: [
      { nome: 'Gardenal®', laboratorio: 'Sanofi', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
      { nome: 'Fenocris®', laboratorio: 'Cristália', concentracoes: ['40 mg/mL solução injetável'], formas: ['Ampola IV'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIDEMENCIAIS
  // (donepezila e memantina já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'rivastigmina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Rivastigmina',
    nome_generico: 'Tartarato de Rivastigmina',
    sinonimos: ['exelon', 'rivastigmine', 'rivastigmina', 'antidemencial patch', 'alzheimer rivastigmina', 'parkinson demencia'],
    categoria: 'neurologico',
    classe: 'Antidemencial',
    subclasse: 'Inibidor da acetilcolinesterase E butirrilcolinesterase (pseudo-irreversível)',
    indicacoes_principais: [
      'Doença de Alzheimer leve a moderada',
      'Demência da doença de Parkinson (única aprovada especificamente)',
      'Demência com corpos de Lewy (off-label)',
    ],
    dose_adulto: {
      habitual: '4,6 mg/24h patch (iniciar) → 9,5 mg/24h → 13,3 mg/24h | VO: 1,5–6 mg 2×/dia',
      min: '4,6 mg/24h patch | 1,5 mg VO 2×/dia',
      max: '13,3 mg/24h patch | 12 mg/dia VO',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['Patch: 1×/dia (trocar a cada 24h) | VO: 2×/dia com alimento'],
      instrucoes: 'PATCH preferível: menor incidência de náuseas/vômitos (liberação gradual). Aplicar em costas, ombros ou parte superior do braço (não seios, virilha ou abdome). Titular patch a cada 4 semanas. Rivastigmina: única aprovada em demência de Parkinson.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela — reduzir dose', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Reação cutânea grave ao patch anterior', 'Doença do nó sinusal ou bloqueio AV'],
    interacoes_importantes: [
      { com: 'Anticolinérgicos (biperideno, oxibutinina, amitriptilina)', severidade: 'moderada', descricao: 'Efeito antagonista — reduz eficácia da rivastigmina' },
      { com: 'Betabloqueadores / outros bradicardizantes', severidade: 'moderada', descricao: 'Bradicardia sinérgica' },
      { com: 'Succinilcolina (cirurgia)', severidade: 'moderada', descricao: 'Prolonga bloqueio neuromuscular — informar anestesista' },
    ],
    alertas_especiais: [
      'ÚNICA APROVADA EM DEMÊNCIA DE PARKINSON — donepezila pode piorar sintomas extrapiramidais em Parkinson',
      'NÁUSEAS/VÔMITOS: principal motivo de abandono. Patch reduz em 70% vs VO',
      'Não misturar patches (risco de superdose colinérgica)',
      'START: considerar IChE em Alzheimer leve-moderado (evidência forte)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: uso apropriado em Alzheimer/demência Parkinson — não listado como inapropriado',
    start: 'START B7: inibidor da colinesterase em demência de Alzheimer ou Parkinson leve a moderada',
    pgx_genes: ['BCHE (butirrilcolinesterase — variante K: reduz eficácia; variante A: deficiência — toxicidade)'],
    marcas: [
      { nome: 'Exelon® Patch', laboratorio: 'Novartis', concentracoes: ['4,6 mg/24h', '9,5 mg/24h', '13,3 mg/24h'], formas: ['Adesivo transdérmico'], lab_id: 'novartis' },
      { nome: 'Exelon® cápsulas', laboratorio: 'Novartis', concentracoes: ['1,5 mg', '3 mg', '4,5 mg', '6 mg'], formas: ['Cápsula'] },
      { nome: 'Rivastigmina EMS', laboratorio: 'EMS', concentracoes: ['1,5 mg', '3 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'galantamina',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Galantamina',
    nome_generico: 'Bromidrato de Galantamina',
    sinonimos: ['reminyl', 'galantamine', 'galantamina', 'antidemencial galantamina', 'alzheimer galantamina'],
    categoria: 'neurologico',
    classe: 'Antidemencial',
    subclasse: 'Inibidor da AChE + modulador alostérico dos receptores nicotínicos (ação dupla)',
    indicacoes_principais: [
      'Doença de Alzheimer leve a moderada',
    ],
    dose_adulto: {
      habitual: '8–16 mg/dia LP (1×/dia) | 4–12 mg 2×/dia (IR)',
      min: '4 mg 2×/dia (IR) | 8 mg/dia (LP)',
      max: '24 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['LP: 1×/dia (manhã) | IR: 2×/dia com alimento'],
      instrucoes: 'Titular lentamente (menor risco GI). LP: preferir por comodidade posológica. Não aprovada em demência vascular ou demência de Parkinson (ao contrário de rivastigmina).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Máx 16 mg/dia', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Máx 16 mg/dia', child_b: 'Máx 8 mg/dia', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['DRC grave (TFG < 9)', 'Insuficiência hepática grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Anticolinérgicos', severidade: 'moderada', descricao: 'Antagonismo — reduz eficácia' },
      { com: 'Paroxetina / fluoxetina (CYP2D6)', severidade: 'moderada', descricao: 'Inibição CYP2D6 e 3A4 → galantamina aumenta → náuseas/vômitos' },
      { com: 'Cetoconazol / eritromicina (CYP3A4)', severidade: 'moderada', descricao: 'Aumenta galantamina → mais efeitos GI' },
    ],
    alertas_especiais: [
      'AÇÃO DUAL: IChE + nicotínico — potencialmente sinérgico, mas diferença clínica vs donepezila é pequena',
      'START: indicado em Alzheimer leve-moderado como antidemencial',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    start: 'START B7: inibidor da colinesterase em demência de Alzheimer leve-moderada',
    pgx_genes: ['CYP2D6 (PM: galantamina aumenta → mais efeitos GI)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Reminyl®', laboratorio: 'Janssen', concentracoes: ['4 mg', '8 mg', '12 mg'], formas: ['Comprimido'] },
      { nome: 'Reminyl® LP', laboratorio: 'Janssen', concentracoes: ['8 mg', '16 mg', '24 mg'], formas: ['Cápsula LP'] },
      { nome: 'Galantamina EMS', laboratorio: 'EMS', concentracoes: ['4 mg', '8 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // HIPNÓTICOS
  // (zolpidem já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'zopiclona',
    molecula: 'Zopiclona',
    nome_generico: 'Zopiclona',
    sinonimos: ['imovane', 'zopiclone', 'zopiclona', 'hipnotico z-drug', 'insonia zopiclona'],
    categoria: 'psiquiatria',
    classe: 'Hipnótico',
    subclasse: 'Ciclopirrolona (Z-drug) — agonista do receptor GABA-A no sítio BZD (diferente da estrutura BZD)',
    indicacoes_principais: [
      'Insônia aguda (≤ 4 semanas)',
    ],
    dose_adulto: {
      habitual: '7,5 mg VO antes de dormir',
      min: '3,75 mg (idosos — INICIAR aqui)',
      max: '7,5 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia (antes de dormir)'],
      instrucoes: 'USO MÁXIMO 4 SEMANAS. Idosos: iniciar 3,75 mg (Beers). Sabor amargo (gosto metálico característico). Não associar a álcool. Efeito residual matutino comum (cautela ao dirigir).',
    },
    ajuste_renal: { normal: '7,5 mg', tfg_60_30: '3,75–7,5 mg', tfg_30_15: '3,75 mg', tfg_lt_15: '3,75 mg — cautela', dialisavel: false },
    ajuste_hepatico: { child_a: '3,75 mg', child_b: '3,75 mg', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'Insuficiência respiratória grave', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Álcool / BZD / opioides', severidade: 'grave', descricao: 'Depressão SNC e respiratória aditiva — overdose' },
      { com: 'Eritromicina / cetoconazol (CYP3A4)', severidade: 'moderada', descricao: 'Aumenta zopiclona — sedação excessiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — risco de queda, confusão, dependência. Se imprescindível: 3,75 mg máximo',
      'DEPENDÊNCIA FÍSICA: pode ocorrer em semanas — descontinuação gradual',
      'COMPORTAMENTOS COMPLEXOS DO SONO: sonambulismo, alimentação noturna sem memória — suspender',
      'NÃO É SUPERIOR A BZD em segurança de dependência — benefício de marketing superestimado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — Z-drugs causam quedas, fraturas, delirium',
    stopp: 'STOPP D2: hipnótico Z-drug em idoso — risco de queda e dependência',
    pgx_genes: ['CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Imovane®', laboratorio: 'Sanofi', concentracoes: ['7,5 mg'], formas: ['Comprimido'] },
      { nome: 'Zopiclona EMS', laboratorio: 'EMS', concentracoes: ['7,5 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'midazolam',
    indicacao_contexto: 'Sedação / ansiólise (geral)',
    molecula: 'Midazolam',
    nome_generico: 'Maleato de Midazolam',
    sinonimos: ['dormicum', 'midazolam', 'benzodiazepínico iv', 'sedacao procedimento', 'midazolam status epilepticus'],
    categoria: 'psiquiatria',
    classe: 'Benzodiazepínico',
    subclasse: 'BZD de ação ultracurta — agonista GABA-A — lipossolúvel, IV/IM/intranasal/bucal',
    indicacoes_principais: [
      'Sedação para procedimentos (endoscopia, cardioversão, pequenos procedimentos)',
      'Indução anestésica',
      'Status epilepticus (IM/IV — 1ª linha em pré-hospitalar como alternativa ao diazepam)',
      'Sedação em UTI (infusão contínua)',
      'Crises convulsivas agudas (intranasal, bucal — uso domiciliar em epilepsia refratária)',
    ],
    dose_adulto: {
      habitual: '1–5 mg IV lento (sedação procedimento) | 10 mg IM (status epilepticus pré-hospitalar)',
      min: '0,5 mg IV (idoso)',
      max: '0,2 mg/kg IV (indução anestésica)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Dose única (procedimento) | Infusão contínua (UTI)'],
      instrucoes: 'IV: administrar lentamente (0,5 mg/min) — apneia se rápido. ANTÍDOTO: flumazenil 0,2 mg IV. IM status: 10 mg adulto (≥ 40 kg). Intranasal: 0,2 mg/kg (crises domiciliares).',
    },
    ajuste_renal: { normal: 'Sem ajuste (dose única)', tfg_60_30: 'Cautela em infusão prolongada', tfg_30_15: 'Reduzir velocidade de infusão', tfg_lt_15: 'Cautela extrema', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado (insuf grave)' },
    contraindicacoes_rapidas: ['Glaucoma de ângulo fechado (sem tratamento)', 'Miastenia grave', 'Insuficiência respiratória grave sem suporte'],
    interacoes_importantes: [
      { com: 'Cetoconazol / eritromicina / grapefruit', severidade: 'grave', descricao: 'Inibição CYP3A4 → midazolam aumenta 3–16× → sedação excessiva, apneia' },
      { com: 'Opioides / propofol', severidade: 'grave', descricao: 'Apneia e colapso CV aditivos — reduzir doses de ambos' },
      { com: 'Fluconazol (CYP3A4)', severidade: 'grave', descricao: 'Sedação prolongada' },
    ],
    alertas_especiais: [
      'APNEIA: risco de depressão respiratória grave — ter suporte ventilatório imediato disponível',
      'ANTÍDOTO: flumazenil (0,2 mg IV, repetir a cada 60s até 1 mg) — efeito mais curto que midazolam (vigilância necessária)',
      'AMNÉSIA ANTERÓGRADA: efeito desejado em procedimentos; não usar em anamnese importante',
      'UTI: tolerância e dependência com uso prolongado — desmame gradual ao suspender',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR BZD em idosos — depressão respiratória, queda, delirium',
    stopp: 'STOPP D2: benzodiazepínico em idoso',
    pgx_genes: ['CYP3A4 (metabolismo principal — interações críticas)'],
    marcas: [
      { nome: 'Dormicum®', laboratorio: 'Roche', concentracoes: ['5 mg/mL', '1 mg/mL'], formas: ['Ampola IV/IM'], lab_id: 'roche' },
      { nome: 'Midazolam Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['5 mg/mL'], formas: ['Ampola IV/IM'], lab_id: 'eurofarma' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANSIOLÍTICOS / BENZODIAZEPÍNICOS
  // (alprazolam já em PHARMA_DB)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'diazepam',
    molecula: 'Diazepam',
    nome_generico: 'Diazepam',
    sinonimos: ['valium', 'diazepam', 'benzodiazepínico ansiedade', 'bzd meia vida longa', 'status diazepam'],
    categoria: 'psiquiatria',
    classe: 'Benzodiazepínico',
    subclasse: 'BZD de longa ação (meia-vida 20–100h + metabólito ativo desmetildiazepam)',
    indicacoes_principais: [
      'Transtorno de ansiedade — agudo (curto prazo)',
      'Espasmo muscular',
      'Abstinência alcoólica grave (protocolo CIWA)',
      'Status epilepticus (IV — 1ª linha junto com lorazepam)',
      'Sedação pré-procedimento (VO/IV)',
      'Tenesmo em cuidados paliativos',
    ],
    dose_adulto: {
      habitual: '2–10 mg VO 2–4×/dia | 5–10 mg IV lento (status)',
      min: '2 mg/dia',
      max: '40 mg/dia (abstinência alcoólica)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–4×/dia (ansiedade) | Dose única IV (status)'],
      instrucoes: 'MEIA-VIDA LONGA: acúmulo em uso crônico — especialmente perigoso em idosos. IV: lento (risco apneia). Abstinência alcoólica: regime fixo ou CIWA-Ar (10 mg IV/VO se CIWA ≥ 8).',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela — acúmulo', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'Insuficiência respiratória grave', 'Glaucoma de ângulo fechado', 'Dependência atual de BZD (risco cruzado)'],
    interacoes_importantes: [
      { com: 'Opioides / álcool / outros depressores SNC', severidade: 'contraindicado', descricao: 'Apneia e morte — FDA black box: opioides + BZD' },
      { com: 'Fluvoxamina / omeprazol (CYP2C19)', severidade: 'moderada', descricao: 'Aumentam diazepam — sedação excessiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — meia-vida muito longa → acúmulo → quedas, fratura de quadril, delirium',
      'FDA BLACK BOX: opioides + BZD → risco de morte por depressão respiratória',
      'DEPENDÊNCIA: física e psicológica após semanas. Síndrome de abstinência grave (convulsões) se suspensão abrupta',
      'ANTÍDOTO: flumazenil',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: EVITAR em idosos — BZD de meia-vida longa tem maior risco de acúmulo',
    stopp: 'STOPP D2: benzodiazepínico de longa ação em idoso — risco máximo de queda e delirium',
    pgx_genes: ['CYP2C19 (metabolismo — PM: maior sedação)', 'CYP3A4 (metabolismo)'],
    marcas: [
      { nome: 'Valium®', laboratorio: 'Roche', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'roche' },
      { nome: 'Diazepam EMS', laboratorio: 'EMS', concentracoes: ['5 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'lorazepam',
    indicacao_contexto: 'Ansiedade / status epilepticus (psiquiatria)',
    molecula: 'Lorazepam',
    nome_generico: 'Lorazepam',
    sinonimos: ['ativan', 'lorazepam', 'bzd ação intermediária', 'status lorazepam', 'antiemetico quimio'],
    categoria: 'psiquiatria',
    classe: 'Benzodiazepínico',
    subclasse: 'BZD de ação intermediária (meia-vida 10–20h) — glucuronidação DIRETA (sem CYP)',
    indicacoes_principais: [
      'Ansiedade aguda',
      'Status epilepticus (IV — 1ª linha — preferido ao diazepam em UTI pela meia-vida)',
      'Sedação pré-procedimento',
      'Náuseas e vômitos por quimioterapia (adjuvante)',
      'Delirium agitado em cuidados paliativos',
    ],
    dose_adulto: {
      habitual: '1–2 mg VO 2–3×/dia | 2–4 mg IV (status)',
      min: '0,5 mg (idoso)',
      max: '10 mg/dia (ansiedade) | Status: repetir até controle',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (ansiedade) | Dose única IV (status)'],
      instrucoes: 'VANTAGEM: glucuronidação direta — sem metabolismo CYP, sem interações de CYP, sem acúmulo de metabólito ativo. Preferível em hepatopatas e idosos (vs diazepam). Status IV: 2–4 mg em 2 min, repetir 1× se sem resposta.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Reduzir dose', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste (glucuronidação não reduzida levemente)', child_b: 'Cautela', child_c: 'Cautela' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Miastenia grave', 'Insuficiência respiratória grave'],
    interacoes_importantes: [
      { com: 'Opioides / álcool / depressores SNC', severidade: 'grave', descricao: 'Apneia — FDA black box' },
      { com: 'Ácido valpróico', severidade: 'moderada', descricao: 'Inibe glucuronidação — aumenta lorazepam' },
    ],
    alertas_especiais: [
      'PREFERÍVEL AO DIAZEPAM em status epilepticus hospitalar (meia-vida mais favorável)',
      'PREFERÍVEL EM IDOSOS entre BZDs por menor risco de acúmulo vs diazepam/clordiazepóxido',
      'Ainda assim: Beers recomenda evitar BZDs em idosos de forma geral',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos — menos problemático que diazepam mas ainda causa quedas e delirium',
    stopp: 'STOPP D2: benzodiazepínico em idoso',
    pgx_genes: ['UGT2B15 (glucuronidação — variantes afetam metabolismo)'],
    marcas: [
      { nome: 'Ativan®', laboratorio: 'Pfizer', concentracoes: ['1 mg', '2 mg'], formas: ['Comprimido', 'Ampola IV'], lab_id: 'pfizer' },
      { nome: 'Lorazepam Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['1 mg', '2 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'clonazepam',
    molecula: 'Clonazepam',
    nome_generico: 'Clonazepam',
    sinonimos: ['rivotril', 'klonopin', 'clonazepam', 'bzd anticonvulsivante', 'rivotril pânico', 'clonazepam ansiedade'],
    categoria: 'psiquiatria',
    classe: 'Benzodiazepínico',
    subclasse: 'BZD de longa ação (meia-vida 20–50h) — indicação dupla: ansiedade e epilepsia',
    indicacoes_principais: [
      'Transtorno de pânico (1ª linha BZD)',
      'Epilepsia — especialmente epilepsia mioclônica e atônica',
      'Síndrome das pernas inquietas (adjuvante)',
      'Transtorno de ansiedade (curto prazo)',
      'Tremor essencial (adjuvante)',
    ],
    dose_adulto: {
      habitual: '0,5–2 mg VO 2–3×/dia (ansiedade/pânico)',
      min: '0,25 mg/dia',
      max: '20 mg/dia (epilepsia) | 4 mg/dia (pânico)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia'],
      instrucoes: 'Transtorno de pânico: 0,25 mg 2×/dia → titular para 1–4 mg/dia. Epilepsia: 0,05 mg/kg/dia → até 20 mg/dia. TOLERÂNCIA ANTICONVULSIVANTE: pode ocorrer em meses — planejamento para substituição.',
    },
    ajuste_renal: { normal: 'Sem ajuste formal', tfg_60_30: 'Cautela', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['Apneia do sono grave', 'Insuficiência hepática grave', 'Glaucoma de ângulo fechado'],
    interacoes_importantes: [
      { com: 'Opioides / álcool / depressores SNC', severidade: 'grave', descricao: 'Depressão respiratória — FDA black box' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — como todos os BZDs, risco de queda e delirium',
      'TOLERÂNCIA: anticonvulsivante — pode perder eficácia. Ansiolítica: persiste mais',
      'DEPENDÊNCIA: física grave — nunca suspender abruptamente (convulsões, delirium). Desmame 10%/semana',
      'USO NO BRASIL: prescrito excessivamente para insônia e ansiedade crônica — revisão obrigatória com o paciente',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: EVITAR em idosos',
    stopp: 'STOPP D2: benzodiazepínico em idoso com histórico de queda ou demência',
    pgx_genes: ['CYP3A4 (metabolismo principal)'],
    marcas: [
      { nome: 'Rivotril®', laboratorio: 'Roche', concentracoes: ['0,5 mg', '2 mg', '2,5 mg/mL solução'], formas: ['Comprimido', 'Solução oral'], lab_id: 'roche' },
      { nome: 'Clonazepam EMS', laboratorio: 'EMS', concentracoes: ['0,5 mg', '2 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'buspirona',
    molecula: 'Buspirona',
    nome_generico: 'Cloridrato de Buspirona',
    sinonimos: ['buspar', 'buspirone', 'buspirona', 'ansiolítico não bzd', 'tag buspirona', 'buspirona idoso'],
    categoria: 'psiquiatria',
    classe: 'Ansiolítico',
    subclasse: 'Azaspirodecanodiona — agonista parcial 5-HT1A + antagonista D3/D4 — SEM dependência',
    indicacoes_principais: [
      'Transtorno de ansiedade generalizada (TAG) — especialmente idosos e pacientes com histórico de abuso',
      'Ansiedade crônica (tratamento contínuo)',
    ],
    dose_adulto: {
      habitual: '15–30 mg/dia em 2–3 tomadas',
      min: '5 mg 2×/dia',
      max: '60 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3×/dia (com alimento)'],
      instrucoes: 'LATÊNCIA: 2–4 semanas para efeito ansiolítico (diferente de BZD — educação do paciente fundamental). NÃO age em crise de pânico aguda. NÃO tem efeito em pacientes já usando BZD cronicamente. Tomar sempre com ou sem alimento (consistência).',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Sem ajuste', tfg_30_15: 'Cautela', tfg_lt_15: 'Contraindicado', dialisavel: false },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Contraindicado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['IMAO (últimas 2 semanas)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'HAS (agonismo D3/D4) — crise hipertensiva' },
      { com: 'Cetoconazol / itraconazol / eritromicina', severidade: 'moderada', descricao: 'Inibição CYP3A4 → buspirona aumenta 5–13×' },
      { com: 'Rifampicina', severidade: 'moderada', descricao: 'Indução CYP3A4 → buspirona cai 10× — sem efeito' },
    ],
    alertas_especiais: [
      'VANTAGEM: SEM dependência, SEM sedação, SEM prejudicar cognição — IDEAL para idosos vs BZD',
      'INEFICAZ EM PÂNICO AGUDO: não usar para sintomas agudos — é ansiolítico de manutenção',
      'INEFICAZ SE O PACIENTE USA BZD: competição pelo receptor diminui efeito. Descontinuar BZD antes',
      'Beers: PREFERIDO ao BZD em idosos com TAG',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    beers_criteria: 'Beers 2023: alternativa preferível a BZDs em idosos com ansiedade',
    start: 'START E2: buspirona ou ISRS preferível a BZD em idoso com TAG',
    pgx_genes: ['CYP3A4 (metabolismo — interações com azóis e rifampicina)'],
    marcas: [
      { nome: 'Ansiced®', laboratorio: 'Bristol-Myers Squibb', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Buspirona EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'hidroxizina',
    molecula: 'Hidroxizina',
    nome_generico: 'Dicloridrato de Hidroxizina',
    sinonimos: ['atarax', 'hydroxyzine', 'hidroxizina', 'anti-histaminico ansiolítico', 'prurido hidroxizina', 'urticaria hidroxizina'],
    categoria: 'psiquiatria',
    classe: 'Ansiolítico',
    subclasse: 'Anti-histamínico H1 de 1ª geração — antagonista H1, muscarínico, α1, 5-HT2A — sedação e ansiedade',
    indicacoes_principais: [
      'Ansiedade aguda (curto prazo)',
      'Prurido alérgico / urticária',
      'Ansiedade pré-procedimento / pré-anestésica',
      'Sedação em crianças (procedimentos)',
    ],
    dose_adulto: {
      habitual: '25–50 mg VO 3–4×/dia',
      min: '25 mg/dia',
      max: '400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3–4×/dia'],
      instrucoes: 'Ansiedade aguda: 50–100 mg VO (pode repetir). Prurido: 25 mg 3–4×/dia. Efeito ansiolítico mais rápido que buspirona mas menor que BZD. SEM dependência.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Reduzir intervalo', tfg_30_15: 'Reduzir dose', tfg_lt_15: 'Evitar', dialisavel: false },
    ajuste_hepatico: { child_a: 'Reduzir dose', child_b: 'Reduzir 50%', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: ['QTc prolongado', 'Hipersensibilidade à cetirizina/piperazinas', 'Porfiria'],
    interacoes_importantes: [
      { com: 'QT-prolongadores', severidade: 'moderada', descricao: 'QT aditivo — hidroxizina prolonga QT dose-dependente' },
      { com: 'Anticolinérgicos', severidade: 'moderada', descricao: 'Efeito aditivo — retenção urinária, constipação' },
      { com: 'Álcool / depressores SNC', severidade: 'moderada', descricao: 'Sedação aditiva' },
    ],
    alertas_especiais: [
      'BEERS 2023: EVITAR em idosos — anti-histamínico de 1ª geração → alta carga anticolinérgica → confusão, retenção urinária, queda',
      'QT: monitorar ECG em cardiopatas e associação com outros QT-prolongadores',
      'Vantagem vs BZD: SEM dependência e SEM abuso. Bom para ansiedade situacional',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    beers_criteria: 'Beers 2023: EVITAR em idosos — anticolinérgico e sedativo de 1ª geração; QT prolongado',
    stopp: 'STOPP D4: anti-histamínico de 1ª geração em idoso',
    pgx_genes: ['CYP2D6 (metabolismo principal — PM: maior sedação)'],
    marcas: [
      { nome: 'Atarax®', laboratorio: 'UCB', concentracoes: ['25 mg', '10 mg/5 mL xarope'], formas: ['Comprimido', 'Xarope'] },
      { nome: 'Pergo®', laboratorio: 'Eurofarma', concentracoes: ['2 mg/mL solução oral'], formas: ['Solução Oral'], lab_id: 'eurofarma' },
      { nome: 'Hidroxizina EMS', laboratorio: 'EMS', concentracoes: ['25 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // ANTIPSICÓTICO ATÍPICO ADICIONAL
  // ══════════════════════════════════════════════════════════════

  {
    id: 'lurasidona',
    molecula: 'Lurasidona',
    nome_generico: 'Cloridrato de Lurasidona',
    sinonimos: ['latuda', 'lurasidone', 'lurasidona', 'antipsicótico depressão bipolar', 'antipsicótico cognitivo'],
    categoria: 'psiquiatria',
    classe: 'Antipsicótico Atípico',
    subclasse: 'Benzisotiazol — antagonismo D2/D3, 5-HT2A, 5-HT7 + agonismo parcial 5-HT1A — perfil metabólico favorável',
    indicacoes_principais: [
      'Esquizofrenia',
      'Depressão bipolar (como monoterapia ou adjuvante a lítio/valproato)',
    ],
    dose_adulto: {
      habitual: '40–80 mg/dia VO (esquizofrenia) | 20–60 mg/dia (depressão bipolar)',
      min: '20 mg/dia',
      max: '160 mg/dia (esquizofrenia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia COM refeição ≥ 350 kcal'],
      instrucoes: 'TOMAR COM ALIMENTO (≥ 350 kcal): absorção aumenta 2× vs jejum. Metabolismo CYP3A4 — evitar inibidores potentes (cetoconazol) e indutores (rifampicina). Vantagem: menor ganho de peso e sedação vs olanzapina/quetiapina.',
    },
    ajuste_renal: { normal: 'Sem ajuste', tfg_60_30: 'Máx 80 mg/dia', tfg_30_15: 'Máx 40 mg/dia', tfg_lt_15: 'Máx 40 mg/dia', dialisavel: false },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Máx 80 mg/dia', child_c: 'Máx 40 mg/dia' },
    contraindicacoes_rapidas: ['Uso com CYP3A4 potente inibidor (cetoconazol, claritromicina)', 'CYP3A4 potente indutor (rifampicina, carbamazepina)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'Cetoconazol / claritromicina (CYP3A4 inibidores potentes)', severidade: 'contraindicado', descricao: 'Aumenta lurasidona dramaticamente — toxicidade' },
      { com: 'Rifampicina / carbamazepina (CYP3A4 indutores potentes)', severidade: 'contraindicado', descricao: 'Reduz lurasidona ao mínimo — ineficaz' },
    ],
    alertas_especiais: [
      'ALIMENTO OBRIGATÓRIO: sem refeição, biodisponibilidade cai 50%',
      'MENOR EFEITO METABÓLICO: peso neutro ou ganho mínimo — preferível em DM2 e obesos',
      'DEPRESSÃO BIPOLAR: uma das pouções opções aprovadas especificamente para depressão bipolar',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    pgx_genes: ['CYP3A4 (metabolismo exclusivo — interações críticas)'],
    marcas: [
      { nome: 'Latuda®', laboratorio: 'Sumitomo/Sunovion', concentracoes: ['20 mg', '40 mg', '60 mg', '80 mg', '120 mg'], formas: ['Comprimido'] },
    ],
  },

];