// ============================================================
// PRESCREVE-AI — Extensão Farmacológica: ENDOCRINOLOGIA (Phase 21.4)
// 20 moléculas: Insulinas · GLP-1 · Dual GIP/GLP-1 · Biguanidas
//               DPP4 · SGLT2 · Sulfonilureias · Tiazolidinedionas
//               Hipotireoidismo · Hipertireoidismo · Osteoporose · Obesidade
// ============================================================

import type { QuickDrug } from './pharma-database';

export const PHARMA_DB_ENDO: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════════
  // INSULINAS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'insulina_nph',
    guidelines_referencia: ['ADA 2024 — insulina basal (NPH)'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Insulina NPH',
    nome_generico: 'Insulina Isófana Humana (NPH)',
    sinonimos: ['nph', 'insulina nph', 'insulina intermediaria', 'insulina isofana', 'humulin n', 'novolin n'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Ação intermediária (Isófana — ligada à protamina)',
    indicacoes_principais: ['DM tipo 1 (componente basal)', 'DM tipo 2 (insulinização basal)', 'Hiperglicemia hospitalar', 'DM gestacional'],
    dose_adulto: {
      habitual: '0,1–0,2 UI/kg/dia SC ao deitar',
      min: '0,1 UI/kg/dia',
      max: '1,5 UI/kg/dia (DM1 com múltiplas doses)',
      unidade: 'UI/kg',
      via: 'SC',
      frequencias: ['1x/dia (ao deitar)', '2x/dia (manhã e noite)'],
      instrucoes: 'DM2: iniciar 10 UI SC ao deitar. Titular 2 UI a cada 3 dias até glicemia jejum 80–130 mg/dL. Agitar suavemente (suspensão leitosa). Aplicar SC (não IV).',
    },
    ajuste_renal: {
      normal: '0,1–0,2 UI/kg/dia',
      tfg_60_30: 'Reduzir dose em 25% — menor clearance de insulina em DRC',
      tfg_30_15: 'Reduzir dose em 50% — hipoglicemia frequente',
      tfg_lt_15: 'Dose muito reduzida — monitorização contínua de glicemia',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir dose (menor gliconeogênese)', child_c: 'Reduzir significativamente — hipoglicemia frequente' },
    contraindicacoes_rapidas: ['Hipoglicemia em andamento', 'Hipersensibilidade à insulina'],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Mascara sintomas de hipoglicemia (taquicardia, tremor) — sudorese persiste' },
      { com: 'Corticosteroides', severidade: 'moderada', descricao: 'Aumentam resistência à insulina — necessidade de dose maior' },
      { com: 'iSGLT2 (empagliflozina, dapagliflozina)', severidade: 'moderada', descricao: 'Risco de hipoglicemia — reduzir insulina em 20% ao iniciar iSGLT2' },
      { com: 'IECA/ARA-II', severidade: 'leve', descricao: 'Podem aumentar sensibilidade à insulina — monitorar glicemia' },
    ],
    alertas_especiais: [
      'PICO de ação: 4–12h. Risco de hipoglicemia noturna com dose ao deitar excessiva',
      'Suspensão leitosa — homogeneizar suavemente antes de usar (sem agitar vigorosamente)',
      'PODE ser misturada com insulina regular na mesma seringa (aspirar regular primeiro)',
      'Rodízio obrigatório nos locais de aplicação — lipodistrofia em locais repetidos',
      'Gestação: insulina NPH é SEGURA — primeira escolha insulínica em DM gestacional',
      'BEERS: em idosos, preferir análogos de ação prolongada (menor variabilidade, menor hipoglicemia noturna)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Novolin® N', laboratorio: 'Novo Nordisk', concentracoes: ['100 UI/mL'], formas: ['Suspensão injetável'], lab_id: 'novo_nordisk' },
      { nome: 'Humulin® N', laboratorio: 'Eli Lilly', concentracoes: ['100 UI/mL'], formas: ['Suspensão injetável'], lab_id: 'eli_lilly' },
      { nome: 'Insulina NPH Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['100 UI/mL'], formas: ['Suspensão injetável'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'insulina_regular',
    molecula: 'Insulina Regular',
    nome_generico: 'Insulina Humana Regular',
    sinonimos: ['insulina regular', 'insulina r', 'insulina rapida', 'humulin r', 'novolin r', 'insulina simples'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Ação curta (Regular) — ÚNICA insulina para uso IV',
    indicacoes_principais: ['DM tipo 1 (componente prandial)', 'Cetoacidose diabética (CAD — IV em UTI)', 'Estado hiperosmolar hiperglicêmico', 'Hiperglicemia perioperatória (bomba IV)', 'Hipercalemia grave (associar glicose)'],
    dose_adulto: {
      habitual: 'SC: 4–8 UI antes das refeições principais; IV: 0,1 UI/kg/h (CAD)',
      min: '1 UI/dose SC',
      max: '0,2 UI/kg/h IV (protocolo UTI)',
      unidade: 'UI',
      via: 'SC',
      frequencias: ['SC: 3x/dia antes das refeições', 'IV: infusão contínua em bomba'],
      instrucoes: 'SC: aplicar 30 min antes das refeições. CAD IV: protocolo: 0,1 UI/kg/h em bomba, sem bolus inicial se K+ < 3,5 (corrigir K+ primeiro). ÚNICA insulina compatível com administração IV direta.',
    },
    ajuste_renal: {
      normal: 'SC: dose conforme glicemia',
      tfg_60_30: 'Reduzir dose em 25%',
      tfg_30_15: 'Reduzir 50% — monitorar intensivamente',
      tfg_lt_15: 'Dose muito reduzida — monitorar de hora em hora em UTI',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir dose', child_c: 'Reduzir significativamente' },
    contraindicacoes_rapidas: ['Hipoglicemia ativa'],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Mascara hipoglicemia' },
      { com: 'Corticosteroides', severidade: 'moderada', descricao: 'Hiperglicemia — necessidade de dose maior' },
      { com: 'Tiazolidinedionas', severidade: 'moderada', descricao: 'Retenção hídrica — edema e risco de IC' },
    ],
    alertas_especiais: [
      'ÚNICA insulina para uso IV — regular para IV, NPH é EXCLUSIVAMENTE SC',
      'Início SC: 30 min. Pico: 2–4h. Duração: 5–7h — maior risco de hipoglicemia pós-prandial tardia vs análogos',
      'CAD: glicemia não deve cair > 50 mg/dL/h — risco de edema cerebral (especialmente em crianças)',
      'COMPATÍVEL com NPH na mesma seringa: aspirar regular PRIMEIRO',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Novolin® R', laboratorio: 'Novo Nordisk', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
      { nome: 'Humulin® R', laboratorio: 'Eli Lilly', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'eli_lilly' },
    ],
  },

  {
    id: 'insulina_glargina',
    guidelines_referencia: ['ADA 2024 — insulina basal quando indicado'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Insulina Glargina',
    nome_generico: 'Insulina Glargina (rDNA)',
    sinonimos: ['lantus', 'toujeo', 'basaglar', 'glargina', 'insulina basal', 'insulina prolongada', 'análogo basal'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Análogo de ação prolongada — sem pico definido, duração ~24h',
    indicacoes_principais: ['DM tipo 1 (basal em esquema basal-bolus)', 'DM tipo 2 (insulinização basal)', 'Transição de NPH para menor hipoglicemia noturna'],
    dose_adulto: {
      habitual: '0,2 UI/kg 1x/dia ao deitar (DM2 virgem de insulina)',
      min: '0,1 UI/kg/dia',
      max: '1,0 UI/kg/dia',
      unidade: 'UI/kg',
      via: 'SC',
      frequencias: ['1x/dia (qualquer horário fixo)'],
      instrucoes: 'DM2: iniciar 10 UI ou 0,2 UI/kg SC ao deitar. Titular 2 UI a cada 3 dias até glicemia jejum 80–130 mg/dL. NÃO misturar com outras insulinas. NÃO usar IV.',
    },
    ajuste_renal: {
      normal: '0,2 UI/kg 1x/dia',
      tfg_60_30: 'Reduzir dose em 25%',
      tfg_30_15: 'Reduzir 50% — risco de hipoglicemia aumentado',
      tfg_lt_15: 'Dose muito reduzida — monitorar rigorosamente',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir dose', child_c: 'Reduzir significativamente' },
    contraindicacoes_rapidas: ['Hipoglicemia ativa', 'NÃO usar IV (precipitação)'],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Mascara hipoglicemia' },
      { com: 'GLP-1 (liraglutida, semaglutida)', severidade: 'moderada', descricao: 'Risco de hipoglicemia — reduzir glargina ao iniciar GLP-1' },
      { com: 'iSGLT2', severidade: 'moderada', descricao: 'Risco de hipoglicemia — reduzir glargina 20% ao iniciar' },
      { com: 'Corticosteroides', severidade: 'moderada', descricao: 'Hiperglicemia — aumentar dose de glargina' },
    ],
    alertas_especiais: [
      'Perfil mais estável que NPH: sem pico definido, menor variabilidade glicêmica noturna',
      'Toujeo® (U300): mesma molécula com concentração 3× maior — absorção mais lenta, duração > 36h; NÃO converter 1:1 com Lantus',
      'NÃO misturar com outra insulina na mesma seringa — precipitação ácida altera perfil de ação',
      'LIPODISTROFIA: rodízio obrigatório — 1 cm de distância entre aplicações',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Lantus®', laboratorio: 'Sanofi', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'sanofi' },
      { nome: 'Toujeo®', laboratorio: 'Sanofi', concentracoes: ['300 UI/mL'], formas: ['Solução injetável'], lab_id: 'sanofi' },
      { nome: 'Basaglar®', laboratorio: 'Eli Lilly', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'] },
    ],
  },

  {
    id: 'insulina_asparte',
    molecula: 'Insulina Asparte',
    nome_generico: 'Insulina Asparte (rDNA)',
    sinonimos: ['novorapid', 'fiasp', 'asparte', 'insulina ultrarapida', 'análogo ultrarapido'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Análogo de ação ultra-rápida — início 10–20 min, pico 1–3h, duração 3–5h',
    indicacoes_principais: ['DM tipo 1 (componente prandial — esquema basal-bolus)', 'DM tipo 2 em esquema intensivo', 'Bomba de infusão subcutânea de insulina (CSII)'],
    dose_adulto: {
      habitual: '0–15 min antes das refeições (SC)',
      min: 'Individualizar por contagem de carboidratos',
      max: 'Individualizar',
      unidade: 'UI',
      via: 'SC',
      frequencias: ['3x/dia (antes de cada refeição)', 'Bomba CSII contínua'],
      instrucoes: 'Aplicar 0–15 min antes da refeição (ou imediatamente após se quantidade de carboidratos incerta). Dose: relação insulina/carboidrato × gramas de CHO ingeridos. Fator de correção: 1 UI reduz glicemia ~50 mg/dL (variável).',
    },
    ajuste_renal: {
      normal: 'Dose conforme glicemia',
      tfg_60_30: 'Reduzir em 25%',
      tfg_30_15: 'Reduzir em 50%',
      tfg_lt_15: 'Monitorar intensivamente',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir dose', child_c: 'Reduzir — hipoglicemia frequente' },
    contraindicacoes_rapidas: ['Hipoglicemia ativa'],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Mascara hipoglicemia' },
      { com: 'Corticosteroides', severidade: 'moderada', descricao: 'Hiperglicemia pós-prandial — necessidade de dose maior' },
    ],
    alertas_especiais: [
      'Menor risco de hipoglicemia pós-prandial TARDIA vs insulina regular (duração mais curta)',
      'FIASP® (asparte + nicotinamida): início ainda mais rápido (~2,5 min) — para uso na mesma hora da refeição',
      'Pode ser usada em CSII (bomba de infusão) — solução transparente, não misturar com suspensões',
      'Aprovada a partir de 2 anos de idade',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'NovoRapid®', laboratorio: 'Novo Nordisk', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
      { nome: 'Fiasp®', laboratorio: 'Novo Nordisk', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
    ],
  },

  {
    id: 'insulina_lispro',
    molecula: 'Insulina Lispro',
    nome_generico: 'Insulina Lispro (rDNA)',
    sinonimos: ['humalog', 'admelog', 'lispro', 'insulina ultrarapida', 'análogo ultrarapido lispro'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Análogo de ação ultra-rápida — início 5–15 min, pico 1–2h, duração 3–4h',
    indicacoes_principais: ['DM tipo 1 (prandial)', 'DM tipo 2 (intensivo)', 'CSII'],
    dose_adulto: {
      habitual: '0–15 min antes das refeições',
      min: 'Individualizar',
      max: 'Individualizar',
      unidade: 'UI',
      via: 'SC',
      frequencias: ['3x/dia (prandial)', 'CSII contínua'],
      instrucoes: 'Aplicar 0–15 min antes ou imediatamente após refeição. Farmacocinética similar ao asparte.',
    },
    ajuste_renal: {
      normal: 'Dose conforme glicemia',
      tfg_60_30: 'Reduzir em 25%',
      tfg_30_15: 'Reduzir em 50%',
      tfg_lt_15: 'Monitorar intensivamente',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir', child_c: 'Reduzir significativamente' },
    contraindicacoes_rapidas: ['Hipoglicemia ativa'],
    interacoes_importantes: [
      { com: 'Betabloqueadores', severidade: 'moderada', descricao: 'Mascara hipoglicemia' },
    ],
    alertas_especiais: [
      'Perfil de ação praticamente idêntico ao asparte — diferença clinicamente irrelevante na maioria dos pacientes',
      'Humalog® U200: 200 UI/mL — volume 2× menor, útil em resistência insulínica grave',
      'Aprovada a partir de 3 anos de idade',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Humalog®', laboratorio: 'Eli Lilly', concentracoes: ['100 UI/mL', '200 UI/mL'], formas: ['Solução injetável'], lab_id: 'eli_lilly' },
      { nome: 'Admelog®', laboratorio: 'Sanofi', concentracoes: ['100 UI/mL'], formas: ['Solução injetável'], lab_id: 'sanofi' },
    ],
  },

  {
    id: 'insulina_degludeca',
    molecula: 'Insulina Degludeca',
    nome_generico: 'Insulina Degludeca (rDNA)',
    sinonimos: ['tresiba', 'degludeca', 'insulina ultra-prolongada', 'análogo basal ultra-prolongado', 'u200 degludeca'],
    categoria: 'antidiabético',
    classe: 'Insulina',
    subclasse: 'Análogo de ação ultra-prolongada — formação de multihexâmeros SC, duração > 42h',
    indicacoes_principais: ['DM tipo 1 (basal — menor variabilidade vs glargina)', 'DM tipo 2 (menor hipoglicemia vs glargina — SWITCH 1 e 2)', 'Hipoglicemia noturna recorrente com NPH/glargina'],
    dose_adulto: {
      habitual: '10 UI 1x/dia (DM2)',
      min: '0,1 UI/kg/dia',
      max: '1,0 UI/kg/dia',
      unidade: 'UI/kg',
      via: 'SC',
      frequencias: ['1x/dia (horário FLEXÍVEL — pode variar 8h sem prejuízo)'],
      instrucoes: 'DM2: iniciar 10 UI 1x/dia. Titular 2 UI a cada 3 dias até glicemia jejum 80–130 mg/dL. Conversão de glargina 100: usar mesma dose. Conversão de Toujeo (glargina 300): reduzir 20%.',
    },
    ajuste_renal: {
      normal: '10 UI 1x/dia',
      tfg_60_30: 'Reduzir 25% — monitorar',
      tfg_30_15: 'Reduzir 50%',
      tfg_lt_15: 'Cautela extrema',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Reduzir', child_c: 'Reduzir significativamente' },
    contraindicacoes_rapidas: ['Hipoglicemia ativa'],
    interacoes_importantes: [
      { com: 'GLP-1/iSGLT2', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir degludeca ao iniciar' },
    ],
    alertas_especiais: [
      'SWITCH 1 e 2: menor hipoglicemia noturna vs glargina U100 — vantagem em pacientes com hipoglicemias recorrentes',
      'FLEXIBILIDADE DE HORÁRIO: pode variar até 8h sem perda de controle (diferença crucial em pacientes com horários irregulares)',
      'U200: 200 UI/mL — volume pela metade, útil em doses altas',
      'DURAÇÃO > 42h: estado estacionário atingido após 3 dias de uso regular',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'avaliar',
    marcas: [
      { nome: 'Tresiba®', laboratorio: 'Novo Nordisk', concentracoes: ['100 UI/mL', '200 UI/mL'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // GLP-1 E DUAL GIP/GLP-1
  // ══════════════════════════════════════════════════════════════

  {
    id: 'liraglutida',
    guidelines_referencia: ['ADA 2024 — GLP-1 RA com protecao cardiorrenal (preferencial)', 'LEADER'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Liraglutida',
    nome_generico: 'Liraglutida',
    sinonimos: ['victoza', 'saxenda', 'liraglutide', 'glp-1', 'ar-glp1', 'agonista glp-1'],
    categoria: 'antidiabético',
    classe: 'AR-GLP-1',
    subclasse: 'Agonista do Receptor GLP-1 — análogo humano (97% homologia), T½ ~13h — 1x/dia',
    indicacoes_principais: [
      'DM tipo 2 (Victoza® — controle glicêmico + benefício CV — LEADER trial)',
      'Obesidade IMC ≥ 30 ou ≥ 27 com comorbidade (Saxenda® 3 mg — SCALE trial)',
    ],
    dose_adulto: {
      habitual: 'DM2: 1,2 mg SC 1x/dia. Obesidade: 3 mg SC 1x/dia',
      min: '0,6 mg SC 1x/dia (titulação)',
      max: '1,8 mg/dia (DM2); 3 mg/dia (obesidade)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1x/dia (qualquer horário, independente de refeições)'],
      instrucoes: 'Titulação: iniciar 0,6 mg/dia × 1 semana → 1,2 mg/dia × 1 semana → 1,8 mg/dia. Obesidade: 0,6 mg → 1,2 → 1,8 → 2,4 → 3 mg (cada etapa com 1 semana).',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste — dados limitados em DRC moderada',
      tfg_30_15: 'Dados insuficientes — cautela',
      tfg_lt_15: 'Não recomendado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Dados limitados', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: [
      'Carcinoma medular de tireoide (pessoal ou familiar)',
      'NEM tipo 2',
      'Gravidez',
      'Pancreatite aguda prévia',
    ],
    interacoes_importantes: [
      { com: 'Insulina', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir insulina 20% ao iniciar liraglutida' },
      { com: 'Sulfonilureias', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir sulfonilureia' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Possível alteração de INR — monitorar' },
    ],
    alertas_especiais: [
      'LEADER trial: redução de 13% em MACE (morte CV, IAM, AVC) em DM2 com alto risco CV — benefício cardiovascular confirmado',
      'Redução de peso: média de 3–5 kg em DM2; até 8–10% do peso corporal em obesidade',
      'Náuseas/vômitos: frequentes no início — minimizar com titulação lenta',
      'Pancreatite: suspender se sintomas abdominais graves inexplicados',
      'Nódulos/carcinoma medular: orientar paciente sobre sintomas (disfagia, rouquidão, massa cervical)',
      'SAXENDA (3 mg): indicação de obesidade distinta de Victoza (DM2) — mesma molécula, doses diferentes',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Victoza®', laboratorio: 'Novo Nordisk', concentracoes: ['6 mg/mL'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
      { nome: 'Saxenda®', laboratorio: 'Novo Nordisk', concentracoes: ['6 mg/mL (3 mg/dose)'], formas: ['Solução injetável'], lab_id: 'novo_nordisk' },
    ],
  },

  {
    id: 'tirzepatida',
    guidelines_referencia: ['ADA 2024 — agonista duplo GIP/GLP-1 (muito alta eficacia)', 'SURPASS'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Tirzepatida',
    nome_generico: 'Tirzepatida',
    sinonimos: ['mounjaro', 'zepbound', 'tirzepatide', 'dual gip glp-1', 'agonista duplo', 'twincretin'],
    categoria: 'antidiabético',
    classe: 'Dual GIP/GLP-1',
    subclasse: 'Agonista duplo dos receptores GIP e GLP-1 — molécula híbrida (twincretin)',
    indicacoes_principais: [
      'DM tipo 2 (Mounjaro® — SURPASS trials — maior redução de HbA1c vs semaglutida)',
      'Obesidade IMC ≥ 30 (Zepbound® — SURMOUNT trials — perda de peso de 20–22%)',
    ],
    dose_adulto: {
      habitual: '5 mg SC 1x/semana (DM2 inicial)',
      min: '2,5 mg SC 1x/semana',
      max: '15 mg SC 1x/semana',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1x/semana (mesmo dia da semana)'],
      instrucoes: 'Iniciar 2,5 mg SC 1x/semana × 4 semanas. Aumentar 2,5 mg a cada 4 semanas até dose alvo (5, 10 ou 15 mg). Qualquer dia da semana, com ou sem alimento.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Dados limitados — cautela',
      tfg_lt_15: 'Dados insuficientes — não recomendado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Dados limitados', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: [
      'Carcinoma medular de tireoide (pessoal ou familiar)',
      'NEM tipo 2',
      'Gravidez',
      'DM tipo 1',
    ],
    interacoes_importantes: [
      { com: 'Insulina', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir insulina ao iniciar' },
      { com: 'Sulfonilureias', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir sulfonilureia' },
      { com: 'Anticoncepcionais orais', severidade: 'leve', descricao: 'Tirzepatida pode reduzir absorção de contraceptivos orais — considerar método não-oral por 4 semanas após início ou aumento de dose' },
    ],
    alertas_especiais: [
      'SURPASS-2: maior redução de HbA1c vs semaglutida 1 mg (–2,4% vs –2,1%)',
      'SURMOUNT-1: perda de peso de 20,9% vs 3,1% (placebo) em obesidade — resultado sem precedentes',
      'MECANISMO DUPLO: GIP + GLP-1 — efeito aditivo em controle glicêmico e perda de peso',
      'BENEFÍCIO CV: em estudo (SURPASS-CVOT em andamento)',
      'Náuseas: frequentes no início — titulação lenta é essencial',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Mounjaro®', laboratorio: 'Eli Lilly', concentracoes: ['2,5 mg/dose', '5 mg/dose', '7,5 mg/dose', '10 mg/dose', '12,5 mg/dose', '15 mg/dose'], formas: ['Solução injetável autoaplicador'], lab_id: 'eli_lilly' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // TIAZOLIDINEDIONAS
  // ══════════════════════════════════════════════════════════════

  {
    id: 'pioglitazona',
    guidelines_referencia: ['ADA 2024 — tiazolidinediona (alta eficacia; cautela IC/edema)'],
    nivel_evidencia: 'B',
    grau_recomendacao: 'IIa',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Pioglitazona',
    nome_generico: 'Cloridrato de Pioglitazona',
    sinonimos: ['actos', 'pioglitazona', 'tiazolidinediona', 'glitazona', 'ppar-gama'],
    categoria: 'antidiabético',
    classe: 'Tiazolidinediona',
    subclasse: 'Agonista PPARγ — sensibilizador de insulina periférico (músculo, tecido adiposo)',
    indicacoes_principais: ['DM tipo 2 (especialmente com esteatohepatite não-alcoólica — NASH/MAFLD)', 'Síndrome metabólica com resistência insulínica'],
    dose_adulto: {
      habitual: '15–30 mg 1x/dia',
      min: '15 mg 1x/dia',
      max: '45 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/dia (com ou sem alimento)'],
      instrucoes: 'Iniciar 15 mg. Aumentar para 30–45 mg conforme tolerância (edema) e controle glicêmico. Efeito máximo em 8–12 semanas.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste — cautela com edema',
      tfg_lt_15: 'Dados limitados',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela — enzimas hepáticas antes de iniciar', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'IC classes NYHA III e IV',
      'Hepatopatia ativa (ALT > 2,5× LSN)',
      'Histórico de câncer de bexiga',
      'Hematúria macroscópica inexplicada',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'Insulina', severidade: 'moderada', descricao: 'Retenção hídrica e edema — maior risco de IC quando combinados' },
      { com: 'CYP2C8 inibidores (gemfibrozila)', severidade: 'grave', descricao: 'Aumenta pioglitazona em 3× — risco de retenção hídrica' },
      { com: 'CYP2C8 indutores (rifampicina)', severidade: 'moderada', descricao: 'Reduz pioglitazona' },
    ],
    alertas_especiais: [
      'RETENÇÃO HÍDRICA: edema periférico em 5–8% — contraindicado em IC NYHA III–IV',
      'GANHO DE PESO: 2–4 kg (redistribuição para tecido adiposo subcutâneo)',
      'CÂNCER DE BEXIGA: metanálise sugere associação com uso prolongado — contraindicar em histórico',
      'NASH/MAFLD: única classe com benefício histológico comprovado em esteatohepatite — uso off-label importante',
      'FRATURAS: risco aumentado em mulheres (extremidades distais)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Actos®', laboratorio: 'Takeda', concentracoes: ['15 mg', '30 mg', '45 mg'], formas: ['Comprimido'] },
      { nome: 'Pioglitazona EMS', laboratorio: 'EMS', concentracoes: ['15 mg', '30 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'acarbose',
    guidelines_referencia: ['ADA 2024 — inibidor da alfa-glicosidase (baixa eficacia)'],
    nivel_evidencia: 'B',
    grau_recomendacao: 'IIb',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Acarbose',
    nome_generico: 'Acarbose',
    sinonimos: ['glucobay', 'acarbose', 'inibidor alfa-glicosidase', 'iag'],
    categoria: 'antidiabético',
    classe: 'Inibidor de alfa-glicosidase',
    subclasse: 'Retarda absorção intestinal de carboidratos — sem hipoglicemia intrínseca',
    indicacoes_principais: ['DM tipo 2 (coadjuvante)', 'Hiperglicemia pós-prandial isolada'],
    dose_adulto: {
      habitual: '50 mg 3x/dia com a 1ª garfada de cada refeição',
      min: '25 mg 3x/dia',
      max: '300 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3x/dia (JUNTO com a 1ª garfada de cada refeição)'],
      instrucoes: 'Titular: iniciar 25 mg 3x/dia por 2 semanas. Aumentar para 50 mg → 100 mg 3x/dia conforme tolerância GI.',
    },
    ajuste_renal: {
      normal: '50–100 mg 3x/dia',
      tfg_60_30: 'Cautela',
      tfg_30_15: 'Contraindicado',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Doença inflamatória intestinal',
      'TFG < 25 mL/min',
      'Cirrose hepática',
      'Condições que pioram com flatulência (obstrução intestinal)',
    ],
    interacoes_importantes: [
      { com: 'Insulina/Sulfonilureias', severidade: 'moderada', descricao: 'Hipoglicemia — se hipoglicemia ocorrer, tratar com GLICOSE PURA (não sacarose/amido — acarbose retarda digestão)' },
      { com: 'Digoxina', severidade: 'moderada', descricao: 'Acarbose pode reduzir absorção de digoxina' },
    ],
    alertas_especiais: [
      'Flatulência e distensão abdominal em > 50% — titulação lenta essencial para adesão',
      'TRATAMENTO DE HIPOGLICEMIA: usar GLICOSE PURA (dextrose) — acarbose impede conversão de sacarose e amido em glicose',
      'Menor eficácia que metformina ou SGLT2i na redução de HbA1c (~0,5–0,8%)',
      'Vantagem: neutro em peso; sem risco cardiovascular identificado',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Glucobay®', laboratorio: 'Bayer', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
      { nome: 'Acarbose EMS', laboratorio: 'EMS', concentracoes: ['50 mg', '100 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // HIPOTIREOIDISMO
  // ══════════════════════════════════════════════════════════════

  {
    id: 'levotiroxina',
    guidelines_referencia: ['ATA — reposicao no hipotireoidismo (padrao-ouro)'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Levotiroxina',
    nome_generico: 'Levotiroxina Sódica (L-T4)',
    sinonimos: ['puran', 'synthroid', 'euthyrox', 'levotiroxina', 'l-t4', 'tiroxina', 'hipotireoidismo', 't4'],
    categoria: 'hormonio',
    classe: 'Hormônio Tireoidiano',
    subclasse: 'T4 sintético — pró-hormônio convertido em T3 ativo perifericamente',
    indicacoes_principais: ['Hipotireoidismo primário (Tireoidite de Hashimoto e outras causas)', 'Hipotireoidismo secundário/terciário', 'Supressão de TSH em carcinoma diferenciado de tireoide', 'Nódulos tireoidianos (supressão — uso controverso)'],
    dose_adulto: {
      habitual: '1,6 mcg/kg/dia (adultos jovens); 1,0–1,2 mcg/kg/dia (idosos)',
      min: '12,5 mcg 1x/dia (iniciar em idosos/coronariopatas)',
      max: '200–300 mcg/dia (supressão em Ca tireoide)',
      unidade: 'mcg',
      via: 'VO',
      frequencias: ['1x/dia (30 min antes do café, em jejum)'],
      instrucoes: 'Tomar em jejum, 30–60 min antes do café da manhã (ou 3–4h após refeição). Adultos jovens saudáveis: iniciar dose plena. Idosos > 65a ou coronariopatas: iniciar 12,5–25 mcg e aumentar 12,5–25 mcg a cada 6–8 semanas. Meta TSH: 0,5–2,5 mUI/L (adultos).',
    },
    ajuste_renal: {
      normal: '1,6 mcg/kg/dia',
      tfg_60_30: 'Sem ajuste formal — monitorar TSH',
      tfg_30_15: 'Sem ajuste formal — monitorar TSH',
      tfg_lt_15: 'Sem ajuste formal — monitorar TSH',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela — conversão T4→T3 pode estar reduzida', child_c: 'Cautela' },
    contraindicacoes_rapidas: [
      'Tireotoxicose não tratada',
      'Insuficiência adrenal não tratada (risco de crise adrenal)',
      'IAM recente (doses suprafisiológicas)',
    ],
    interacoes_importantes: [
      { com: 'Carbonato de cálcio', severidade: 'moderada', descricao: 'Reduz absorção de T4 em 30–50% — tomar T4 ao menos 4h antes de cálcio' },
      { com: 'Sulfato ferroso', severidade: 'moderada', descricao: 'Reduz absorção de T4 — tomar T4 ao menos 4h antes do ferro' },
      { com: 'Antiácidos com Al ou Mg', severidade: 'moderada', descricao: 'Redução de absorção — espaçar 4h' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Levotiroxina potencializa efeito anticoagulante — monitorar INR' },
      { com: 'Colestiramina', severidade: 'moderada', descricao: 'Quelação intestinal — tomar T4 4h antes da colestiramina' },
      { com: 'Amiodarona', severidade: 'moderada', descricao: 'Amiodarona bloqueia conversão T4→T3 e inibe receptor — TSH pode não refletir status tireoidiano real' },
    ],
    alertas_especiais: [
      'TSH ALVO VARIA COM INDICAÇÃO: hipotireoidismo padrão 0,5–2,5; gestação 0,1–2,5; Ca tireoide: < 0,1 (supressão) ou 0,1–0,5 (baixo risco)',
      'MARCA ESPECÍFICA: trocar de marca pode alterar controle (bioequivalência não garante equivalência biológica na prática clínica) — manter marca estável',
      'INTERAÇÕES ALIMENTARES: soja, fibras, café podem reduzir absorção',
      'OSTEOPOROSE: doses suprafisiológicas (TSH suprimido) em mulheres pós-menopausa aumentam risco de fratura',
      'GESTAÇÃO: necessidade aumenta 30–50% — monitorar TSH a cada 4–6 semanas',
      'BEERS: em idosos, monitorar sinais de toxicidade (FA, angina, perda óssea)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Puran T4®', laboratorio: 'Abbott', concentracoes: ['25 mcg', '50 mcg', '75 mcg', '100 mcg', '125 mcg', '150 mcg', '175 mcg', '200 mcg'], formas: ['Comprimido'] },
      { nome: 'Euthyrox®', laboratorio: 'Merck KGaA', concentracoes: ['25 mcg', '50 mcg', '75 mcg', '100 mcg', '125 mcg', '150 mcg'], formas: ['Comprimido'] },
      { nome: 'Levotiroxina Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['25 mcg', '50 mcg', '100 mcg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // HIPERTIREOIDISMO
  // ══════════════════════════════════════════════════════════════

  {
    id: 'metimazol',
    guidelines_referencia: ['ATA — antitireoidiano de 1a linha no hipertireoidismo (Graves)'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    molecula: 'Metimazol',
    nome_generico: 'Metimazol (Tiamazol)',
    sinonimos: ['tapazol', 'metimazol', 'tiamazol', 'antitireoideo', 'hipertireoidismo', 'doença de graves'],
    categoria: 'hormonio',
    classe: 'Antitireoidiano',
    subclasse: 'Tionamida — inibe síntese de T3/T4 por bloqueio da peroxidase tireoidiana',
    indicacoes_principais: ['Doença de Graves', 'Bócio multinodular tóxico', 'Nódulo tóxico único', 'Preparo para tireoidectomia ou iodo radioativo'],
    dose_adulto: {
      habitual: '20–40 mg/dia divididos em 2x (fase de ataque)',
      min: '5 mg/dia',
      max: '60 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2–3x/dia (ataque)', '1x/dia (manutenção — T½ longa permite dose única)'],
      instrucoes: 'Ataque: 20–40 mg/dia. Manutenção: 5–10 mg/dia após eutireoidismo (4–8 semanas). Monitorar T4 livre e TSH a cada 4–8 semanas.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Cautela',
      tfg_lt_15: 'Dados limitados',
      dialisavel: true,
    },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Reduzir dose', child_c: 'Evitar — hepatotoxicidade' },
    contraindicacoes_rapidas: [
      '1º trimestre de gestação (usar PTU no 1º tri, metimazol no 2º–3º)',
      'Histórico de agranulocitose por tionamida',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Metimazol reduz hipertireoidismo → metabolismo da varfarina diminui → INR sobe' },
      { com: 'Betabloqueadores (propranolol)', severidade: 'leve', descricao: 'Complementam controle sintomático (taquicardia, tremor) — combinação comum' },
    ],
    alertas_especiais: [
      'AGRANULOCITOSE: risco de 0,3–0,5% — suspender IMEDIATAMENTE se febre ou faringite. Hemograma de urgência',
      'PREFERIDO em relação ao PTU fora do 1º trimestre (menor hepatotoxicidade)',
      '1º TRIMESTRE DE GESTAÇÃO: substituir por PTU (metimazol tem risco de aplasia cútis no feto)',
      'STORM TIREOIDIANA: iniciar metimazol 60 mg/dose imediatamente, em associação com propranolol e iodeto de potássio',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Tapazol®', laboratorio: 'Aspen', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
      { nome: 'Metimazol EMS', laboratorio: 'EMS', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido'] },
    ],
  },

  {
    id: 'propiltiouracil',
    molecula: 'Propiltiouracil',
    nome_generico: 'Propiltiouracil (PTU)',
    sinonimos: ['ptu', 'propiltiouracil', 'antitireoideo gestacao', 'hipertireoidismo 1o trimestre'],
    categoria: 'hormonio',
    classe: 'Antitireoidiano',
    subclasse: 'Tionamida + inibição periférica da conversão T4→T3',
    indicacoes_principais: [
      '1º trimestre de gestação (preferido sobre metimazol neste período)',
      'Crise tireotóxica (storm tireoidiana — bloqueia conversão periférica T4→T3)',
      'Doença de Graves em alergia ao metimazol',
    ],
    dose_adulto: {
      habitual: '100–150 mg 3x/dia (ataque)',
      min: '50 mg 3x/dia',
      max: '600 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3x/dia (dose dividida — T½ curta, 2h)'],
      instrucoes: 'Deve ser tomado a cada 8h (3x/dia) — meia-vida curta exige divisão de doses. Manutenção: 50 mg 3x/dia após eutireoidismo.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Cautela',
      tfg_lt_15: 'Cautela',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Cautela', child_b: 'Evitar', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Hepatite severa induzida por PTU prévia',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Altera metabolismo da varfarina conforme estado tireoidiano' },
    ],
    alertas_especiais: [
      '1º TRIMESTRE: fármaco de eleição — metimazol associado a aplasia cútis fetal neste período',
      'HEPATOTOXICIDADE: mais grave que metimazol — risco de insuficiência hepática fulminante (evitar fora da gestação/storm)',
      'Desvantagem: 3x/dia (vs metimazol 1x/dia) — pior adesão',
      'AGRANULOCITOSE: mesmo risco que metimazol — suspender se febre/faringite',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'PTU genérico', laboratorio: 'Vários', concentracoes: ['100 mg'], formas: ['Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // OSTEOPOROSE
  // ══════════════════════════════════════════════════════════════

  {
    id: 'alendronato',
    guidelines_referencia: ['Diretriz de osteoporose — bisfosfonato de 1a linha'],
    nivel_evidencia: 'A',
    grau_recomendacao: 'I',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Alendronato',
    nome_generico: 'Alendronato Sódico',
    sinonimos: ['fosamax', 'alendronato', 'bifosfonato', 'osteoporose', 'alendronate'],
    categoria: 'hormonio',
    classe: 'Bifosfonato',
    subclasse: 'Inibidor da reabsorção óssea osteoclástica — aminobifosfonato',
    indicacoes_principais: ['Osteoporose pós-menopáusica', 'Osteoporose em homens', 'Osteoporose induzida por corticosteroides'],
    dose_adulto: {
      habitual: '70 mg 1x/semana (VO)',
      min: '5 mg 1x/dia',
      max: '70 mg/semana (ou 10 mg/dia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1x/semana (70 mg)', '1x/dia (10 mg)'],
      instrucoes: 'Tomar em JEJUM absoluto ao acordar com 200 mL de água. Permanecer SENTADO ou EM PÉ por 30 min (não deitar — risco de esofagite). Não comer por 30–60 min após.',
    },
    ajuste_renal: {
      normal: '70 mg 1x/semana',
      tfg_60_30: 'Usar com cautela',
      tfg_30_15: 'Contraindicado (TFG < 35)',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Sem ajuste — excreção renal' },
    contraindicacoes_rapidas: [
      'TFG < 35 mL/min',
      'Hipocalcemia (corrigir antes de iniciar)',
      'Esôfago de Barrett, esofagite ativa ou dificuldade de deglutição',
      'Incapacidade de ficar em pé/sentado por 30 min',
    ],
    interacoes_importantes: [
      { com: 'Cálcio/Ferro/Antiácidos', severidade: 'moderada', descricao: 'Reduzem absorção de alendronato — espaçar ao menos 30–60 min' },
      { com: 'AINEs', severidade: 'moderada', descricao: 'Risco aditivo de úlceras GI' },
    ],
    alertas_especiais: [
      'ESOFAGITE: risco real se não seguir instruções de administração — orienta com ênfase',
      'OSTEONECROSE DE MANDÍBULA (ONM): risco com uso prolongado, especialmente em oncologia (IV) — baixo risco em osteoporose oral',
      'FRATURA ATÍPICA DE FÊMUR: risco com uso > 5 anos — rever indicação anualmente',
      'HIPOCALCEMIA: corrigir deficiência de cálcio e vitamina D ANTES de iniciar',
      'Tratamento por 5 anos → reavaliação (drug holiday em baixo risco)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Fosamax®', laboratorio: 'MSD', concentracoes: ['10 mg', '70 mg'], formas: ['Comprimido'] },
      { nome: 'Alendronato EMS', laboratorio: 'EMS', concentracoes: ['10 mg', '70 mg'], formas: ['Comprimido'] },
      { nome: 'Alendronato Eurofarma', laboratorio: 'Eurofarma', concentracoes: ['70 mg'], formas: ['Comprimido'], lab_id: 'eurofarma' },
    ],
  },

  {
    id: 'denosumabe',
    molecula: 'Denosumabe',
    nome_generico: 'Denosumabe',
    sinonimos: ['prolia', 'xgeva', 'denosumab', 'anti-rankl', 'anticorpo anti-rankl', 'osteoporose biologico'],
    categoria: 'imunossupressor',
    classe: 'Anticorpo Monoclonal Anti-RANK-L',
    subclasse: 'Inibidor do RANK-L — bloqueia diferenciação e ativação de osteoclastos',
    indicacoes_principais: [
      'Osteoporose pós-menopáusica de alto risco (FREEDOM trial)',
      'Osteoporose em homens',
      'Perda óssea por hormônio (ADT em Ca próstata; IAT em Ca mama)',
      'Metástases ósseas de tumores sólidos (Xgeva® 120 mg)',
    ],
    dose_adulto: {
      habitual: '60 mg SC a cada 6 meses (osteoporose)',
      min: '60 mg SC/6 meses',
      max: '120 mg SC/4 semanas (metástases ósseas)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1x a cada 6 meses (osteoporose)', '1x/mês (metástases)'],
      instrucoes: 'SC na coxa, abdome ou parte posterior do braço. Garantir suplementação de cálcio (1000 mg/dia) e vitamina D (≥ 800 UI/dia) durante todo o tratamento.',
    },
    ajuste_renal: {
      normal: '60 mg SC/6 meses',
      tfg_60_30: 'Sem ajuste — vantagem sobre bifosfonatos',
      tfg_30_15: 'Sem ajuste — maior risco de hipocalcemia em DRC grave',
      tfg_lt_15: 'Usar com extrema cautela — monitorar Ca2+ com frequência',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Sem ajuste', child_c: 'Sem ajuste' },
    contraindicacoes_rapidas: [
      'Hipocalcemia (corrigir ANTES de iniciar)',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'Cálcio (suplemento)', severidade: 'leve', descricao: 'Suplementação obrigatória — sinérgico' },
    ],
    alertas_especiais: [
      'HIPOCALCEMIA: monitorar Ca2+ nas primeiras semanas (especialmente em TFG < 30)',
      'REBOUND ÓSSEO: ao suspender denosumabe, há reativação acentuada de osteoclastos — perda óssea abrupta e fraturas múltiplas em 12–18 meses pós-suspensão. SEQUÊNCIA com bifosfonato é obrigatória ao descontinuar',
      'ONM: menor risco que IV de bifosfonatos em osteoporose',
      'FRATURA ATÍPICA: risco similar a bifosfonatos com uso prolongado',
      'VANTAGEM sobre bifosfonatos: eficácia em DRC (TFG < 35) e via SC (sem esofagite)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Prolia®', laboratorio: 'Amgen/UCB', concentracoes: ['60 mg/mL'], formas: ['Solução injetável (seringa preenchida)'] },
      { nome: 'Xgeva®', laboratorio: 'Amgen', concentracoes: ['120 mg/1,7 mL'], formas: ['Solução injetável'] },
    ],
  },

  // ══════════════════════════════════════════════════════════════
  // OBESIDADE
  // ══════════════════════════════════════════════════════════════

  {
    id: 'orlistate',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Orlistate',
    nome_generico: 'Orlistate',
    sinonimos: ['xenical', 'orlistat', 'inibidor lipase', 'obesidade'],
    categoria: 'outro',
    classe: 'Antiobesidade',
    subclasse: 'Inibidor de lipase pancreática e gástrica — reduz absorção de gordura em 30%',
    indicacoes_principais: ['Obesidade (IMC ≥ 30)', 'Sobrepeso com comorbidades (IMC ≥ 27) — HAS, DM2, dislipidemia'],
    dose_adulto: {
      habitual: '120 mg 3x/dia com as refeições',
      min: '60 mg 3x/dia (Alli®)',
      max: '360 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['3x/dia com cada refeição principal contendo gordura'],
      instrucoes: 'Tomar durante ou até 1h após cada refeição contendo gordura. Se refeição pular ou não contiver gordura: não tomar.',
    },
    ajuste_renal: {
      normal: 'Sem ajuste',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Sem ajuste',
      tfg_lt_15: 'Dados limitados',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Cautela', child_c: 'Dados insuficientes' },
    contraindicacoes_rapidas: [
      'Síndrome de má-absorção crônica',
      'Colestase',
      'Gravidez e lactação',
      'Hipersensibilidade',
    ],
    interacoes_importantes: [
      { com: 'Ciclosporina', severidade: 'grave', descricao: 'Reduz absorção de ciclosporina significativamente — monitorar nível sérico' },
      { com: 'Varfarina', severidade: 'moderada', descricao: 'Reduz absorção de vitamina K → potencializa varfarina — monitorar INR' },
      { com: 'Levotiroxina', severidade: 'moderada', descricao: 'Reduz absorção de T4 — espaçar 2h' },
      { com: 'Antirretrovirais (lopinavir)', severidade: 'moderada', descricao: 'Reduz absorção' },
    ],
    alertas_especiais: [
      'Efeitos GI: esteatorreia, urgência fecal, flatulência oleosa — relacionados a dieta rica em gordura. Reduzir gordura < 30% das calorias minimiza efeitos',
      'Vitaminas lipossolúveis: suplementar A, D, E, K 2h após orlistate (reduz absorção)',
      'Perda de peso: modesta (~3 kg a mais vs placebo) — efeito limitado sem mudança alimentar',
      'PREVENÇÃO DM2: reduz incidência em 40% em pré-diabéticos obesos (Xendos trial)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Xenical®', laboratorio: 'Roche', concentracoes: ['120 mg'], formas: ['Cápsula'], lab_id: 'roche' },
      { nome: 'Alli®', laboratorio: 'Haleon', concentracoes: ['60 mg'], formas: ['Cápsula'] },
    ],
  },

  {
    id: 'naltrexona_bupropiona',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Naltrexona/Bupropiona',
    nome_generico: 'Cloridrato de Naltrexona + Cloridrato de Bupropiona (LP)',
    sinonimos: ['contrave', 'mysimba', 'naltrexona bupropiona', 'antiobesidade combinado'],
    categoria: 'outro',
    classe: 'Antiobesidade',
    subclasse: 'Antagonista opioide (naltrexona) + Inibidor de recaptação de DA/NA (bupropiona) — ação hipotalâmica sinérgica',
    indicacoes_principais: ['Obesidade (IMC ≥ 30)', 'Sobrepeso (IMC ≥ 27) + DM2 ou dislipidemia', 'Compulsão alimentar associada a obesidade'],
    dose_adulto: {
      habitual: '32 mg/360 mg 2x/dia (fase de manutenção)',
      min: '8 mg/90 mg 1x/dia (fase 1)',
      max: '32 mg/360 mg 2x/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['Titulação em 4 semanas', '2x/dia (manutenção)'],
      instrucoes: 'Titulação: Semana 1: 1 comprimido pela manhã. Semana 2: 1+1. Semana 3: 2+1. Semana 4: 2+2 (dose plena). Não esmagar ou partir (LP).',
    },
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'Máximo 1 cp 2x/dia',
      tfg_30_15: 'Contraindicado',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Não recomendado', child_c: 'Contraindicado' },
    contraindicacoes_rapidas: [
      'Uso de opioides ou síndrome de abstinência de opioides',
      'Epilepsia ou distúrbios convulsivos (bupropiona abaixa limiar convulsivo)',
      'HAS não controlada (> 180/110)',
      'Anorexia nervosa ou bulimia',
      'IMAO nas últimas 2 semanas',
    ],
    interacoes_importantes: [
      { com: 'Opioides', severidade: 'contraindicado', descricao: 'Naltrexona bloqueia efeito analgésico e pode precipitar abstinência aguda' },
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Crise hipertensiva' },
      { com: 'Metoprolol/Betabloqueadores', severidade: 'moderada', descricao: 'Bupropiona inibe CYP2D6 — aumenta betabloqueadores — bradicardia' },
      { com: 'Tamoxifeno', severidade: 'grave', descricao: 'Bupropiona inibe CYP2D6 — reduz formação de endoxifeno (metabólito ativo do tamoxifeno)' },
    ],
    alertas_especiais: [
      'CONVULSÕES: risco dose-dependente pela bupropiona — evitar em epilépticos; risco aumenta com álcool',
      'PA: monitorar PA regularmente — bupropiona pode aumentar PA levemente',
      'BLACKBOX WARNING FDA: aumento de pensamentos suicidas em adolescentes (bupropiona) — monitorar humor',
      'Perda de peso média: ~5–8% do peso em 1 ano (superior ao orlistate)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Contrave®', laboratorio: 'Currax Pharmaceuticals', concentracoes: ['8 mg/90 mg'], formas: ['Comprimido LP'] },
    ],
  },

  {
    id: 'semaglutida_obesidade',
    uso_pediatrico: 'nao_aplicavel',
    molecula: 'Semaglutida 2,4 mg',
    nome_generico: 'Semaglutida (dose obesidade)',
    sinonimos: ['wegovy', 'semaglutida obesidade', 'semaglutida 2.4', 'glp-1 obesidade', 'ar-glp1 anti-obesidade'],
    categoria: 'outro',
    classe: 'AR-GLP-1',
    subclasse: 'Agonista GLP-1 em dose antiobesidade (dose superior à dose DM2 — Ozempic® 1 mg)',
    indicacoes_principais: [
      'Obesidade (IMC ≥ 30) — STEP trials — perda de peso de 15–17% em 68 semanas',
      'Sobrepeso (IMC ≥ 27) com HAS, dislipidemia ou apneia do sono',
      'Benefício CV em obesidade (SELECT trial — redução de MACE em obesos sem DM)',
    ],
    dose_adulto: {
      habitual: '2,4 mg SC 1x/semana (dose manutenção)',
      min: '0,25 mg SC 1x/semana (fase 1)',
      max: '2,4 mg SC 1x/semana',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1x/semana (mesmo dia)'],
      instrucoes: 'Titulação em 16 semanas: 0,25 mg × 4 sem → 0,5 mg × 4 sem → 1,0 mg × 4 sem → 1,7 mg × 4 sem → 2,4 mg (manutenção). Qualquer dia, independente de refeições.',
    },
    ajuste_renal: {
      normal: '2,4 mg 1x/semana',
      tfg_60_30: 'Sem ajuste',
      tfg_30_15: 'Dados limitados — cautela',
      tfg_lt_15: 'Não recomendado',
      dialisavel: false,
    },
    ajuste_hepatico: { child_a: 'Sem ajuste', child_b: 'Dados limitados', child_c: 'Não recomendado' },
    contraindicacoes_rapidas: [
      'Carcinoma medular de tireoide (pessoal ou familiar)',
      'NEM tipo 2',
      'Gravidez',
    ],
    interacoes_importantes: [
      { com: 'Insulina/Sulfonilureias', severidade: 'moderada', descricao: 'Hipoglicemia — reduzir doses de antidiabéticos ao iniciar' },
    ],
    alertas_especiais: [
      'SELECT trial (2023): semaglutida 2,4 mg reduziu MACE em 20% em pacientes com DCV estabelecida e obesidade (SEM DM) — mudança de paradigma',
      'Maior perda de peso entre todas as terapias aprovadas para obesidade (~15–17%)',
      'Diferente do Ozempic® (1 mg para DM2): dose mais alta, indicação e embalagem distintas',
      'Náuseas: frequentes — titulação de 16 semanas minimiza abandono',
      'SUSPENSÃO: recuperação de peso progressiva — uso provavelmente crônico',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Wegovy®', laboratorio: 'Novo Nordisk', concentracoes: ['0,25 mg/dose', '0,5 mg/dose', '1 mg/dose', '1,7 mg/dose', '2,4 mg/dose'], formas: ['Solução injetável autoaplicador'], lab_id: 'novo_nordisk' },
    ],
  },

];