// ============================================================
// PRESCREVE-AI — Banco Farmacológico: Cuidados Paliativos
// Phase 21.14
// ============================================================

import { QuickDrug } from './pharma-database';

export const PHARMA_DB_PALLIATIVE: QuickDrug[] = [

  // ══════════════════════════════════════════════════════════
  // ── OPIOIDES — DEGRAU 2 WHO ───────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'tramadol-paliativo',
    molecula: 'tramadol',
    nome_generico: 'Tramadol (Dor Moderada — WHO 2)',
    sinonimos: ['Tramal', 'cloridrato de tramadol', 'opioide fraco', 'WHO degrau 2'],
    categoria: 'paliativo',
    classe: 'Opioide fraco — agonista µ parcial + inibidor recaptação serotonina/noradrenalina',
    indicacoes_principais: ['Dor moderada (EVN 4–6) — WHO degrau 2', 'Dor mista nociceptiva + neuropática leve', 'Transição de degrau 1 para 3'],
    dose_adulto: {
      habitual: '50–100 mg VO 6/6h–8/8h (IR) | 100–200 mg 12/12h (LP) | IC SC: 100–300 mg/24h',
      max: '400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['6/6h ou 8/8h (IR)', '12/12h (LP — não partir/mastigar)', 'IC SC em bomba'],
      instrucoes: 'Iniciar 50 mg 8/8h → titular. Formulação LP: engolir inteiro. Em idosos: iniciar 25 mg 8/8h. SEMPRE combinar com paracetamol (sinergismo). Converter para morfina se inadequado.',
    },
    contraindicacoes_rapidas: [
      'Uso com IMAO ou 14 dias após IMAO (síndrome serotoninérgica)',
      'Epilepsia não controlada (abaixa limiar convulsivo)',
      'Insuficiência respiratória grave',
      'ClCr < 10 mL/min',
    ],
    interacoes_importantes: [
      { com: 'ISRS / IRSN', severidade: 'grave', descricao: 'Síndrome serotoninérgica — monitorar ou substituir' },
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica fatal' },
      { com: 'BZD / opioides', severidade: 'moderada', descricao: 'Depressão do SNC e respiratória aditiva' },
    ],
    alertas_especiais: [
      '⚠ Síndrome serotoninérgica: hipertermia, tremor, mioclonias, agitação — emergência',
      'Metabolizadores ultra-rápidos CYP2D6: toxicidade opioide (morfina excess); lentos: ineficácia',
      'Não há vantagem sobre morfina em baixas doses em paliativo avançado — rota para degrau 3',
      'Antídoto: naloxona (efeito opioide) — não reverte componente serotonérgico',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'Intervalo q12h (não q8h)',
      tfg_30_15: 'Máx 200 mg/dia, q12h',
      tfg_lt_15: 'CONTRAINDICADO',
      dialisavel: false,
    },
    marcas: [
      { nome: 'Tramal', laboratorio: 'Grünenthal', concentracoes: ['50 mg (cápsula)', '100 mg LP', '200 mg LP'], formas: ['Cápsula IR', 'Comprimido LP', 'Gotas (100 mg/mL)', 'Ampola IV 50 mg/mL'] },
      { nome: 'Tramadol (genérico)', laboratorio: 'Várias', concentracoes: ['50 mg', '100 mg LP'], formas: ['Cápsula', 'Comprimido LP'] },
    ],
  },
  {
    id: 'codeina',
    molecula: 'codeína',
    nome_generico: 'Codeína',
    sinonimos: ['fosfato de codeína', 'opioide fraco', 'WHO degrau 2', 'codeína + paracetamol'],
    categoria: 'paliativo',
    classe: 'Opioide fraco — pró-fármaco da morfina (via CYP2D6)',
    indicacoes_principais: ['Dor moderada — WHO degrau 2', 'Tosse seca refratária (antitussígeno)', 'Diarreia em cuidados paliativos'],
    dose_adulto: {
      habitual: '30–60 mg 4/4h–6/6h VO (combinada com paracetamol)',
      max: '360 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['4/4h ou 6/6h'],
      instrucoes: 'Sempre combinar com paracetamol (sinergismo, dose menor de ambos). Combinado: paracetamol 500 mg + codeína 30 mg. Avaliar resposta em 24–48h; se inadequada → escalonar para degrau 3 (morfina).',
    },
    contraindicacoes_rapidas: [
      'Metabolizadores ultra-rápidos CYP2D6 (polimorfismo — etnia africana/mediterrânea: > 30%)',
      'Crianças pós-amigdalectomia/adenoidectomia (EUA/Europa: contraindicado por morte)',
      'Insuficiência respiratória grave',
      'Gravidez / lactação',
    ],
    interacoes_importantes: [
      { com: 'inibidores CYP2D6 (fluoxetina, paroxetina)', severidade: 'moderada', descricao: 'Reduzem conversão a morfina → analgesia inadequada' },
    ],
    alertas_especiais: [
      'Pró-fármaco: convertida a morfina por CYP2D6 (polimorfismo). Metabolizadores ultra-rápidos: toxicidade grave por acúmulo de morfina',
      'Menos previsível que morfina direta — em paliativo avançado, preferir morfina',
      'Tosse: 10–20 mg q4–6h (antitussígeno)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Tylex (codeína + paracetamol)', laboratorio: 'Janssen', concentracoes: ['30 mg codeína + 500 mg APAP'], formas: ['Comprimido'] },
      { nome: 'Codeína (genérico)', laboratorio: 'Várias', concentracoes: ['30 mg', '60 mg'], formas: ['Comprimido', 'Solução oral'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── OPIOIDES — DEGRAU 3 WHO ───────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'morfina-paliativa',
    molecula: 'morfina',
    nome_generico: 'Morfina (Cuidados Paliativos)',
    sinonimos: ['MST', 'Dimorf', 'morfina IR', 'morfina LP', 'opioide forte', 'WHO degrau 3'],
    categoria: 'paliativo',
    classe: 'Opioide forte — agonista µ pleno (padrão ouro em cuidados paliativos)',
    indicacoes_principais: [
      'Dor intensa (EVN ≥ 7) — WHO degrau 3',
      'Dispneia refratária em cuidados paliativos',
      'Tosse intratável',
      'Dor irruptiva (resgate)',
    ],
    dose_adulto: {
      habitual: 'NAÏVE (sem opioide prévio): morfina IR 5–10 mg VO q4h + resgate 5 mg q1h SOS | SC: 2,5–5 mg q4h (÷2 da dose oral)',
      max: 'Sem teto de dose — titular pelo efeito e tolerância',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['4/4h (IR)', '12/12h (LP)', 'IC SC em bomba (continuo)'],
      instrucoes: 'NAÏVE: iniciar morfina IR 5 mg q4h VO. Calcular dose total 24h após 24–48h → converter para LP 12/12h. Resgate: 10–15% dose total 24h (IR). Se ≥ 3 resgates/dia: aumentar dose base 25–50%. Converter VO→SC: dividir por 2 (morfina VO 30 mg/dia = SC 15 mg/dia).',
    },
    contraindicacoes_rapidas: [
      'ClCr < 30 mL/min: EVITAR (acúmulo de M6G → sedação prolongada, mioclonias) — preferir fentanil TD ou buprenorfina',
      'Íleo paralítico grave',
    ],
    interacoes_importantes: [
      { com: 'BZD / outros depressores SNC', severidade: 'grave', descricao: 'Depressão respiratória — FDA Black Box; titular cuidadosamente' },
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Síndrome serotoninérgica e crise hipertensiva' },
    ],
    alertas_especiais: [
      '⚠ IR grave: M6G acumula → mioclonias, sedação excessiva — preferir fentanil ou buprenorfina',
      'SEMPRE prescrever laxante osmótico/estimulante ao iniciar opioide (constipação é universal)',
      'Antídoto: naloxona 0,04–0,4 mg IV/SC titulado (não reverter toda a analgesia)',
      'Dispneia: morfina 2,5–5 mg SC q4h alivia sem depressão respiratória em doses analgésicas',
      'Tolerância física: após 1–2 semanas — titular pela necessidade de resgates',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'Reduzir 25–50% / aumentar intervalo para q6h',
      tfg_30_15: 'EVITAR — acúmulo de M6G; considerar fentanil ou buprenorfina',
      tfg_lt_15: 'CONTRAINDICADO — usar fentanil TD ou buprenorfina TD',
      dialisavel: false,
    },
    marcas: [
      { nome: 'Dimorf (morfina)', laboratorio: 'Cristália', concentracoes: ['10 mg/mL (1 mL)', '0,4 mg/mL (5 mL)'], formas: ['Ampola SC/IV', 'Solução oral'] },
      { nome: 'MST Continus (LP)', laboratorio: 'Mundipharma', concentracoes: ['10 mg', '30 mg', '60 mg', '100 mg LP'], formas: ['Comprimido LP 12/12h'] },
      { nome: 'Sevredol (IR)', laboratorio: 'Mundipharma', concentracoes: ['10 mg', '20 mg IR'], formas: ['Comprimido IR 4/4h'] },
    ],
  },
  {
    id: 'oxicodona-paliativa',
    molecula: 'oxicodona',
    nome_generico: 'Oxicodona',
    sinonimos: ['OxyContin', 'Targin', 'oxicodona LP', 'WHO degrau 3'],
    categoria: 'paliativo',
    classe: 'Opioide forte — agonista µ/κ pleno',
    indicacoes_principais: ['Dor intensa — WHO degrau 3', 'Alternativa à morfina (especialmente dor visceral e neuropática)', 'Oxicodona + naloxona (Targin): dor + prevenção de OIC'],
    dose_adulto: {
      habitual: 'NAÏVE: 5–10 mg 4/4h (IR) | LP: 10 mg 12/12h | Targin: 5/2,5 mg a 40/20 mg 12/12h',
      max: 'Sem teto de dose',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['4/4h (IR)', '12/12h (LP / Targin)'],
      instrucoes: 'Equianalgesia: morfina oral 30 mg ≈ oxicodona oral 20 mg. Targin: naloxona periférica reduz constipação sem reverter analgesia central.',
    },
    contraindicacoes_rapidas: ['Insuficiência respiratória grave', 'Íleo paralítico', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'inibidores CYP3A4 (cetoconazol, eritromicina)', severidade: 'moderada', descricao: 'Aumentam nível de oxicodona — monitorar sedação' },
      { com: 'BZD', severidade: 'grave', descricao: 'Depressão respiratória' },
    ],
    alertas_especiais: [
      'Targin (oxicodona LP + naloxona LP): naloxona oral atua localmente no intestino → menos constipação; não deve ser usada em pacientes com desvio hepático (ex.: cirrose grave — naloxona absorve e reverte analgesia)',
      'LP: nunca partir, mastigar ou dissolver (risco de dose dump)',
      'Menos náusea que morfina em alguns pacientes (evidência moderada)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'OxyContin', laboratorio: 'Mundipharma', concentracoes: ['10 mg', '20 mg', '40 mg', '80 mg LP'], formas: ['Comprimido LP 12/12h'] },
      { nome: 'Targin', laboratorio: 'Mundipharma', concentracoes: ['5/2,5 mg', '10/5 mg', '20/10 mg', '40/20 mg'], formas: ['Comprimido LP (oxicodona/naloxona)'] },
    ],
  },
  {
    id: 'fentanil-transdermico',
    molecula: 'fentanil',
    nome_generico: 'Fentanil Transdérmico (Adesivo)',
    sinonimos: ['Durogesic', 'adesivo de fentanil', 'fentanil TD', 'patch opioide'],
    categoria: 'paliativo',
    classe: 'Opioide forte — transdérmico (70h de duração)',
    indicacoes_principais: [
      'Dor crônica estável intensa — alternativa à morfina oral',
      'Pacientes com disfagia ou intolerância à via oral',
      'IR grave (seguro — sem acúmulo)',
      'Melhor tolerabilidade GI (menos constipação que morfina oral)',
    ],
    dose_adulto: {
      habitual: 'Inicial (naïve): 12 mcg/h q72h | Conversão: morfina oral 60 mg/dia ≈ fentanil 25 mcg/h',
      max: 'Sem teto de dose — titular conforme eficácia',
      unidade: 'mcg/h',
      via: 'TD',
      frequencias: ['Trocar a cada 72h (3 dias) — some locais: q48h em catabólicos'],
      instrucoes: 'Aplicar em pele íntegra, seca, sem pelos (tórax, braço, dorso). Rodar sítio. Onset: 12–24h após aplicação. Manter morfina IR como resgate nas primeiras 24h. Febre ou diaforese: absorção aumenta → monitorar toxicidade. Descontinuação: efeito persiste 24h após retirada.',
    },
    contraindicacoes_rapidas: [
      'Dor aguda / instável (não adequado para titular rapidamente)',
      'Febre recorrente ou diaforese (absorção variável)',
      'NÃO aplicar sobre pele irritada, queimada, radiada',
    ],
    interacoes_importantes: [
      { com: 'inibidores CYP3A4', severidade: 'moderada', descricao: 'Aumentam exposição ao fentanil — monitorar sedação' },
      { com: 'BZD / depressores SNC', severidade: 'grave', descricao: 'Depressão respiratória' },
    ],
    alertas_especiais: [
      '⚠ NÃO cortar o adesivo (altera cinética de liberação)',
      'Retirada: meia-vida TD prolongada (~20h após remoção) — sintomas de abstinência podem surgir apenas no D2',
      'IR grave: fentanil TD é opioide de escolha (< 1% excretado inalterado pelo rim)',
      'Descarte: dobrar adesivo usado sobre si mesmo (fentanil residual) e descartar em local seguro (crianças e animais)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'Dose plena — monitorar',
      tfg_30_15: 'PREFERÊNCIA sobre morfina — dose plena, monitorar',
      tfg_lt_15: 'OPIOIDE DE ESCOLHA na IR grave (sem acúmulo renal)',
      dialisavel: false,
    },
    marcas: [
      { nome: 'Durogesic', laboratorio: 'Janssen', concentracoes: ['12 mcg/h', '25 mcg/h', '50 mcg/h', '75 mcg/h', '100 mcg/h'], formas: ['Adesivo transdérmico 72h'] },
      { nome: 'Fentanil TD (genérico)', laboratorio: 'Eurofarma / Cristália', concentracoes: ['25 mcg/h', '50 mcg/h', '100 mcg/h'], formas: ['Adesivo transdérmico 72h'] },
    ],
  },
  {
    id: 'buprenorfina-transdermico',
    molecula: 'buprenorfina',
    nome_generico: 'Buprenorfina Transdérmica',
    sinonimos: ['Norspan', 'BuTrans', 'agonista parcial opioide TD', 'opioide IR seguro'],
    categoria: 'paliativo',
    classe: 'Agonista µ parcial — transdérmico (seguro em IR/IH)',
    indicacoes_principais: ['Dor moderada a intensa em pacientes com IR grave', 'Dor crônica oncológica e não oncológica', 'Alternativa à morfina/fentanil TD'],
    dose_adulto: {
      habitual: '5–20 mcg/h adesivo q7 dias (Norspan) | 35–70 mcg/h q4 dias (BuTrans/Transtec)',
      max: '70 mcg/h (Transtec)',
      unidade: 'mcg/h',
      via: 'TD',
      frequencias: ['Trocar a cada 7 dias (Norspan) ou 4 dias (Transtec)'],
      instrucoes: 'Norspan (5/10/20 mcg/h): troca semanal. Transtec (35/52,5/70 mcg/h): troca a cada 4 dias. Conversão: buprenorfina TD 35 mcg/h ≈ morfina oral 60 mg/dia.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade', 'Uso concomitante com IMAO'],
    interacoes_importantes: [
      { com: 'outros opioides fortes', severidade: 'moderada', descricao: 'Agonismo parcial pode antagonizar parcialmente opioides plenos em doses altas' },
    ],
    alertas_especiais: [
      'SEGURO EM IR GRAVE: metabolismo hepático, excreção biliar — sem acúmulo renal',
      'Agonista PARCIAL µ: teto de efeito analgésico em altas doses — para dor muito intensa, considerar rotação para agonista pleno',
      'Naloxona é eficaz como antídoto mesmo com agonismo parcial (doses maiores podem ser necessárias)',
      'Sublingual (comprimido): alternativa para ajuste de dose',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Norspan', laboratorio: 'Mundipharma', concentracoes: ['5 mcg/h', '10 mcg/h', '20 mcg/h'], formas: ['Adesivo TD 7 dias'] },
      { nome: 'Transtec', laboratorio: 'Grünenthal', concentracoes: ['35 mcg/h', '52,5 mcg/h', '70 mcg/h'], formas: ['Adesivo TD 4 dias'] },
    ],
  },
  {
    id: 'hidromorfona',
    molecula: 'hidromorfona',
    nome_generico: 'Hidromorfona',
    sinonimos: ['Dilaudid', 'hidromorphone', 'opioide forte alternativo'],
    categoria: 'paliativo',
    classe: 'Opioide forte — agonista µ pleno (análogo hidrogenado da morfina)',
    indicacoes_principais: ['Rotação de opioide por efeitos colaterais da morfina', 'Dor intensa — WHO degrau 3', 'Alternativa SC em paciente com volume limitado'],
    dose_adulto: {
      habitual: 'VO: 2–4 mg 4/4h | SC: 0,5–1,5 mg 4/4h | IC SC: 3–12 mg/24h',
      max: 'Sem teto de dose — titular',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['4/4h (IR)', 'IC SC (bomba)'],
      instrucoes: 'Conversão: morfina oral 30 mg ≈ hidromorfona oral 4–6 mg (fator 5–7,5:1). Morfina SC 10 mg ≈ hidromorfona SC 1,5–2 mg. Útil quando volume SC precisa ser mínimo (alta potência).',
    },
    contraindicacoes_rapidas: ['IR grave (metabólito H3G pode causar neuroexcitação)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'BZD', severidade: 'grave', descricao: 'Depressão respiratória' },
    ],
    alertas_especiais: [
      'Potência SC: ~5× maior que morfina SC — atenção ao converter (erros de dose graves)',
      'Metabólito H3G: neuroexcitatório — monitorar mioclonias/agitação em IR moderada',
      'Alta concentração: vantagem em infusões SC (volume menor)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Dilaudid (importado)', laboratorio: 'Várias', concentracoes: ['2 mg', '4 mg'], formas: ['Comprimido', 'Ampola SC/IV'] }],
  },
  {
    id: 'metadona-paliativa',
    molecula: 'metadona',
    nome_generico: 'Metadona',
    sinonimos: ['cloridrato de metadona', 'dolophine', 'WHO degrau 3 especial', 'NMDA antagonista opioide'],
    categoria: 'paliativo',
    classe: 'Opioide forte — agonista µ pleno + antagonista NMDA + inibidor recaptação serotonina',
    indicacoes_principais: [
      'Dor neuropática refratária a outros opioides',
      'Rotação em altas doses de morfina/oxicodona (custo-efetiva)',
      'Dependência a opioides (tratamento de substituição)',
    ],
    dose_adulto: {
      habitual: 'Conversão complexa — NÃO linear: depende da dose prévia de morfina. Iniciar 5–10 mg 12/12h com titulação lenta',
      max: 'Sem teto — titular com cuidado extremo',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['8/8h ou 12/12h'],
      instrucoes: 'CONVERSÃO NÃO LINEAR: morfina 30–90 mg/dia → fator 4:1; morfina 90–300 mg/dia → fator 8:1; morfina > 300 mg/dia → fator 12:1. REDUÇÃO 30% por tolerância cruzada incompleta. SEMPRE prescrever por especialista. Monitorar QTc (ECG antes e após aumento de dose).',
    },
    contraindicacoes_rapidas: [
      'QTc > 500 ms',
      'Arritmia ventricular',
      'Uso com fármacos que prolongam QT sem avaliação de especialista',
    ],
    interacoes_importantes: [
      { com: 'antifúngicos azólicos', severidade: 'grave', descricao: 'Inibição CYP3A4 → ↑ metadona → acúmulo tardio e prolongamento QT' },
      { com: 'rifampicina / fenitoína', severidade: 'grave', descricao: 'Indutores CYP → ↓ nível de metadona → abstinência ou inadequado controle de dor' },
      { com: 'amiodarona / sotalol', severidade: 'grave', descricao: 'Torsades de pointes' },
    ],
    alertas_especiais: [
      '⚠ MEIA-VIDA VARIÁVEL 24–150h: acúmulo silencioso → sedação/depressão respiratória D3–D5',
      '⚠ ECG OBRIGATÓRIO: antes, 24–72h após início e a cada aumento de dose',
      'VANTAGEM: custo baixo, antagonismo NMDA (dor neuropática refratária), sem metabólito acumulável em IR',
      'CONVERTER APENAS COM ESPECIALISTA em cuidados paliativos ou dor',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Metadona (genérico)', laboratorio: 'Cristália', concentracoes: ['5 mg', '10 mg'], formas: ['Comprimido', 'Solução oral 1 mg/mL'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── SEDAÇÃO PALIATIVA ─────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'midazolam-paliativo',
    molecula: 'midazolam',
    nome_generico: 'Midazolam (Sedação Paliativa / SC)',
    sinonimos: ['Dormicum', 'sedação terminal', 'midazolam SC', 'agitação terminal'],
    categoria: 'paliativo',
    classe: 'Benzodiazepínico — sedativo-hipnótico (GABA-A)',
    indicacoes_principais: [
      'Sedação paliativa proporcional (delirium / agitação refratária)',
      'Sedação paliativa profunda (sofrimento existencial refratário / agonia)',
      'Ansiedade refratária em fim de vida',
      'Dispneia refratária (adjuvante à morfina)',
      'Convulsões em fase agônica',
    ],
    dose_adulto: {
      habitual: 'Sedação proporcional: 2,5–5 mg SC q4h + SOS 2,5 mg SC q1h | IC SC: 10–30 mg/24h',
      max: 'Sem teto absoluto em sedação paliativa — titular pelo RASS alvo',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['4/4h (bolus horário) ou IC 24h (bomba SC)'],
      instrucoes: 'IC SC PREFERÍVEL (estabilidade sérica): diluir em bomba de seringa (compatível com morfina/haloperidol/hioscina). Resgate: 1/6 da dose diária SC. Titular RASS -2 a -3 (proporcional) ou -4 a -5 (profunda). Aumentar 25–50% a cada 24h se resgates ≥ 3.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade a BZD', 'Glaucoma ângulo fechado não tratado'],
    interacoes_importantes: [
      { com: 'morfina SC (mesma seringa)', severidade: 'leve', descricao: 'Compatível em mesma bomba SC — combinação comum em paliativo' },
      { com: 'haloperidol SC', severidade: 'leve', descricao: 'Compatível em bomba (verificar estabilidade antes)' },
    ],
    alertas_especiais: [
      'ÉTICA: documentar indicação, consentimento e RASS seriado no prontuário',
      'IC SC: compatível com morfina, haloperidol, hioscina (verificar compatibilidade de mistura)',
      'Antídoto: flumazenil 0,2 mg IV (meia-vida curta — pode ressedir; usar em toxicidade acidental, não reverter sedação paliativa)',
      'Sedação paliativa ≠ eutanásia: intenção é alívio de sofrimento refratário',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Dormicum', laboratorio: 'Roche', concentracoes: ['5 mg/mL (5 mL)', '1 mg/mL (5 mL)'], formas: ['Ampola SC/IV'] },
      { nome: 'Midazolam (genérico)', laboratorio: 'Cristália', concentracoes: ['5 mg/mL'], formas: ['Ampola SC/IV'] },
    ],
  },
  {
    id: 'fenobarbital-paliativo',
    molecula: 'fenobarbital',
    nome_generico: 'Fenobarbital (Sedação Paliativa Refratária)',
    sinonimos: ['gardenal', 'barbitúrico sedação terminal', 'sedação refratária'],
    categoria: 'paliativo',
    classe: 'Barbitúrico — modulador GABA-A (sedação mais profunda que BZD)',
    indicacoes_principais: [
      'Sedação paliativa quando midazolam insuficiente',
      'Status epiléptico em fase agônica',
      'Agitação terminal refratária',
    ],
    dose_adulto: {
      habitual: 'Inicial: 50–100 mg SC/IV q6–12h | IC SC: 200–600 mg/24h (refratário: até 1200 mg/24h)',
      max: '1200 mg/24h IC SC (sedação profunda refratária)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['6/6h ou 12/12h (bolus) | IC SC (bomba)'],
      instrucoes: 'Usar quando midazolam IC ≥ 60 mg/24h sem controle adequado. Atenção à compatibilidade: fenobarbital SC geralmente em bomba separada (precipita com muitos fármacos). Diluir em SF ou AD.',
    },
    contraindicacoes_rapidas: ['Porfiria aguda intermitente'],
    interacoes_importantes: [
      { com: 'midazolam / BZD', severidade: 'moderada', descricao: 'Sinergismo sedativo — usar combinação com titulação cuidadosa' },
    ],
    alertas_especiais: [
      '2ª linha após midazolam em sedação paliativa',
      'SC: irritação local — diluição e rotação de sítio importantes',
      'Indutor enzimático (CYP 3A4, 2C): irrelevante em fase terminal',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Gardenal', laboratorio: 'Sanofi', concentracoes: ['100 mg/mL (1 mL)'], formas: ['Ampola IV/SC'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── DELIRIUM / AGITAÇÃO ───────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'haloperidol-paliativo',
    molecula: 'haloperidol',
    nome_generico: 'Haloperidol',
    sinonimos: ['Haldol', 'antipsicótico típico', 'delirium paliativo', 'náusea opioide'],
    categoria: 'paliativo',
    classe: 'Antipsicótico típico — antagonista D2 (butirofenona)',
    indicacoes_principais: [
      'Delirium / agitação em cuidados paliativos (1ª linha)',
      'Náusea e vômito (antiemético central — 2ª linha)',
      'Agitação terminal',
    ],
    dose_adulto: {
      habitual: 'Delirium leve: 0,5–1 mg SC/VO 8/8h–12/12h | Delirium grave: 2,5–5 mg SC q4–6h + SOS 1–2 mg SC q1h',
      max: '10–20 mg/24h (IC SC)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['8/8h ou 12/12h (delirium leve)', 'IC SC (agitação intensa)'],
      instrucoes: 'Via SC: compatível com morfina e midazolam em bomba. IC SC: 5–20 mg/24h. Iniciar baixo e titular pelo CAM/agitação. Náusea: 0,5–1 mg SC/VO 8/8h.',
    },
    contraindicacoes_rapidas: [
      'Doença de Parkinson (piora parkinsonismo — preferir quetiapina)',
      'QTc > 500 ms',
      'Corpos de Lewy (piora drasticamente)',
    ],
    interacoes_importantes: [
      { com: 'amiodarona / sotalol', severidade: 'grave', descricao: 'QT prolongado — torsades de pointes' },
      { com: 'lítio', severidade: 'moderada', descricao: 'Neurotoxicidade' },
    ],
    alertas_especiais: [
      'Parkinson e corpos de Lewy: CONTRAINDICADO — usar quetiapina 12,5–25 mg/noite',
      'EPS: menos provável em doses baixas SC; monitorar rigidez, acatisia',
      'Haloperidol IV/SC: mais rápido onset que VO — preferir SC em paliativo',
      'Compatível em bomba SC com morfina e midazolam (verificar concentração)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Haldol', laboratorio: 'Janssen', concentracoes: ['5 mg/mL (1 mL)'], formas: ['Ampola SC/IV/IM', 'Comprimido 1 mg / 5 mg', 'Gotas 2 mg/mL'] },
      { nome: 'Haloperidol (genérico)', laboratorio: 'Várias', concentracoes: ['5 mg/mL'], formas: ['Ampola', 'Comprimido'] },
    ],
  },
  {
    id: 'levomepromazina',
    molecula: 'levomepromazina',
    nome_generico: 'Levomepromazina (Metotrimeprazina)',
    sinonimos: ['Neozine', 'antipsicótico sedativo', 'multimodal paliativo', 'levomepromazina SC'],
    categoria: 'paliativo',
    classe: 'Antipsicótico fenotiazínico sedativo — antagonista D2, H1, M1, α1, 5-HT2',
    indicacoes_principais: [
      'Delirium refratário em paliativo (mais sedativo que haloperidol)',
      'Náusea refratária (antiemético multimodal)',
      'Agitação terminal',
      'Sedação paliativa adjuvante',
    ],
    dose_adulto: {
      habitual: 'Delirium: 6,25–12,5 mg SC q6–8h | Náusea: 3,125–6,25 mg SC q6–8h | IC SC: 25–100 mg/24h',
      max: '200 mg/24h',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['6/6h ou 8/8h (bolus) | IC SC (bomba)'],
      instrucoes: 'SC: preferível em paliativo. Hipotensão: monitorar (efeito α1). Diluir bem (irritação local).',
    },
    contraindicacoes_rapidas: ['Doença de Parkinson grave', 'Hipotensão grave'],
    interacoes_importantes: [
      { com: 'outros antipsicóticos', severidade: 'moderada', descricao: 'Potencialização de EPS e prolongamento QT' },
    ],
    alertas_especiais: [
      'Sedação mais intensa que haloperidol — útil quando se quer algum grau de sedação junto ao controle do delirium',
      'Hipotensão postural: relevante em idosos — monitorar PA',
      'Fotossensibilidade: menos relevante em fase terminal',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [{ nome: 'Neozine', laboratorio: 'Sanofi', concentracoes: ['25 mg/mL (1 mL)'], formas: ['Ampola SC/IV/IM'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── DISPNEIA / ANSIEDADE ──────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'lorazepam-paliativo',
    molecula: 'lorazepam',
    nome_generico: 'Lorazepam',
    sinonimos: ['Ativan', 'ansiolítico paliativo', 'dispneia ansiedade', 'BZD sublingual'],
    categoria: 'paliativo',
    classe: 'Benzodiazepínico de ação intermediária (sem metabólito ativo)',
    indicacoes_principais: [
      'Ansiedade em cuidados paliativos',
      'Dispneia com componente ansioso significativo',
      'Convulsões agudas (status epiléptico em fase agônica)',
      'Insônia em paciente com dor ou dispneia',
    ],
    dose_adulto: {
      habitual: '0,5–1 mg SL / SC / VO 6/6h–8/8h | Convulsão: 4 mg IV lento',
      max: '4 mg/dose (convulsão) | 4–6 mg/dia (paliativo)',
      unidade: 'mg',
      via: 'Sublingual',
      frequencias: ['6/6h ou 8/8h', 'SOS q2–4h se ansiedade aguda'],
      instrucoes: 'SL: absorção rápida sem acesso venoso. SC: compatível com midazolam. Vantagem sobre midazolam oral: sem metabólito ativo (útil em IH/IR). Via sublingual: colocar sob a língua e aguardar dissolução.',
    },
    contraindicacoes_rapidas: ['Insuficiência respiratória grave sem suporte ventilatório (relativa)'],
    interacoes_importantes: [
      { com: 'opioides', severidade: 'moderada', descricao: 'Sinergismo sedativo e depressão respiratória — combinar com cautela' },
    ],
    alertas_especiais: [
      'SEM metabólito ativo: seguro em IH e IR moderada (vs. diazepam/midazolam — acumulam)',
      'Via SL: útil em fase final sem acesso venoso (absorção em 2–5 min)',
      'Antídoto: flumazenil (meia-vida curta — monitorar ressedação)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Ativan', laboratorio: 'Pfizer', concentracoes: ['1 mg/mL', '2 mg/mL'], formas: ['Comprimido 1/2 mg', 'Ampola IV/SC'] },
      { nome: 'Lorazepam (genérico)', laboratorio: 'Várias', concentracoes: ['1 mg', '2 mg'], formas: ['Comprimido', 'Ampola'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── NÁUSEA / VÔMITO ───────────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'metoclopramida-paliativa',
    molecula: 'metoclopramida',
    nome_generico: 'Metoclopramida',
    sinonimos: ['Plasil', 'procinético', 'antiemético paliativo', 'gastroparesia'],
    categoria: 'paliativo',
    classe: 'Antagonista D2 / 5-HT4 agonista — antiemético + procinético',
    indicacoes_principais: [
      'Náusea por gastroparesia em cuidados paliativos',
      'Náusea por opioide (início do tratamento)',
      'Obstrução intestinal funcional (íleo paralítico)',
      'Soluço persistente (off-label)',
    ],
    dose_adulto: {
      habitual: '10 mg SC/VO/IV 8/8h (antes das refeições) | IC SC: 30–60 mg/24h',
      max: '60 mg/dia (5 dias consecutivos máximo — ANVISA)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['8/8h (preferir antes das refeições)'],
      instrucoes: 'SC: compatível com morfina e midazolam em bomba. Evitar em obstrução mecânica. Limitar a 5 dias consecutivos (EPS). Em idosos: 5 mg 8/8h.',
    },
    contraindicacoes_rapidas: [
      'Obstrução intestinal mecânica (procinético piora)',
      'Feocromocitoma',
      'Doença de Parkinson (piora)',
      'Epilepsia (abaixa limiar)',
    ],
    interacoes_importantes: [
      { com: 'haloperidol / antipsicóticos', severidade: 'moderada', descricao: 'EPS aditivo — evitar combinação prolongada' },
    ],
    alertas_especiais: [
      'ANVISA: limitar a 5 dias consecutivos (risco de discinesia tardia)',
      'EPS: mais raro em SC que VO, mas possível (distonia, acatisia, discinesia)',
      'Obstrução mecânica: CONTRAINDICADA (perfuração) — usar haloperidol/dexametasona/octreotida',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Plasil', laboratorio: 'Sanofi', concentracoes: ['10 mg/2 mL (5 mg/mL)'], formas: ['Ampola SC/IV', 'Comprimido 10 mg', 'Gotas'] },
      { nome: 'Metoclopramida (genérico)', laboratorio: 'Várias', concentracoes: ['5 mg/mL'], formas: ['Ampola SC/IV', 'Comprimido'] },
    ],
  },
  {
    id: 'ondansetrona-paliativa',
    molecula: 'ondansetrona',
    nome_generico: 'Ondansetrona',
    sinonimos: ['Zofran', '5-HT3 antagonista', 'antiemético paliativo'],
    categoria: 'paliativo',
    classe: 'Antagonista 5-HT3 — antiemético central e periférico',
    indicacoes_principais: [
      'Náusea e vômito em cuidados paliativos (2ª linha)',
      'Náusea por opioides refratária a haloperidol/metoclopramida',
      'Náusea pós-quimioterapia em paliativo',
    ],
    dose_adulto: {
      habitual: '4–8 mg SC/VO/IV 8/8h',
      max: '24 mg/dia',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['8/8h ou 12/12h'],
      instrucoes: 'SC: usar ampola IV diluída. ODT (comprimido orodispersível 4/8 mg): útil em disfagia leve. Constipação: efeito adverso frequente (não usar como 1ª linha se constipação concomitante).',
    },
    contraindicacoes_rapidas: ['Síndrome do QT longo', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'apomorfina', severidade: 'contraindicado', descricao: 'Hipotensão grave' },
    ],
    alertas_especiais: [
      'Constipação: efeito adverso relevante em paliativo (pacientes já em opioide)',
      'Preferir haloperidol SC como 1ª linha para náusea em paliativo avançado (menor custo, também antiemético central)',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Zofran', laboratorio: 'Novartis', concentracoes: ['2 mg/mL (2 mL)', '4 mg/5 mL'], formas: ['Ampola IV', 'Comprimido 4/8 mg', 'ODT'] },
      { nome: 'Ondansetrona (genérico)', laboratorio: 'EMS / Eurofarma', concentracoes: ['2 mg/mL'], formas: ['Ampola', 'Comprimido'] },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // ── ESTERTORES / SECREÇÕES ────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'hioscina-butilbrometo',
    molecula: 'hioscina butilbrometo',
    nome_generico: 'Hioscina Butilbrometo (Escopolamina Butilbrometo)',
    sinonimos: ['Buscopan', 'butilescopolamina', 'estertores terminais', 'anticolinérgico periférico'],
    categoria: 'paliativo',
    classe: 'Anticolinérgico quaternário — antagonista muscarínico periférico (não cruza BHE)',
    indicacoes_principais: [
      'Estertores terminais / secreção ruidosa em fase agônica (1ª linha)',
      'Cólica e espasmos GI / biliares em cuidados paliativos',
      'Obstrução intestinal maligna (reduz secreções GI)',
    ],
    dose_adulto: {
      habitual: '20 mg SC q4h | IC SC: 60–120 mg/24h',
      max: '120–200 mg/24h',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['4/4h (bolus) | IC 24h (bomba SC)'],
      instrucoes: 'IC SC: compatível com morfina e midazolam na mesma bomba (verificar estabilidade). Não cruza BHE: sem sedação central, sem confusão — ativo apenas em secreções periféricas.',
    },
    contraindicacoes_rapidas: ['Taquicardia grave não controlada (relativa)', 'Glaucoma ângulo fechado'],
    interacoes_importantes: [
      { com: 'morfina SC', severidade: 'leve', descricao: 'Compatível em bomba SC — combinação frequente em paliativo' },
    ],
    alertas_especiais: [
      'NÃO cruza barreira hematoencefálica (BHE): sem efeito sedativo central, sem confusão (vs atropina)',
      'Não aspirar secreções: piora produção; reposicionamento + hioscina são suficientes',
      'Explicar à família: estertores causam angústia aos familiares, não ao paciente inconsciente',
      'Boca seca: cuidados de higiene oral mais frequentes',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Buscopan', laboratorio: 'Boehringer Ingelheim', concentracoes: ['20 mg/mL (1 mL)', '10 mg/5 mL (VO)'], formas: ['Ampola SC/IV', 'Drágea 10 mg', 'Supositório'] },
      { nome: 'Hioscina Butilbrometo (genérico)', laboratorio: 'Várias', concentracoes: ['20 mg/mL'], formas: ['Ampola SC/IV'] },
    ],
  },
  {
    id: 'glicopirronio-sc',
    molecula: 'Glicopirrônio SC/IV',
    nome_generico: 'Glicopirronato (Glicopirrônio — uso SC/IV paliativo)',
    sinonimos: ['Robinul', 'anticolinérgico estertores', 'glicopirrolate', 'glicopirronio sc', 'glicopirronio iv'],
    categoria: 'paliativo',
    classe: 'Anticolinérgico quaternário — antagonista muscarínico periférico',
    indicacoes_principais: ['Estertores terminais (alternativa à hioscina)', 'Sialorréia (drooling)'],
    dose_adulto: {
      habitual: '0,2 mg SC q4–6h | IC SC: 0,6–1,2 mg/24h',
      max: '2,4 mg/24h',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['4/4h ou 6/6h (bolus) | IC SC'],
      instrucoes: 'Compatível com morfina/midazolam em bomba SC. Potência similar à hioscina butilbrometo.',
    },
    contraindicacoes_rapidas: ['Glaucoma ângulo fechado', 'Hipersensibilidade'],
    interacoes_importantes: [],
    alertas_especiais: [
      'Não cruza BHE — sem efeito central (vantagem sobre atropina)',
      'Alternativa à hioscina butilbrometo quando não disponível',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [{ nome: 'Robinul', laboratorio: 'Fresenius / Importado', concentracoes: ['0,2 mg/mL (1 mL)'], formas: ['Ampola SC/IV'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── CONSTIPAÇÃO POR OPIOIDE (OIC) ────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'metilnaltrexona',
    molecula: 'metilnaltrexona',
    nome_generico: 'Metilnaltrexona',
    sinonimos: ['Relistor', 'PAMORA', 'constipação opioide', 'antagonista periférico µ'],
    categoria: 'paliativo',
    classe: 'Antagonista opioide periférico (PAMORA) — bloqueio intestinal sem reverter analgesia central',
    indicacoes_principais: ['Constipação induzida por opioide (OIC) refratária a laxantes convencionais', 'OIC em cuidados paliativos avançados'],
    dose_adulto: {
      habitual: '< 62 kg: 8 mg SC | 62–114 kg: 12 mg SC | > 114 kg: 0,15 mg/kg SC — 1 dose/dia (max qod)',
      max: '12 mg/dose (ou 0,15 mg/kg)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1 dose/dia (diária ou em dias alternados)'],
      instrucoes: 'Injetar em abdome, coxa ou braço. Efeito em 30–60 min (evacuação em 50% dos casos). Manter laxantes convencionais. NÃO usar se suspeita de obstrução mecânica.',
    },
    contraindicacoes_rapidas: ['Obstrução intestinal mecânica conhecida ou suspeita (risco de perfuração)', 'Hipersensibilidade'],
    interacoes_importantes: [],
    alertas_especiais: [
      'NÃO reverte analgesia central (antagonista periférico — não cruza BHE)',
      'OIC: desenvolve em 90% dos em uso crônico de opioides — prevenir profilaticamente',
      'Dor abdominal severa após dose: suspender e investigar (possível perfuração em diverticulite/obstrução)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    ajuste_renal: {
      normal: 'Dose plena',
      tfg_60_30: 'Dose plena',
      tfg_30_15: 'Reduzir dose à metade',
      tfg_lt_15: 'Contraindicado',
      dialisavel: false,
    },
    marcas: [{ nome: 'Relistor', laboratorio: 'Bausch Health / Pfizer', concentracoes: ['12 mg/0,6 mL'], formas: ['Seringa pré-cheia SC', 'Comprimido 150 mg'] }],
  },

  // ══════════════════════════════════════════════════════════
  // ── ADJUVANTES PALIATIVOS ─────────────────────────────────
  // ══════════════════════════════════════════════════════════
  {
    id: 'dexametasona-paliativa',
    molecula: 'dexametasona',
    nome_generico: 'Dexametasona (Paliativo — Múltiplas Indicações)',
    sinonimos: ['Decadron', 'corticoide paliativo', 'dexametasona SC', 'anti-inflamatório paliativo'],
    categoria: 'paliativo',
    classe: 'Corticosteroide — glicocorticoide (potência relativa: 1 mg dex ≈ 7 mg prednisona)',
    indicacoes_principais: [
      'Compressão medular metastática (dose alta — emergência)',
      'Hipertensão intracraniana por tumor (edema perilesional)',
      'Dor por compressão nervosa / inflamação perilesional',
      'Anorexia / estimulante de apetite (degrau paliativo)',
      'Náusea refratária',
      'Dispneia por linfangite / obstrução vias aéreas',
      'Obstrução intestinal maligna (adjuvante)',
    ],
    dose_adulto: {
      habitual: 'Compressão medular: 16 mg/dia IV/SC (dexametasona) | Edema cerebral: 8–16 mg/dia | Sintomas gerais: 2–8 mg/dia VO/SC',
      max: '16 mg/dia (agudo) | 4–8 mg/dia (crônico)',
      unidade: 'mg',
      via: 'SC',
      frequencias: ['1×/dia (manhã) para menor insônia | 2×/dia se dose alta'],
      instrucoes: 'MANHÃ: administrar pela manhã para reduzir insônia. Compressão medular: dexametasona 16 mg IV/SC imediato + RT urgente (emergência). SC: compatível com morfina em bomba (concentrações específicas).',
    },
    contraindicacoes_rapidas: ['Infecção fúngica sistêmica sem cobertura (relativa)', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'AINEs', severidade: 'moderada', descricao: 'Risco GI aditivo — IBP profilático' },
      { com: 'insulina / hipoglicemiantes', severidade: 'moderada', descricao: 'Hiperglicemia — monitorar e ajustar' },
    ],
    alertas_especiais: [
      'Duração: efeito a curto prazo (4–8 semanas); após prolongado → benefício decai e efeitos adversos aumentam',
      'Hiperglicemia: monitorar (relevante mesmo em paliativo — desconforto)',
      'Suspensão após uso prolongado (> 2 semanas): redução gradual (insuficiência adrenal)',
      'Candidose oral: frequente com uso prolongado — nistatina profilática',
      'Úlcera péptica: IBP profilático se uso ≥ 2 semanas ou combinado com AINE',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Decadron', laboratorio: 'Ache', concentracoes: ['0,5 mg', '0,75 mg', '4 mg (comp)'], formas: ['Comprimido', 'Ampola 4 mg/mL', 'Ampola 10 mg/2,5 mL'] },
      { nome: 'Dexametasona (genérico)', laboratorio: 'Várias', concentracoes: ['4 mg/mL'], formas: ['Ampola SC/IV'] },
    ],
  },
  {
    id: 'gabapentina-paliativa',
    molecula: 'gabapentina',
    nome_generico: 'Gabapentina (Dor Neuropática — Paliativo)',
    sinonimos: ['Neurontin', 'adjuvante dor neuropática', 'canal cálcio antagonista'],
    categoria: 'paliativo',
    classe: 'Análogo GABA — modulador de canais de cálcio (α2δ) — antineuropático',
    indicacoes_principais: ['Dor neuropática (queimação, choque, parestesias)', 'Adjuvante em dor mista oncológica', 'Prurido (off-label, especialmente urêmico)', 'Calafrios (quimioterapia, tamoxifeno — off-label)'],
    dose_adulto: {
      habitual: 'Início: 100–300 mg/noite → titular 300 mg 8/8h em 1–2 semanas',
      max: '3600 mg/dia (dor neuropática)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['8/8h ou 6/6h'],
      instrucoes: 'Titular lentamente (sonolência, tontura dose-dependente). Idosos: iniciar 100 mg/noite. Reduzir dose em IR. Efeito pleno em 2–4 semanas.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'opioides / BZD', severidade: 'moderada', descricao: 'Depressão do SNC e respiratória aditiva — FDA 2019 alerta' },
      { com: 'antiácidos com alumínio/magnésio', severidade: 'leve', descricao: 'Reduzem absorção de gabapentina' },
    ],
    alertas_especiais: [
      'FDA 2019: risco de depressão respiratória em combinação com opioides/BZD — monitorar',
      'Ajuste renal obrigatório: ClCr < 60 → reduzir dose',
      'Sonolência e tontura: frequentes inicialmente — melhoram com titulação lenta',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    ajuste_renal: {
      normal: 'Até 3600 mg/dia',
      tfg_60_30: 'Máx 700 mg/dia (dividir q12h)',
      tfg_30_15: 'Máx 300 mg/dia',
      tfg_lt_15: 'Máx 150 mg/dia (150 mg em dias alternados)',
      dialisavel: true,
    },
    marcas: [
      { nome: 'Neurontin', laboratorio: 'Pfizer', concentracoes: ['100 mg', '300 mg', '400 mg'], formas: ['Cápsula'] },
      { nome: 'Gabapentina (genérico)', laboratorio: 'EMS / Merck', concentracoes: ['300 mg', '400 mg'], formas: ['Cápsula', 'Comprimido'] },
    ],
  },
  {
    id: 'amitriptilina-paliativa',
    molecula: 'amitriptilina',
    nome_generico: 'Amitriptilina (Dor Neuropática — Paliativo)',
    sinonimos: ['Tryptanol', 'antidepressivo tricíclico', 'adjuvante dor neuropática', 'TCA'],
    categoria: 'paliativo',
    classe: 'Antidepressivo tricíclico (TCA) — inibidor recaptação NE/5-HT + anticolinérgico',
    indicacoes_principais: ['Dor neuropática (1ª linha adjuvante — queimação, alodínia)', 'Insônia em cuidados paliativos', 'Depressão em paliativo (dose antidepressiva — 75–150 mg)'],
    dose_adulto: {
      habitual: 'Dor neuropática: 10–25 mg/noite → titular 75 mg/noite (dose analgésica)',
      max: '150 mg/noite (analgesia) | 300 mg/dia (antidepressivo — raramente em paliativo)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/noite (sedação — administrar à noite)'],
      instrucoes: 'Iniciar 10 mg/noite em idosos. Titular 10–25 mg/semana. Efeito analgésico: independente do antidepressivo (menor dose).',
    },
    contraindicacoes_rapidas: [
      'IAM recente (< 6 meses)',
      'BAV 2°/3°',
      'Glaucoma ângulo fechado',
      'Retenção urinária',
      'Idosos com demência (risco delirium anticolinérgico)',
    ],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Crise hipertensiva / síndrome serotoninérgica' },
      { com: 'tramadol', severidade: 'moderada', descricao: 'Síndrome serotoninérgica' },
    ],
    alertas_especiais: [
      'Efeitos anticolinérgicos: boca seca, constipação, retenção urinária — relevantes em paliativo',
      'Idosos: risco de delirium anticolinérgico — preferir nortriptilina (menos anticolinérgica) ou gabapentina',
      'Tontura ortostática: avaliar risco de queda',
      'Efeito analgésico: semanas; efeito hipnótico: imediato',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Tryptanol', laboratorio: 'Aspen', concentracoes: ['10 mg', '25 mg', '75 mg'], formas: ['Comprimido'] },
      { nome: 'Amitriptilina (genérico)', laboratorio: 'Várias', concentracoes: ['10 mg', '25 mg'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'octreotida-paliativa',
    molecula: 'octreotida',
    nome_generico: 'Octreotida (Obstrução Intestinal Maligna)',
    sinonimos: ['Sandostatin', 'análogo somatostatina', 'OIM paliativo', 'redução secreções GI'],
    categoria: 'paliativo',
    classe: 'Análogo da somatostatina — inibidor de secreções GI e pancreáticas',
    indicacoes_principais: [
      'Obstrução intestinal maligna inoperável (1ª linha — reduz náusea/vômito e volume de secreções)',
      'Fístula enterocutânea de alto débito',
      'Diarreia refratária em paliativo (carcinoide, VIPoma)',
    ],
    dose_adulto: {
      habitual: '100–300 mcg SC 8/8h ou IC SC 300–600 mcg/24h',
      max: '600 mcg/24h (OIM)',
      unidade: 'mcg',
      via: 'SC',
      frequencias: ['8/8h (bolus) ou IC SC 24h'],
      instrucoes: 'OIM inoperável: octreotida + haloperidol + dexametasona SC (protocolo de 3 fármacos). IC SC: diluir em SF compatível em bomba. Reduz débito de vômitos e náusea em OIM mesmo sem reverter a obstrução.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'insulina / antidiabéticos', severidade: 'moderada', descricao: 'Altera glicemia (inibe insulina e glucagon)' },
    ],
    alertas_especiais: [
      'OIM paliativo: náusea/vômito — octreotida + haloperidol + dexametasona SC é protocolo de referência',
      'Hiperglicemia: monitorar em diabéticos',
      'Colelitíase: uso prolongado (> 6 meses) → cálculos biliares (irrelevante em fase terminal)',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Sandostatin', laboratorio: 'Novartis', concentracoes: ['0,05 mg/mL', '0,1 mg/mL', '0,5 mg/mL'], formas: ['Ampola SC'] },
      { nome: 'Octreotida (genérico)', laboratorio: 'Várias', concentracoes: ['0,1 mg/mL'], formas: ['Ampola SC'] },
    ],
  },
  {
    id: 'naloxona-antidoto-opioide',
    molecula: 'naloxona',
    nome_generico: 'Naloxona (Antídoto / Toxicidade por Opioide)',
    sinonimos: ['Narcan', 'antídoto opioide', 'reversão opioide paliativo'],
    categoria: 'paliativo',
    classe: 'Antagonista opioide — bloqueador µ competitivo',
    indicacoes_principais: [
      'Toxicidade aguda por opioide em cuidados paliativos (depressão respiratória)',
      'Prurido intenso por opioides intratecais (dose baixa — 0,04 mg IV)',
    ],
    dose_adulto: {
      habitual: 'Toxicidade: 0,04–0,1 mg IV/SC q2–3 min TITULADO (não reverter toda a analgesia)',
      max: '0,4 mg/dose em paliativo (vs. 2 mg em overdose naive)',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Repetir q2–3 min até FR > 10 ipm e SpO₂ > 90%'],
      instrucoes: 'PALIATIVO: dose muito menor que em overdose não-tolerante. Objetivo: restaurar respiração SEM reverter analgesia por completo. Titular 0,04 mg IV q2 min. IC após bolus efetivo: 2/3 dose efetiva/hora (evitar ressedação).',
    },
    contraindicacoes_rapidas: [
      'Hipersensibilidade à naloxona ou aos componentes da fórmula',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      '⚠ TITULAR EM PACIENTE TOLERANTE: dose usual de overdose (2 mg) pode precipitar dor intensa e síndrome de abstinência aguda',
      'Meia-vida 60–90 min: < maioria dos opioides de longa ação → IC ou vigilância estrita após bolus',
      'Em paliativo: objetivo é FR > 10 ipm, não despertar completo',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Narcan', laboratorio: 'Indivior', concentracoes: ['0,4 mg/mL (1 mL)'], formas: ['Ampola IV/SC/IM'] },
      { nome: 'Naloxona (genérico)', laboratorio: 'Cristália', concentracoes: ['0,4 mg/mL'], formas: ['Ampola IV/SC'] },
    ],
  },
];
