// ============================================================
// PRESCREVE-AI — Banco Farmacológico: Ginecologia + Obstetrícia
// Phase 21.11
// ============================================================

import { QuickDrug } from './pharma-database';

export const PHARMA_DB_GINECO: QuickDrug[] = [
  // ─── CONTRACEPTIVOS ORAIS ─────────────────────────────────
  {
    id: 'etinilestradiol-levonorgestrel',
    molecula: 'etinilestradiol + levonorgestrel',
    nome_generico: 'Etinilestradiol + Levonorgestrel (ACO)',
    sinonimos: ['anticoncep', 'pílula anticoncepcional', 'ACO combinado', 'anticoncepcional oral', 'Ciclo 21', 'Nordette', 'Levordiol'],
    categoria: 'hormonio',
    classe: 'Contraceptivo oral combinado (COC) — 1ª geração',
    indicacoes_principais: ['Contracepção', 'Dismenorreia', 'Endometriose (uso off-label)', 'TPM (transtorno pré-menstrual)'],
    dose_adulto: {
      habitual: '30 mcg EE + 150 mcg LNG — 1 cp/dia por 21 dias, pausa de 7 dias',
      max: '1 cp/dia (não ultrapasse)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia, horário fixo'],
      instrucoes: 'Iniciar no 1º dia da menstruação (proteção imediata) ou Quick Start (usar preservativo 7 dias). Monofásico 21+7 ou contínuo 28 dias.',
    },
    contraindicacoes_rapidas: [
      'Gravidez (MEC 4)',
      'Enxaqueca com aura (MEC 4)',
      'Tabagismo ≥ 35 anos (MEC 4)',
      'TVP/TEP atual ou histórico (MEC 4)',
      'HAS ≥ 160/100 mmHg (MEC 4)',
      'Cardiopatia isquêmica (MEC 4)',
      'AVC (MEC 4)',
      'Amamentação < 6 semanas pós-parto (MEC 4)',
      'Hepatite ativa ou cirrose descompensada (MEC 4)',
      'Câncer de mama (MEC 4)',
    ],
    interacoes_importantes: [
      { com: 'rifampicina', severidade: 'grave', descricao: 'Indução de CYP3A4 → reduz 90% dos níveis hormonais → falha contraceptiva' },
      { com: 'carbamazepina', severidade: 'grave', descricao: 'Indução enzimática → falha contraceptiva — usar DIU de cobre' },
      { com: 'fenitoína', severidade: 'grave', descricao: 'Indução enzimática → falha contraceptiva' },
      { com: 'lamisil (terbinafina)', severidade: 'leve', descricao: 'Dados insuficientes — orientar preservativo' },
    ],
    alertas_especiais: [
      'Risco tromboembólico: gestágenos de 3ª geração (desogestrel, gestodeno) > LNG para TEV',
      'Iniciar SEMPRE com dose mínima de EE (20–30 mcg) — ajustar se breakthrough bleeding',
      'Enxaqueca com aura: CONTRAINDICADO (risco 4× AVC isquêmico)',
      'Interação com anticonvulsivantes: falha contraceptiva — DIU de cobre é mais seguro',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Nordette', laboratorio: 'Pfizer', concentracoes: ['30 mcg EE + 150 mcg LNG'], formas: ['Comprimido revestido'] },
      { nome: 'Ciclo 21', laboratorio: 'EMS', concentracoes: ['30 mcg EE + 150 mcg LNG'], formas: ['Comprimido revestido'] },
      { nome: 'Micronor/Minesse', laboratorio: 'Wyeth/Pfizer', concentracoes: ['20 mcg EE + 150 mcg LNG'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'etinilestradiol-desogestrel',
    molecula: 'etinilestradiol + desogestrel',
    nome_generico: 'Etinilestradiol + Desogestrel (ACO 3ª geração)',
    sinonimos: ['Mercilon', 'Marvelon', 'desogestrel', 'ACO 3ª geração'],
    categoria: 'hormonio',
    classe: 'Contraceptivo oral combinado (COC) — 3ª geração',
    indicacoes_principais: ['Contracepção', 'Acne', 'Dismenorreia', 'Endometriose'],
    dose_adulto: {
      habitual: '20 mcg EE + 150 mcg desogestrel (Mercilon) ou 30 mcg + 150 mcg (Marvelon)',
      max: '1 cp/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia'],
    },
    contraindicacoes_rapidas: [
      'Enxaqueca com aura (MEC 4)', 'Tabagismo ≥ 35 anos (MEC 4)', 'TVP/TEP histórico (MEC 4)',
      'Risco tromboembólico: ↑ TEV vs LNG (gestágenos 3ª geração)',
    ],
    interacoes_importantes: [
      { com: 'rifampicina', severidade: 'grave', descricao: 'Falha contraceptiva' },
      { com: 'carbamazepina', severidade: 'grave', descricao: 'Falha contraceptiva' },
    ],
    alertas_especiais: [
      'Desogestrel/gestodeno: risco de TEV 2× maior que LNG — reservar para acne ou when LNG intolerável',
      'Não preferível como 1ª escolha apenas para contracepção',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Mercilon', laboratorio: 'MSD', concentracoes: ['20 mcg EE + 150 mcg desogestrel'], formas: ['Comprimido'] },
      { nome: 'Marvelon', laboratorio: 'MSD', concentracoes: ['30 mcg EE + 150 mcg desogestrel'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'desogestrel-75mcg',
    molecula: 'desogestrel',
    nome_generico: 'Desogestrel 75 mcg (Minipílula)',
    sinonimos: ['Cerazette', 'minipílula', 'pílula só de progestogênio', 'POP', 'amamentando anticoncepcional'],
    categoria: 'hormonio',
    classe: 'Contraceptivo oral de progestogênio puro',
    indicacoes_principais: ['Contracepção (especialmente em amamentação)', 'Contracepção em contraindicação a estrogênio', 'Enxaqueca com aura'],
    dose_adulto: {
      habitual: '75 mcg 1 cp/dia contínuo sem pausa',
      max: '1 cp/dia',
      unidade: 'mcg',
      via: 'VO',
      frequencias: ['1×/dia contínuo — janela de 12h'],
      instrucoes: 'Tomar no mesmo horário. Janela de 12h (vs 3h dos outros POP). Iniciar no 1º–5º dia do ciclo (proteção imediata) ou a qualquer momento (preservativo por 2 dias). Iniciar 21 dias pós-parto se amamentando.',
    },
    contraindicacoes_rapidas: [
      'Câncer de mama (MEC 4)',
      'Cirrose grave / hepatite ativa (MEC 4)',
      'TVP/TEP ativo (MEC 3)',
    ],
    interacoes_importantes: [
      { com: 'carbamazepina', severidade: 'grave', descricao: 'Indução de CYP3A4 → falha contraceptiva' },
      { com: 'rifampicina', severidade: 'grave', descricao: 'Falha contraceptiva' },
    ],
    alertas_especiais: [
      'Spotting irregular: efeito colateral frequente nos primeiros meses (60%) — counseling prévio',
      'Seguro durante amamentação (MEC 1 pós 6 semanas)',
      'Inibição da ovulação em 97% dos ciclos (mecanismo principal — diferente de outros POP)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Cerazette', laboratorio: 'MSD', concentracoes: ['75 mcg'], formas: ['Comprimido revestido'] },
      { nome: 'Cerelle', laboratorio: 'Gedeon Richter', concentracoes: ['75 mcg'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'levonorgestrel-emergencia',
    molecula: 'levonorgestrel',
    nome_generico: 'Levonorgestrel 1,5 mg (Contracepção de Emergência)',
    sinonimos: ['pílula do dia seguinte', 'postinor', 'escapelle', 'contracepção emergência', 'CE'],
    categoria: 'hormonio',
    classe: 'Contraceptivo de emergência — progestogênio puro',
    indicacoes_principais: ['Contracepção de emergência após relação desprotegida ou falha contraceptiva'],
    dose_adulto: {
      habitual: '1,5 mg dose única',
      max: '1,5 mg (dose única)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['Dose única — o mais precocemente possível (até 120h)'],
      instrucoes: 'Eficácia: 95% (< 24h) → 85% (24–72h) → 58% (72–120h). NÃO é abortiva — adia ou inibe ovulação. Peso > 75 kg: eficácia reduzida — DIU de cobre é superior.',
    },
    contraindicacoes_rapidas: ['Gestação confirmada (ineficaz — não é abortiva)'],
    interacoes_importantes: [
      { com: 'carbamazepina', severidade: 'moderada', descricao: 'Reduz eficácia — usar DIU de cobre como alternativa' },
    ],
    alertas_especiais: [
      'Peso > 75 kg: eficácia significativamente reduzida — DIU de cobre até 5 dias é mais eficaz',
      'Não é abortiva — inibe/atrasa ovulação',
      'Disponível sem prescrição no Brasil',
      'Menstruação esperada em ± 7 dias. Atraso > 7 dias: teste de gravidez',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Postinor 2 (em 1 cp)', laboratorio: 'Gedeon Richter', concentracoes: ['1,5 mg'], formas: ['Comprimido'] },
      { nome: 'Escapelle', laboratorio: 'Libbs', concentracoes: ['1,5 mg'], formas: ['Comprimido'] },
      { nome: 'Norlevo', laboratorio: 'HRA Pharma', concentracoes: ['1,5 mg'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'medroxiprogesterona-injetavel',
    molecula: 'acetato de medroxiprogesterona',
    nome_generico: 'Acetato de Medroxiprogesterona (Injetável)',
    sinonimos: ['Depo-Provera', 'injetável trimestral', 'AMPD', 'anticoncepcional injetável 3 meses'],
    categoria: 'hormonio',
    classe: 'Contraceptivo injetável trimestral — progestogênio de depósito',
    indicacoes_principais: ['Contracepção de longa duração', 'Endometriose', 'Sangramento uterino disfuncional', 'Contracepção em epilepsia (não afetada por anticonvulsivantes)'],
    dose_adulto: {
      habitual: '150 mg IM a cada 12 semanas',
      max: '150 mg/dose (janela de 11–13 semanas)',
      unidade: 'mg',
      via: 'IM',
      frequencias: ['1×/12 semanas (90 dias)'],
      instrucoes: 'Injeção IM profunda (deltóide ou glúteo — não massagear). Iniciar nos primeiros 5 dias do ciclo. Pós-parto amamentando: a partir de 6 semanas.',
    },
    contraindicacoes_rapidas: [
      'Câncer de mama (MEC 4)',
      'Osteoporose grave em adolescentes ou em risco (MEC 3)',
      'Doença cardiovascular grave com múltiplos FR (MEC 3)',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      'Irregularidade menstrual: spotting/amenorreia em 50% no 1º ano',
      'Retorno de fertilidade: 3–18 meses (mediana 10 meses) — informar antes',
      'Perda de DMO: reversível após descontinuação; não usar > 2 anos em adolescentes sem alternativa',
      'Não afetada por indutores enzimáticos (rifampicina, anticonvulsivantes) — vantagem',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Depo-Provera', laboratorio: 'Pfizer', concentracoes: ['150 mg/mL (1 mL)'], formas: ['Suspensão injetável IM'] },
    ],
  },

  // ─── TERAPIA HORMONAL DA MENOPAUSA ───────────────────────
  {
    id: 'estradiol-transdermico',
    molecula: 'estradiol',
    nome_generico: 'Estradiol Transdérmico',
    sinonimos: ['adesivo estrogênio', 'gel estradiol', 'TH transdérmica', 'TRH transdérmica', 'Estraderm', 'Climara'],
    categoria: 'hormonio',
    classe: 'Estrogênio natural transdérmico',
    indicacoes_principais: ['Terapia hormonal da menopausa (fogachos, sintomas urogenitais)', 'Prevenção de osteoporose pós-menopausa', 'Hipogonadismo feminino'],
    dose_adulto: {
      habitual: '50 mcg/24h (adesivo) ou 1 g/dia gel 0,1% (dose de 0,5–1,5 mg/dia)',
      max: '100 mcg/24h (adesivo)',
      unidade: 'mcg',
      via: 'Tópico',
      frequencias: ['Adesivo: 1× a cada 3–4 dias; Gel: 1×/dia'],
      instrucoes: 'Adesivo: aplicar em pele limpa e seca (abdome, glúteo — não mamas). Gel: aplicar em braço ou coxa. Combinar com progestogênio em pacientes com útero. Via transdérmica: menor risco tromboembólico que via oral.',
    },
    contraindicacoes_rapidas: [
      'Câncer de mama (absoluta)',
      'Câncer de endométrio ativo (absoluta)',
      'TEV ativo ou recente',
      'Doença hepática grave',
      'Sangramento uterino não investigado',
      'Gestação',
    ],
    interacoes_importantes: [
      { com: 'tamoxifeno', severidade: 'contraindicado', descricao: 'Antagonismo — cancela efeito do tamoxifeno' },
      { com: 'rifampicina', severidade: 'moderada', descricao: 'Reduz eficácia estrogênica' },
    ],
    alertas_especiais: [
      'Via transdérmica: NÃO aumenta risco de TEV (ao contrário da via oral)',
      'Obrigatório combinar com progestogênio em mulheres COM útero (previne CA endométrio)',
      'Rever indicação a cada 1–2 anos (menor dose eficaz pelo menor tempo)',
      'Iniciar o mais precocemente possível após menopausa ("janela de oportunidade" 50–59 anos)',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Climara', laboratorio: 'Bayer', concentracoes: ['25 mcg/24h', '50 mcg/24h', '100 mcg/24h'], formas: ['Adesivo transdérmico'] },
      { nome: 'Oestrogel', laboratorio: 'Besins', concentracoes: ['Gel 0,06% (1 dose = 0,75 mg)'], formas: ['Gel transdérmico'] },
    ],
  },
  {
    id: 'progesterona-micronizada',
    molecula: 'progesterona micronizada',
    nome_generico: 'Progesterona Micronizada',
    sinonimos: ['Utrogestan', 'progestogênio natural', 'progesterona bioidêntica', 'progesterona vaginal', 'suporte lúteo'],
    categoria: 'hormonio',
    classe: 'Progestogênio natural micronizado',
    indicacoes_principais: [
      'Oposição endometrial na TH com estrogênio (mulheres com útero)',
      'Suporte de fase lútea (FIV)',
      'Prevenção de parto prematuro (colo < 25 mm)',
      'Ameaça de abortamento (1T)',
    ],
    dose_adulto: {
      habitual: 'TH: 200 mg/dia via vaginal ou oral × 12–14 dias/mês (TH cíclica) ou 100 mg/dia contínuo',
      max: '400 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–2×/dia (conforme indicação)'],
      instrucoes: 'TH: 100 mg/noite oral ou 200 mg/dia vaginal. FIV/suporte lúteo: 600 mg/dia vaginal em 3 doses. Prevenção PPT: 200 mg/noite vaginal até 34–36 semanas.',
    },
    contraindicacoes_rapidas: [
      'Câncer de mama ativo',
      'TEV ativo (via oral — via vaginal mais segura)',
      'Doença hepática grave',
      'Sangramento uterino não investigado',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      'Progesterona NATURAL (bioidêntica) — melhor perfil de tolerabilidade e segurança mamária vs progestinas sintéticas',
      'Via oral: sedação — tomar à noite. Via vaginal: sem efeito sistêmico sedativo',
      'Prevenção de PPT: Cochrane 2022 — reduz PPT < 34 semanas em colo < 25 mm',
      'TH: associar a estradiol para proteção endometrial (nunca usar estrogênio isolado com útero)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'risco',
    marcas: [
      { nome: 'Utrogestan', laboratorio: 'Besins', concentracoes: ['100 mg', '200 mg'], formas: ['Cápsula oral/vaginal'] },
      { nome: 'Crinone', laboratorio: 'Merck', concentracoes: ['90 mg (gel 8%)'], formas: ['Gel vaginal'] },
    ],
  },
  {
    id: 'tibolona',
    molecula: 'tibolona',
    nome_generico: 'Tibolona',
    sinonimos: ['Libiam', 'Livial', 'TH combinada sintética'],
    categoria: 'hormonio',
    classe: 'Esteroide sintético — ação estrogênica + progestagênica + androgênica',
    indicacoes_principais: ['Sintomas climatéricos (fogachos)', 'Prevenção de osteoporose pós-menopausa', 'Libido hipoativa na menopausa'],
    dose_adulto: {
      habitual: '2,5 mg/dia oral contínuo',
      max: '2,5 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia'],
      instrucoes: 'Iniciar ≥ 12 meses pós-menopausa (sangramento uterino raro). Não requer progestogênio separado (tem ação progestagênica intrínseca).',
    },
    contraindicacoes_rapidas: [
      'Câncer de mama (LIFT trial: ↑ recidiva)',
      'CA de endométrio (atividade estrogênica endometrial)',
      'TVP/TEP histórico (↑ risco — via oral)',
      'AVC / DCV (LIFT trial: ↑ AVC)',
    ],
    interacoes_importantes: [],
    alertas_especiais: [
      'LIFT Trial (Lancet 2009): ↑ recidiva de CA de mama — CONTRAINDICADA em sobreviventes de CA de mama',
      '↑ Risco de AVC em mulheres ≥ 60 anos — prefira transdermal + progesterona nessa faixa etária',
      'Atividade androgênica: melhora da libido e humor',
    ],
    uso_gestante: 'contraindicado',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Livial', laboratorio: 'MSD', concentracoes: ['2,5 mg'], formas: ['Comprimido'] },
      { nome: 'Libiam', laboratorio: 'Eurofarma', concentracoes: ['2,5 mg'], formas: ['Comprimido'] },
    ],
  },

  // ─── TERAPIA GESTACIONAL ─────────────────────────────────
  {
    id: 'sulfato-magnesio',
    molecula: 'sulfato de magnésio',
    nome_generico: 'Sulfato de Magnésio',
    sinonimos: ['MgSO4', 'magnésio gestação', 'eclâmpsia', 'pré-eclâmpsia grave', 'neuroproteção fetal'],
    categoria: 'outro',
    classe: 'Eletrólito / Anticonvulsivante obstétrico',
    indicacoes_principais: [
      'Prevenção e tratamento de eclâmpsia',
      'Neuroproteção fetal em PPT < 32 semanas',
      'Tocólise (uso off-label, de curta duração)',
    ],
    dose_adulto: {
      habitual: 'Ataque: 4 g IV em 20 min → Manutenção: 1 g/h IV contínuo',
      max: 'Ataque máx 6 g; manutenção máx 2 g/h',
      unidade: 'g',
      via: 'IV',
      frequencias: ['Ataque único + infusão contínua'],
      instrucoes: 'Zuspan: 4 g IV (20 min) → 1–2 g/h (manutenção por 24h pós-parto).\nPritchard: 4 g IV + 10 g IM (5g/nádega) → 5 g IM 4/4h.\nNeuroproteção fetal: 4 g IV em 30 min se parto < 32 sem iminente.',
    },
    contraindicacoes_rapidas: [
      'Miastenia gravis',
      'Bloqueio AV grave',
      'Hipocalcemia grave',
      'Oligúria grave (< 25 mL/h) sem diurese adequada',
    ],
    interacoes_importantes: [
      { com: 'nifedipino', severidade: 'moderada', descricao: 'Potencializa hipotensão e bloqueio neuromuscular — monitorar' },
      { com: 'bloqueadores neuromusculares', severidade: 'grave', descricao: 'Potencializa paralisia muscular' },
    ],
    alertas_especiais: [
      'TOXICIDADE: reflexo patelar ausente > 7 mEq/L; parada resp > 10; parada cardíaca > 15',
      'ANTÍDOTO: Gluconato de cálcio 1 g IV lento (10 mL a 10%) — ter à beira do leito',
      'Monitorar: reflexo patelar e diurese a cada 1h; FR a cada 30 min',
      'Nível terapêutico: 4–7 mEq/L (2–3,5 mmol/L)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Sulfato de Magnésio 50%', laboratorio: 'Diversas', concentracoes: ['500 mg/mL (50%)'], formas: ['Ampola 10 mL = 5g'] },
    ],
  },
  {
    id: 'metildopa',
    molecula: 'metildopa',
    nome_generico: 'Metildopa',
    sinonimos: ['Aldomet', 'alfa-metildopa', 'hipertensão gestacional', 'pré-eclâmpsia leve'],
    categoria: 'antihipertensivo',
    classe: 'Agonista alfa-2 central',
    indicacoes_principais: ['Hipertensão arterial na gestação (1ª linha)', 'Pré-eclâmpsia sem critério de gravidade'],
    dose_adulto: {
      habitual: '250 mg 8/8h → ajustar até 500 mg 8/8h',
      max: '3000 mg/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['8/8h ou 12/12h'],
      instrucoes: 'Iniciar 250 mg 8/8h. Ajustar em 2 dias até controle. Máx 3 g/dia. 1ª linha para HAS na gestação.',
    },
    contraindicacoes_rapidas: ['Hepatite ativa (hepatotóxica)', 'Depressão grave', 'Feocromocitoma', 'Hipersensibilidade'],
    interacoes_importantes: [
      { com: 'IMAO', severidade: 'contraindicado', descricao: 'Crise hipertensiva grave' },
      { com: 'lítio', severidade: 'moderada', descricao: 'Pode ↑ nível sérico do lítio' },
    ],
    alertas_especiais: [
      'Sedação materna: tomar maior dose ao deitar',
      'Hepatotoxicidade: monitorar transaminases se uso > 12 semanas',
      'Teste de Coombs positivo (benigno) em 20% — não indica hemólise',
      'Compatível com amamentação — nível mínimo no leite',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    ajuste_renal: {
      normal: 'Dose habitual',
      tfg_60_30: 'Intervalo estendido — monitorar sedação',
      tfg_30_15: 'Dose reduzida 50% — usar com cautela',
      tfg_lt_15: 'Evitar — acúmulo de metabólitos',
      dialisavel: true,
    },
    marcas: [
      { nome: 'Aldomet', laboratorio: 'MSD', concentracoes: ['250 mg', '500 mg'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'hidralazina',
    molecula: 'hidralazina',
    nome_generico: 'Hidralazina',
    sinonimos: ['Nepresol', 'crise hipertensiva gestacional', 'emergência hipertensiva obstetrícia'],
    categoria: 'antihipertensivo',
    classe: 'Vasodilatador direto arterial',
    indicacoes_principais: ['Emergência hipertensiva na gestação (IV)', 'Pré-eclâmpsia grave — PA ≥ 160/110'],
    dose_adulto: {
      habitual: '5 mg IV lento → repetir 5 mg a cada 20 min até PA controlada',
      max: '20 mg total por episódio',
      unidade: 'mg',
      via: 'IV',
      frequencias: ['Dose fracionada a cada 20 min (emergência)'],
      instrucoes: 'Diluir 20 mg em 20 mL SF. 5 mg IV lento (1 mg/min). Monitorar PA a cada 5 min. Alvo: PAS 140–155 mmHg. Não reduzir abruptamente (risco de hipoperfusão uteroplacentária).',
    },
    contraindicacoes_rapidas: ['Lúpus (piora)', 'Taquiarritmia grave', 'Aneurisma aórtico'],
    interacoes_importantes: [
      { com: 'sulfato de magnésio', severidade: 'moderada', descricao: 'Potencializa hipotensão — monitorar PA com frequência' },
    ],
    alertas_especiais: [
      'Taquicardia reflexa materna e cefaleia: efeitos frequentes',
      'Não reduzir PA abruptamente — risco de sofrimento fetal',
      'Monitorar BCF após cada dose',
      'Segunda opção após labetalol IV ou nifedipino VO em muitos protocolos',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Nepresol', laboratorio: 'Torrent', concentracoes: ['20 mg/mL (1 mL)'], formas: ['Ampola IV'] },
    ],
  },
  {
    id: 'ocitocina',
    molecula: 'ocitocina',
    nome_generico: 'Ocitocina',
    sinonimos: ['Syntocinon', 'ocitocina sintética', 'uterotônico', 'indução parto', 'HPP'],
    categoria: 'hormonio',
    classe: 'Hormônio neurohipofisário / Uterotônico',
    indicacoes_principais: [
      'Indução e condução do trabalho de parto',
      'Prevenção e tratamento de hemorragia pós-parto (HPP)',
      'Hipotonia uterina',
    ],
    dose_adulto: {
      habitual: 'Indução: 0,5–2 mUI/min IV → aumentar 1–2 mUI/min a cada 30–40 min (máx 20–40 mUI/min)',
      max: '40 mUI/min (indução/condução)',
      unidade: 'UI',
      via: 'IV',
      frequencias: ['Infusão contínua IV (bomba de infusão)'],
      instrucoes: 'HPP prevenção: 10 UI IM ou IV lento imediatamente após expulsão. HPP tratamento: 20–40 UI em 500 mL SG5% → 150 mL/h IV. Indução: bomba de infusão obrigatória.',
    },
    contraindicacoes_rapidas: [
      'Apresentação fetal anômala não corrigida',
      'Cicatriz uterina com risco de rotura',
      'Desproporção céfalo-pélvica absoluta',
      'Sofrimento fetal agudo',
    ],
    interacoes_importantes: [
      { com: 'misoprostol', severidade: 'moderada', descricao: 'Potencialização do efeito uterotônico — risco de hiperestimulação' },
    ],
    alertas_especiais: [
      'Hiperestimulação uterina: suspender infusão imediatamente se contração > 5/10 min ou duração > 90s',
      'Hipotensão: dose IV rápida (bolus) — NUNCA administrar em bolus rápido (colapso CV)',
      'Hiponatremia dilucional: risco com grandes volumes diluídos + antidiurese',
      'Monitorar BCF continuamente durante infusão',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Syntocinon', laboratorio: 'Novartis', concentracoes: ['5 UI/mL (1 mL)', '10 UI/mL'], formas: ['Ampola IV/IM'] },
    ],
  },
  {
    id: 'misoprostol',
    molecula: 'misoprostol',
    nome_generico: 'Misoprostol',
    sinonimos: ['Cytotec', 'Prostokos', 'uterotônico PGE1', 'amadurecimento cervical', 'maturação colo'],
    categoria: 'gastroenterologia',
    classe: 'Análogo sintético da prostaglandina E1 (PGE1)',
    indicacoes_principais: [
      'Amadurecimento cervical / Indução de trabalho de parto',
      'Prevenção de hemorragia pós-parto (HPP)',
      'Tratamento de HPP refratária a ocitocina',
      'Tratamento de aborto incompleto',
    ],
    dose_adulto: {
      habitual: 'Amadurecimento cervical: 25 mcg vaginal 4/4–6/6h (máx 200 mcg/24h)',
      max: '600 mcg (dose única HPP) | 200 mcg/24h (indução)',
      unidade: 'mcg',
      via: 'VO',
      frequencias: ['Vaginal, sublingual ou retal — conforme indicação'],
      instrucoes: 'HPP prevenção (OMS): 600 mcg VO ou 400 mcg sublingual dose única pós-expulsão se ocitocina indisponível. HPP tratamento: 800 mcg sublingual. Indução: 25–50 mcg vaginal 4/4–6/6h (FIGO 2017).',
    },
    contraindicacoes_rapidas: [
      'Cesárea anterior (risco de rotura — usar com extrema cautela)',
      'Hiperestimulação uterina em andamento',
      'BCF alterado / sofrimento fetal agudo',
    ],
    interacoes_importantes: [
      { com: 'ocitocina', severidade: 'moderada', descricao: 'Intervalo mínimo de 6h entre misoprostol vaginal e início de ocitocina' },
    ],
    alertas_especiais: [
      'Taquissistolia (> 5 contrações/10 min): suspender e considerar tocolítico (terbutalina)',
      'Cesárea anterior: dose máxima 25 mcg vaginal; intervalo ≥ 6h',
      'Taquicardia, febre, calafrios: efeitos comuns — autolimitados',
      'FIGO 2017: misoprostol 25 mcg vaginal é recomendação de 1ª linha para indução',
    ],
    uso_gestante: 'avaliar',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Cytotec', laboratorio: 'Pfizer', concentracoes: ['200 mcg'], formas: ['Comprimido'] },
      { nome: 'Prostokos', laboratorio: 'Hebron', concentracoes: ['25 mcg'], formas: ['Comprimido vaginal'] },
    ],
  },
  {
    id: 'betametasona-antenatal',
    molecula: 'betametasona',
    nome_generico: 'Betametasona (Corticoide Antenatal)',
    sinonimos: ['Celestone', 'corticoide fetal', 'maturação pulmonar', 'corticoterapia antenatal'],
    categoria: 'hormonio',
    classe: 'Corticosteroide fluorado — maturação pulmonar fetal',
    indicacoes_principais: [
      'Maturação pulmonar fetal em risco de parto prematuro (24–34 semanas)',
      'Considerar em 34–36+6 semanas (late preterm)',
    ],
    dose_adulto: {
      habitual: '12 mg IM a cada 24h × 2 doses',
      max: '12 mg/dose × 2 doses',
      unidade: 'mg',
      via: 'IM',
      frequencias: ['12 mg IM 24/24h × 2 doses (48h de intervalo)'],
      instrucoes: 'Indicado quando parto < 37 semanas é esperado em 7 dias. Benefício máximo: > 24h após 1ª dose. Curso de resgate único pode ser considerado se > 14 dias do ciclo anterior e IG ainda < 34 sem.',
    },
    contraindicacoes_rapidas: ['Infecção materna sistêmica (relativa)', 'DM descompensado (hiperglicemia grave)'],
    interacoes_importantes: [],
    alertas_especiais: [
      'Hiperglicemia materna transitória (1–3 dias): monitorar em diabéticas',
      'Reduz: SDR neonatal (-50%), hemorragia intraventricular, enterocolite necrosante, mortalidade perinatal',
      'Benefício documentado de 24h a 7 dias após administração',
      'Cursos repetidos: maior cuidado (supressão HPA fetal)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Celestone Soluspan', laboratorio: 'MSD', concentracoes: ['6 mg/mL (3 mg betametasona base + 3 mg fosfato)'], formas: ['Suspensão injetável IM'] },
    ],
  },
  {
    id: 'acido-folico',
    molecula: 'ácido fólico',
    nome_generico: 'Ácido Fólico',
    sinonimos: ['folato', 'vitamina B9', 'suplemento gestacional', 'prevenção DTN', 'vitamina gestação'],
    categoria: 'outro',
    classe: 'Vitamina do complexo B / Coenzima síntese de nucleotídeos',
    indicacoes_principais: [
      'Prevenção de defeitos do tubo neural (DTN)',
      'Suplementação pré-concepcional e gestacional',
      'Anemia megaloblástica por deficiência de folato',
    ],
    dose_adulto: {
      habitual: '400–800 mcg/dia',
      max: '5 mg/dia (alto risco: antiepilépticos, DMG, histórico de DTN)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1×/dia'],
      instrucoes: 'Iniciar pelo menos 1 mês (ideal 3 meses) antes da concepção e manter até 12 semanas. Alto risco: 5 mg/dia — mulheres em uso de anticonvulsivantes, DM, obesidade, histórico de DTN, gêmeos.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade (raro)'],
    interacoes_importantes: [
      { com: 'metotrexato', severidade: 'moderada', descricao: 'Antagonismo — metotrexato inibe DHFR (ácido fólico protege da toxicidade sem reduzir eficácia terapêutica)' },
      { com: 'carbamazepina', severidade: 'leve', descricao: 'Antiepilépticos reduzem absorção de folato — usar 5 mg/dia' },
    ],
    alertas_especiais: [
      'TODOS os anticonvulsivantes: usar 5 mg/dia (não 400 mcg)',
      'Deficiência de B12 não diagnosticada: suplementação isolada de folato pode mascarar anemia megaloblástica e não tratar neuropatia',
      'Disponível na rede SUS (RENAME)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Ácido Fólico 5 mg', laboratorio: 'Várias (genérico)', concentracoes: ['400 mcg', '1 mg', '5 mg'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'sulfato-ferroso-gestacao',
    molecula: 'sulfato ferroso',
    nome_generico: 'Sulfato Ferroso (Gestação)',
    sinonimos: ['ferro gestacional', 'suplemento ferro gestação', 'anemia ferropriva gestante', 'Noripurum', 'Ferrolab'],
    categoria: 'outro',
    classe: 'Suplemento de ferro ferroso oral',
    indicacoes_principais: ['Profilaxia de anemia ferropriva gestacional', 'Tratamento de anemia ferropriva na gestação'],
    dose_adulto: {
      habitual: '40 mg de ferro elementar/dia (profilaxia) | 120–200 mg/dia (tratamento)',
      max: '200 mg de ferro elementar/dia',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['1–2×/dia em jejum ou com vitamina C'],
      instrucoes: 'Sulfato ferroso 325 mg = 65 mg de ferro elementar. Profilaxia: 1 cp 200 mg (40 mg Fe) a partir do 2T. Tratamento: 2–3 cp/dia. Tomar 30 min antes das refeições ou com suco de laranja (↑ absorção). NÃO tomar com leite, chá, cálcio ou antiácidos.',
    },
    contraindicacoes_rapidas: ['Hemocromatose', 'Anemia hemolítica (sem deficiência de ferro)', 'Úlcera GI ativa'],
    interacoes_importantes: [
      { com: 'cálcio', severidade: 'moderada', descricao: 'Reduz absorção de ferro em 60% — separar por 2h' },
      { com: 'levotiroxina', severidade: 'moderada', descricao: 'Ferro quelata tiroxina — separar por 4h' },
    ],
    alertas_especiais: [
      'Constipação e náuseas: efeitos frequentes — tomar após refeição leve se intolerância em jejum',
      'Fezes escurecidas: normal e esperado',
      'OMS 2022: suplementação universal a partir de 20 semanas',
      'Anemia grave (Hb < 7): considerar ferro IV (sacarato ou carboximaltose)',
    ],
    uso_gestante: 'seguro',
    uso_lactante: 'seguro',
    marcas: [
      { nome: 'Noripurum Gotas', laboratorio: 'Zambon', concentracoes: ['125 mg/mL (25 mg Fe/mL)'], formas: ['Solução oral'] },
      { nome: 'Ferrolab', laboratorio: 'Merck', concentracoes: ['200 mg cp (40 mg Fe)'], formas: ['Comprimido'] },
    ],
  },
  {
    id: 'cabergolina',
    molecula: 'cabergolina',
    nome_generico: 'Cabergolina',
    sinonimos: ['Dostinex', 'agonista dopaminérgico', 'inibição lactação', 'hiperprolactinemia', 'prolactinoma'],
    categoria: 'hormonio',
    classe: 'Agonista dopaminérgico D2 de longa ação',
    indicacoes_principais: [
      'Hiperprolactinemia (1ª linha)',
      'Prolactinoma (micro e macroprolactinoma)',
      'Inibição da lactação (quando necessário por indicação médica)',
      'Síndrome de hiperestimulação ovariana grave (SHEO)',
    ],
    dose_adulto: {
      habitual: 'Hiperprolactinemia: 0,25–0,5 mg 2×/semana. Inibição de lactação: 1 mg dose única',
      max: '3 mg/semana (hiperprolactinemia)',
      unidade: 'mg',
      via: 'VO',
      frequencias: ['2×/semana (hiperprolactinemia)', 'Dose única (inibição lactação)'],
      instrucoes: 'Hiperprolactinemia: iniciar 0,25 mg 2×/semana à noite com alimento. Aumentar 0,25 mg por 4 semanas até dose eficaz. Prolactinoma: titular até nível normal de prolactina.',
    },
    contraindicacoes_rapidas: ['Hipersensibilidade a ergotamina', 'Valvulopatia (uso crônico em altas doses)', 'Gestação (exceto prolactinoma: risco/benefício)'],
    interacoes_importantes: [
      { com: 'antipsicóticos', severidade: 'moderada', descricao: 'Antagonismo — reduz eficácia de ambos' },
    ],
    alertas_especiais: [
      'Valvulopatia: risco com doses altas e uso prolonged (> 3 mg/semana) — US cardíaco se > 2 anos',
      'Gestação: suspender quando gravidez confirmada (salvo macroprolactinoma sintomático)',
      'Inibição de lactação: 1 mg dose única no 1º dia pós-parto — mais eficaz que bromocriptina',
      'Náuseas: principal EAd — tomar com alimento e iniciar à noite',
    ],
    uso_gestante: 'risco',
    uso_lactante: 'contraindicado',
    marcas: [
      { nome: 'Dostinex', laboratorio: 'Pfizer', concentracoes: ['0,5 mg'], formas: ['Comprimido'] },
    ],
  },
];
